### ISSUE TITLE
Document pod-overrides and container-overrides

### ISSUE THREAD

**Issue by kadel** [devfile/api#1005]
## Which area is this feature related to?

/area documentation

## Which area is this documentation change is related to?

/area api
/area library

## Issue details

pod-overrides and container-overrides were implemented in https://github.com/devfile/library/pull/158 and https://github.com/devfile/library/pull/157

but there is no documentation on devfile.io about how to use it and what is it for

context in https://github.com/devfile/api/issues/920

**Comment by valaparthvi** [comment]
Thank you for opening this. I am planning on working on this. I was waiting for both the PRs to go in.
