### ISSUE TITLE
CI Test required in registry to test for changes against Appstudio

### ISSUE THREAD

**Issue by yangcao77** [devfile/api#1010]
## Which area/kind this issue is related to?

/area ci
/area registry
/area test-automation

## Issue Description

We are seeing [PR change](https://github.com/devfile-samples/devfile-sample-java-springboot-basic/pull/13/files) affecting appstudio and causes regression. This is not caught since we do not have CI Tests in registry to test for changes against Appstudio.

We should introduce a basic Appstudio test suite  to prevent from further issues caused by registry changes.

## Target Odo version

> Target Odo version: N/A

**Comment by michael-valdron** [comment]
Waiting to see if we'll need to continue to test against AppStudio in the near future
