### ISSUE TITLE
remove sparseCheckoutDir from the docs

### ISSUE THREAD

**Issue by agiertli** [devfile/api#1011]
sparseCheckoutDir has been removed from the APi as per the:

https://github.com/devfile/api/issues/128

But it's still documented here:
https://devfile.io/docs/2.2.0/adding-projects#procedure
CTRL+F "sparseCheckoutDir"

Since this is no longer part of the API, it should be removed from the docs.

**Comment by kim-tsao** [comment]
Yes it should be removed.  It looks like it got replaced by "subDir" but that's only available for starterProjects

**Comment by kim-tsao** [comment]
@mike-hoang can you take a look at this?  We need to remove it for versions 2.0.0 and above
