### ISSUE TITLE
Fix gosec breakage 

### ISSUE THREAD

**Issue by kim-tsao** [devfile/api#1021]
## Which area/kind this issue is related to?

 /area ci

## Issue Description

Pulling the latest gosec package breaks our [CI.](https://github.com/devfile/registry-support/actions/runs/4105697869/jobs/7082922248#step:7:29)  It looks like we may need to update to go 1.19 to fix this or if moving up poses a problem, lock it down to v2.14.0 package until we're ready to move up.  

```
Run export PATH=$PATH:$(go env GOPATH)/bin
go: downloading github.com/securego/gosec v0.0.0-20200401082031-e946c8c39989
go: downloading github.com/securego/gosec/v2 v2.15.0
go: downloading golang.org/x/tools v0.5.0
go: downloading github.com/nbutton23/zxcvbn-go v0.0.0-20210217022336-fa2cb2858354
go: downloading github.com/google/uuid v1.3.0
go: downloading github.com/gookit/color v1.5.2
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading golang.org/x/sys v0.4.0
go: downloading github.com/xo/terminfo v0.0.0-20210125001918-ca9a967f8778
go: downloading golang.org/x/mod v0.7.0
# github.com/securego/gosec/v2/rules
Error: ../../../go/pkg/mod/github.com/securego/gosec/v2@v2.15.0/rules/readfile.go:29:17: undefined: any
Error: ../../../go/pkg/mod/github.com/securego/gosec/v2@v2.15.0/rules/readfile.go:63:11: assignment mismatch: 2 variables but 1 value
Error: ../../../go/pkg/mod/github.com/securego/gosec/v2@v2.15.0/rules/readfile.go:135:19: undefined: any
note: module requires Go 1.19
Error: Process completed with exit code 2.

```

Affected repos:

- [x] api
- [x] library
- [x] registry-support
- [x] registry-operator

## Target Odo version

> Target Odo version:

**Target Date: 03-03-2023**

**Comment by michael-valdron** [comment]
[devfile/registry-support](https://github.com/devfile/registry-support) has the fix for this issue (#1020), other repositories need this fix.

**Comment by michael-valdron** [comment]
blocked by #1036

**Comment by michael-valdron** [comment]
All gosec fixes have been merged.
