### ISSUE TITLE
Enable notification for failing integration tests

### ISSUE THREAD

**Issue by kim-tsao** [devfile/api#1026]
/kind task

## Which area this feature is related to?

/area ci
/area test-automation
/area integration-tests

## Issue Description

All ODC tests have been failing recently https://github.com/devfile/integration-tests#odc-tests-on-openshift-ci. We need to ensure we are enabling notification on any future failures.

## Acceptance Criteria
- [ ] Create mechanism to push notifications to slack
- [ ] All future runs should send a message to team channel with the result of the task.
- [ ] The message should follow the following format:
       * Status: [{red light emoji} failure | {green light emoji} success]
       * Severity: [for failure - medium | for success low]
       * In case of failure mention `@ app-devfile` in order to take action.
       * Title: Product & Community Registries Check
       * Description: Mention Branch and Commit, add a short message and link to logs

**Comment by michael-valdron** [comment]
The description needs the following changes:
- Needs conversion to a task or story
- Needs acceptance criteria

**Comment by thepetk** [comment]
I'd say we can follow the same format as the other 2 similar items we have created for other notifications we need:
- https://github.com/devfile/api/issues/1255
- https://github.com/devfile/api/issues/1061

That said I've updated this item to a task and added the same acceptance criteria as the similar issues. I've also added this item as part of the epic https://github.com/devfile/api/issues/1272

**Comment by michael-valdron** [comment]
> /area test-automation

Not sure this would fall under this area, `test-automation` I believe is specific to devfile/api testing correct me if I'm wrong.

cc: @kim-tsao @thepetk

**Comment by thepetk** [comment]
Added `blocker` as this item should be done first and the rest items of the epic later

**Comment by thepetk** [comment]
PR https://github.com/devfile/integration-tests/pull/104 is now ready for review
