### ISSUE TITLE
rename devfile/kubernetes-api to devfile/api

### ISSUE THREAD

**Issue by sbose78** [devfile/api#103]
**Describe the bug**

Similar to openshift/api or kubernetes/api, it would be nice to have devfile/api. 
The name `kubernetes-api` makes it look like Kubernetes API Server-ish API :)

**Comment by l0rd** [comment]
Yes I think we should do that indeed. Le's wait for @davidfestal +1 here as well and then let's rename it.

**Comment by davidfestal** [comment]
I'm OK with this as well.

**Comment by gorkem** [comment]
+1 
Let's do this as soon as possible

**Comment by neeraj-laad** [comment]
+1
This would make it much clearer.

**Comment by l0rd** [comment]
Renamed

**Comment by amisevsk** [comment]
Follow up PR: https://github.com/devfile/api/pull/110
