### ISSUE TITLE
Remove post-stop event from the devfile spec

### ISSUE THREAD

**Issue by l0rd** [devfile/api#1032]
## Which area this feature is related to?

/area api

## Which functionality do you think we should add?

We want to remove the  `post-stop` event as this is hasn't been implemented and there are no known valid use case for it.

**Why is this needed? Is your feature request related to a problem?**

Having both `pre-stop` and `post-stop` is confusing.
Implementing `post-stop` may be challeging.

**Comment by michael-valdron** [comment]
We should deprecate the field first and remove after several version of deprecation
