### ISSUE TITLE
Clarify devfile placement and filename

### ISSUE THREAD

**Issue by kadel** [devfile/api#1035]
## Which area this feature is related to?

/area documentation

- Clarify the placement of the `devfile.yaml` in the repository. Is it required for devfile to always be in the root of the project directory / git repository?

- What are acceptable filenames for devfile? Does it always have to be `devfile.yaml` or `devfile.yml`?

- precedence rules which one will be selected if we have all the 4 combinations - devfile.yaml / devfile.yml / .devfile.yaml / devfile.yml ?

**Comment by vishaltak** [comment]
@kadel - Thank you for opening this issue.

> Is it required for devfile to always be in the root of the project directory / git repository?

Is this assuming that there will only be 1 devfile for a project? Do we not see the a scenario where there can be 2 devfiles in a project?

**Artifact 1**
GitHub Codespaces supports `.devcontainer.json` format and this is what they say in their [documentation](https://docs.github.com/en/codespaces/setting-up-your-project-for-codespaces/adding-a-dev-container-configuration/introduction-to-dev-containers)

> You can define a single dev container configuration for a repository, different configurations for different branches, or multiple configurations. When multiple configurations are available, users can choose their preferred configuration when they create a codespace. This is particularly useful for large repositories that contain source code in different programming languages or for different projects. You can create a choice of configurations that allow different teams to work in a codespace that's set up appropriately for the work they are doing.

**Artifact 2**

https://gitlab.com/gitlab-org/remote-development/gitlab-remote-development-docs/-/merge_requests/11#note_1279032366

---

> What are acceptable filenames for devfile? Does it always have to be devfile.yaml or devfile.yml?

devfile is essentially a configuration file. Thus, I would assume it would follow the [`dotfile` convention](https://www.freecodecamp.org/news/dotfiles-what-is-a-dot-file-and-how-to-create-it-in-mac-and-linux/) i.e. `.devfile.yaml` / `.devfile.yml` ?

Also, if both `.yaml` and `.yml` are acceptable, what to do when both these files are present?

**Comment by l0rd** [comment]
We should specify a default (e.g. `.devfile.yaml`) but also make allow configurability (for the large repository use case for example). Eclipse Che looks for `.devfile.yaml` and `devfile.yaml` but, with the `devfilePath` URL parameter, supports Devfiles with a different name and path.

For the default name I am in favor of the proposal to follow the dotfile convention: `.devfile.yaml` (all lowercase)

For the default extension I would support `.yaml` only based on the [YAML spec FAQ](https://yaml.org/faq.html).

**Comment by maysunfaisal** [comment]
We may documented this usage, I will find out and confirm

**Comment by rm3l** [comment]
> We may have documented this usage, I will find out and confirm

@maysunfaisal Were you able to determine if/where this was documented? A user reported a related issue in https://github.com/redhat-developer/odo/issues/7060 (about the default filename extension), and I think we need to clarify this.

**Comment by elsony** [comment]
Discussed on community call on 9/18:
1. We'll support both .yaml and .yml
2. If variants of them present in the same directory, the .yaml one has priority

**Comment by rm3l** [comment]
Added to the upcoming refinement call.

**Comment by thewoolleyman** [comment]
@elsony Looks like this got auto-closed by a bot. Can we re-open it based on the action plan given in https://github.com/devfile/api/issues/1035#issuecomment-1723384280?

cc @vishaltak

**Comment by l0rd** [comment]
@thewoolleyman reopened. Are you planning to submit a PR to address this issue?

**Comment by thewoolleyman** [comment]
> @thewoolleyman reopened. Are you planning to submit a PR to address this issue?

Not currently, we were mainly looking for an official decision on the naming standards.

It looks like that was decided in https://github.com/devfile/api/issues/1035#issuecomment-1723384280, so that's good.

But I don't think that this issue should be closed until the documentation is updated to reflect this decision.

Alternately, you could open a separate issue for the documentation update, but it seems like this one can serve that purpose?

**Comment by thewoolleyman** [comment]
@elsony @maysunfaisal Regarding the decisions recorded here (https://github.com/devfile/api/issues/1035#issuecomment-1723384280) - can you confirm that these default filenames only apply to the root directory of the project/repository, and not any subdirectories?

**Comment by thewoolleyman** [comment]
@elsony @maysunfaisal Also regarding the decisions recorded here (https://github.com/devfile/api/issues/1035#issuecomment-1723384280) - can you confirm whether default names include both the leading-dot hidden `.devfile...` as well as (or instead of) the non-leading-dot `devfile...`?
