### ISSUE TITLE
Registry Viewer container doesn't have liveness/readiness probes

### ISSUE THREAD

**Issue by johnmcollier** [devfile/api#1040]
/kind bug
/area registry

As part of the fix for https://github.com/devfile/api/issues/1019, the probes for the registry viewer container were [removed from the OpenShift template](https://github.com/devfile/registry/commit/2f5066b7f2e862acc55158b83bf9f0a663206506). This isn't ideal because if the Registry Viewer container crashes, this won't be detected by the liveness probe, and the container won't be restarted by Kube.

**Target Date: 03-29-2023**

**Comment by michael-valdron** [comment]
Places this needs to be fixed:
- [ ] [devfile/registry - deployment template](https://github.com/devfile/registry/blob/591d0fd232059bc94202a84cdd32d4cea12cb445/.ci/deploy/devfile-registry.yaml#L109)
- [ ] [devfile/registry-support - helm chart](https://github.com/devfile/registry-support/blob/71186fe1d425fe3a551f3a9341192c252f73a0fd/deploy/chart/devfile-registry/templates/deployment.yaml#L113)
- [ ] [devfile/registry-operator](https://github.com/devfile/registry-operator/blob/eecf84eae0d0109698f7084a5a7fdacd7c589cba/pkg/registry/deployment.go#L210)

**Comment by michael-valdron** [comment]
The OpenShift template for the community registry and the registry operator are experiencing client timeout errors when probing the registry viewer. Currently investigating the root cause to this, leaving devfile/registry-operator#36 and devfile/registry#164 in WIP status till the culprit is found in the template specs.

**Comment by michael-valdron** [comment]
> > The OpenShift template for the community registry and the registry operator are experiencing client timeout errors when probing the registry viewer. Currently investigating the root cause to this, leaving [devfile/registry-operator#36](https://github.com/devfile/registry-operator/pull/36) and [devfile/registry#164](https://github.com/devfile/registry/pull/164) in WIP status till the culprit is found in the template specs. [devfile/registry-support#166](https://github.com/devfile/registry-support/pull/166) is ready for review.
> 
> With recent changes to the delays of the registry viewer probing and other minor changes in the registry operator the timeouts experienced seem to have been reduced. Currently fine tuning the probes to attempt to create a stable deployment using the registry operator. Will replicate these changes in the OpenShift template once a solution is found.

After some fine tuning of probes, increasing the timeouts from `3` seconds to `20` seconds seems to have removed these errors from triggering.

**Comment by michael-valdron** [comment]
The following PRs are ready for review:
- https://github.com/devfile/registry-operator/pull/36
- https://github.com/devfile/registry/pull/164
