### ISSUE TITLE
Container image security review to ensure no security vulnerabilites

### ISSUE THREAD

**Issue by elsony** [devfile/api#1058]
## Which area/kind this issue is related to?
/area registry

## Issue Description
Quarterly review of the devfile containers to make sure container images used do not have security vulnerabilities. The containers to cover:

- [x] devfile-index (clean)
- [x] devfile-index-base (clean)
- [x] Registry Viewer - registry-viewer (vuln)
- [ ] Registry Operator - registry-operator () - scan not supported `Manifest is not supported by Quay Security Scanner
This manifest has an operating system or package manager unsupported by Quay Security Scanner. `.   Investigate if Clair supports scanning distroless images
- [x] Devfile registry integration testing - devfile-registry-integration (vuln) https://github.com/devfile/api/issues/1062
- [x] OCI server - oci-registry (clean)

## Target Odo version
N/A

Target date:

March 24, 2023

**Comment by kim-tsao** [comment]
Opened up issue to investigate why the scans are not running for registry-operator https://github.com/devfile/api/issues/1108
