### ISSUE TITLE
Add sample testing to nightly test automation in devfile registry

### ISSUE THREAD

**Issue by elsony** [devfile/api#1059]
## Which area/kind this issue is related to?
/area registry

## Issue Description
The current nightly test run in the devfile registry only test for the stacks but there is no sample coverage. We need to add the sample tests to the nightly to catch any problems related to the samples due to change in the starter projects.

## Target Odo version
N/A

> Target Odo version:

**Comment by michael-valdron** [comment]
This might have some overlap with #1142, I'd say we should preserve this one.

cc: @elsony

**Comment by michael-valdron** [comment]
https://github.com/devfile/registry/pull/195 covers part of this though there is still some additional coverage needed, e.g. testing on starter projects.

**Comment by thepetk** [comment]
We might need to define acceptance criteria for the issue. I'm putting it on waiting for now.

**Comment by michael-valdron** [comment]
> We might need to define acceptance criteria for the issue. I'm putting it on waiting for now.

cc: @elsony

**Comment by michael-valdron** [comment]
#1142 may become a blocker for this issue.
