### ISSUE TITLE
Add dependency check to make sure child devfiles are being tested when parent stack has been changed

### ISSUE THREAD

**Issue by elsony** [devfile/api#1060]
## Which area/kind this issue is related to?
/area registry

## Issue Description
The current PR tests in the devfile registry only test for stacks/samples that have been changed. However, if there are other stacks/samples referring to the changed stacks as parents, the child stacks/samples test does not run.  There is a risk in case the parent stack change may break the depending stacks/samples.

We need to:

1. Set up a dependency tree (auto-generated based on the current registry contents) so that we can easily find out the depending stacks/samples of a given stack.
2. Triggers the child stacks/samples test as part of the PR tests of the parent stacks

## Target Odo version
N/A

**Comment by michael-valdron** [comment]
The initial dependency check work for current child samples is now being tracked under #1142, this issue will now track the continuation of that work to expand to considering additional child stacks/samples not yet part of the community registry.

**Comment by Jdubrick** [comment]
Depends on completion of https://github.com/devfile/api/issues/1142
