### ISSUE TITLE
Create notification on nightly devfile registry test failure

### ISSUE THREAD

**Issue by elsony** [devfile/api#1061]
## Which area/kind this issue is related to?
/area registry

## Issue Description
A nightly test run has been set up to test out all the stacks (samples to be added later as part of https://github.com/devfile/api/issues/1059) to make sure the starter projects are working as expected. However, there is currently no notification sent out to alert the team when the tests failed. A notification should be sent to the team channel when the nightly test run failed.

## Target Odo version
N/A

UPDATE [@thepetk]
## Acceptance Criteria
- [ ] Every nightly run should send a message to team channel in case the workflow fails.
- [ ] The message should follow the following format:
       * Status: {red light emoji} failure
       * Severity: failure - medium
       * Mention `@ app-devfile` in order to take action.
       * Title: Validate stacks
       * Description: Mention Branch and Commit, add a short message and link to logs

**Comment by michael-valdron** [comment]
I think this should be implemented but is not a high priority at this time. I would say we should preserve this issue for now.

cc: @elsony

**Comment by michael-valdron** [comment]
Possible devtools week item.

**Comment by thepetk** [comment]
I've added the label for devtools week as this could be a team wide issue for how to handle all alerting for devfiles org

**Comment by thepetk** [comment]
I've updated the issue with the same acceptance criteria as https://github.com/devfile/api/issues/1255
qq: Should we only send a notification on failure. IMO it could also make sense to monitor the job with a notification. The only difference could be that in case of failure we could mention team devfile in order to take action. WDYT?

cc @michael-valdron @elsony

**Comment by thepetk** [comment]
blocked by: https://github.com/devfile/api/issues/1026

**Comment by thepetk** [comment]
Removing blocked label as I don't think is relevant anymore

**Comment by thepetk** [comment]
PR https://github.com/devfile/registry/pull/279 is now ready for review
