### ISSUE TITLE
Viewer support for deprecated devfile stacks and samples

### ISSUE THREAD

**Issue by kim-tsao** [devfile/api#1064]
/kind user-story

## Which area this user story is related to?

/area registry-viewer

## User Story

As an devfile client, I want to be able to determine if the devfiles I'm using are currently supported or deprecated so that I can build my applications knowing that I am using an actively maintained devfile.  

## Approach

<img width="693" alt="image" src="https://github.com/devfile/api/assets/84398375/1949cf64-8c3b-49ab-9909-ae7a37643794">

The registry viewer currently displays the tag but it doesn't do anything special with it.  In order to bring attention to the deprecated devfile, we should:

- Ensure the `Deprecated` tag is the first tag on the list and is displayed in a different colour
- ~The tags are pulled from all devfile versions of a specific runtime which is incorrect.  It should only display the tags for a specific runtime version.~ 
- ~Similarly, the tags shown on the registry viewer tiles represent tags from all runtime versions when it should only display the tags for the default devfile.  This means if the default devfile is not deprecated, then the deprecated tag should not show up.  Users would only see it if they click on the tile and toggle between versions.~
- ~Blocked by bug https://github.com/devfile/api/issues/1289~

## Acceptance Criteria

We should implement something similar to what the [Redhat Catalog](https://catalog.redhat.com/software/containers/search) has.  

- [ ] Display the Deprecated tag first always and on different color (red)
- [ ] Add a deprecated toggle (off by default) to hide the deprecated devfiles
- [ ] If default is deprecated the entire stack should be

**Comment by thepetk** [comment]
Blocked by https://github.com/devfile/api/issues/1065 as it has to be completed before starting this one

**Comment by michael-valdron** [comment]
> Blocked by #1065 as it has to be completed before starting this one

Blocked by ~~#1065~~ #959 as it has to be completed before starting this one

**Comment by thepetk** [comment]
@kim-tsao we have updated the viewer behavior and atm we are:

* Adding a different (red) color to the `Deprecated` label
* The viewer has been fixed and now we show tags per version.

Should we update the current issue only for the prioritization of the `Deprecated` label, which I think is also a potential `good first issue`?

**Comment by thepetk** [comment]
> > Blocked by #1065 as it has to be completed before starting this one
> 
> Blocked by ~#1065~ #959 as it has to be completed before starting this one

@michael-valdron I was wondering if the #959 is a blocker or maybe it is better to create a toggle only on the viewer side. More detailed:

* The viewer will have to take all the samples and stacks with one call to the registry API.
* After the first call the viewer will have all the required information (which is also the case right now) so it can just filter out the deprecated stacks by default.

**Comment by thepetk** [comment]
Removed `blocked` as the bug issue has been fixed

**Comment by thepetk** [comment]
The only two items remaining to be done for this issue are:

1. Display the Deprecated tag first always and on different color (red)
2. Add a deprecated toggle (off by default) to hide the deprecated devfiles
