### ISSUE TITLE
Clarification on image `BuildConfig` files

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1074]
## Which area this feature is related to?

/area documentation

## Which area is this documentation change is related to?

/area api

## Issue details

**What mistake did you find / what is missing in the documentation?**

Currently, the documentation does not provide clarification for new users how a [`BuildConfig`](https://docs.openshift.com/container-platform/4.12/cicd/builds/understanding-image-builds.html) file for building container images differs from a devfile, only provides limited instruction on how a devfile uses a `BuildConfig` file such as with a `Dockerfile` in '[Adding an image component](https://devfile.io/docs/2.2.0/adding-an-image-component)', and does not provide what `BuildConfig` devfiles support (currently only dockerfiles).

Here is what is needed to clarify:
1. What a devfile is that a `BuildConfig` is not and vice versa
2. Brief showcase of how a `BuildConfig` can be references in a devfile using the kubernetes component
3. Brief showcase of how to migrate from `BuildConfig` and move all information within the devfile
4. What `BuildConfig` file(s) are supported by devfiles (e.g. what elements in `BuildConfig` are supported).

**Comment by michael-valdron** [comment]
Due to the backlog of items in this past sprint, this issue will be targeted for completion in the upcoming sprint.

**Comment by michael-valdron** [comment]
This is a future addition that is planned to occur and part of a ongoing epic, removing the stale status.

**Comment by maysunfaisal** [comment]
We decided to move it as a devtools week item
