### ISSUE TITLE
Update Python samle image tag

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1075]
## Which area/kind this issue is related to?

/area registry

## Issue Description
We should update the image tag of Python registry sample in order not to use the `latest` tag and have a more specific one.

**Comment by arewm** [comment]
What is the rationale behind pinning to a specific version? This pinned image is now months old and has a C container grade. If `latest` were used, then it would have been updated as recently as yesterday: https://catalog.redhat.com/software/containers/ubi9/python-39/61a61032bfd4a5234d59629e?

**Comment by thepetk** [comment]
Hey @arewm I think we can track the discussion in the more generic issue which is here: https://github.com/devfile/api/issues/849 and it mentions all images :)
