### ISSUE TITLE
Reorganization of the doc pages

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1079]
## Which area this feature is related to?

/area documentation

## Which area is this documentation change is related to?

/area landing-page

## Issue details

**What mistake did you find / what is missing in the documentation?**

After reviewing the organization of our doc pages it has become clear that there is a few items of reorganization to be done:

1. The ordering of our doc page sections needs changing
    - e.g. **Getting Started** should be second in the ordering after the **Introduction** section
2. Review of doc page / section assignment. The order of the sections on the left should be in the order that we think a typical user will read from the top.
    1. Devfile perspective pages *Application developer*, *Enterprise architect and runtime provider*, and *Registry administrator* and *Technology and tool builders* should be under the **General** rather than **Getting Started**. They should be group together as persona docs that are probably referred to at the end of the ***Devfile ecosystem**
    2. Move **Devfile ecosystem to under **General** as well
    3. Move **General** to the third section after **Getting Started**
    4. Move **API reference** after **General**
    5. Move existing **General**, **Events**, **Components**, **Commands** to 2nd level section and group them under a new section of **Authoring devfiles**
    6. Move **Creating devfiles with templates** and **Innerloop versus outerloop** to the new first level **General** section, i.e. same level as **Devfile ecosystem**
6. Any other changes needed such as section renaming or adding/removal of sections

**Target Date: 2023-04-05**

**Comment by mike-hoang** [comment]
_03/28_
sorting content; some duplicated info with the Introduction and Get Started section

**Comment by mike-hoang** [comment]
explored alternatives to adding a second layer of side bar nav (i.e. using overview page in detailed authoring section to link in higher level overview page)

will need to sort some details in the authoring devfile section needs to be sorted
