### ISSUE TITLE
Provide proxy support for git clone in the devfile library

### ISSUE THREAD

**Issue by kim-tsao** [devfile/api#1088]
## Which area this feature is related to?

/kind bug

### Which area this bug is related to?

 /area library

## Bug Summary

**Describe the bug:**

The devfile library is consumed by ODC which requires proxy support.  Currently, most of the URL requests are made via a custom HTTP Transport which ensures proxies are handled but since we introduced the ability to download resources from parent devfiles via a git clone CLI mechanism, we need to ensure this call is also proxied to avoid breaking ODC.  

**To Reproduce:**

**Comment by maysunfaisal** [comment]
TIP: Scan ODC codebase to see how they handle proxy support for git operations

**Comment by maysunfaisal** [comment]
Proxy setup documentation: https://docs.google.com/document/d/19lCV5XajuO7ZZKiHvVcqer76XrE3bAw9l94aoq0whlM/edit?pli=1#heading=h.fzwm1jrxff34

**Comment by thepetk** [comment]
Spike issue has been created here https://github.com/devfile/api/issues/1445. Adding the `blocked` label as it needs the spike issue to be completed before refinement.
