### ISSUE TITLE
Devfile API repo missing license header

### ISSUE THREAD

**Issue by yangcao77** [devfile/api#1104]
## Which area/kind this issue is related to?

/area ci
/area api

## Issue Description

code under devfile/api are missing license header. 
this issue is expecting all files have license added, and similar as other repos, create script to auto-adding the header, and also create a check in CI

## Acceptance Criteria

- [x] All files have license added
- [x] Create script to auto-adding the header
- [x] Create a check in CI

refined by: @michael-valdron

**Comment by michael-valdron** [comment]
license header file and add headers script included with documentation on these. https://github.com/devfile/api/pull/1256 is ready for review.

**Comment by michael-valdron** [comment]
Addressed review feedback: https://github.com/devfile/api/pull/1256#issuecomment-1723574934
- https://github.com/devfile/api/pull/1256#issuecomment-1724311504
- https://github.com/devfile/api/pull/1256#issuecomment-1724609500
- https://github.com/devfile/api/pull/1256#issuecomment-1724617800

**Comment by michael-valdron** [comment]
Addressed review feedback: https://github.com/devfile/api/pull/1256#discussion_r1330654942

Ready for re-review.

cc: @maysunfaisal @yangcao77

**Comment by michael-valdron** [comment]
> and also create a check in CI

Noticed this as an acceptance criteria, moving back in progress to include this under the [PR](https://github.com/devfile/api/pull/1256).

**Comment by michael-valdron** [comment]
> > and also create a check in CI
> 
> Noticed this as an acceptance criteria, moving back in progress to include this under the [PR](https://github.com/devfile/api/pull/1256).

[Changes addressed](https://github.com/devfile/api/pull/1256#issuecomment-1730291413) are ready for review.

cc: @maysunfaisal @yangcao77
