### ISSUE TITLE
Create OWNERS file for registry operator

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1105]
## Which area/kind this issue is related to?

/area registry

## Issue Description

[devfile/registry-operator](https://github.com/devfile/registry-operator) is missing the `OWNERS` file to define reviewers and approvers for this repository. This file should contain the up to date reviewers and approvers for the registry operator and the following line at the top of the file:

```yaml
# See the OWNERS docs: https://git.k8s.io/community/contributors/guide/owners.md
```

**Comment by kim-tsao** [comment]
This is a dup of https://github.com/devfile/api/issues/1027.  PR https://github.com/devfile/registry-operator/pull/43 should take care of this
