### ISSUE TITLE
Registry operator should be in sync with operator SDK releases

### ISSUE THREAD

**Issue by kim-tsao** [devfile/api#1106]
/kind user-story

## Which area this user story is related to?

 /area registry

## User Story

As a registry operator provider, I want to ensure the operator sdk is kept up to date and in sync with supported k8s and go versions so there is no breakage when running makefile commands. 

## Acceptance Criteria

- [x] When updating k8s and go versions, we need to monitor compatibility with the operator SDK version: https://sdk.operatorframework.io/docs/upgrading-sdk-version/ and perform any migration if necessary
- [x] We need to ensure these changes are tested on Openshift and Kubernetes
- [x] Ensure README and Release notes are documented with this changes

**Target Date: 08-31-2023**

**Comment by kim-tsao** [comment]
related to epic: https://github.com/devfile/api/issues/1007

**Comment by michael-valdron** [comment]
Matching status of https://github.com/devfile/api/issues/1007

**Comment by michael-valdron** [comment]
Is there anything further information needed for this issue to be ready for a sprint?

cc: @kim-tsao

**Comment by michael-valdron** [comment]
Need to start next sprint due to giving focus towards completion of other tasks.

**Comment by michael-valdron** [comment]
Adding all changes needed for `go/v3` to go from previous version of the operator sdk v1.22 to the current version v1.26:
- [v1.23.0 changes](https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.23.0/)
- [v1.24.0 changes](https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.24.0/)
- [v1.25.0 changes](https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.25.0/)
- [v1.26.0 changes](https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.26.0/)

**Comment by michael-valdron** [comment]
Troubleshooting problem:
```
E0731 23:31:10.200109       1 leaderelection.go:330] error retrieving resource lock registry-operator-system/1984829e.devfile.io: leases.coordination.k8s.io "1984829e.devfile.io" is forbidden: User "system:serviceaccount:registry-operator-system:registry-operator-default" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "registry-operator-system"
2023-07-31T23:31:11Z    DEBUG   controller-runtime.webhook.webhooks     received request        {"webhook": "/mutate-registry-devfile-io-v1alpha1-devfileregistry", "UID": "cf3aafb5-a4b7-4e10-996b-9cfac32ca8d8", "kind": "registry.devfile.io/v1alpha1, Kind=DevfileRegistry", "resource": {"group":"registry.devfile.io","version":"v1alpha1","resource":"devfileregistries"}}
2023-07-31T23:31:11Z    INFO    devfileregistry-resource        default {"name": "devfile-registry"}
2023-07-31T23:31:11Z    DEBUG   controller-runtime.webhook.webhooks     wrote response  {"webhook": "/mutate-registry-devfile-io-v1alpha1-devfileregistry", "code": 200, "reason": "", "UID": "cf3aafb5-a4b7-4e10-996b-9cfac32ca8d8", "allowed": true}
2023-07-31T23:31:11Z    DEBUG   controller-runtime.webhook.webhooks     received request        {"webhook": "/validate-registry-devfile-io-v1alpha1-devfileregistry", "UID": "e6a73772-32d8-48f7-8515-d4515ea39b3e", "kind": "registry.devfile.io/v1alpha1, Kind=DevfileRegistry", "resource": {"group":"registry.devfile.io","version":"v1alpha1","resource":"devfileregistries"}}
2023-07-31T23:31:11Z    INFO    devfileregistry-resource        validate create {"name": "devfile-registry"}
2023-07-31T23:31:11Z    DEBUG   controller-runtime.webhook.webhooks     wrote response  {"webhook": "/validate-registry-devfile-io-v1alpha1-devfileregistry", "code": 200, "reason": "", "UID": "e6a73772-32d8-48f7-8515-d4515ea39b3e", "allowed": true}
```

**Comment by michael-valdron** [comment]
> Adding all changes needed for `go/v3` to go from previous version of the operator sdk v1.22 to the current version v1.26

Current version of the operator sdk actually should be v1.28: https://github.com/devfile/registry-operator/blob/dea070ae240936e290c59e7a1490d836137cbc7d/README.md?plain=1#L30

Adding all `go/v3` changes needed for v1.26 to v1.28:
- [v1.27.0 changes](https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.27.0/) (*no changes*)
- [v1.28.0 changes](https://sdk.operatorframework.io/docs/upgrading-sdk-version/v1.28.0/)

**Comment by michael-valdron** [comment]
> Troubleshooting problem:
> 
> ```
> E0731 23:31:10.200109       1 leaderelection.go:330] error retrieving resource lock registry-operator-system/1984829e.devfile.io: leases.coordination.k8s.io "1984829e.devfile.io" is forbidden: User "system:serviceaccount:registry-operator-system:registry-operator-default" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "registry-operator-system"
> 2023-07-31T23:31:11Z    DEBUG   controller-runtime.webhook.webhooks     received request        {"webhook": "/mutate-registry-devfile-io-v1alpha1-devfileregistry", "UID": "cf3aafb5-a4b7-4e10-996b-9cfac32ca8d8", "kind": "registry.devfile.io/v1alpha1, Kind=DevfileRegistry", "resource": {"group":"registry.devfile.io","version":"v1alpha1","resource":"devfileregistries"}}
> 2023-07-31T23:31:11Z    INFO    devfileregistry-resource        default {"name": "devfile-registry"}
> 2023-07-31T23:31:11Z    DEBUG   controller-runtime.webhook.webhooks     wrote response  {"webhook": "/mutate-registry-devfile-io-v1alpha1-devfileregistry", "code": 200, "reason": "", "UID": "cf3aafb5-a4b7-4e10-996b-9cfac32ca8d8", "allowed": true}
> 2023-07-31T23:31:11Z    DEBUG   controller-runtime.webhook.webhooks     received request        {"webhook": "/validate-registry-devfile-io-v1alpha1-devfileregistry", "UID": "e6a73772-32d8-48f7-8515-d4515ea39b3e", "kind": "registry.devfile.io/v1alpha1, Kind=DevfileRegistry", "resource": {"group":"registry.devfile.io","version":"v1alpha1","resource":"devfileregistries"}}
> 2023-07-31T23:31:11Z    INFO    devfileregistry-resource        validate create {"name": "devfile-registry"}
> 2023-07-31T23:31:11Z    DEBUG   controller-runtime.webhook.webhooks     wrote response  {"webhook": "/validate-registry-devfile-io-v1alpha1-devfileregistry", "code": 200, "reason": "", "UID": "e6a73772-32d8-48f7-8515-d4515ea39b3e", "allowed": true}
> ```

This was a result of the [`namePrefix`](https://github.com/devfile/registry-operator/blob/dea070ae240936e290c59e7a1490d836137cbc7d/config/default/kustomization.yaml#L9) not applying correctly to reference fields. Need to investigate further to decide on a solution going forward, for now the short term fix seems to be assuming this prefix will not be applied to references and manually setting the prefix in with the base name seems to work.

**Comment by michael-valdron** [comment]
Continuing in Sprint 245 due to vacation leave.

**Comment by thepetk** [comment]
Moving item to 245 as requested

**Comment by michael-valdron** [comment]
> > Troubleshooting problem:
> > ```
> > E0731 23:31:10.200109       1 leaderelection.go:330] error retrieving resource lock registry-operator-system/1984829e.devfile.io: leases.coordination.k8s.io "1984829e.devfile.io" is forbidden: User "system:serviceaccount:registry-operator-system:registry-operator-default" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "registry-operator-system"
> > 2023-07-31T23:31:11Z    DEBUG   controller-runtime.webhook.webhooks     received request        {"webhook": "/mutate-registry-devfile-io-v1alpha1-devfileregistry", "UID": "cf3aafb5-a4b7-4e10-996b-9cfac32ca8d8", "kind": "registry.devfile.io/v1alpha1, Kind=DevfileRegistry", "resource": {"group":"registry.devfile.io","version":"v1alpha1","resource":"devfileregistries"}}
> > 2023-07-31T23:31:11Z    INFO    devfileregistry-resource        default {"name": "devfile-registry"}
> > 2023-07-31T23:31:11Z    DEBUG   controller-runtime.webhook.webhooks     wrote response  {"webhook": "/mutate-registry-devfile-io-v1alpha1-devfileregistry", "code": 200, "reason": "", "UID": "cf3aafb5-a4b7-4e10-996b-9cfac32ca8d8", "allowed": true}
> > 2023-07-31T23:31:11Z    DEBUG   controller-runtime.webhook.webhooks     received request        {"webhook": "/validate-registry-devfile-io-v1alpha1-devfileregistry", "UID": "e6a73772-32d8-48f7-8515-d4515ea39b3e", "kind": "registry.devfile.io/v1alpha1, Kind=DevfileRegistry", "resource": {"group":"registry.devfile.io","version":"v1alpha1","resource":"devfileregistries"}}
> > 2023-07-31T23:31:11Z    INFO    devfileregistry-resource        validate create {"name": "devfile-registry"}
> > 2023-07-31T23:31:11Z    DEBUG   controller-runtime.webhook.webhooks     wrote response  {"webhook": "/validate-registry-devfile-io-v1alpha1-devfileregistry", "code": 200, "reason": "", "UID": "e6a73772-32d8-48f7-8515-d4515ea39b3e", "allowed": true}
> > ```
> 
> This was a result of the [`namePrefix`](https://github.com/devfile/registry-operator/blob/dea070ae240936e290c59e7a1490d836137cbc7d/config/default/kustomization.yaml#L9) not applying correctly to reference fields. Need to investigate further to decide on a solution going forward, for now the short term fix seems to be assuming this prefix will not be applied to references and manually setting the prefix in with the base name seems to work.

Continuing to use full account and namespace names under role bindings.

**Comment by michael-valdron** [comment]
> > > Troubleshooting problem:
> > > ```
> > > E0731 23:31:10.200109       1 leaderelection.go:330] error retrieving resource lock registry-operator-system/1984829e.devfile.io: leases.coordination.k8s.io "1984829e.devfile.io" is forbidden: User "system:serviceaccount:registry-operator-system:registry-operator-default" cannot get resource "leases" in API group "coordination.k8s.io" in the namespace "registry-operator-system"
> > > 2023-07-31T23:31:11Z    DEBUG   controller-runtime.webhook.webhooks     received request        {"webhook": "/mutate-registry-devfile-io-v1alpha1-devfileregistry", "UID": "cf3aafb5-a4b7-4e10-996b-9cfac32ca8d8", "kind": "registry.devfile.io/v1alpha1, Kind=DevfileRegistry", "resource": {"group":"registry.devfile.io","version":"v1alpha1","resource":"devfileregistries"}}
> > > 2023-07-31T23:31:11Z    INFO    devfileregistry-resource        default {"name": "devfile-registry"}
> > > 2023-07-31T23:31:11Z    DEBUG   controller-runtime.webhook.webhooks     wrote response  {"webhook": "/mutate-registry-devfile-io-v1alpha1-devfileregistry", "code": 200, "reason": "", "UID": "cf3aafb5-a4b7-4e10-996b-9cfac32ca8d8", "allowed": true}
> > > 2023-07-31T23:31:11Z    DEBUG   controller-runtime.webhook.webhooks     received request        {"webhook": "/validate-registry-devfile-io-v1alpha1-devfileregistry", "UID": "e6a73772-32d8-48f7-8515-d4515ea39b3e", "kind": "registry.devfile.io/v1alpha1, Kind=DevfileRegistry", "resource": {"group":"registry.devfile.io","version":"v1alpha1","resource":"devfileregistries"}}
> > > 2023-07-31T23:31:11Z    INFO    devfileregistry-resource        validate create {"name": "devfile-registry"}
> > > 2023-07-31T23:31:11Z    DEBUG   controller-runtime.webhook.webhooks     wrote response  {"webhook": "/validate-registry-devfile-io-v1alpha1-devfileregistry", "code": 200, "reason": "", "UID": "e6a73772-32d8-48f7-8515-d4515ea39b3e", "allowed": true}
> > > ```
> > 
> > 
> > This was a result of the [`namePrefix`](https://github.com/devfile/registry-operator/blob/dea070ae240936e290c59e7a1490d836137cbc7d/config/default/kustomization.yaml#L9) not applying correctly to reference fields. Need to investigate further to decide on a solution going forward, for now the short term fix seems to be assuming this prefix will not be applied to references and manually setting the prefix in with the base name seems to work.
> 
> Continuing to use full account and namespace names under role bindings.

Resolved these errors by using a different service account name for the operator, previously using the `default` service account.

**Comment by michael-valdron** [comment]
Multi arch build and push rule `docker-buildx` fixed up, this rule only supports docker: https://github.com/devfile/registry-operator/pull/45/commits/f73ea53aab3520c2952c8ad133dcaf58a8278e8a

**Comment by michael-valdron** [comment]
Need to merge https://github.com/openshift/release/pull/42759 before proceeding.

**Comment by michael-valdron** [comment]
> Need to merge [openshift/release#42759](https://github.com/openshift/release/pull/42759) before proceeding.

[openshift/release#42759](https://github.com/openshift/release/pull/42759) has been merged, unblocked.

**Comment by michael-valdron** [comment]
Set back with unexpected integration test errors on the OpenShift CI: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/devfile_registry-operator/45/pull-ci-devfile-registry-operator-main-v4.12-registry-operator-integration-test/1696556383018684416

**Comment by michael-valdron** [comment]
Testing is failing possibly due to missed Ginkgo V2 changes for creating a timeout to allow the test devfile registries to deploy.

**Comment by michael-valdron** [comment]
> Testing is failing possibly due to missed Ginkgo V2 changes for creating a timeout to allow the test devfile registries to deploy.

This does not seem to be the case, the integration tests seem to fail if the operator is deployed during `make test-integration` rather than separately by running `make install && make deploy` beforehand.

**Comment by feloy** [comment]
> > Testing is failing possibly due to missed Ginkgo V2 changes for creating a timeout to allow the test devfile registries to deploy.
> 
> This does not seem to be the case, the integration tests seem to fail if the operator is deployed during `make test-integration` rather than separately by running `make install && make deploy` beforehand.
> 
> ```
> Pod registry-operator-controller-manager-75f6b6dcf8-9cpwt created in namespace registry-operator-system...Checking startup data.
> Pod started after 25.703438619 seconds
> Devfile Registry pod to be ready
> I0830 12:31:53.758728  240169 request.go:690] Waited for 1.047570809s due to client-side throttling, not priority and fairness, request: GET:https://api.crc.testing:6443/apis/authorization.openshift.io/v1?timeout=32s
> exit status 1
> exit status 1
> ------------------------------
> • [FAILED] [2.105 seconds]
> [Create Devfile Registry resource with headless enabled] [It] Should deploy a headless devfile registry on to the cluster
> /home/mvaldron/source/repos/michael-valdron/devfile-registry-operator/tests/integration/pkg/tests/devfileregistry_tests.go:120
> 
>   [FAILED] Failed to create devfileregistry instance: exit status 1
>   In [It] at: /home/mvaldron/source/repos/michael-valdron/devfile-registry-operator/tests/integration/pkg/tests/devfileregistry_tests.go:127 @ 08/30/23 12:31:57.032
> ------------------------------
> SSS
> 
> Summarizing 1 Failure:
>   [FAIL] [Create Devfile Registry resource with headless enabled] [It] Should deploy a headless devfile registry on to the cluster
>   /home/mvaldron/source/repos/michael-valdron/devfile-registry-operator/tests/integration/pkg/tests/devfileregistry_tests.go:127
> 
> Ran 1 of 4 Specs in 43.097 seconds
> FAIL! -- 0 Passed | 1 Failed | 0 Pending | 3 Skipped
> ```

I probably encountered the same problem when testing the operator, working on #46. I have seen that if the operator is not deployed before running `make test-integration`, the operator is started at the beginning of the tests, but the Pod does not have the time to completely start, and the tests fail due to this.

**Comment by michael-valdron** [comment]
> > > Testing is failing possibly due to missed Ginkgo V2 changes for creating a timeout to allow the test devfile registries to deploy.
> > 
> > 
> > This does not seem to be the case, the integration tests seem to fail if the operator is deployed during `make test-integration` rather than separately by running `make install && make deploy` beforehand.
> > ```
> > Pod registry-operator-controller-manager-75f6b6dcf8-9cpwt created in namespace registry-operator-system...Checking startup data.
> > Pod started after 25.703438619 seconds
> > Devfile Registry pod to be ready
> > I0830 12:31:53.758728  240169 request.go:690] Waited for 1.047570809s due to client-side throttling, not priority and fairness, request: GET:https://api.crc.testing:6443/apis/authorization.openshift.io/v1?timeout=32s
> > exit status 1
> > exit status 1
> > ------------------------------
> > • [FAILED] [2.105 seconds]
> > [Create Devfile Registry resource with headless enabled] [It] Should deploy a headless devfile registry on to the cluster
> > /home/mvaldron/source/repos/michael-valdron/devfile-registry-operator/tests/integration/pkg/tests/devfileregistry_tests.go:120
> > 
> >   [FAILED] Failed to create devfileregistry instance: exit status 1
> >   In [It] at: /home/mvaldron/source/repos/michael-valdron/devfile-registry-operator/tests/integration/pkg/tests/devfileregistry_tests.go:127 @ 08/30/23 12:31:57.032
> > ------------------------------
> > SSS
> > 
> > Summarizing 1 Failure:
> >   [FAIL] [Create Devfile Registry resource with headless enabled] [It] Should deploy a headless devfile registry on to the cluster
> >   /home/mvaldron/source/repos/michael-valdron/devfile-registry-operator/tests/integration/pkg/tests/devfileregistry_tests.go:127
> > 
> > Ran 1 of 4 Specs in 43.097 seconds
> > FAIL! -- 0 Passed | 1 Failed | 0 Pending | 3 Skipped
> > ```
> 
> I probably encountered the same problem when testing the operator, working on #46. I have seen that if the operator is not deployed before running `make test-integration`, the operator is started at the beginning of the tests, but the Pod does not have the time to completely start, and the tests fail due to this.

I suspect the same thing, it looks like in the integration test suite we are checking if the pod is running but not if the pod is ready: https://github.com/devfile/registry-operator/blob/9ac99619807eccb75f0cdfff01c189d71c5bd921/tests/integration/pkg/client/pod.go#L66

For this issue I'm trying a short term fix https://github.com/michael-valdron/devfile-registry-operator/blob/2f45c9e2ec83f7444d13203e8d1f068aee12e184/.ci/openshift_integration.sh#L32, but moving forward we should be checking readiness as well. I'll open an issue for this after I have resolved the current issue.

**Comment by michael-valdron** [comment]
openshift-ci is currently failing during setup of the environment: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/devfile_registry-operator/45/pull-ci-devfile-registry-operator-main-v4.12-registry-operator-integration-test/1696984101262725120

This has pushed the target date for completing this item.
