### ISSUE TITLE
Product Registry is showing community stacks

### ISSUE THREAD

**Issue by kim-tsao** [devfile/api#1111]
## Which area this feature is related to?

/kind bug

### Which area this bug is related to?

 /area registry

The [product registry]( https://devfile-registry.redhat.com/viewer)  is incorrectly displaying the community stacks.  It should only be the JBoss ones

### Go project

**Operating System and version:**

**Go Pkg Version:**

### Node.js project

**Operating System and version:**

**Node.js version:**

**Yarn version:**

**Project.json:**

### Web browser

**Operating System and version:**

**Browser name and version:**

## Bug Summary

**Describe the bug:**

**To Reproduce:**

**Comment by michael-valdron** [comment]
Staging of the product registry does show the correct stacks, therefore this could be isolated to production or fixed in the most recent build: https://devfile-registry.stage.redhat.com/viewer

**Comment by michael-valdron** [comment]
All individuals that would be able to fix this are unavailable for the upcoming sprints due to higher priority items regarding the devfile registry. Fixing this is important so we'll need to keep track of this.

Perhaps we could include this under the upcoming devtools week.

cc: @elsony @mike-hoang @johnmcollier @kim-tsao

**Comment by michael-valdron** [comment]
Waiting for 2024 to review with the team.

**Comment by thepetk** [comment]
Moving back to refinement to be reviewed by the team

**Comment by michael-valdron** [comment]
Since the product registry is planned to be retired https://github.com/devfile/api/issues/1527 and has no further planned promotions that would introduce this bug into the live service, I will close this issue as not planned.
