### ISSUE TITLE
Registry validate stacks test failing on the java-quarkus stack

### ISSUE THREAD

**Issue by mike-hoang** [devfile/api#1115]
## Which area this feature is related to?

/kind bug

### Which area this bug is related to?

/area ci
/area registry

## Bug Summary

**Describe the bug:**

odo v2 and v3 tests are failing on the java-quarkus 1.3.0 stack

## Any logs, error output, screenshots etc? Provide the devfile that sees this bug, if applicable

odo v2: https://github.com/devfile/registry/actions/runs/4879253176/jobs/8705646284#step:7:11186

```
The following tests failed:
name: java-quarkus version: 1.3.0 error: unable to get working url
```

odo v3: https://github.com/devfile/registry/actions/runs/4879253176/jobs/8705645896#step:9:22982

```
Error: : [ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:3.0.2.Final:dev (default-cli) on project code-with-quarkus: Detected Maven Version (3.6.2)  is not supported, it must be in [3.8.2,). -> [Help 1]
Error: : [ERROR] 
Error: : [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
Error: : [ERROR] Re-run Maven using the -X switch to enable full debug logging.
Error: : [ERROR] 
Error: : [ERROR] For more information about the errors and possible solutions, please read the following articles:
Error: : [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by thepetk** [comment]
Same issue was found here: https://github.com/quarkusio/quarkus/issues/23562

**Comment by mike-hoang** [comment]
This failure is no longer seen since run `Validate stacks #437` on 2023/06/07: https://github.com/devfile/registry/actions/runs/5207553312
