### ISSUE TITLE
Failures on the registry validate stack nightly run should notify the team channel

### ISSUE THREAD

**Issue by mike-hoang** [devfile/api#1116]
## Which area this feature is related to?

/area ci
/area registry

## Which functionality do you think we should add?

The `validate stacks` workflow is scheduled to run every day against all the stacks in the registry. When a nightly run fails, there is no alerting that happens.

## Describe the solution you'd like

A failed run should notify our team channel. The [slack-send GitHub action](https://github.com/marketplace/actions/slack-send) can be used.

**Comment by thepetk** [comment]
This item was duplicate of https://github.com/devfile/api/issues/1061 so I think it should remain closed
