### ISSUE TITLE
Create a new devfile component for docker-compose file

### ISSUE THREAD

**Issue by yangcao77** [devfile/api#1120]
/kind user-story

## Which area this user story is related to?

/area api

## User Story
As a developer working on an existing project, I want to be able to have a docker-compose reference in devfile which allows me to provide an existing docker-compose file for the application definition

## Acceptance Criteria

- [x] A new component in devfile API for docker-compose file reference
- [x] validation need to be done for the new component
- [x] new tests for testing the new component
- [ ] documentation for usage and limitation

**Comment by Mahajanet** [comment]
Link to PR: https://github.com/devfile/api/pull/1134
Completed creating the compose component. Currently troubleshooting validation code.

**Comment by yangcao77** [comment]
This issue is currently waiting for the first piece of library support #1122 in order to get the spec change merged
