### ISSUE TITLE
support existing containers, single service & Multi-service with no dependencies

### ISSUE THREAD

**Issue by yangcao77** [devfile/api#1122]
## Which area this feature is related to?

/area library

## Which functionality do you think we should add?

**Why is this needed? Is your feature request related to a problem?**

**Detailed description:**

The docker-compose file is only relying on containers that are already built and available in the container catalog (docker-compose not relying on dockerfiles). We should be able to use the docker-compose file and use its services as components for the devfile.

**Targets:**
We would need to formalize an improvement to the specification, so that it is possible to link devfile components from the docker-compose file - so it'll not be a "conversion" of the docker-compose file to devfile, but a way to use the docker-compose and the devfile together.

**Implementation:** 

Directly use [Kompose](https://github.com/kubernetes/kompose) and convert to a kubernetes component in devfile. 
Document the limitation of the conversion. (will be from Kompose tool)
 
Add a way to refer to a docker-compose file from the devfile, e.g. a docker-compose component element. (should be similar to image component, with a uri reference)
Update the parsing model in the devfile library with a flag, for devfiles with the docker-compose component, convert the docker-compose component to other existing components using the library above, e.g. kubernetes components, and replace the docker-compose component with those generated components

## Describe alternatives you've considered

1) [Podman](https://www.redhat.com/sysadmin/compose-kubernetes-podman): Limited documentation + only available for CLI. 
2) Parsing the inputs, building an intermediate representation, output the desired files: No documentation available + better considered for supporting new container implementation.

**Comment by yangcao77** [comment]
blocked by #1120

**Comment by Mahajanet** [comment]
Investigating [Kompose](https://github.com/kubernetes/kompose/blob/main/cmd/convert.go) repository to import package for use. Adopted new schema + created flag in the parsing module. Working on convertor utils function.

**Comment by amisevsk** [comment]
Potential blocker for this issue: https://github.com/kubernetes/kompose/issues/464

**Comment by Mahajanet** [comment]
In the next release of [Kompose 1.29.0](https://github.com/kubernetes/kompose/pull/1593), there will be in built support to convert docker compose files into kubernetes objects. Presently, using select kompose library functions for conversion.

**Comment by Mahajanet** [comment]
Finished conversion of Docker-Compose to Kube representation, and further conversion to a Kube component. Currently testing for each case (uri + url + inline). Next step will be applying some commands to the components and clean up before a PR.

**Comment by Mahajanet** [comment]
Create a [draft PR](https://github.com/devfile/library/pull/177) detailing the tasks finished and the tasks to be completed next.

**Comment by yangcao77** [comment]
things left to be done:

- cmds associated with the kube components need to be added
- revert back kube components and cmds added when calling `devfileObj.writeYaml`
- clean up for temp folder after the operation or upon errors
- unit tests
