### ISSUE TITLE
support Multi-service with dependencies in separate pod

### ISSUE THREAD

**Issue by yangcao77** [devfile/api#1125]
## Which area this feature is related to?

/area library

## Which functionality do you think we should add?

**Why is this needed? Is your feature request related to a problem?**

**Detailed description:**

The services need to be deployed in expected order, i.e. will be defined by [depend_on](https://docs.docker.com/compose/compose-file/05-services/#depends_on) in the docker-compose file

**Targets:**
The containers will be built and deployed in order. MUST guarantee dependency services have been started before starting a dependent service
The services will be linked.

**Implementation:**

Can use service binding to connect services, see https://docs.openshift.com/container-platform/4.9/applications/connecting_applications_to_services/understanding-service-binding-operator.html

Ensure the commands for execution and deployment are in order.

**Comment by maysunfaisal** [comment]
@yangcao77 do we want to track this on our board?
