### ISSUE TITLE
[Devtools Week] Investigate usage of renovate to keep registry image up-to-date

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1126]
## Which area/kind this issue is related to?

/area registry

## Issue Description

In order to be sure that we the images used from registry stacks are always up-to-date we can investigate a tool like renovate.
More details for renovate here: https://github.com/renovatebot/renovate

## Target Odo version

> Target Odo version:

**Comment by thepetk** [comment]
I've added a renovate bot for my fork, following [this tutorial](https://github.com/renovatebot/tutorial). Investigating usage for the bot with this config: https://github.com/thepetk/registry/blob/main/renovate.json

**Comment by thepetk** [comment]
I'm currently investigating the correct configuration of renovate. A first result can be found here: https://github.com/thepetk/registry/pulls

Notes:

- We cannot update an image that has the latest tag, so it might be better to first merge the (https://github.com/devfile/api/issues/849 -> which is actually blocked from https://github.com/devfile/api/issues/1115).
- We need to define: 
    1. Schedule for those runs (e.g once a day every afternoon)
    2. The quantity of the PRs per time (for example, we may only allow 5 PRs max per run, as it might be overwhelming for the 
person responsible to monitor)
    3. Who will be monitoring the opened PRs. Do we need any assignees on them? Ping someone?

**Comment by thepetk** [comment]
I've listed all images that cannot be updated due to invalid tags:
| image                                          | Version                    |
|------------------------------------------------|----------------------------|
| icr.io/appcafe/websphere-liberty-devfile-stack | {{liberty-version}}-gradle |
| icr.io/appcafe/websphere-liberty-devfile-stack | {{liberty-version}}        |
| icr.io/appcafe/open-liberty-devfile-stack      | {{liberty-version}}-gradle |
| icr.io/appcafe/open-liberty-devfile-stack      | {{liberty-version}}        |
| registry.access.redhat.com/ubi8/openjdk-11     | latest                     |
| quay.io/eclipse/che-java11-maven               | next                       |
| registry.access.redhat.com/ubi8/nodejs-16      | latest                     |
| quay.io/devfile/universal-developer-image      | latest                     |

**Comment by thepetk** [comment]
> We might also need to decide how we will host the bot (most probably we can rely on the mend environment, but it could be also useful to host it ourselves?)

I've checked other configurations of renovate inside `redhat-developer` or `redhat-appstudio` and they are using pretty much the same setup with https://github.com/thepetk/registry/blob/main/renovate.json. So I don't see a need of self hosting etc.

**Comment by michael-valdron** [comment]
> I've listed all images that cannot be updated due to invalid tags:
>
> | image                                          | Version                    |
> |------------------------------------------------|----------------------------|
> | icr.io/appcafe/websphere-liberty-devfile-stack | {{liberty-version}}-gradle |
> | icr.io/appcafe/websphere-liberty-devfile-stack | {{liberty-version}}        |
> | icr.io/appcafe/open-liberty-devfile-stack      | {{liberty-version}}-gradle |
> | icr.io/appcafe/open-liberty-devfile-stack      | {{liberty-version}}        |
> | registry.access.redhat.com/ubi8/openjdk-11     | latest                     |
> | quay.io/eclipse/che-java11-maven               | next                       |
> | registry.access.redhat.com/ubi8/nodejs-16      | latest                     |
> | quay.io/devfile/universal-developer-image      | latest                     |

There might be a PR coming to change `registry.access.redhat.com/ubi8/nodejs-16:latest` into a fixed version tag.

**Comment by thepetk** [comment]
From the above images, if we fix the tag in all of them I see:
- [ ] https://github.com/thepetk/registry/pull/32  -> [Success]
- [ ] https://github.com/thepetk/registry/pull/31 -> [Success]
- [ ] https://github.com/thepetk/registry/pull/36 -> [Success]
- [ ] https://github.com/thepetk/registry/pull/35 -> [Success]
- [ ] https://github.com/thepetk/registry/pull/34 -> [Success]
- [ ] The only image not able to be updated I see is quay.io/devfile/universal-developer-image

**Comment by thepetk** [comment]
I'll now check if there is a way to fix the regex manager and checking as tag the `variable` field for open-liberty cases.

**Comment by thepetk** [comment]
For using it on samples:
* We want to have another renovate bot inside our org for devfile samples.
* The case here is pretty simple. We will only enable dockerfile manager in the configuration and we will only keep updated the tags inside dockerfiles (i think)

**Comment by thepetk** [comment]
Invesigating the update of github-actions (following documentation [here](https://docs.renovatebot.com/modules/manager/github-actions/)). The trickiest part if we want to include renovate to all the repos will be to combine the configuration for devfile with the configuration for github-actions

**Comment by thepetk** [comment]
> Invesigating the update of github-actions (following documentation [here](https://docs.renovatebot.com/modules/manager/github-actions/)). The trickiest part if we want to include renovate to all the repos will be to combine the configuration for devfile with the configuration for github-actions

I see is pretty simple to combine the two actions.

**Github Actions & Renovate**
I've gone through registry and applied the config to update github actions, while also pining the digest to the action.

Results:
- [ ] https://github.com/thepetk/registry/pull/38 > pins digest instead of version

- [ ] https://github.com/thepetk/registry/pull/21
- [ ] https://github.com/thepetk/registry/pull/15

As we are not using digest, the first PR is dedicated to pin digest everywhere so as a first time it might conflicts with the updates.

**Comment by thepetk** [comment]
FInal thing to investigate before opening a PR, is if the usage of packageRules will improve the configuration of renovate

**Comment by thepetk** [comment]
As a result of this investigation issue, I'd say that we should add a renovate bot in our repos. Moreover:

**Registry Images Update**
For images mentioned inside devfiles, I've tried using a custom `regexManager` which only checks for dependency updates inside a `devfile.y[a]ml` file and tries to find an `image :` string to check for any dependency updates.

Every new update has its own PR, as it might need different approach on testing etc.

Note, that renovate cannot update tags that have `latest` or `next` as value. The value has to be a valid version. As a result **some of the images inside stacks have to be updated and use fixed tags**. For the record, during investigation I have tried to fix the version in my fork and everything was being updated correctly.

Some of the PRs we will see on the first run right now on registry would be:
- [ ] https://github.com/thepetk/registry/pull/9
- [ ] https://github.com/thepetk/registry/pull/10
- [ ] https://github.com/thepetk/registry/pull/12
- [ ] https://github.com/thepetk/registry/pull/13

**Github Actions Update**
For github actions I've introduced the `github-actions` manager and I've included all these updates into the same group as a `packageRule` (it helps reduce the noise from many different PRs opened). This way we will see each time only one PR opened. One more addition is to extend the `renovate.json` file to use the `helpers:pinGitHubActionDigests` in order to use digest instead of versions.

An example of github actions PR would be:
- [ ] https://github.com/thepetk/registry/pull/51

**Configuration of Renovate**
As I've seen in other issues inside `redhat-developer` and `redhat-appstudio` orgs, we are not self hosting the renovate bot and most of the configuration files don't have a schedule defined. Some points of interest could be:

* Do we need a specific schedule for renovate runs?
* Do we need a limit for PR created by the bot?

**Automatic Alizer Update**
For alizer, as it is a go module used by another application we can follow [this docs](https://docs.renovatebot.com/modules/manager/gomod/) and using a `packageRule` for alizer only.

**Next steps**
As a next step for renovate bot we should add the renovate bot to `devfiles` organization (if we want to include samples it should be added to this org too). For HAS the renovate bot is already running on its organization on github so we will just have to add a renovate.json file (for github-actions).

The bot creation process requires a specific level of access to the org and is pretty simple following [this guide](https://docs.renovatebot.com/getting-started/installing-onboarding/).

**Comment by thepetk** [comment]
I've created a new issue, dedicated only to next steps sections (#1133)
