### ISSUE TITLE
Getting unexpected error responses when using minSchemaVersion or maxSchemaVersion

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1128]
## Which area this feature is related to?

/kind bug

### Which area this bug is related to?

/area registry

### Go project

**Operating System and version:** N/A

**Go Pkg Version:** 1.18

## Bug Summary

While working on https://github.com/redhat-developer/alizer/issues/226 I've experienced a 500 error when I've tried to use a URL params for minSchemaVersion and maxSchemaVersion. More detailed when I've tried to use a version older than 2.x or with 3 digits like 2.x.x I'm getting a 500 response.

This error might be existing due to this code: https://github.com/devfile/registry-support/blob/200b4f015149a2c23314ea2ef83711869e4d09c9/index/server/pkg/server/endpoint.go#L432

Adding this as a bug, as I would expect a 400 status code instead of 500. Additionally I think we should might add the range of accepted versions here: https://github.com/devfile/registry-support/blob/main/index/server/registry-REST-API.adoc#query-parameters

**To Reproduce:**

**Reproduces error for passing three digit devfile version:**
```sh
curl -o - -i http://devfile-registry.192.168.1.1.nip.io/v2index?minSchemaVersion=2.1&maxSchemaVersion=2.1.9
```

**Reproduces unexpected 500 internal server error:**
```sh
curl -o - -i "https://registry.devfile.io/v2index?minSchemaVersion=1.1&maxSchemaVersion=1.4"
```

## Expected behavior

1. I was expecting a 400 status code response in case of not accepted URL query param.
2. I was expecting to be able to use the full devfile version number.

### Any workaround?

None.

### Suggestion on how to fix the bug

Fix validation to allow the optional use of the bugfix part of the devfile version number and the response for invalid request parameters should be changed from 500 internal server error to 400 bad request.

**Target Date: 06-27-2023**

**Comment by thepetk** [comment]
I've added the `blocked` label to https://github.com/redhat-developer/alizer/issues/226 as it requires first to have this issue completed

**Comment by michael-valdron** [comment]
Schema version validation error responses now will return error code `400` bad request instead of `500` internal server error. In addition, the API endpoints now will allow both `2.2` and `2.2.0` for the schema version parameters. https://github.com/devfile/registry-support/commit/9e8694b1383fe7fd2b2661dc7cbd5e398067c866

**Comment by michael-valdron** [comment]
Added test cases for these changes and an open PR is ready for review: https://github.com/devfile/registry-support/pull/174
