### ISSUE TITLE
Change the default support to devfile 2.2 for stacks that supports both devfile 2.1 and devfile 2.2 in devfile community registry

### ISSUE THREAD

**Issue by elsony** [devfile/api#1129]
/kind user-story

## Which area this user story is related to?
/area registry

## User Story

As an application developer, I want to use the newest devfile version on my application development by default, so that I can take advantage of the function in the latest specification version. 

Some of the existing stacks in the community devfile registry, e.g. spring boot, has different versions of the stacks using devfile 2.1 and 2.2. In the past, we keep the older devfile version one, e.g. devfile 2.1, as the default stack since not all tools support devfile 2.2. As discussed on the devfile community call on May 29, we'll move the default stack to use devfile 2.2 if a given stack have different versions of the stacks that supports both 2.1 and 2.2 version of the devfile schema.

## Acceptance Criteria
- [ ] For stacks that support both devfile 2.1 and devfile 2.2, switch the default version to the one that uses devfile 2.2
- [ ] Give heads up on the public community before moving a given stack for advanced notice
- [ ] Test out the change with existing starter projects and samples in the devfile entries
- [ ] Test out on odc and RHTAP to make sure the change does not causes regression on existing products

**Comment by thepetk** [comment]
Removing stale label, as I think this issue remains important
