### ISSUE TITLE
Add renovate to devfiles registry

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1133]
## Which area this feature is related to?

/area registry
/area documentation

## Which functionality do you think we should add?

After the investigation during devtools week 6-2023 we should include a renovate bot check to our registry repository, in order to automatically update the image tags used by the stacks inside the registry.

**Why is this needed? Is your feature request related to a problem?**

This addition will automate the process of image tags update and will keep all stack images up-to-date.

**Detailed description:**

The results of the previous investigation of issue #1126 are here: https://github.com/devfile/api/issues/1126#issuecomment-1584563306

## Related tasks

- [x] #1137
- [x] https://github.com/devfile/api/issues/1202
- [x] #1138
- [x] #1139

**Comment by thepetk** [comment]
Regarding the usage of an existing bot I'd rather create a proper renovate bot, having in mind that this is the case for redhat-developer and redhat-appstudio organizations.

**Comment by thepetk** [comment]
I've shared our proposed solution to other interested devs in order to review our configuration.

**Comment by lmilbaum** [comment]
You are welcome to use the already existing self-hosted renovate runner - https://github.com/platform-engineering-org/renovate-runner

**Comment by thepetk** [comment]
Adding also the comment from #1139 (https://github.com/devfile/api/issues/1139#issuecomment-1628108711)

**Comment by thepetk** [comment]
@lmilbaum thank you for your input, it helps a lot! :)
One question that I have is: Could you share more details about the benefits of self-hosting the renovate bot instead of using the default one from mend.io?

**Comment by thepetk** [comment]
After consideration for a self hosted renovate runner I've created the #1202 in order to see which is the best option for this automation.

**Comment by thepetk** [comment]
The two main steps are now ready to work on:
- Add a PR for renovate to registry repo
- Update documentation for stack owners

**Comment by thepetk** [comment]
Closing the existing item as now the registry supports the PRs from renovate. Created an item for all other repos regarding the updates of the github-actions https://github.com/devfile/api/issues/1278
