### ISSUE TITLE
Check non-terminating images job fails after some time of run

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1135]
## Which area this feature is related to?

/kind bug

### Which area this bug is related to?

/area ci
/area registry
/area test-automation

### Go project

**Operating System and version:**

**Go Pkg Version:**

### Node.js project

**Operating System and version:**

**Node.js version:**

**Yarn version:**

**Project.json:**

### Web browser

**Operating System and version:**

**Browser name and version:**

## Bug Summary

**Describe the bug:**
The post-merge check for non-terminating images fails for unknown reason after ~33min of running.
More detailed, this occurred after the merge of https://github.com/devfile/registry/pull/183 where we have updated five images (fixed their image tag):

- stacks/java-quarkus/devfile.yaml
- stacks/java-springboot/2.0.0/devfile.yaml
- stacks/java-springboot/1.2.0/devfile.yaml
- stacks/java-maven/devfile.yaml
- stacks/java-vertx/devfile.yaml

For all the of the above images the test passes.

**To Reproduce:**
An example of this issue can bee seen here: 
- [Attempt 1](https://github.com/devfile/registry/actions/runs/5278822721/attempts/1)
- [Attempt 2](https://github.com/devfile/registry/actions/runs/5278822721)

## Expected behavior
As test passes for all devfiles they had updates for their images, the job should be successful or should have a more clear error trace.

## Any logs, error output, screenshots etc? Provide the devfile that sees this bug, if applicable
The full log is here: https://github.com/devfile/registry/actions/runs/5278822721/jobs/9549582352
```
Testing /home/runner/work/registry/registry/stacks/java-websphereliberty-gradle/devfile.yaml
  COMMAND: minikube ssh docker pull icr.io/appcafe/websphere-liberty-devfile-stack:22.0.0.1-gradle
Error: Process completed with exit code 1.
```

### Suggestion on how to fix the bug

**Target date:** Jun 21

**Comment by mike-hoang** [comment]
Workflow is still failing after merging the pr. Looking into why it still continues to fail

**Comment by mike-hoang** [comment]
Was failing due to there sometimes being a conflict when removing a docker image:

```shell
COMMAND: "minikube ssh docker image rm registry.access.redhat.com/ubi8/nodejs-18:1-47.1684740189"
Error response from daemon: conflict: unable to remove repository reference "registry.access.redhat.com/ubi8/nodejs-18:1-47.1684740189" (must force) - container 2e45242f9811 is using its referenced image f77092719a71
```

Using the `--force` flag fixes this problem, successful run here: https://github.com/devfile/registry/actions/runs/5349207551
