### ISSUE TITLE
Update ODC's Devfile Library version

### ISSUE THREAD

**Issue by maysunfaisal** [devfile/api#1136]
## Which area/kind this issue is related to?

/area library

## Issue Description

Update to a newer version of devfile/library on ODC.

This issue should also 
- [ ] look at if switching to the latest version of the library, affects ODC because of the proxy support that is required on git cli, that was put in devfile/library. 
- [ ] Update to the devfile/library version that has the new devfile validation for same port numbers in devfile components

Target Date: Mar 31, 2024

**Comment by kim-tsao** [comment]
@maysunfaisal we can also consider introducing a new parser arg to disable downloading from parent devfiles, especially if ODC is not relying on these artifacts right now (download by default so it doesn't change existing behaviour).

**Comment by thepetk** [comment]
I think this issue is still work in progress and the PR is under review

**Comment by thepetk** [comment]
@maysunfaisal I've tested locally your branch of console and I was able to create an application for each one of our samples:

* `nodejs-basic`
* `code-with-quarkus`
* `java-springboot-basic`
* `python-basic`
* `go-basic`

![Image](https://github.com/devfile/api/assets/12788684/415510a0-e9fc-4b9d-9c10-4873b330a789)

**Comment by thepetk** [comment]
@maysunfaisal my main concern is when I'm trying to parse a new sample:

* I have created a new version of `go-basic` here: https://github.com/thepetk/devfile-sample-go-basic.git
* This version uses consistent ports and the latest `go` parent.
* I've included this version in a locally running image of the registry which I connected with my locally running ODC instance.
* When I'm trying to create an application for this sample I have the following error:
```
Failed to parse devfile: failed to convert kubernetes uri to inlined for component 'deploy': error getting kubernetes resources definition information, unable to resolve the file uri: deploy.yaml
```

This error comes from here: https://github.com/openshift/console/blob/master/pkg/devfile/handler.go#L55.

From what I can understand this error comes from the `library` and we are not able to locate the `deploy.yaml` file.

**Comment by thepetk** [comment]
This is not a blocker anymore as the scope of the blocked item has changed.

**Comment by thepetk** [comment]
@maysunfaisal closing as the related PR was merged

**Comment by maysunfaisal** [comment]
Back ported to Openshift 4.15 https://github.com/openshift/console/pull/13762
