### ISSUE TITLE
Install Renovate bot to devfile registry

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1139]
## Which area/kind this issue is related to?

/area ci

## Issue Description

Follow the Installation notes [here](https://github.com/renovatebot/renovate/blob/main/docs/usage/getting-started/installing-onboarding.md) in order to add renovate to the devfiles org. Some details:

* At first only the registry repo should be included to the bot's configuration. In the future all other repos will be added.
* After the installation of renovate a PR will be created to the registry repo. We will have to update this PR with the following configuration:

```json
{
    "$schema": "https://docs.renovatebot.com/renovate-schema.json",
    "extends": [
      "config:base",
    // Using this helper in order to pin digest of github action
      "helpers:pinGitHubActionDigests"
    ],
    // Helps the bot only to run these managers and skip all others
    "enabledManagers": ["regex", "github-actions"],
    "regexManagers": [
      {
        // Using regex manager to define a custom way to fetch devfile image tags
        "fileMatch": [
          "devfile.*y[a]?ml$"
        ],
        "matchStrings": [
          "image: (?<depName>\\S*):(?<currentValue>\\S*)"
        ],
        "datasourceTemplate": "docker",
        "depNameTemplate": "{{{depName}}}"
      }
    ],
    "packageRules": [
        // Grouping github-actions in order to reduce renovate PR noise
        {
          "matchManagers": ["github-actions"],
          "groupName": "github actions",
          "groupSlug": "github-actions",
          "commitMessageTopic": "{{depName}}"
        }
    ],
    // Ignoring these paths in order to reduce PR noise
    "ignorePaths": [
      "**/docker/**",
      ".ci/**",
      "tests/**"
    ]
}
```

## Acceptance Criteria

- [x] Ensure all image references (including innerloop and outerloop) are updated for every stack
- [ ] Add renovate.json and invite the self hosted bot to registry repo
- [x] #1138 should also be completed in the same PR

**Comment by lmilbaum** [comment]
I'd suggest to configure the self-hosted renovate-runner not to onboard by default. With that, every repo you do want to onboard, just add the renovate.json file and add the repository name to the renovate-runner config.js file.

**Comment by thepetk** [comment]
@lmilbaum moving the discussion to the parent issue :)

**Comment by kim-tsao** [comment]
Epic https://github.com/devfile/api/issues/992 was opened to address manually updating the Node.js v12 actions since the due date is more imminent.  We can wait for renovatebot to be installed to remediate the other deprecating action https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

**Comment by thepetk** [comment]
Created [PR](https://github.com/devfile/registry/pull/205) in order to add the renovate.json configuration to the registry repo. Once is reviewed & merged we can add the repo to the self hosted renovate runner as mentioned previously.

**Comment by thepetk** [comment]
Regarding https://github.com/devfile/registry/pull/205 I've sent a [reminder](https://github.com/devfile/registry/pull/205#issuecomment-1731382307) to the stack owners in order to review the pr so we can proceed with the installation of renovate.

**Comment by thepetk** [comment]
All conversations with owners have been resolved and the PR is now again ready to be reviewed :)

**Comment by thepetk** [comment]
Re-Opening the issue as we have to add the repo to the self-hosted runner

**Comment by thepetk** [comment]
The registry repo is now included to the self hosted runner config. The last step is to [invite their bot to registry repo](https://github.com/platform-engineering-org/renovate-runner#onboarding-your-githubcom-project)

**Comment by thepetk** [comment]
The bot is now invited to the repo and the demo of this feature is ready. Moving back to current sprint and marking it as done

**Comment by rm3l** [comment]
@thepetk Out of curiosity, where are demos usually stored? A Youtube playlist? On the shared drive?
