### ISSUE TITLE
Devfile registry index should contain the starterProjects for each devfile

### ISSUE THREAD

**Issue by johnmcollier** [devfile/api#115]
It would be nice if the index.json for a devfile registry could contain the list of starterProjects in a given devfile:

For odo, when we list devfile components, we want to be able to include the name of the starter projects available in each devfile, e.g:
```
$ odo catalog list components
Odo Devfile Components:
NAME                 DESCRIPTION                            STARTER PROJECTS                REGISTRY
java-maven           Upstream Maven and OpenJDK 11                                          DefaultDevfileRegistry
java-openliberty     Open Liberty microservice in Java      user-app                        DefaultDevfileRegistry
java-quarkus         Upstream Quarkus with Java+GraalVM     quarkus-ex                      DefaultDevfileRegistry
java-springboot      Spring Boot® using Java                springbootproject               DefaultDevfileRegistry
```

However, to get the list of projects now would require downloading each devfile and parsing it. If the index.json is updated to include the projects for each devfile, then we would only need to parse the index.json (as-is today).

Sample new index.json:
```
[
  {
    "name": "java-maven",
    "displayName": "Maven Java",
    "description": "Upstream Maven and OpenJDK 11",
    "tags": [
      "Java",
      "Maven"
    ],
    "projectType": "maven",
    "language": "java",
    "links": {
      "self": "/devfiles/java-maven/devfile.yaml"
    }
  },
  {
    "name": "java-openliberty",
    "displayName": "Open Liberty",
    "description": "Open Liberty microservice in Java",
    "projectType": "docker",
    "language": "java",
    "links": {
      "self": "/devfiles/java-openliberty/devfile.yaml"
    },
    "starterProjects": [
      "user-app"
    ]
  },
  {
    "name": "java-quarkus",
    "displayName": "Quarkus Java",
    "description": "Upstream Quarkus with Java+GraalVM",
    "tags": [
      "Java",
      "Quarkus"
    ],
    "projectType": "quarkus",
    "language": "java",
    "links": {
      "self": "/devfiles/java-quarkus/devfile.yaml"
    },
    "starterProjects": [
      "quarkus-ex"
    ]
  },
]
```

**Comment by kadel** [comment]
> It would be nice if the index.json for a devfile registry could contain the list of projects in a given devfile:

do you mean `projects` or `starterProjects` (https://github.com/devfile/api/issues/42)

**Comment by johnmcollier** [comment]
@kadel Thanks, good catch. I mean starter projects 🙂 

I'll go update the description so it's more clear.

**Comment by johnmcollier** [comment]
We discussed on today's call - we'll add the starterProjects field to the index.json of the registry. When we migrate to the new registry format, we'll make sure it's included as part of the required metadata.

**Comment by rnapoles-rh** [comment]
starterProject still missing for java-maven

**Comment by GeekArthur** [comment]
I notice that our devfile registry repo doesn't include starter project for `java-maven` https://github.com/devfile/registry/blob/master/stacks/java-maven/devfile.yaml, we might need to refer odo devfile registry here: https://github.com/odo-devfiles/registry/blob/master/devfiles/java-maven/devfile.yaml#L5
