### ISSUE TITLE
Create proposal for defining a dockerfile component on alizer

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1160]
## Which area/kind this issue is related to?

/area alizer

## Issue Description

Related: EPIC https://github.com/devfile/api/issues/1159

To improve port detection around dockerfiles, we need to consider cases where a dockerfile may not be inside a detected component. This requires a new component definition which this proposal will focus on.

**Target date:** July 04

**Comment by thepetk** [comment]
Follow old comments on https://github.com/redhat-developer/alizer/issues/244

**Comment by mike-hoang** [comment]
PR moved from redhat-developer/alizer to https://github.com/devfile/alizer/pull/3
