### ISSUE TITLE
Migrate Alizer to Dependabot

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1163]
## Which area this feature is related to?
/area alizer
/area ci

## Issue details
This issue is part of [alizer#160](https://github.com/redhat-developer/alizer/issues/160). As mentioned inside, we have to separate the gosec and dependabot. The latter will be added in alizer after the onboarding to devfile team.

## Related Issues
https://github.com/redhat-developer/alizer/issues/119
https://github.com/redhat-developer/alizer/issues/160

**Target Date**: 11 July 2023

**Comment by thepetk** [comment]
I've created a `dependabot.yaml` and enabled dependabot updates on my fork (https://github.com/thepetk/devfile-alizer)

**Comment by thepetk** [comment]
In order to allow dependabot alerts for alizer we should:

* Go to **repo > settings > code security and analysis**

* Enable the dependabot alerts:
![Image](https://github.com/devfile/api/assets/12788684/51548b16-7d50-4799-9e87-e01613500fdb)

**Comment by elsony** [comment]
I have changed the dependabot setting

**Comment by thepetk** [comment]
Closing this as it is done after the update of the settings and is aligned to the rest of the projects inside devfiles org
