### ISSUE TITLE
Rename DevFile to Devfile inside alizer code

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1173]
## Which area this feature is related to?

/area alizer

## Which functionality do you think we should add?

Inside the project we are mentioning the term `DevFile` instead of `Devfile` in various variables and functions.
This will improve the consistency between the different places that this term is found inside this project, but also on other devfiles projects.

**Comment by michael-valdron** [comment]
We can use deprecation to ensure no breaking changes, e.g. keep both `DevFile` and `Devfile`

**Comment by thepetk** [comment]
Regarding the scope of the issue: The main reason that we need to be cautious about this update is the usage of `recognizer.SelectDevFilesFromTypes` func. This function is replaced by the `recognizer.MatchDevfiles`, but it is used from external users already.

As a result, we need to add a deprecation warning to our documentation for this specific function and we can keep it as is. In the future it can be removed in favor of `recognizer.MatchDevfiles` which has a new feature of filters (passing filters to the devfile API)
