### ISSUE TITLE
Support variable values on open libery alizer's port detection

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1177]
## Which area/kind this issue is related to?

/area alizer

## Issue Description

Right now the `openliberty_detector` expects a hardcoded value for port detection:
```xml
 <httpEndpoint host="*" httpPort="1234" httpsPort="1235" id="defaultHttpEndpoint"/>
```

There are cases where someone can define a variable for this cause:
```xml
<variable name="default.http.port" defaultValue="9080"/>
<variable name="default.https.port" defaultValue="9443"/>

<httpEndpoint host="*" httpPort="${default.http.port}" httpsPort="${default.https.port}" id="defaultHttpEndpoint"/>
```

So alizer should be able to look also for the value of the variable and not only the hardcoded values.

**Comment by thepetk** [comment]
Not a priority but definitely a good feature, so I'd like to keep it active

**Comment by michael-valdron** [comment]
> Not a priority but definitely a good feature, so I'd like to keep it active

Keeping this active
