### ISSUE TITLE
Support multiple sample versions on Registry Viewer

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1184]
/kind user-story

## Which area this user story is related to?

/area registry-viewer

## User Story

As mentioned inside https://github.com/devfile/api/issues/1112 we would like to add reference to all samples to v2.2.0 parent stacks. To do so we will need to have multiple versions for samples like stacks (details in the description of referenced issue).

Right now the viewer is not supporting multiple versions on samples. More detailed as seen in the [fetch-devfiles.tsx](https://github.com/devfile/devfile-web/blob/main/libs/core/src/functions/fetch-devfiles/fetch-devfiles.tsx#L38):

```typescript
interface DevfileJsonSample extends DevfileJsonBase {
  type: 'sample';
  versions?: never;
}

interface DevfileJsonStack extends DevfileJsonBase {
  type: 'stack';
  versions: VersionDevfile[];
}
```
This also can be seen here on the viewer when fetching a sample, as there is no option to choose different versions of a sample:
![Screenshot from 2023-07-11 12-06-43](https://github.com/devfile/api/assets/12788684/1cfdfee5-6d6c-49ef-8f62-b9651517cd40)

## Acceptance Criteria

- [ ] Support multiple versions inside on the registry-viewer
- [ ] Update any documentation referring to multiple versions of samples

**Comment by michael-valdron** [comment]
This issue should be planned for an upcoming sprint once out of refinement.
