### ISSUE TITLE
Documented the default devfile locations as part of the devfile doc

### ISSUE THREAD

**Issue by elsony** [devfile/api#1185]
## Which area this feature is related to?

/area documentation

## Which area is this documentation change is related to?
/area api

## Issue details
Documented the default devfile locations as part of the devfile doc, e.g. devfile.yaml, .devfile.yaml, .devfile/devfile.yaml, .devfile/.devfile.yaml, etc? This information should be part of the intro information to allow users to easily found from our doc website.

**What mistake did you find / what is missing in the documentation?**
The current doc is missing information on where the default location of the devfile.yaml should be placed. After the information has been provided, we should communicate the standard locations to the tools to make sure the tools are supporting the default locations.

**Comment by maysunfaisal** [comment]
We should also consider devfile.yml and variations. I have noticed ppl use devfile.yml too; but first need to check if devfile/library is able to handle that

**Comment by michael-valdron** [comment]
> first need to check if devfile/library is able to handle that

I don't believe it does currently but if it does we should update the status of devfile/api#744.

**Comment by mike-hoang** [comment]
related to https://github.com/devfile/api/issues/1035
