### ISSUE TITLE
Revise repository documentation for registry-operator

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1190]
## Which area/kind this issue is related to?

/area documentation
/area registry
/area releng

## Issue Description

A review and revising of all the documentation in [registry-operator](https://github.com/devfile/registry-operator), including READMEs. This includes adding missing instructions, updating outdated information and separation of documentation where it makes sense.

## Acceptance Criteria

- [ ] [README](https://github.com/devfile/registry-operator/blob/main/README.md)
- [ ] [CONTRIBUTING](https://github.com/devfile/registry-operator/blob/main/CONTRIBUTING.md)

**Comment by michael-valdron** [comment]
Rest of the acceptance criteria needs completion.

**Comment by thepetk** [comment]
Putting it in a later date for refinement as some more criteria should be defined :) Also updating the status to waiting
cc @michael-valdron

**Comment by michael-valdron** [comment]
> Putting it in a later date for refinement as some more criteria should be defined :) Also updating the status to waiting cc @michael-valdron

Correct, I'll need to complete the documentation checklist for this issue.

**Comment by feloy** [comment]
Isn't this issue redondant with https://github.com/devfile/api/issues/1015?

**Comment by michael-valdron** [comment]
> Isn't this issue redondant with #1015?

After reviewing the only item that #1015 does not cover is [CONTRIBUTING](https://github.com/devfile/registry-operator/blob/main/CONTRIBUTING.md), I'd say let's close this one and open another for updating CONTRIBUTING.
