### ISSUE TITLE
Improve devfile registry index server testing

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1192]
## Which area/kind this issue is related to?

/area registry
/area integration-tests

## Issue Description

The devfile registry index server has limited testing and test cases across unit tests and integration tests. We need to improve the existing coverage to ensure less area of unknown problems.

**Comment by feloy** [comment]
Needs some research to find which tests need to be added

**Comment by Jdubrick** [comment]
@michael-valdron is this issue still being planned for? Going through the waiting queue and noticed this was stale.

**Comment by michael-valdron** [comment]
@Jdubrick This should still be planned to improve the code coverage of testing under registry-support, which is only 35% atm. In addition, seeing why this is under waiting I think we should create a spike for this issue to investigate what are the test cases we still need to include.

> Needs some research to find which tests need to be added

**Comment by Jdubrick** [comment]
Opened spike issue designed to add more clarity to this issue: https://github.com/devfile/api/issues/1420

**Comment by thepetk** [comment]
Adding blocker label for the spike issue

**Comment by maysunfaisal** [comment]
moving back to backlog

**Comment by michael-valdron** [comment]
> moving back to backlog

@maysunfaisal should we move into refinement as it's not sized yet?
