### ISSUE TITLE
Fix Devfile Web Client telemetry

### ISSUE THREAD

**Issue by kim-tsao** [devfile/api#1208]
/kind user-story

## Which area this user story is related to?

/area telemetry

## User Story

As a product manager, I want to reduce the number of events in Amplitude so we do not hit our event limits

## Acceptance Criteria

- Ensure events sent to Amplitude are "Page Viewed" events and not events pointing to the path segment of our URLs.  Switch to the following format for the registry-viewer and landing-page clients

```
analytics.track(
  userId: 'anonymousUID',
  event: 'Page Viewed', 
  properties: {
    path: '/docs/2.2.0/defining-endpoints'
  },
  context: {
    app: {
      name: 'landing-page'
    }
  }
);
```
- Verify events in Amplitude are received in the above format (in the Data tab)
- Post in the `Telesense:..` gSpace channel to get our data pipeline turned back on

- [ ] ....
- [ ] ....

**Comment by yangcao77** [comment]
@kim-tsao Can you provide more information on how the current acceptance criteria related to "reducing events"? More information can be added to this issue?

**Comment by kim-tsao** [comment]
> @kim-tsao Can you provide more information on how the current acceptance criteria related to "reducing events"? More information can be added to this issue?

@yangcao77 I wouldn't have visibility into that.  It's the Amplitude account holders who can verify.  All we have to do is ensure the event follows the format they expect.  The only thing is once this is fixed, you'd have to reach out to the gChat channel to get this enabled again
