### ISSUE TITLE
Provide Mock Interface for Devfile Downloads on devfile/library 

### ISSUE THREAD

**Issue by kim-tsao** [devfile/api#1221]
/kind user-story

## Which area this user story is related to?

/area library

## User Story

As a devfile library client, I want to mock test devfile downloads from a private repo so I can test my client code properly. 

From the investigation that was done in https://github.com/devfile/api/issues/1216#issuecomment-1677353799, we need to fix the DownloadInMemory function to:

1. Error out when we receive an unsupported git vendor URL
2. Convert the function to a method so tooling clients can write mock tests
3. See what the impact is for the following scenarios:

   1. Setting the devfile content in context.Populate/PopulateURL - which would require mocking of these two methods as well 
   2. Converting K8s URI to inline  
   3. Reading the Kubernetes yaml for outerloop support, affecting our client usage.

## Acceptance Criteria

- Create/Update test cases and ensure they run on both happy path and error scenarios
- If there's API breakage, ensure the old methods/functions are marked deprecated
- Update documentation

- [ ] ....
- [ ] ....

**Comment by maysunfaisal** [comment]
> Error out when we receive an unsupported git vendor URL

Thought about this, but we should not error out in these situations and treat such git vendors as regular URLs and attempt a best case regular GET like other URLs
