### ISSUE TITLE
Update deprecated Node.js 12 actions in the API repo

### ISSUE THREAD

**Issue by kim-tsao** [devfile/api#1224]
/kind user-story

## Which area this user story is related to?

 /area api

## User Story

As a devfile developer I want to my github actions updated to the latest, supported Node.js v16 so that my CI workflow will not be disrupted

## Acceptance Criteria

- [ ] Scan the repo actions to determine if the latest runs have Node.js deprecation warnings.  E.g. https://github.com/devfile/api/actions/runs/4808019769
- [ ] Fix the actions by following this blog: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
- [ ] Ensure we are pinning the updates to the commit hash: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

**Comment by thepetk** [comment]
I've opened a [PR](https://github.com/devfile/api/pull/1231). I've noticed there are some failures in the actions tab of the repo so I opened the https://github.com/devfile/api/issues/1232.

I see my PR is failing for this reason https://github.com/devfile/api/actions/runs/5962813005/job/16175116765?pr=1231 
Also the previous checks have failed for the same reason. I'm investigating a fix.
