### ISSUE TITLE
Update deprecated Node.js 12 actions in the integration-tests repo

### ISSUE THREAD

**Issue by kim-tsao** [devfile/api#1229]
/kind user-story

## Which area this user story is related to?

 /area integration-tests

## User Story

As a devfile developer I want to my github actions updated to the latest, supported Node.js v16 so that my CI workflow will not be disrupted

## Acceptance Criteria

- [x] Scan the repo actions to determine if the latest runs have Node.js deprecation warnings.  E.g. https://github.com/devfile/integration-tests/actions/runs/4002017118
- [x] Fix the actions by following this blog: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
- [x] Ensure we are pinning the updates to the commit hash: https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

**Comment by thepetk** [comment]
@kim-tsao I've created the [PR](https://github.com/devfile/integration-tests/pull/99) but the ci is failing (not related to our changes). I've tried to retest without success.

**Comment by thepetk** [comment]
Still I haven't found the way to fix the ci. It seems there is an issue with the golang version used for the workflow.

**Comment by michael-valdron** [comment]
@thepetk Opened related issue #1249 and assigned you.

**Comment by thepetk** [comment]
The [PR](https://github.com/devfile/api/issues/1229) which also updates the go version to `v1.19` now passes all checks and is good to be merged.
