### ISSUE TITLE
Release typescript models and code coverage report workflows are failing

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1232]
## Which area this feature is related to?

/kind bug

### Which area this bug is related to?

/area api
/area test-automation

## Bug Summary

**Describe the bug:**

I've noticed that two workflows are failing for the API repo:

* The first one is the code coverage report. The error trace for this check is:
```
Run go test ./... -coverprofile cover.out
# k8s.io/apimachinery/third_party/forked/golang/reflect
Error: vendor/k8s.io/apimachinery/third_party/forked/golang/reflect/deep_equal.go:37[6](https://github.com/devfile/api/actions/runs/5425938477/job/14695275008#step:4:7):[7](https://github.com/devfile/api/actions/runs/5425938477/job/14695275008#step:4:8): undefined: reflect.Pointer
note: module requires Go 1.19
```

* The second one is the release typescript models. I've found 1 related issue https://github.com/devfile/api/issues/989
The error trace is:
```
Error: /typescript-model/generate.sh: line 63: [ERROR] Generated typescript model failed to build. Check it at /home/runner/work/api/api/api/build/typescript-model/workdir/typescript-models.: No such file or directory
Error: Process completed with exit code 127.
```

**To Reproduce:**

Check the actions tab here:
- Code coverage: https://github.com/devfile/api/actions/workflows/codecov.yaml
- Typescript Models: https://github.com/devfile/api/actions/workflows/release-typescript-models.yaml

## Expected behavior

Both actions should be completed successful.

## Any logs, error output, screenshots etc? Provide the devfile that sees this bug, if applicable

The traces have been shared earlier above.

**Comment by thepetk** [comment]
> @thepetk Should we close #989 and track it here, or add to the same epic?

Nice catch! I've closed #989 in favor of this issue, as is part of an epic and we can track better the progress and the overall status of the ci

**Comment by svor** [comment]
hello,
any updates on it, when we can expect a new release of npm library?

**Comment by michael-valdron** [comment]
> hello, any updates on it, when we can expect a new release of npm library?

Hi @svor, thanks for bring this to our attention.

Our team is reviewing criteria for this issue and we will provide further updates as they come.

**Comment by thepetk** [comment]
I've created the https://github.com/devfile/api/pull/1343 which can potentially fix the Typescript Models generation issue.

**Comment by thepetk** [comment]
The PR https://github.com/devfile/api/pull/1343 is now updated and includes both fixes for code coverage and the typescript models workflows.

I've added it in the current sprint (in review status) and put the story points spent.
