### ISSUE TITLE
Update Integration Test to use Go 1.19

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1249]
## Which area/kind this issue is related to?

/area ci
/area integration-tests
/area releng

## Issue Description

To meet the objective of #1237, we need to ensure our integration test suite is using Go 1.19 with updated dependencies.

## Acceptance Criteria
- [x] Update `go.mod` to use Go 1.19
- [x] Update dependencies under `go.mod` and `go.sum` and migrate any changes
- [x] Update workflows to use Go 1.19
- [x] ~Update requirements under documentation~ **Already up to date**

**Comment by thepetk** [comment]
The [PR](https://github.com/devfile/api/issues/1229) which also updates the go version to `v1.19` now passes all checks and is good to be merged.

**Comment by thepetk** [comment]
As [PR](https://github.com/devfile/api/issues/1229) is merged and now the Go version used for the repo is 1.19 I'm closing this issue
