### ISSUE TITLE
Create notification on Product & Community Registries Check nightly run

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1255]
## Which area/kind this issue is related to?

/area ci
/area alizer

## Issue Description

The nightly run which checks the starter projects of all stacks inside product and community registry should have an alerting mechanism in order to notify people for the status of the job. As a result a notification should be added after every run, as a message to the appropriate team channel so people can monitor easier the results of this job.

## Acceptance Criteria
- [ ] Every nightly run should send a message to team channel with the result of the task.
- [ ] The message should follow the following format:
       * Status: [{red light emoji} failure | {green light emoji} success]
       * Severity: [for failure - medium | for success low]
       * In case of failure mention `@ app-devfile` in order to take action.
       * Title: Product & Community Registries Check
       * Description: Mention Branch and Commit, add a short message and link to logs

**Comment by thepetk** [comment]
Currently blocked from https://github.com/devfile/api/issues/1248

**Comment by feloy** [comment]
Similar to https://github.com/devfile/api/issues/1061

**Comment by thepetk** [comment]
Blocked by https://github.com/devfile/api/issues/1026

**Comment by thepetk** [comment]
Removing `blocked` label as I don't think is relevant anymore

**Comment by thepetk** [comment]
Putting item back to "in review" cause I'm still looking for a proper way to test the related PR

**Comment by thepetk** [comment]
PR https://github.com/devfile/alizer/pull/43 is now ready for review
