### ISSUE TITLE
Replace Alizer io/ioutil dependency

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1257]
## Which area/kind this issue is related to?

/area alizer

## Issue Description

At the moment alizer is using the [io/ioutil](https://pkg.go.dev/io/ioutil) in order to read files. As it is mentioned:
```
"io/ioutil" has been deprecated since Go 1.19: As of Go 1.16, the same functionality is now provided
by package io or package os, and those implementations should be preferred in new code. See the
specific function documentation for details
```

As a result, we shall replace this dependency and start using the `os` library.

## Acceptance Criteria

- [x] Remove the `io/ioutils` dependency and replace it with a non-deprecated one.
- [ ] Enforce the package is not used in the future using linter (run the linter into CI)

**Comment by trader7** [comment]
I can work on this

**Comment by michael-valdron** [comment]
@trader7 Thank you for offering your contribution! I have assigned you this issue, keep us up to date on your progress. I recommend reviewing [CONTRIBUTING.md](https://github.com/devfile/alizer/blob/main/CONTRIBUTING.md) as well before starting.

When your changes are ready you can open a PR to main branch of [devfile/alizer](https://github.com/devfile/alizer).

**Comment by trader7** [comment]
I submitted a pull request in Alizer repo with Fixes #1257
Branch is alizer-ioutil-dependency

**Comment by michael-valdron** [comment]
> I submitted a pull request in Alizer repo with Fixes #1257 Branch is alizer-ioutil-dependency

Awesome, I'll review your changes.

**Comment by michael-valdron** [comment]
Partial fix applied: https://github.com/devfile/alizer/pull/30

Re-opening for the addition of the linter check, I will assign myself to work on this part.

**Comment by rm3l** [comment]
/assign @rm3l 
/unassign @michael-valdron 

Going to look into this issue in the upcoming sprint (2249)
