### ISSUE TITLE
Support `.yml` extension

### ISSUE THREAD

**Issue by feloy** [devfile/api#1265]
/kind user-story

## Which area this user story is related to?

/area library

## User Story

As a library consumer, I want the Devfile parser to support Devfile with `.yml` extension for a Devfile, So that my users can provide a `devfile.yml`, which is also commonly used for YAML files (even if `.yaml` is [preferred and recommended](https://yaml.org/faq.html)).

Ideally, the Devfile parser should not make any assumptions about the file name it is provided. It should be able to parse any file path provided.
Currently, trying to parse a `devfile.yml` file returns the error below. It looks like the parser interprets `/path/to/devfile.yml` as a folder, as it looks for a `/path/to/devfile.yml/devfile.yaml` file, which does not exist:
```
☸ in ~/w/p/d/library on  main [$] via 🐹 v1.19.6 
$ ./main /path/to/devfile.yml
parsing devfile from /path/to/devfile.yml
failed to populateAndParseDevfile: failed to read devfile from path '/path/to/devfile.yml/devfile.yaml': open /path/to/devfile.yml/devfile.yaml: not a directory
```

## Acceptance Criteria
- [x] It should support any file name - https://github.com/devfile/api/issues/1035#issuecomment-1723384280
  - [x] If passed a path to a file, the library should not make any assumption about the file names. It should be able to parse any file provided and return an error if it is not a valid Devfile.
  - [x] If variants of them are present in the same directory, the .yaml one has priority (in places where library is discovering a Devfile)
- [x] After this item is done, we'll need other tools, e.g. odo, ODC, and RHTAP, to start supporting .yml extensions. => check that the change does not break current clients
- [x] It should update any relevant documentation to reflect the changes
- [x] Demo required

## Notes
https://github.com/devfile/api/issues/1035#issuecomment-1723384280

## Links
- Related to https://github.com/devfile/api/issues/1035
- Closes https://github.com/devfile/api/issues/744

**Comment by rm3l** [comment]
Demo recorded and uploaded in the team Shared Drive: `Demo` > `Sprint 2250` > `devfile-library-parse-any-file-including-yml.mkv`

**Comment by rm3l** [comment]
/reopen

Reopening to have the documentation PR (https://github.com/devfile/devfile-web/pull/106) close it.
