### ISSUE TITLE
Automatically publish registry operator release images

### ISSUE THREAD

**Issue by johnmcollier** [devfile/api#1267]
## Which area/kind this issue is related to?

/area registry
/kind task

## Issue Description

When a new version of the registry operator is published, GitHub Actions workflows should run which automatically publish the release images to Quay.io. 

It’s possible to get the release tag when a GitHub Action runs upon the creation of a new release, so it should be a straightforward to tag the image in Quay.io

Guide to creating release workflows: https://birtony.medium.com/setting-up-automated-release-workflow-with-github-actions-628dbca2446e

**Release Workflow Trigger Example**
```
on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
```

## Acceptance Criteria

- [x] Create a workflow file that triggers on release cuts
- [x] Create tasks to build and push `quay.io/devfile/registry-operator` and `quay.io/devfile/registry-operator-bundle` on the release changes, use version label as tag
- [x] Perform integration testing on release images

**Revised by (2023-10-12): @michael-valdron**

**Comment by michael-valdron** [comment]
Adding as part of #410.

**Comment by michael-valdron** [comment]
Blocker to #1194: https://github.com/devfile/api/issues/410#issuecomment-1769515474

**Comment by michael-valdron** [comment]
Starting point for [`.goreleaser.yaml`](https://github.com/michael-valdron/devfile-registry-operator/blob/f1d5e85b6f0609d02c43ec671d15ce2702661699/.goreleaser.yaml), publishes release and snapshot/release images. Investigating generating a changelog that contains PRs instead of commits.

**Comment by michael-valdron** [comment]
> Starting point for [`.goreleaser.yaml`](https://github.com/michael-valdron/devfile-registry-operator/blob/f1d5e85b6f0609d02c43ec671d15ce2702661699/.goreleaser.yaml), publishes release and snapshot/release images. Investigating generating a changelog that contains PRs instead of commits.

Setting `use: github-native` solves the above:

```yaml
changelog:
  use: github-native
```

**Release result**

![Image](https://github.com/devfile/api/assets/14838510/dcae6232-c3eb-4e31-8579-7f38c69a29dd)

**Comment by michael-valdron** [comment]
[Release workflow](https://github.com/michael-valdron/devfile-registry-operator/blob/97fef202fc4a8b8c5d6ddb485979215d7261bcad/.github/workflows/release.yaml) completed.

**Comment by michael-valdron** [comment]
> [Release workflow](https://github.com/michael-valdron/devfile-registry-operator/blob/be317e431368396e915ca21eee5fcefa6e4123d8/.github/workflows/release.yaml) completed for release image pushing.

Testing of the release workflow was successful, got triggered and had successful runs on tags `v0.1.4` and `v0.1.4-rc.1` but did not trigger on `v0.1.4-rc.a` which does not use the release version format.

![Screenshot from 2023-10-23 16-07-32](https://github.com/devfile/api/assets/14838510/13df8e1d-c256-46e1-a817-db7208a088d2)

![Screenshot from 2023-10-23 16-08-05](https://github.com/devfile/api/assets/14838510/9d97cfb2-de0c-4af8-8cfe-6085837221a7)

**Comment by michael-valdron** [comment]
https://github.com/devfile/registry-operator/pull/56 adds the GH actions needed for this process, still need to resolve https://github.com/openshift/release/pull/44995 to close this issue, reopening..

**Comment by michael-valdron** [comment]
Based on revisions to the release process, https://github.com/devfile/api/issues/1194#issuecomment-1792826955, a refactor to the release workflow is needed.

`version-check` and `k8s-integration-test` should be moved into a separate workflow that is triggered on PRs targeting release branches. The changes to https://github.com/openshift/release/pull/44995 should be revised to target existing release branches, if a new release branch is added then a change is needed to https://github.com/openshift/release to target that branch.

**Comment by michael-valdron** [comment]
> Based on revisions to the release process, [#1194 (comment)](https://github.com/devfile/api/issues/1194#issuecomment-1792826955), a refactor to the release workflow is needed.
> 
> `version-check` and `k8s-integration-test` should be moved into a separate workflow that is triggered on PRs targeting release branches. The changes to [openshift/release#44995](https://github.com/openshift/release/pull/44995) should be revised to target existing release branches, if a new release branch is added then a change is needed to [openshift/release](https://github.com/openshift/release) to target that branch.

PR for GitHub workflow revisions ready for review: https://github.com/devfile/registry-operator/pull/57

**Comment by michael-valdron** [comment]
> > Based on revisions to the release process, [#1194 (comment)](https://github.com/devfile/api/issues/1194#issuecomment-1792826955), a refactor to the release workflow is needed.
> > `version-check` and `k8s-integration-test` should be moved into a separate workflow that is triggered on PRs targeting release branches. The changes to [openshift/release#44995](https://github.com/openshift/release/pull/44995) should be revised to target existing release branches, if a new release branch is added then a change is needed to [openshift/release](https://github.com/openshift/release) to target that branch.
> 
> PR for GitHub workflow revisions ready for review: [devfile/registry-operator#57](https://github.com/devfile/registry-operator/pull/57)

PR for OpenShift CI prow job revisions ready for review: https://github.com/openshift/release/pull/44995#event-10877168509

**Comment by michael-valdron** [comment]
https://github.com/devfile/registry-operator/pull/57 & https://github.com/openshift/release/pull/44995 have been merged, resolving this issue.
