### ISSUE TITLE
Devfile samples generates broken Routes which use http instead of https

### ISSUE THREAD

**Issue by alexeykazakov** [devfile/api#1270]
## Which area this feature is related to?

Devfile samples

/kind bug

### Which area this bug is related to?

/area registry

## What versions of software are you using?

OpenShift 4.13.13

## Bug Summary

**Describe the bug:**

I didn't check all the samples but at least those two:

https://github.com/devfile-samples/devfile-sample-code-with-quarkus.git
https://github.com/devfile-samples/devfile-sample-java-springboot-basic.git

result in broken Routes when used in OpenShift. The Routes are missing:
```
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
```

**To Reproduce:**

1. In Web Console go to the Developer perspective. Then "Add" and choice there the affected samples. After the app is build and deployed try to open the route. The route uses `http://` instead of `https://`

### Any workaround?

Manually modify the route and fix it by adding:
```
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
```

**Comment by alexeykazakov** [comment]
You can easily reproduce it in Dev Sandbox for OpenShift btw.

**Comment by michael-valdron** [comment]
@alexeykazakov  Thanks for reporting this, we'll take a look into our registry stacks/samples.

> I'm not sure what area it is.

Should be:

/area registry

**Comment by michael-valdron** [comment]
Refinement date changed to **October 27th** for other high priority items, was previously October 20th.

**Comment by michael-valdron** [comment]
> Refinement date changed to October 27th for other high priority items, was previously October 20th.

Refinement date changed to **November 3rd** for other high priority items.

**Comment by michael-valdron** [comment]
> > Refinement date changed to October 27th for other high priority items, was previously October 20th.
> 
> Refinement date changed to **November 3rd** for other high priority items.

Holding off on sizing until more details are able to gathered for refinement.

**Comment by michael-valdron** [comment]
While working on the `go-basic` sample https://github.com/devfile-samples/devfile-sample-go-basic/pull/34, I discovered that the route is created by ODC from the devfile `endpoint` entry.

When ODC creates the Route it does not create an endpoint for tls when the `secure: true` or `protocol: https` is set as expected. After investigating this, it is found that when a `uri` is used instead of `inlined` the `secure` route parameter is always set to `false`: https://github.com/openshift/console/blob/170c455125d05b9b6c80b53e2e666617666fb80a/pkg/devfile/resources.go#L162

We'll need to patch this to match what is inplace for `inlined`: https://github.com/openshift/console/blob/170c455125d05b9b6c80b53e2e666617666fb80a/pkg/devfile/resources.go#L186

Once this is patch, then the changes I am making to the sample devfiles will resolve this issue.

cc: @alexeykazakov

**Comment by alexeykazakov** [comment]
Thanks for looking at this. Can you please create a JIRA for the console folks?

**Comment by michael-valdron** [comment]
> Thanks for looking at this. Can you please create a JIRA for the console folks?

I have created a JIRA issue for this: https://issues.redhat.com/browse/CONSOLE-3891

I will continue using this issue (devfile/api#1270) to track progress in patching the devfile samples.

**Comment by michael-valdron** [comment]
For each sample, patching requires the addition of `secure: true` under the kubernetes component endpoint: https://github.com/devfile-samples/devfile-sample-go-basic/pull/35/commits/fcdefb788cc1df96db49ba2f7f18b9d8af9d58a6

**Comment by michael-valdron** [comment]
List of PRs to enable TLS across community samples:
- [ ] https://github.com/devfile-samples/devfile-sample-code-with-quarkus/pull/27
- [X] https://github.com/devfile-samples/devfile-sample-java-springboot-basic/pull/40
- [X] https://github.com/devfile-samples/devfile-sample-java-springboot-basic/pull/41
- [X] https://github.com/devfile-samples/devfile-sample-python-basic/pull/39
- [X] https://github.com/devfile-samples/devfile-sample-python-basic/pull/40
- [X] https://github.com/devfile-samples/devfile-sample-go-basic/pull/34
- [X] https://github.com/devfile-samples/devfile-sample-go-basic/pull/35
- [ ] https://github.com/devfile-samples/devfile-sample-dotnet60-basic/pull/11
- [ ] https://github.com/nodeshift-starters/devfile-sample/pull/41

**Comment by michael-valdron** [comment]
Received approval on the [final PR](https://github.com/nodeshift-starters/devfile-sample/pull/41#pullrequestreview-1832320910), will need help to merge this PR: https://github.com/nodeshift-starters/devfile-sample/pull/41#issuecomment-1904337280

**Comment by maysunfaisal** [comment]
@michael-valdron would advise to reach out on Slack for the node sample, if possible.

**Comment by michael-valdron** [comment]
Sample changes are completed, there needs to be a fix applied to [openshift/console](https://github.com/openshift/console): https://github.com/devfile/api/issues/1270#issuecomment-1865306305

Will provide a link to the continuing issue that will track this once it is ready.

**Comment by michael-valdron** [comment]
> > Thanks for looking at this. Can you please create a JIRA for the console folks?
> 
> I have created a JIRA issue for this: https://issues.redhat.com/browse/CONSOLE-3891
> 
> I will continue using this issue (#1270) to track progress in patching the devfile samples.

Portion of console which this bug resides is maintained by Devfile Services team and the issue has been migrated to #1455 to track.

cc: @alexeykazakov
