### ISSUE TITLE
RHTAP nightly tests failing on nodejs-basic sample

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1271]
## Which area this feature is related to?

/kind bug

### Which area this bug is related to?

/area registry

### Go project

**Operating System and version:** N/A

**Go Pkg Version:** 1.18

## Bug Summary

**Describe the bug:**

Nightly testing of the community devfile registry stacks/samples on RHTAP is failing when testing the [`nodejs-basic`](https://github.com/nodeshift-starters/devfile-sample).

**To Reproduce:**

Run the [RHTAP test suite](https://github.com/devfile/registry/tree/main/tests/rhtap) on the registry content.

## Expected behavior

Test suite should run without failure status.

## Any logs, error output, screenshots etc? Provide the devfile that sees this bug, if applicable

See for full log: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-devfile-registry-main-v4.12-rhtap-nightly-devfile-compatibility/1707002224158183424

```
INFO[2023-09-27T13:13:47Z] Ran for 1h13m20s                             
ERRO[2023-09-27T13:13:47Z] Some steps failed:                           
ERRO[2023-09-27T13:13:47Z] 
  * could not run steps: step rhtap-nightly-devfile-compatibility failed: "rhtap-nightly-devfile-compatibility" test steps failed: "rhtap-nightly-devfile-compatibility" pod "rhtap-nightly-devfile-compatibility-devfile-rhtap-nightly" failed: could not watch pod: the pod ci-op-y5dwnzzm/rhtap-nightly-devfile-compatibility-devfile-rhtap-nightly failed after 22m34s (failed containers: test): ContainerFailed one or more containers exited
Container test exited with code 1, reason Error
---
son: Running
  PipelineRun devfile-sample-tv789 reason: Running
  PipelineRun devfile-sample-tv789 reason: Running
  PipelineRun devfile-sample-tv789 reason: Running
  PipelineRun devfile-sample-tv789 reason: Completed
  [FAILED] in [AfterAll] - /tmp/tmp.8s3irlKe7O/registry/tests/rhtap/rhtap_test.go:61 @ 09/27/23 12:55:49.29
  << Timeline
  [FAILED] Expected success, but got an error:
      <*errors.errorString | 0xc0003e6cc0>: 
      timed out waiting for the condition
      {
          s: "timed out waiting for the condition",
      }
  In [AfterAll] at: /tmp/tmp.8s3irlKe7O/registry/tests/rhtap/rhtap_test.go:61 @ 09/27/23 12:55:49.29 
```

### Any workaround?

Unknown at this time.

### Suggestion on how to fix the bug

Unknown at this time.

**Comment by michael-valdron** [comment]
Mostly likely the result of devfile/registry#205 changes, there is a mismatch between the `nodejs-basic` base image and the parent `nodejs` base image:

Sample Image Ref: https://github.com/nodeshift-starters/devfile-sample/blob/cb64992eebf5c18900d283a9bca08b4ab5db2874/Dockerfile#L14
Parent Image Ref: https://github.com/devfile/registry/blob/f6f5fba56ceb559181ec91af68ea15c322b9d785/stacks/nodejs/2.1.1/devfile.yaml#L22

**Comment by thepetk** [comment]
Created a [PR](https://github.com/devfile/registry/pull/207) to rollback the updates introduced by https://github.com/devfile/registry/pull/205

**Comment by michael-valdron** [comment]
Nightly tests are still unverified, will re-open until they are.

**Comment by michael-valdron** [comment]
Nightly test still failing: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-devfile-registry-main-v4.12-rhtap-nightly-devfile-compatibility/1707407999657578496

Keeping open..

**Comment by michael-valdron** [comment]
> Looking further into the issue I see that [this update](https://github.com/nodeshift-starters/devfile-sample/commit/cb64992eebf5c18900d283a9bca08b4ab5db2874) inside the `sample` might have caused the issue (merged 11 Aug).
> 
> Also I see in the [job history](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/periodic-ci-devfile-registry-main-v4.12-rhtap-nightly-devfile-compatibility) section that we also have successful runs for this job. I can identify as the job task failing the `rhtap-nightly-devfile-compatibility`. The first time I can see this failing is https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-devfile-registry-main-v4.12-rhtap-nightly-devfile-compatibility/1696311725915115520 (date: 19 Aug - no records existing before that point so we may have even older failures)
> 
> I think the best approach to fix this incompatibility issue is to:
> 
>     * Try to merge the changes introduced by [PR#196](https://github.com/devfile/registry/pull/196)
> 
>     * Remove the ignore rules from the `renovate.json`
> 
> 
> cc @michael-valdron

@thepetk 

I agree https://github.com/devfile/registry/pull/196 would restore compatibility between the `nodejs` parent stack and the `nodejs-basic` sample.

Though, I think there is more to do to ensure proper compatibility with renovate. The other challenge here is that we do not maintain `nodejs-basic` itself, so it would not receive the same patch PRs from our renovate set up.

If we did support updates through renovate for `nodejs` stack (or any parent stack of samples we don't maintain), we would need to ensure all PRs renovate creates follows a similar process. In addition to reviewing and approving these PRs stack owners or whomever owns the child samples need to follow up with patch PRs to the child samples. It would also mean that if there is a different sample owner to the parent stack owner that the sample owner should also be involved in the review process for the patch to the parent stack.

**Comment by michael-valdron** [comment]
**Update**: The testing seems to be succeeding sometimes which means the problem makes testing flaky, based on the timeout errors this is most likely due to the pipeline runs timing out before being created. We are doing more debugging to investigate this further.

**Comment by thepetk** [comment]
> > Looking further into the issue I see that [this update](https://github.com/nodeshift-starters/devfile-sample/commit/cb64992eebf5c18900d283a9bca08b4ab5db2874) inside the `sample` might have caused the issue (merged 11 Aug).
> > Also I see in the [job history](https://prow.ci.openshift.org/job-history/gs/origin-ci-test/logs/periodic-ci-devfile-registry-main-v4.12-rhtap-nightly-devfile-compatibility) section that we also have successful runs for this job. I can identify as the job task failing the `rhtap-nightly-devfile-compatibility`. The first time I can see this failing is https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-devfile-registry-main-v4.12-rhtap-nightly-devfile-compatibility/1696311725915115520 (date: 19 Aug - no records existing before that point so we may have even older failures)
> > I think the best approach to fix this incompatibility issue is to:
> > ```
> > * Try to merge the changes introduced by [PR#196](https://github.com/devfile/registry/pull/196)
> > 
> > * Remove the ignore rules from the `renovate.json`
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > cc @michael-valdron
> 
> @thepetk
> 
> I agree [devfile/registry#196](https://github.com/devfile/registry/pull/196) would restore compatibility between the `nodejs` parent stack and the `nodejs-basic` sample.
> 
> Though, I think there is more to do to ensure proper compatibility with renovate. The other challenge here is that we do not maintain `nodejs-basic` itself, so it would not receive the same patch PRs from our renovate set up.
> 
> If we did support updates through renovate for `nodejs` stack (or any parent stack of samples we don't maintain), we would need to ensure all PRs renovate creates follows a similar process. In addition to reviewing and approving these PRs stack owners or whomever owns the child samples need to follow up with patch PRs to the child samples. It would also mean that if there is a different sample owner to the parent stack owner that the sample owner should also be involved in the review process for the patch to the parent stack.

@michael-valdron I agree and renovate is not part of this item too. So we can try to merge https://github.com/devfile/registry/pull/196 only and keep this stack excluded from renovate
