### ISSUE TITLE
remove sparseCheckoutDir

### ISSUE THREAD

**Issue by kadel** [devfile/api#128]
Currently, it is defined as

```
             "sparseCheckoutDir": {
                "description": "Part of project to populate in the working directory.",
                "type": "string",
                "markdownDescription": "Part of project to populate in the working directory."
              }
```

As I understand this, if I have a repo with a structure like this.
```
- file0.txt
- /dir1/
    - file1.txt
- /dir2/
   - file2.txt
```
and I do `sparseCheckoutDir: dir2` I should end up with directory with `/file2.txt`.
Problem is that this is not how git sparse checkout works, and as far as I know, you can never clone the repo like this.

The way how [sparse checkout in git](https://github.blog/2020-01-17-bring-your-monorepo-down-to-size-with-sparse-checkout/) works is that it can populate only certain directories, but the directory structure remains.

For example, If I have a repo with the above structure and I want to do sparse checkout if a `/dir2` I would end up with a directory structure like this:
```
- file0.txt
- /dir2/
   - file2.txt
``` 
But what we want to do here is to end up with `/file2.txt` and that is not what sparse checkout does.

I would actually consider completely removing this field from Devfile, It will create a lot of confusion and problems.

**Comment by kadel** [comment]
from meeting:
" We are going to remove the sparseCheckoutDir from `project` and add it to `starterProject` and rename it to something like `subDir`. "

**Comment by l0rd** [comment]
@kadel can we close this issue?

**Comment by elsony** [comment]
Done
