### ISSUE TITLE
Migrate away from default OpenShift CI cluster profiles 

### ISSUE THREAD

**Issue by johnmcollier** [devfile/api#1284]
## Which area/kind this issue is related to?

/area ci

## Issue Description

The following Devfile repos currently use OpenShift CI:

- devfile/devworkspace-operator
- devfile/integration-tests
- devfile/registry
- devfile/registry-operator
- devfile/integration-tests

We have been asked by OpenShift CI to migrate away from the default OpenShift CI profile, and to start using a separate profile (such as our own), within 60 days.

https://docs.ci.openshift.org/docs/how-tos/adding-a-cluster-profile/ provides instructions on providing your own cluster profile in the OpenShift CI config

## Prerequisites:

- AWS account provisioned and necessary developers added to the account (in progress)
- Domain name created for testing (if devfile.devcluster.openshiftci.com is unavailable)

## Child Issues
- New cluster-profile registered in openshift/ci-tools: #1333 
- New leases added to Boskos: #1335
- Providing credentials to OpenShift CI: #1336 
- Devfile OpenShift CI jobs updated to use new cluster profile

**Comment by johnmcollier** [comment]
Wrote up some of our options here: https://docs.google.com/document/d/18aRRbMvm2BvC83Jh-PuWC9KLD5Gp_aBotQVvY582Jmk/edit

**Comment by johnmcollier** [comment]
We'll be migrating to our own cluster profile for OpenShift CI. https://docs.ci.openshift.org/docs/how-tos/adding-a-cluster-profile/ provides the necessary instructions for adding a new cluster profile.

**Comment by rm3l** [comment]
/status Backlog

I can see the Refinement date has been set to today for this issue, but could not see it under the issues to discuss during the refinement call today. I updated its status to `Backlog`  so we can discuss and size this item.

**Comment by thepetk** [comment]
I'm putting this to "waiting" as we should define specific acceptance criteria. A question here could be if this should be an EPIC (issue per repo)

cc @johnmcollier

**Comment by michael-valdron** [comment]
@johnmcollier Have we completed everything to onboard to our own OpenShift CI profile?

**Comment by michael-valdron** [comment]
> ## Child Issues
> - New cluster-profile registered in openshift/ci-tools: #1333 
> - New leases added to Boskos: #1335
> - Providing credentials to OpenShift CI: #1336 
> - Devfile OpenShift CI jobs updated to use new cluster profile

Closing this out now as all child issue have been resolved. @johnmcollier Feel free to reopen if I'm incorrect in assuming this.
