### ISSUE TITLE
Create a new release on demand

### ISSUE THREAD

**Issue by yangcao77** [devfile/api#1285]
## Which area/kind this issue is related to?

/area api

## Issue Description

As described in slack thread: https://kubernetes.slack.com/archives/C02SX9E5B55/p1696623992483819

`v2.2.1-alpha` pre-release is there for almost a year, and we are going to officially ship `v2.2.1`. 

Any following changes will be includes in `v2.2.2-alpha`

## Target Odo version

> Target Odo version:

**Comment by feloy** [comment]
Waiting validation on https://github.com/devfile/library/pull/185
