### ISSUE TITLE
Fix Registry Viewer tags display

### ISSUE THREAD

**Issue by kim-tsao** [devfile/api#1289]
## Which area this feature is related to?

/kind bug

## Bug Summary

**Describe the bug:**

Separated out from issue https://github.com/devfile/api/issues/1064 as an independent bug.

- The tags are pulled from all devfile versions of a specific runtime which is incorrect. It should only display the tags for a specific runtime version.
- Similarly, the tags shown on the registry viewer tiles represent tags from all runtime versions when it should only display the tags for the default devfile. This means if the default devfile is not deprecated, then the deprecated tag should not show up. Users would only see it if they click on the tile and toggle between versions.

**To Reproduce:**

We can't use the community registry viewer because tags are common across all stack runtime versions.

To reproduce:
1.  Clone the https://github.com/devfile/registry-support repo
2. (Optional) Add the `Deprecated` tag to one of the[ go stack versions](https://github.com/devfile/registry-support/tree/main/tests/registry/stacks/go)
3. Build the registry by following the instructions: https://github.com/devfile/registry-support/tree/main#build
4. Deploy to a cluster and bring up the local viewer.  

For the Go stack time, note that it displays all the tags from all stack versions:

<img width="1059" alt="image" src="https://github.com/devfile/api/assets/84398375/42dfe893-0102-4a17-8b7f-2973ea8d0b33">

Click on the tile, and note that when you switch runtime versions, the tags do not change

## Expected behavior

Tags should only reflect the selected stack version

**Comment by thepetk** [comment]
Created a [PR](https://github.com/devfile/devfile-web/pull/103) for this issue. I've also added a new color for the `Deprecated` tag. So every time that a stack has `Deprecated` as tag the color changes (becomes red).

**Comment by thepetk** [comment]
Re-opening as [PR](https://github.com/devfile/devfile-web/pull/103) was accidentally pointing to another branch. I have created again a PR pointing to main https://github.com/devfile/devfile-web/pull/104

**Comment by thepetk** [comment]
I'm re-openning the issue as I've noticed two things:

1. The `registry-support` adds all tags for all stack versions into the generic (`grid`) view. As a result we should add a fix into the registry support repo. Fix here: https://github.com/devfile/registry-support/pull/193
2. The color `Deprecated` is not visible anymore (while it was when we first deployed it).

cc @kim-tsao

**Comment by thepetk** [comment]
> The registry-support adds all tags for all stack versions into the generic (grid) view. As a result we should add a fix into the registry support repo. Fix here: https://github.com/devfile/registry-support/pull/193

Fixed as the related PR is merged.

I'm re-opening as the color-related issue still exists

**Comment by thepetk** [comment]
Closing. Will create a separate color issue.
