### ISSUE TITLE
OpenAPI source generation check not showing changes

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1294]
## Which area this feature is related to?

/kind bug

### Which area this bug is related to?

/area ci
/area registry

### Go project

**Operating System and version:** N/A

**Go Pkg Version:** 1.18

## Bug Summary

**Describe the bug:**

When the [check](https://github.com/devfile/registry-support/blob/a95cc889ecaf131b2ce76535ff9d9179607240be/.github/workflows/ci.yaml#L45) to ensure `oapi-codegen` does not produce different changes than on the PR fails the message does not include the change differences in question.

**To Reproduce:**

Submit a PR with changes to any of the `*.gen.go` files that does not match what `oapi-codegen v1.12.4` generates.

## Expected behavior

Error message should produce the following if `endpoint.gen.go` does not match what is generated by `oapi-codegen v1.12.4`:

```diff
generated source does not match current changes 
diff --git a/index/server/pkg/server/endpoint.gen.go b/index/server/pkg/server/endpoint.gen.go
index 7a7041b1..35d21618 100644
--- a/index/server/pkg/server/endpoint.gen.go
+++ b/index/server/pkg/server/endpoint.gen.go
@@ -12,7 +12,7 @@
 // See the License for the specific language governing permissions and
 // limitations under the License.
 //
-// Code generated by github.com/deepmap/oapi-codegen version v1.12.4. **DO NOT EDIT**
+// Code generated by github.com/deepmap/oapi-codegen version v1.15.0. **DO NOT EDIT**
 package server // ServerInterface represents all server handlers.
 import (
        "bytes"
Error: Process completed with exit code 1.
```

## Any logs, error output, screenshots etc? Provide the devfile that sees this bug, if applicable

Just receives this as an error:

```
go: downloading github.com/deepmap/oapi-codegen v1.12.4
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading github.com/getkin/kin-openapi v0.107.0
go: downloading github.com/labstack/echo/v4 v4.9.1
go: downloading golang.org/x/text v0.4.0
go: downloading golang.org/x/tools v0.3.0
go: downloading github.com/go-openapi/jsonpointer v0.19.5
go: downloading github.com/invopop/yaml v0.1.0
go: downloading github.com/mohae/deepcopy v0.0.0-20170929034955-c48cc78d4826
go: downloading github.com/labstack/gommon v0.4.0
go: downloading golang.org/x/crypto v0.1.0
go: downloading golang.org/x/net v0.2.0
go: downloading github.com/go-openapi/swag v0.21.1
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading github.com/mattn/go-colorable v0.1.13
go: downloading github.com/mattn/go-isatty v0.0.[16](https://github.com/devfile/registry-support/actions/runs/6563846946/job/17829003776?pr=186#step:7:17)
go: downloading github.com/valyala/fasttemplate v1.2.2
go: downloading github.com/mailru/easyjson v0.7.7
go: downloading golang.org/x/sys v0.2.0
go: downloading golang.org/x/mod v0.7.0
go: downloading github.com/valyala/bytebufferpool v1.0.0
go: downloading github.com/josharian/intern v1.0.0
Generating type source..
Generating endpoint bindings source..
Done.
generated source does not match current changes 
Error: Process completed with exit code 1.
```

### Any workaround?

Try to reproduce in local environment to get the change diffs.

### Suggestion on how to fix the bug

Fix [ci.yaml#L54](https://github.com/devfile/registry-support/blob/a95cc889ecaf131b2ce76535ff9d9179607240be/.github/workflows/ci.yaml#L54) to display diffs for each file captured.

**Comment by michael-valdron** [comment]
failing tests blocked by: devfile/api#1295

**Comment by thepetk** [comment]
> failing tests blocked by: #1295

@michael-valdron  the blocking issue must have been fixed. We could try to rebase your PR and see if the checks are now passing

**Comment by michael-valdron** [comment]
[PR](https://github.com/devfile/registry-support/pull/186) testing passing, this issue is no longer blocked.
