### ISSUE TITLE
CNCF Cleaner

### ISSUE THREAD

**Issue by maysunfaisal** [devfile/api#1298]
/kind user-story

## Which area this user story is related to?

/area api
/area library
/area registry
/area alizer
/area devworkspace
/area landing-page

## User Story

Cleaner Badge

Requirements - https://github.com/devfile/api/discussions/1283

TODO

Bring all CLOMonitor non-security scores to 100% for the project like Best Practices, Documentation, License, Legal (List of check [here](https://clomonitor.io/docs/topics/checks/) and current assignment [here](https://github.com/cncf/clomonitor/blob/main/data/cncf.yaml))

Estimated Time: Variable as there are a lot of checks, but for a best attempt before the deadline, 1-2 weeks

Triaged at https://github.com/devfile/api/issues/1292#issuecomment-1769308767

## Repo Checklist

- [x] https://github.com/devfile/api/issues/1368
- [x] https://github.com/devfile/api/issues/1369
- [x] https://github.com/devfile/api/issues/1370
- [x] https://github.com/devfile/api/issues/1384
- [x] https://github.com/devfile/api/issues/1385
- [x] https://github.com/devfile/api/issues/1386
- [x] https://github.com/devfile/api/issues/1388
- [x] https://github.com/devfile/api/issues/1387
- [x] https://github.com/devfile/api/issues/1389

**Comment by Jdubrick** [comment]
Added new issues to the checklist for new repositories added to the CLO Monitor

**Comment by Jdubrick** [comment]
All child issues have been completed, closing this item now as completed.
