### ISSUE TITLE
Update Registry Support's k8s dependencies

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1306]
## Which area/kind this issue is related to?

/area registry

## Issue Description

As part of https://github.com/devfile/api/issues/1303 we should check if we can update the dependency of `k8s.io/apimachinery`. This dependency is using the `golang.org/x/net@v0.8.0` which should be updated to a newer version. Both `server` (direct) and `generator` (indirect) are using this module. For `generator` and `registry-library` that have `apimachinery` as indirect dependency we should update the direct dependencies that are using this package.

## Acceptance Criteria

- [x] The direct dependency inside `index/server` should be updated.
- [x] Direct dependencies using `k8s/apimachinery` inside `index/generator` and `registry-library` should be updated.
- [x] Use the same versions that HAS uses

**Comment by michael-valdron** [comment]
Updated all direct dependencies with tied indirect dependencies for patching `k8s.io/apimachinery` to `v0.26.10`. 

Local dependency `github.com/devfile/registry-support/index/generator` now using local path:
```
# index server
replace github.com/devfile/registry-support/index/generator v0.0.0 => ../generator

# registry library
replace github.com/devfile/registry-support/index/generator v0.0.0 => ../index/generator
```

**Comment by michael-valdron** [comment]
PR ready for review: https://github.com/devfile/registry-support/pull/190
