### ISSUE TITLE
Update Registry Operator's k8s dependencies

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1307]
## Which area/kind this issue is related to?

/area registry

## Issue Description

As part of https://github.com/devfile/api/issues/1303 we should check if we can update the dependency (direct or indirect) of `k8s.io/apimachinery`. This dependency is using the `golang.org/x/net@v0.8.0` which should be updated to a newer version.

As inside `go.mod` we are including the `apimachinery` as an indirect dependency we should update the direct depency that is importing it.

## Acceptance Criteria

- [x] Direct dependencies using `k8s/apimachinery` should be updated.
- [x] Use the same versions that HAS uses

**Comment by michael-valdron** [comment]
I can take this issue once its planned.

**Comment by michael-valdron** [comment]
Patch PR is ready for review: https://github.com/devfile/registry-operator/pull/60
