### ISSUE TITLE
Spike: Investigate what is needed for a deployment scope detection mechanism

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1322]
## Which area/kind this issue is related to?

/kind task

/area registry

## Issue Description

We need to investigate into what is needed for an implementation of a deployment scope detection mechanism (#1197) before we can do so. This investigation should also follow #1321 closely to know how to handle the field.

## Acceptance Criteria

- [x] Investigate into what is needed under the index generator to implement a deployment scope detection mechanism
- [x] Define how to handle the field to introduce in #1321
- [x] Define what logic is needed for the index generator to detect and fill deployment scopes
- [x] Write proposal with these results and refine #1197 with what is needed

**Comment by michael-valdron** [comment]
# Proposed New Field
A new field `deploymentScope` will be included as part of the index schema to provide the piece of metadata about which scope(s) the stack is part of. The `deploymentScope` field is to be `string[]` typed with value limitations of either `innerloop` or `outerloop`.

## V1 Example

```json
{
	"name": "go",
	"displayName": "Go Runtime",
	"description": "Stack with the latest Go version",
	"type": "stack",
	"deploymentScope": ["innerloop"],
	...
}
```

## V2 Multi Version Example

```json
{
	"name": "go",
	"displayName": "Go Runtime",
	"description": "Stack with the latest Go version",
	"type": "stack",
	...
	"versions": [
  		{
    			"version": "1.2.0",
    			"schemaVersion": "2.1.0",
    			"description": "Stack with the latest Go version with devfile v2.1.0 schema version",
    			"deploymentScope": ["innerloop"]
			...
  		},
		{
    			"version": "1.3.0",
    			"schemaVersion": "2.2.0",
    			"description": "Stack with the latest Go version with devfile v2.2.0 schema version",
    			"deploymentScope": ["innerloop", "outerloop"]
			...
  		},
	]
}
```

**Comment by michael-valdron** [comment]
# Insights of Interest
- `schemaVersion` - Any version `< 2.2.0` can only do innerloop deployment scope
- **Command Groups**
  - `run`, `debug` - These command groups are within the innerloop deployment scope
  - `deploy` - This command group is within the outerloop deployment scope

**Comment by michael-valdron** [comment]
> # Insights of Interest
> 
>     * `schemaVersion` - Any version `< 2.2.0` can only provide an innerloop deployment scope
> 
>     * **Command Groups**
>       
>       * `run`, `debug` - These command groups are within the innerloop deployment scope
>       * `deploy` - This command group is within the outerloop deployment scope
>       * **Note**: Command groups under parent devfiles and overrides should also checked

Did some revisions to the Insights of Interest to include analysis of components:
* **Components**
  * There should be at least one `container` component for innerloop
  * There should be at least one `kubernetes` or `openshift` component with a `deployment` kind of specification defined for outerloop

**Comment by elsony** [comment]
Change looks good
