### ISSUE TITLE
Implement alizer support for devfile port detection

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1331]
## Which area/kind this issue is related to?

/area alizer

## Issue Description

This issue part of EPIC https://github.com/devfile/api/issues/1363 and is focusing on the implementation of devfile port detection function. This task has several steps we should follow:

* Expand the functionality of `utils.GetLocations()` to detect locations for devfiles too. The function will follow the some prioritization rules:
	1. First look into the root level and then we will look one level down, exactly like the dockerfile case.
	2. The devfile naming follows specific naming prioritization -> `devfile.yaml > .devfile.yaml > devfile.yml > .devfile.yml`

* Implementation of `enricher.GetPortsFromDevfile`, similar to `enricher.GetPortsFromDockerfile` which will be using the library's `parser.Parse` function in order to fetch the ports from the devfile.

* The function will return either inner loop, or outerloop ports (or both), based on what flag the user passes in. 

* Require user to specify inner loop vs. outerloop ports (or both) when retrieving the ports

## Acceptance Criteria
- [ ] The `GetPortsFromDevfile` is implemented and able to detect ports inside a `devfile.y(a)ml`.
- [ ] Specific prioritization will be followed for the naming of the devfiles.
- [ ] Test cases are created.
- [ ] Flags to specify inner loop, outerloop or both types of ports
- [ ] Alizer to use Devfile library to parse devfiles

**Comment by johnmcollier** [comment]
Moving to refinement for Nov 17th - @thepetk to open separate issue under epic for investigating devfile library changes that may be needed.

**Comment by thepetk** [comment]
> Moving to refinement for Nov 17th - @thepetk to open separate issue under epic for investigating devfile library changes that may be needed.

@johnmcollier I've created item: https://github.com/devfile/api/issues/1338

**Comment by thepetk** [comment]
I've added a comment related to this issue here: https://github.com/devfile/api/issues/1338#issuecomment-1863069214
