### ISSUE TITLE
Spike: Investigate podman support in container scripts under devfile repositories

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1334]
/kind user-story

## Which area this user story is related to?

/area api
/area registry
/area landing-page
/area registry-viewer

## User Story

As a contributor, I want script support for podman, so that I can use and support podman when developing for devfile services.

Currently, https://github.com/devfile/registry-support has limited support for podman added to a number of container scripts: https://github.com/devfile/registry-support/pull/101

We would like this support for podman in container scripts given to all of our source repositories. First, we will need to investigate how many of our repositories currently have this support and what level of support is there.

## Acceptance Criteria

- [x] Investigate https://github.com/devfile/registry-support for missing support
- [x] Investigate https://github.com/devfile/registry for missing support
- [x] Investigate https://github.com/devfile/registry-operator for missing support
- [x] Investigate https://github.com/devfile/api for missing support
- [x] Investigate https://github.com/devfile/devfile-web for missing support

**Comment by Jdubrick** [comment]
## Spike Findings

### Registry-Support

This repository has support for podman with the implementation of the `setenv.sh` script which allows the alias to be set in the build scripts runtime. No changes should be required here and the `setenv.sh` script can be used as a guide/fix for some of the other repositories.

### Registry

Currently the `.ci/build.sh` script is explicitly using docker and will need to be adjusted for podman support.
https://github.com/devfile/api/issues/1339

### Registry-Operator

The use of the Makefile in this repository to run commands such as `docker-build` and `docker-push` create the same issue where the podman alias is not being recognized. <Link to issue for this repo>
https://github.com/devfile/api/issues/1340

### Api

Ran into issues trying to run the build for this project as well. The `docker-run.sh` script is explicitly using docker and not allowing for the use of podman without hardcoding changes.
https://github.com/devfile/api/issues/1341

### Devfile-Web

This project is able to be built and deployed without any podman/docker changes as it doesn't rely on those technologies. The main use of docker in this repo is for the GitHub workflows.
