### ISSUE TITLE
Further optimizations on alizer's port detection process

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1337]
## Which area/kind this issue is related to?

/area alizer

## Issue Description

There are cases like https://github.com/stackrox/stackrox where we have to analyze a large project with many files. Some optimizations could also be added in the port detection process:

* We can add directories like `mocks` or `migrations` into the list of `excluded_folders` inside `language-customization.yaml` for `go` language.
* We can exclude files that end with `_test.go` from the port detection process. One workaround could be to update the `GenerateApplicationFileFromFilters` function in order to exclude filepaths. For example we can provide a list of excluded keywords which if they are contained inside a filepath, the filepath should be excluded.

## Acceptance Criteria

- [ ] Directories named `mocks` or `migrations` should be ignored during component detection process.
- [ ] Files like `_test.go` should be ignored during a go component port detection process.
- [ ] Test cases should be added for the enhanced port detection.
- [ ] Updates to documentation (specifically to port detection docs)

**Comment by Jdubrick** [comment]
PR opened: https://github.com/devfile/alizer/pull/38

Also created another issue related to this PR as it was mainly for Go, it would be nice to refactor some code and make it easily adaptable for any language to have excluded folders/filepaths: https://github.com/devfile/api/issues/1376
