### ISSUE TITLE
DownloadGitRepoResources function implementation should also handle variations of other devfile.yaml in its if-block

### ISSUE THREAD

**Issue by maysunfaisal** [devfile/api#1362]
## Which area this feature is related to?

/kind bug

### Which area this bug is related to?

/area library

### Go project

**Operating System and version:**

**Go Pkg Version:**

### Node.js project

**Operating System and version:**

**Node.js version:**

**Yarn version:**

**Project.json:**

### Web browser

**Operating System and version:**

**Browser name and version:**

## Bug Summary

**Describe the bug:**

The `DownloadGitRepoResources` function implementation checks for `devfile.yaml`, 

```
if !gitUrl.IsFile || gitUrl.Revision == "" || !strings.Contains(gitUrl.Path, OutputDevfileYamlPath) {
	return fmt.Errorf("error getting devfile from url: failed to retrieve %s", url)
}
```

The function should also handle various other possibilities of devfile.yaml like devfile.yml, .devfile.yaml, .devfile.yml...

**To Reproduce:**

## Expected behavior

Function should be able to handle various devfile naming conventions.

## Additional context

devfile.yaml has a few naming conventions that is accepted like .devfile.yaml and devfile.yml. They should be considered along side devfile.yaml

**Comment by Jdubrick** [comment]
Need to add acceptance criteria for determining if the function affected should be auto-detecting or if the user is passing a devfile url and we are trying to parse it.

**Comment by Jdubrick** [comment]
> Need to add acceptance criteria for determining if the function affected should be auto-detecting or if the user is passing a devfile url and we are trying to parse it.

Looks like in the [usage documentation](https://github.com/devfile/library?tab=readme-ov-file#usage) at step 1 the entry point is `devfilePkg.ParseDevfileAndValidate(parserArgs)`, this trickles down to the `DownloadGitRepoResources` function. I believe as a result this is going to take a user input for the devfile in an attempt to parse it.
