### ISSUE TITLE
Deprecate stack versions with images using node.js 16

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1364]
## Which area/kind this issue is related to?

/area registry

## Issue Description

As seen in the [nodejs.org](https://nodejs.org/en/blog/announcements/nodejs16-eol) the `Node.js 16` has reached its end-of-life date (September 11th, 2023). The [api#1300](https://github.com/devfile/api/issues/1300) has introduced the `Deprecated` label to stacks.

That said, we can also add the same label to specific stack versions using images with node.js 16. An easy way to identify them is the renovate bot updates [here](https://github.com/devfile/api/issues/1363). Therefore, those stacks are:

- `nodejs-angular/2.0.2`
- `nodejs-nextjs/1.0.3`
- `nodejs-nuxtjs/1.0.3`
- `nodejs-react/2.0.2`
- `nodejs-svelte/1.0.3`
- `nodejs-vue/1.0.2`
- `nodejs/2.1.1`

## Acceptance Criteria

- [ ] The `Deprecated` tag has been added to the stack versions using images with `node.js 16`.
- [ ] Exclude the deprecated stack versions paths from the `renovate.json` (exactly like the golang deprecated versions).

**Comment by Jdubrick** [comment]
Pulling into current sprint for myself as I can complete it before end of sprint. Needed another quick issue to work on while the registry support release process is in discussion phase and changes are being made.

**Comment by michael-valdron** [comment]
PR checks might be blocked by #1484

FYI @Jdubrick

**Comment by Jdubrick** [comment]
> PR checks might be blocked by #1484
> 
> FYI @Jdubrick

can confirm this is breaking the PR checks 
https://github.com/devfile/registry/actions/runs/8348517850/job/22850619349?pr=337

**Comment by michael-valdron** [comment]
No longer blocked: https://github.com/devfile/registry/pull/337#issuecomment-2012732142
