### ISSUE TITLE
devfile/registry CNCF Cleaner Tasks

### ISSUE THREAD

**Issue by maysunfaisal** [devfile/api#1368]
## Which area/kind this issue is related to?

/area registry

## Issue Description

As part of CNCF CLOMonitor report - https://clomonitor.io/projects/cncf/devfile, devfile/registry repo has been tagged with the community checkset https://github.com/cncf/clomonitor/blob/main/data/cncf.yaml#L521

The list of checksets and their requirement can be found at https://clomonitor.io/docs/topics/checks/

- [x] Documentation / Adopters
- [x] Documentation / Code of conduct
- [x] Documentation / Contributing
- [x] Documentation / Governance
- [x] Documentation / Readme
- [x] Documentation / Roadmap
- [x] Documentation / Summary table
- [x] Documentation / Website
- [x] Best practices / Community meeting
- [x] Best practices / GitHub discussions
- [x] Best practices / Slack presence
- [x] Legal / Trademark disclaimer

**Comment by Jdubrick** [comment]
Opened a [PR](https://github.com/devfile/registry/pull/258) that aims to knock most of the items off the above list. In order to complete the `Summary Table` I will need to create a PR on the CLO repo.

**Comment by Jdubrick** [comment]
All tasks were completed except `Documentation/Summary Table` in which I need to make a PR to the CLO repo to add this. This item will need to be added for multiple repos so will be waiting for all of them so I just have to make 1 PR.
