### ISSUE TITLE
devfile/library CNCF Cleaner Tasks

### ISSUE THREAD

**Issue by maysunfaisal** [devfile/api#1369]
## Which area/kind this issue is related to?

/area library

## Issue Description

As part of CNCF CLOMonitor report - https://clomonitor.io/projects/cncf/devfile, devfile/library repo has been tagged with the code-lite checkset https://github.com/cncf/clomonitor/blob/main/data/cncf.yaml#L521 but I think it is wrongly classified and it should a code checkset

The list of checksets and their requirement can be found at https://clomonitor.io/docs/topics/checks/

- [x] Documentation / Changelog
- [x] Documentation / Contributing
- [x] Documentation / Maintainers
- [x] Documentation / Readme
- [x] License
- [x] License / Approved
- [x] License / Scanning
- [x] Best practices / Artifact Hub badge
- [x] Best practices / CLA
- [x] Best practices / DCO
- [x] Best practices / OpenSSF best practices badge
- [ ] Best practices / OpenSSF Scorecard badge
- [x] Best practices / Recent release

**Comment by Jdubrick** [comment]
Pr opened. Last item for the OpenSSF Scorecard badge will be brought up in discussion once the team returns from recharge.

**Comment by Jdubrick** [comment]
PR opened for scorecard badge, after this is merged and it runs properly I will be adding the badge to the rest of the repositories.
