### ISSUE TITLE
devfile/api CNCF Cleaner Tasks

### ISSUE THREAD

**Issue by maysunfaisal** [devfile/api#1370]
## Which area/kind this issue is related to?

/area api

## Issue Description

As part of CNCF CLOMonitor report - https://clomonitor.io/projects/cncf/devfile, devfile/api repo has been tagged with the code checkset https://github.com/cncf/clomonitor/blob/main/data/cncf.yaml#L521 

The list of checksets and their requirement can be found at https://clomonitor.io/docs/topics/checks/

- [x] Documentation / Changelog
- [x] Documentation / Contributing
- [x] Documentation / Maintainers
- [x] Documentation / Readme
- [x] License
- [x] License / Approved
- [x] License / Scanning
- [x] Best practices / Artifact Hub badge
- [x] Best practices / CLA
- [x] Best practices / DCO
- [x] Best practices / OpenSSF best practices badge
- [ ] Best practices / OpenSSF Scorecard badge
- [x] Best practices / Recent release

**Comment by Jdubrick** [comment]
Badge was created for api repo [here](https://www.bestpractices.dev/en/projects/8179). Will have to open separate issues dedicated to going through each badge item and checking it for completeness. Every repo tagged as `Code` on CLOMonitor will need to have their own badge.

**Comment by Jdubrick** [comment]
Opened a PR that covers all tasks but the `OpenSSF Scorecard Badge` as it requires setting up GitHub Workflows. Will see what the team thinks after the recharge when everyone returns.

**Comment by Jdubrick** [comment]
Reopening as one item is still missing and the issue was auto closed by a PR merge.
