### ISSUE TITLE
Fix registry's nightly run check for RHTAP

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1372]
## Which area this feature is related to?

/kind bug

### Which area this bug is related to?

/area ci
/area registry
/area test-automation

## Bug Summary

**Describe the bug:**

The registry nightly run is failing after the completion of https://github.com/devfile/api/issues/1112 (more details here: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-devfile-registry-main-v4.12-rhtap-nightly-devfile-compatibility/1732007644123631616).

This is because the `tests/rhtap/rhtap_test.go` calls `sampleEntry.Git.Remotes.Origin` which has now changed.

**To Reproduce:**

Check the failing test here: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-devfile-registry-main-v4.12-rhtap-nightly-devfile-compatibility/1732007644123631616

## Expected behavior

The test should be passing

## Any logs, error output, screenshots etc? Provide the devfile that sees this bug, if applicable

https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-devfile-registry-main-v4.12-rhtap-nightly-devfile-compatibility/1732007644123631616

## Additional context

We should try to test the default version of the sample and get the git remote from there.

### Any workaround?

Described in the additional context

### Suggestion on how to fix the bug

Described in the additional context

**Comment by michael-valdron** [comment]
blocking community devfile registry promotion

**Comment by michael-valdron** [comment]
Monitoring the results of the nightly testing, if there are problems I will re-open this issue.

**Comment by thepetk** [comment]
I'm re-opening the issue as the nightly run still experiences issues (though I think they are not related)

**Comment by thepetk** [comment]
Closing this issue as I don't think is related to the nightly run failure
