### ISSUE TITLE
devfile/library CNCF Defender tasks

### ISSUE THREAD

**Issue by maysunfaisal** [devfile/api#1374]
## Which area/kind this issue is related to?

/area library

## Issue Description

As part of CNCF CLOMonitor report - https://clomonitor.io/projects/cncf/devfile, devfile/library repo has been tagged with the code-lite but i think it should be code and its checkset https://github.com/cncf/clomonitor/blob/main/data/cncf.yaml#L521 

The list of checksets and their requirement can be found at https://clomonitor.io/docs/topics/checks/

- [x] Security / Code review
- [x] Security / Dangerous workflow
- [ ] Security / Dependency update tool
- [x] Security / Maintained
- [ ] Security / Insights
- [ ] Security / Policy
- [x] Security / Binary artifacts

**Comment by michael-valdron** [comment]
Wait for upcoming refinement call to review with @maysunfaisal
