### ISSUE TITLE
Create a new release for Registry Support

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1398]
## Which area/kind this issue is related to?

/area registry
/area releng

## Issue Description

The latest version of the `registry-support` (1.0.1) was created a long time ago, although all of the components included in this mono-repo were active and updated after this point.

That said, I would propose to cut a new release to include all the new changes introduced between the latest release and the current date. This will also highlight to all the potential consumers/contributors how active this mono repo is.

## Acceptance Criteria

- [ ] A new release has been created including all the new updates for the multiple components of the registry-support.

**Comment by Jdubrick** [comment]
> Linking PR [devfile/registry-support#196](https://github.com/devfile/registry-support/pull/196) as we may need to do more actions regarding the release check after we publish this new release of registry-support

@thepetk the release check on CLOMonitor will automatically detect when a release is cut so whoever does the release won't have to do anything extra!

**Comment by thepetk** [comment]
Linking with the release process automation https://github.com/devfile/api/issues/1450. Might be good to separate the automation part from the release process part.
