### ISSUE TITLE
Default theme is too small and almost unreadable

### ISSUE THREAD

**Issue by metacosm** [devfile/api#140]
It also leaves way too much empty space.
<img width="1279" alt="Screenshot 2020-09-24 at 13 26 04" src="https://user-images.githubusercontent.com/120057/94139311-baf71e80-fe69-11ea-8086-615b3a3c3dbb.png">

… some of us are not getting any younger! 😅

**Comment by mmulholla** [comment]
This problem was introduced by this pull request: https://github.com/devfile/docs/pull/9

It added a bootstrap.css file which causes the issue.  The boostrap.css file pulls in "Bootstrap v3.4.1 (https://getbootstrap.com/)" which contains the font size settings which are the problem.

Investigating further.

**Comment by mmulholla** [comment]
Note: index.html includes two css file, bootstrap.css and site.css, the current inclusion order is:
1. site.css
2. bootstrap.css

If the order is reversed the problem disappears

**Comment by themr0c** [comment]
I added the bootstrap.css as a workaround to embed the API reference HTML properly. If we could avoid loading it for the complete docs site it would be awesome. Would it be an option to rebuild the API reference HTML without the dependency on bootstrap?

**Comment by mmulholla** [comment]
Thank you, will try removing the bootstrap.css this morning.

**Comment by mmulholla** [comment]
If I remove the use of boostrap.css the API reference is embedded correctly, it just doesn't look quite as nice. I propose to remove the boostrap.css for now. There is a lot to do on the docs and we can work on better appearance in the future.

**Comment by themr0c** [comment]
The API reference is rather unreadable without the bootstrap.css ...

**Comment by davidfestal** [comment]
This is fixed (as a side effect) by PR https://github.com/devfile/docs/pull/11

**Comment by mmulholla** [comment]
Closing ----  fixed as David said
