### ISSUE TITLE
Missing parts of the website / need to add link to GitHub / missing links

### ISSUE THREAD

**Issue by cdrage** [devfile/api#141]
Going through the website, there are a few things that I noticed.

- [ ] There is no link to the GitHub page, it was difficult to actually find (I couldn't even find it on Google) until I clicked on the "Edit this page" button
- [ ] The buttons at the top do not work. (where it says Products, Services, Resources as well as Download).
- [ ] No links to Gitter / where you guys generally talk

**Comment by mmulholla** [comment]
The website uses an unedited template from Antora : https://gitlab.com/antora/antora-ui-default . So we get the artifacts defined in the template including ones which we do not use.   This is what Antora sasy about the template:

"While the default UI is ready to be used with Antora, the intent is that you’ll fork it and customize it for your own needs.
It’s intentionally minimalistic so as to give you a good starting point without requiring too much effort to customize."

I propose we follow this advice and make our own version of the template.

**Comment by elsony** [comment]
+1 on making our own version of the template

**Comment by rkratky** [comment]
@cdrage, I opened https://github.com/devfile/api/issues/180 for adding the relevant project links to the website.

And I'd like to repurpose this issue for fixing the Antora theme (which will fix the problem with non-functional buttons and other issues as well).

**Comment by rkratky** [comment]
* #180 used to track addition of relevant links
* Antora theme fixed in https://github.com/devfile/docs/pull/27
