### ISSUE TITLE
[Spike] Investigate Test Cases Required For Registry Index Server

### ISSUE THREAD

**Issue by Jdubrick** [devfile/api#1420]
## Which area/kind this issue is related to?

/area registry

## Issue Description

In order to gain the information required to properly size https://github.com/devfile/api/issues/1192 we need to investigate what tests are missing for the registry index server.

- [ ] Missing test cases are documented and added as items to https://github.com/devfile/api/issues/1192

**Comment by thepetk** [comment]
blocks #1192
