### ISSUE TITLE
Python devfile sample fails to be built in Red Hat OpenShift Dev Spaces 3.10.1

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1423]
## Which area this feature is related to?

/kind bug

### Which area this bug is related to?

/area registry

## Bug Summary

**Describe the bug:**

This issue links to the issue created in the Python devfile sample repo [here](https://github.com/devfile-samples/devfile-sample-python-basic/issues/41) inorder to monitor it from the devfiles org.

**To Reproduce:**

N/A

## Expected behavior

The devfile sample should be built.

## Any logs, error output, screenshots etc? Provide the devfile that sees this bug, if applicable

Asked the user experienced the issue to provide more context ([here](https://github.com/devfile-samples/devfile-sample-python-basic/issues/41#issuecomment-1906055852))

**Comment by thepetk** [comment]
Waiting for user feedback in the sample repo issue

**Comment by michael-valdron** [comment]
> Waiting for user feedback in the sample repo issue

Have not heard feedback since previous comment, will close for now and can re-open again if problem persists.
