### ISSUE TITLE
Devfile samples README is out-of-date

### ISSUE THREAD

**Issue by yangcao77** [devfile/api#1425]
## Which area this feature is related to?

/area documentation

## Which area is this documentation change is related to?

/area registry

## Issue details

**What mistake did you find / what is missing in the documentation?**

All the README files for samples are out-of-date, the links are pointing to incorrect lines
for example: check the link in 1,3 in [springboot sample](https://github.com/devfile-samples/devfile-sample-java-springboot-basic/blob/main/README.md)

The [dotnet sample](https://github.com/devfile-samples/devfile-sample-dotnet60-basic/blob/main/README.md) is missing doc.  please use the [README from dance sample](https://github.com/redhat-appstudio/devfile-sample-dotnet60-dance/blob/main/README.md) when updating the dotnet sample

The [nodejs sample README](https://github.com/nodeshift-starters/devfile-sample/blob/main/README.md) is with wrong port number

## Acceptance Criteria
- [x] go-basic main branch
- [x] go-basic v2.0.0 branch
- [x] python-basic main branch
- [x] python-basic v2.0.0 branch
- [x] dotnet60-basic
- [x] quarkus
- [x] springboot-basic main branch
- [x] springboot-basic v2.0.0 branch
- [x] nodejs

**Comment by Jdubrick** [comment]
Added acceptance criteria to organize the tracking of completion

**Comment by thepetk** [comment]
@

> All of the PRs can be found below:
> 
> * [x]  [go-basic main branch](https://github.com/devfile-samples/devfile-sample-go-basic/pull/37)
> * [x]  [go-basic v2.0.0 branch](https://github.com/devfile-samples/devfile-sample-go-basic/pull/38)
> * [x]  [python-basic main branch](https://github.com/devfile-samples/devfile-sample-python-basic/pull/45)
> * [x]  [python-basic v2.0.0 branch](https://github.com/devfile-samples/devfile-sample-python-basic/pull/46)
> * [x]  [dotnet60-basic](https://github.com/devfile-samples/devfile-sample-dotnet60-basic/pull/12)
> * [x]  [quarkus](https://github.com/devfile-samples/devfile-sample-code-with-quarkus/pull/28)
> * [x]  [springboot-basic main branch](https://github.com/devfile-samples/devfile-sample-java-springboot-basic/pull/42)
> * [x]  [springboot-basic v2.0.0 branch](https://github.com/devfile-samples/devfile-sample-java-springboot-basic/pull/43)
> * [x]  [nodejs](https://github.com/nodeshift-starters/devfile-sample/pull/43)

@Jdubrick all PRs are now merged. Is this good to close?

**Comment by Jdubrick** [comment]
Yup all good to close, didn't realize the last one was merged now! :) @thepetk
