### ISSUE TITLE
Fix registry operator hostname format for k8s

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1431]
## Which area/kind this issue is related to?

/area registry

## Issue Description

Currently, the registry operator hostname setup only uses the CR name value for the hostname part, for openshift deployments and how the helm chart sets up the hostname [_template.tpl#L16](https://github.com/devfile/registry-support/blob/f66264f22310c3c93bf0c77db5f4cd4b560aba5e/deploy/chart/devfile-registry/templates/_template.tpl#L16), the CR name is coupled with the namespace name to create the hostname.

The [registry operator source](https://github.com/devfile/registry-operator/blob/f55ab8e7c8061934547c7d55bd67d81d509a8752/pkg/registry/ingress.go#L72) should be changed to something of the following:

**GetDevfileRegistryIngress**

```go
func GetDevfileRegistryIngress(cr *registryv1alpha1.DevfileRegistry) string {
	return GetHostname(cr) + "." + cr.Spec.K8s.IngressDomain
}
```

**GetHostname**

```go
func GetHostname(cr *registryv1alpha1.DevfileRegistry) string {
	return fmt.Sprintf("%s-%s", cr.Name, cr.Namespace)
}
```

Parent Epic: #1274

## Acceptance Criteria

- [x] Create getter function to receive the hostname part of the ingress address
    - Create hostname using the format `<DevfileRegistry.Name>-<DevfileRegistry.Namespace>`
- [x] Update `GetDevfileRegistryIngress` to couple the result of the hostname getter function and the set ingress domain `DevfileRegistry.Spec.K8s.IngressDomain`
- [x] Ensure integration test cases are passing

**Comment by Jdubrick** [comment]
Functions have been created and updated to reflect the changes. I added some unit tests for these changes and they seem to be working great. 

Currently working on adding a few more cases to the unit tests and then need to integration test. The integration tests are giving me issues as the pods don't want to run properly. Working through that issue before opening a PR.
