### ISSUE TITLE
Add `DevfileRegistry` CRD field for setting the ingress class

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1434]
## Which area/kind this issue is related to?

/area registry

## Issue Description

The registry operator is missing a field to set the ingress class name https://github.com/devfile/registry-operator/blob/f55ab8e7c8061934547c7d55bd67d81d509a8752/api/v1alpha1/devfileregistry_types.go#L117, which is what the helm chart has: https://github.com/devfile/registry-support/blob/f66264f22310c3c93bf0c77db5f4cd4b560aba5e/deploy/chart/devfile-registry/values.yaml#L18

Parent Epic: #1274 

## Acceptance Criteria

- [ ] Implement `DevfileRegistry.K8s.IngressClass` field
- [ ] Create test case to set `DevfileRegistry.K8s.IngressClass` field
- [ ] Run integration tests to verify changes

**Comment by thepetk** [comment]
As discussed this item will not be covered during this sprint so it will be moved to the next one
