### ISSUE TITLE
[Spike] Investigate creation of a registry stack for AI development

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1449]
## Which area this issue is related to?

/area registry

## Issue description

As an application developer or an ML engineer who wants to develop AI solutions I'd like to have a starting point where I can develop ML/AI applications within the kubernetes and OpenShift Environments.

To achieve that, a new registry stack can be created including all the necessary ML & AI tools that an ML engineer should have to work on their ML or AI applications.

This issue focuses on the investigation process around the technologies & tools that this registry stack should include.

## Acceptance Criteria

- [x] The contents of the registry stack are defined.

**Comment by michael-valdron** [comment]
Investigate Eclipse Che requested stack for llama

**Comment by michael-valdron** [comment]
We can start out with the following frameworks:
- [PyTorch](https://pytorch.org/)
- [Tensorflow v2](https://www.tensorflow.org/)
- [FastAI](https://github.com/fastai/fastai)

**Comment by thepetk** [comment]
> We can start out with the following frameworks:
> 
> * [PyTorch](https://pytorch.org/)
> * [Tensorflow v2](https://www.tensorflow.org/)
> * [FastAI](https://github.com/fastai/fastai)

I was wondering if it makes sense to have 3 separate stacks? (e.g. following the `python-flask` / `python-django` separation).

**Comment by michael-valdron** [comment]
> > We can start out with the following frameworks:
> > 
> > * [PyTorch](https://pytorch.org/)
> > * [Tensorflow v2](https://www.tensorflow.org/)
> > * [FastAI](https://github.com/fastai/fastai)
> 
> I was wondering if it makes sense to have 3 separate stacks? (e.g. following the `python-flask` / `python-django` separation).

We decided in a previous team discussion to use one stack with three starter projects (one for each framework). We also deciding to use a purpose built image with this stack to provide common dependencies rather than placing everything in each starter projects dependency definitions.

**Comment by michael-valdron** [comment]
Reviewing current revision: https://docs.google.com/document/d/1oolCZRL4eAiuqTufMni6sOiTQjH7lsfwD09l_BU-G2A/edit?usp=sharing

**Comment by michael-valdron** [comment]
Created epic for tracking creation of the stack: #1574

**Comment by michael-valdron** [comment]
Final revision of the proposal: https://docs.google.com/document/d/1oolCZRL4eAiuqTufMni6sOiTQjH7lsfwD09l_BU-G2A/edit?usp=sharing

Enough is defined now to close this issue, continue tracking progress on creation of the stack here: #1574
