### ISSUE TITLE
Devfile Registry Support Release Automation

### ISSUE THREAD

**Issue by Jdubrick** [devfile/api#1450]
## Which area/kind this issue is related to?

/area registry
/area releng

## Issue Description
As a maintainer of the devfile project I want to have the release process be as efficient as possible. By automating this process it makes it simple to quickly cut new releases and reduces overall time spent by a maintainer performing the release.

Similar efforts have been implemented in `devfile/api` [here](https://github.com/devfile/api/blob/b4fea572af1a98ca487495857add4007c35f5aea/make-release.sh) and is planned to be implemented in `devfile/registry-operator` as well [here](https://github.com/devfile/registry-operator/pull/75). The work required by this issue would closely follow the idea implemented in the other two repositories.

## Acceptance Criteria

- [ ] Create new shell script to perform automation process
- [ ] Script should perform any changes to version numbers in documentation/files (if necessary)
- [ ] Script should automate the process of pushing release (and any necessary changes) to git and tagging the commit as newest version
- [ ] Test the script on a forked repository
- [ ] Update documentation to reflect new release process/script

**Comment by Jdubrick** [comment]
This issue is currently blocked as it requires changes to the git history of the release branches for registry operator. Currently there is squash commits in the release branches which conflict with the automation as the bot cannot handle merge conflicts without human intervention, which defeats the purpose of the automation. This is occurring because the releases are based off of `main` but in the release branches it has diverged from `main` in the git history with these squash commits. In order to prevent this from happening and to allow this issue to become unblocked the git history needs to be altered in the release branches so that it does not diverge from `main`.

`release-v0`: https://github.com/devfile/registry-operator/commits/release-v0/
`main`: https://github.com/devfile/registry-operator/commits/main/

**Comment by michael-valdron** [comment]
Need release process issue before planning into a sprint.

**Comment by Jdubrick** [comment]
Blocked by https://github.com/devfile/api/issues/1472

**Comment by michael-valdron** [comment]
Removing status/blocked with completion of #1472
