### ISSUE TITLE
[Spike] Investigate usage of files clean in the Devfiles org

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1451]
## Which area/kind this issue is related to?

/area api
/area library
/area registry
/area alizer
/area integration-tests

## Issue Description

After the fix introduced for `registry-support` repo (here: https://github.com/devfile/registry-support/commit/0e44b9ca6d03fac4fc3f77d37656d56dc5defe0d) , a thorough check should be made to the rest of the `devfile` repos in order to confirm that we are using properly the file clean.

## Acceptance Criteria

The following repos have been checked and if a patch is needed, it's been applied:
- [x] https://github.com/devfile/api
- [x] https://github.com/devfile/registry
- [x] https://github.com/devfile/library
- [x] https://github.com/devfile/alizer
- [x] https://github.com/devfile/integration-tests

**Comment by Jdubrick** [comment]
Using this comment as a source of information for my findings during the investigation.

### integration-tests
There is a function in our integration tests that performs a similar action to the initial vulnerability we fixed.
https://github.com/devfile/integration-tests/blob/6fc1c86a044bc0632f0b022e4bbc4c1f92bca096/pkg/util/util.go#L913

### alizer
TBD

### library
TBD

### registry
TBD

### api
TBD
