### ISSUE TITLE
[Spike] Investigate on making devfile registry more dynamic

### ISSUE THREAD

**Issue by elsony** [devfile/api#1452]
## Which area/kind this issue is related to?
/area registry

## Issue Description
The current devfile registry requires a rebuild of the container whenever the content of the registry to be rebuilt and redeploy when the content of the registry changes, e.g. devfile, container image change, etc. This issue is to investigate on how we can make it more dynamic without the need for the rebuild/redeploy.

## Target Odo version

> Target Odo version:

**Comment by thepetk** [comment]
Moving back to todo in favor of https://github.com/redhat-appstudio/application-service/pull/451

**Comment by thepetk** [comment]
The suggested workaround is created as an EPIC here: https://github.com/devfile/api/issues/1505. I've also created children issues for each step required for the implementation
