### ISSUE TITLE
Add library support for devfile schema - version 2.2.1 & version 2.2.2

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1454]
## Which area/kind this issue is related to?

/area library

## Issue Description

At the moment when the library parser tries to parse a devfile with `schemaVersion=2.2.2` or `schemaVersion=2.2.1` we get the error:

```
Error: failed to generate index struct: /build/stacks/dotnet60 devfile is not valid:
failed to populateAndParseDevfile: unable to find schema for version "2.2.2".
The parser supports devfile schema for version 2.0.0, 2.1.0, 2.2.0, v1alpha2
```

As seen in the [pkg/devfile/parser/data/versions.go](https://github.com/devfile/library/blob/main/pkg/devfile/parser/data/versions.go#L31-L36) there is no reference for the `2.2.1` or the `2.2.2` versions.

## Acceptance Criteria

- [x] Devfile library supports Devfile schema versions `2.2.1` & `2.2.2`

**Comment by thepetk** [comment]
Steps to follow:

1. Update the [pkg/devfile/parser/data/versions.go](https://github.com/devfile/library/blob/main/pkg/devfile/parser/data/versions.go#L31-L36) to include `2.2.1` & `2.2.2`
2. Cut a pre-release for `2.2.3-alpha` in the devfile/api.

cc @michael-valdron @yangcao77

**Comment by Jdubrick** [comment]
Created PR to add support for 2.2.1 and 2.2.2 here: https://github.com/devfile/library/pull/208

When we cut the pre-release for 2.2.3-alpha it is probably best to open another PR to library to have a 2.2.3 alpha version recognized. I noticed 2.2.1-alpha was being used prior. wdyt?

**Comment by thepetk** [comment]
Re-opening this as we might need to bump up the `registry-support` library's version so we can take advantage of the latest `schemaVersion` support. If you think it should be handled separately happy to open another issue

cc @Jdubrick

**Comment by Jdubrick** [comment]
> Re-opening this as we might need to bump up the `registry-support` library's version so we can take advantage of the latest `schemaVersion` support. If you think it should be handled separately happy to open another issue
> 
> cc [@Jdubrick](https://github.com/Jdubrick)

I think probably a good idea to open a new issue so we can keep the scope of both contained in their own issue. @thepetk
