### ISSUE TITLE
OpenShift Console Routes created from devfiles do not always use HTTPS

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1455]
## Which area this feature is related to?

/kind bug

### Which area this bug is related to?

console support

### Go project

**Operating System and version:** N/A

**Go Pkg Version:** 1.20

## Bug Summary

**Describe the bug:**

In situations when using a devfile from a git source where the devfile kubernetes component is using the `uri` instead `inlined`, the Route is always created with TLS disabled.

Related issue: #1270 

**To Reproduce:**

1. Open web console in a OpenShift 4.1x environment and create a deployment using "Import from Git" on any of the [devfile samples](https://github.com/orgs/devfile-samples/repositories) which use `uri` to reference resources instead of `inlined`
2. Once deployed, try to request using https on any ingress endpoint and route will calm to not exist (even when `secure: true` or `protocol: https` is set). **Note:** Doing the same with plain http will result with expected outcome.

## Expected behavior

When `secure` is set to `true` or `protocol` is set to `https` under the devfile kubernetes component, the route created should enable TLS with redirection from http to https.

This logic is already implemented for kubernetes components which use inlined: https://github.com/openshift/console/blob/170c455125d05b9b6c80b53e2e666617666fb80a/pkg/devfile/resources.go#L186

## Any logs, error output, screenshots etc? Provide the devfile that sees this bug, if applicable

Results are produced with [Go Basic Sample](https://github.com/devfile-samples/devfile-sample-go-basic) with `secure: true` set: https://github.com/devfile-samples/devfile-sample-go-basic/blob/481e66ef328a93db251814a2be8675c86c1cf605/devfile.yaml#L39

**Result with HTTP**

![image](https://github.com/devfile/api/assets/14838510/2e6156b0-82ef-4851-8553-6645e389a6eb)

**Result with HTTPS**

![image](https://github.com/devfile/api/assets/14838510/e5343b6b-2b69-4e62-83d1-ea641e0685c2)

### Any workaround?

None.

### Suggestion on how to fix the bug

Fix described in the following comment should be applied: https://github.com/devfile/api/issues/1270#issuecomment-1865306305

**Comment by Jdubrick** [comment]
Dev console team is looking into this issue and I will add updates here when they become available.

**Comment by michael-valdron** [comment]
> Dev console team is looking into this issue and I will add updates here when they become available.

Moving to waiting until reply.

**Comment by Jdubrick** [comment]
This was moved to the dev console team and the fix was merged into one of their nightly releases. More info here: https://github.com/openshift/console/pull/13771
