### ISSUE TITLE
Deprecate stacks & samples past 1 year since last update

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1459]
## Which area/kind this issue is related to?

/area registry

## Issue Description

Number of stacks and samples in the devfile registry should be state changed to `deprecated` to follow our [stack lifecycle](https://github.com/devfile/registry/blob/main/LIFECYCLE.md#deprecation).

## Acceptance Criteria

Communicate with stack owner to see if there's still interest in maintaining the stack or if a new owner can be found. If not, change state to `deprecated` for all stacks/samples which have not seen updates for > 1 year:

- [ ] [Open Liberty Gradle](https://github.com/devfile/registry/tree/main/stacks/java-openliberty-gradle)
- [ ] [Open Liberty Maven](https://github.com/devfile/registry/tree/main/stacks/java-openliberty)
- [ ] [WebSphere Liberty Gradle](https://github.com/devfile/registry/tree/main/stacks/java-websphereliberty-gradle)
- [ ] [WebSphere Liberty Maven](https://github.com/devfile/registry/tree/main/stacks/java-websphereliberty)
- [ ] [Laravel](https://github.com/devfile/registry/tree/main/stacks/php-laravel)

**Comment by michael-valdron** [comment]
[Laravel](https://github.com/devfile/registry/tree/main/stacks/php-laravel) will remain as acceptance criteria until #1460 is resolved.

**Comment by Jdubrick** [comment]
After looking into this issue the following stacks have been updated recently:

- [Open Liberty Gradle](https://github.com/devfile/registry/pull/350)
- [Open Liberty Maven](https://github.com/devfile/registry/pull/351)
- [WebSphere Liberty Gradle](https://github.com/devfile/registry/pull/344)
- [Websphere Liberty Maven](https://github.com/devfile/registry/pull/343)

It is important to note however these stacks went without any response from the owner for the changes and I believe we should be looking at deprecating them if it happens again.

[Laravel 2.0.1](https://github.com/devfile/registry/pull/349) was updated recently however `2.0.0` and `1.0.1` were not and I will move forward with deprecating those 2 versions as [Team Devfile is the stack owner.](https://github.com/devfile/registry/blob/main/.github/CODEOWNERS#L45)
