### ISSUE TITLE
`e2e-tests` dependency breaking nightly konflux testing

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1468]
## Which area this feature is related to?

/kind bug

### Which area this bug is related to?

/area registry

### Go project

**Operating System and version:** N/A

**Go Pkg Version:** 1.18

## Bug Summary

**Describe the bug:**

Fetching the dependencies for the nightly testing module is currently failing. This is due to the `e2e-tests` dependency being out of date.

This is blocking PRs from testing properly: https://github.com/openshift/release/pull/49019#issuecomment-1977330092

**To Reproduce:**

Run `go mod tidy` under [nightly testing module](https://github.com/devfile/registry/tree/d41593f25e75627a12083b829e490725d16beb4a/tests/rhtap)

## Expected behavior

Should succeed at fetching testing module dependencies.

## Any logs, error output, screenshots etc? Provide the devfile that sees this bug, if applicable

Output is shown in my comment: https://github.com/openshift/release/pull/49019#issuecomment-1977330092

### Any workaround?

None known.

### Suggestion on how to fix the bug

As @thepetk [commented](https://github.com/openshift/release/pull/49019#issuecomment-1979071230), update `github.com/redhat-appstudio/e2e-tests` dependency.

**Comment by thepetk** [comment]
Created https://github.com/devfile/registry/pull/313 to fix this issue

**Comment by thepetk** [comment]
Re-opening as we need to verify that everything is working on https://github.com/openshift/release/pull/49019

**Comment by michael-valdron** [comment]
> Re-opening as we need to verify that everything is working on [openshift/release#49019](https://github.com/openshift/release/pull/49019)

Still failing rehearsals, posted a follow up: https://github.com/openshift/release/pull/49019#issuecomment-1981614091.

**Comment by thepetk** [comment]
> > Re-opening as we need to verify that everything is working on [openshift/release#49019](https://github.com/openshift/release/pull/49019)
> 
> Still failing rehearsals, posted a follow up: [openshift/release#49019 (comment)](https://github.com/openshift/release/pull/49019#issuecomment-1981614091).

I'm pretty sure it's about the way we use the [fw.HasController.WaitForComponentPipelineToBeFinished](https://github.com/devfile/registry/blob/main/tests/rhtap/rhtap_test.go#L118-L119) function. I think all other issues were solved after the https://github.com/devfile/registry/pull/313 and now we can use the latest version of the `e2e-tests`

**Comment by thepetk** [comment]
@michael-valdron I've added a second PR to address the latest issues found for the `rhtap_test.go` (here: https://github.com/devfile/registry/pull/315)

**Comment by thepetk** [comment]
The related pr is currently failing due to an external reason. Waiting a fix to be applied in the release repo side so we can merge and close the issue.

**Comment by thepetk** [comment]
https://github.com/openshift/release/pull/49019 is now merged. Closing the issue
