### ISSUE TITLE
Define Registry Support Release Process

### ISSUE THREAD

**Issue by Jdubrick** [devfile/api#1472]
## Which area/kind this issue is related to?

/area registry
/area releng
/area documentation

## Issue Description
In order to provide consistency across releases for the `registry-support` repository we need to define a process for what needs to be done for each release. This will contain what needs to be done for naming releases, frequency of releases, items to be changed during releases, tagging releases, and creating release branches. This will provide extra information for what needs to be accomplished by the automation planned in https://github.com/devfile/api/issues/1450.

## Acceptance Criteria
- [ ] Release process documented and linked

**Comment by Jdubrick** [comment]
Blocking https://github.com/devfile/api/issues/1450 as it depends on the release process to properly automate.

**Comment by michael-valdron** [comment]
Created a backport release branch for `registry-support v1.1.x`: https://github.com/devfile/registry-support/tree/release/v1.1.x

FYI @Jdubrick

**Comment by Jdubrick** [comment]
Moving this issue to `Review` so that it can accurately reflect the state it's in. Since there is no PR I tagged both of you as a type of review before I close this issue off. If you feel the document is all good to go and this issue is complete please let me know!

[Registry Support Release Process Document](https://docs.google.com/document/d/1JYnQf0M2VcZhJuHn6dxPEYNZ7icoViqJe8dN1jnKsCw/edit?usp=sharing)

cc @thepetk @michael-valdron

**Comment by Jdubrick** [comment]
Marking issue as completed as there seems to be no more comments on the document. This process can be brought up during a parking lot if any additional comments or concerns want to be raised but I believe the content of this issue is completed at this time.

[Registry Support Release Process Document](https://docs.google.com/document/d/1JYnQf0M2VcZhJuHn6dxPEYNZ7icoViqJe8dN1jnKsCw/edit?usp=sharing)
