### ISSUE TITLE
Update Community Devfile Registry to use Go 1.19

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1473]
## Which area/kind this issue is related to?

/area registry

## Issue Description

To meet the objective of #1237, we need to ensure our devfile community registry build and deployment workflows is using Go 1.19.

## Acceptance Criteria
- [x] Update all `go.mod` files under the [test modules](https://github.com/devfile/registry/tree/main/tests) to use Go 1.19
- [x] Refactor all library calls to `io/ioutil` since it is now deprecated
- [ ] Update all dockerfiles and workflows to use Go 1.19
- [ ] Unfreeze `devfile-index-base` and index/generator
   - **Important:** See https://github.com/devfile/registry/pull/316 and https://github.com/devfile/registry/pull/317 for changes to revert
- [ ] Update OpenShift prow jobs to use Go 1.19
- [ ] Update requirements under documentation

**Comment by michael-valdron** [comment]
> Update all `go.mod` files under the [test modules](https://github.com/devfile/registry/tree/main/tests) to use Go 1.19
> Refactor all library calls to `io/ioutil` since it is now deprecated

These are already done, see the following PRs:

- https://github.com/devfile/registry/pull/265
- https://github.com/devfile/registry/pull/313

**Comment by Jdubrick** [comment]
Openshift PR opened here: https://github.com/openshift/release/pull/49735
Registry PR opened here: https://github.com/devfile/registry/pull/318
