### ISSUE TITLE
Devfile Library v2.2.2

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1476]
## Which area/kind this issue is related to?

/kind epic

/area library
/area releng

## Issue Description

A number of changes done to [devfile/library](https://github.com/devfile/library) require a new release to be cut. Additional there are a number of dependency patches done in the latest changes which need to be patched in dependents of [devfile/library](https://github.com/devfile/library).

## Acceptance Criteria

- [x] https://github.com/devfile/api/issues/1454
- [x] #1477
- [x] #1478
- [x] #1479

**Comment by thepetk** [comment]
Closing as the last item was closed when merging https://github.com/devfile/registry/pull/396

cc @Jdubrick as the epic owner
