### ISSUE TITLE
Patch dependent test modules under devfile/registry

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1479]
## Which area/kind this issue is related to?

/kind task

/area registry

## Issue Description

After new `v2.2.2` release of [devfile/library](https://github.com/devfile/library) is made #1477, there should be a version bump of this dependency on [devfile/registry](https://github.com/devfile/registry).

## Acceptance Criteria

- [ ] Bump `github.com/devfile/library` to `v2.2.2`

**Comment by thepetk** [comment]
Related issue: https://github.com/devfile/api/issues/1494

**Comment by Jdubrick** [comment]
Removed blocked status as `v2.2.2` is released

**Comment by thepetk** [comment]
Opened PR https://github.com/devfile/registry/pull/396 to bump up the necessary dependent modules

**Comment by thepetk** [comment]
Sized as 1, after the time spent for the PR
