### ISSUE TITLE
Ensure that every registry stack has the latest version as default

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1482]
## Which area/kind this issue is related to?

/area registry

## Issue Description

There are cases like `nodejs-svelte` that the latest stack version is not the default stack version (has default `1.0.3` while the latest is `1.2.0`). For cases like this the latest version should be `1.2.0`.

Note that the if the stack has outerloop and innerloop versions (e.g. like `go` stack) we should keep the latest to the same category. For example if `1.0.3` (innerloop) is the default and we have `1.2.0` (innerloop) and `2.2.0` (outerloop) we should make `1.2.0` the default.

## Acceptance Criteria

- [ ] All stacks have the latest version as default

**Comment by michael-valdron** [comment]
Recommend manual setting for latest major version bumps.
