### ISSUE TITLE
Broken Node.js stack/sample icon links

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1484]
## Which area this feature is related to?

/kind bug

### Which area this bug is related to?

/area registry

### Go project

**Operating System and version:** N/A

**Go Pkg Version:** 1.19

### Node.js project

**Operating System and version:**

**Node.js version:** 18

**Yarn version:** 1.22.19

**Project.json:**

### Web browser

**Operating System and version:** RHEL 8.9

**Browser name and version:** Firefox 115.8.0esr

## Bug Summary

**Describe the bug:**

Changes to [nodejs.org](http://nodejs.org/) has remove the static vector images currently being referenced by the nodejs stacks and samples under the devfile registries.

During deployment the icons fail to load and are blank. During container image build of `devfile-index`, the build fails reporting the broken icon URL.

**To Reproduce:**

For build error, run any of the scripts used to build devfile registries, such as `build_registry.sh` under [devfile/registry-support](https://github.com/devfile/registry-support) to attempt to build the test registry or `.ci/build.sh` under [devfile/registry](https://github.com/devfile/registry) to attempt to build the community registry.

For deployment, simply visit https://registry.devfile.io/viewer/devfiles/community/nodejs or visit the same stack in your own deployment of the current revisions of `devfile-index`.

## Any logs, error output, screenshots etc? Provide the devfile that sees this bug, if applicable

Missing Node.js images are noticed in any current deployment of the devfile registry:
![image](https://github.com/devfile/api/assets/14838510/b6deb5ff-2460-46cb-848b-7b3d2c372c99)

Below is the build error produced:
```
Error: failed to generate index struct: nodejs index component is not valid: Devfile nodejs has broken or not existing icon

Failed to build the devfile registry index
Error building the devfile registry
Error: building at STEP "RUN bash /build-tools/build.sh /registry /build": while running runtime: exit status 1
```

### Any workaround?

None. Removal of validation for existence of icon during registry build could correct build error until a replacement icon is selected and referenced, this workaround might not be desired.

### Suggestion on how to fix the bug

Replacement icons for Node.js stack and sample will need to be selected and referenced in all our registries, [nodejs.org](http://nodejs.org/) has replacement vector logos here: https://nodejs.org/en/about/branding

### Acceptance Criteria

- [ ] Fix applied for test registry under [devfile/registry-support](https://github.com/devfile/registry-support)
- [x] Fix applied for [devfile/registry](https://github.com/devfile/registry) community registry content

**Comment by thepetk** [comment]
Created 2 PRs to temporarily fix the issue and unblock the build of the registry:
* https://github.com/devfile/registry/pull/338
* https://github.com/devfile-samples/devfile-stack-icons/pull/2

Adding blocker label because is currently blocking https://github.com/devfile/registry/pull/339

**Comment by michael-valdron** [comment]
> > Fix applied for test registry under [devfile/registry-support](https://github.com/devfile/registry-support)
> 
> Need same fix for [devfile/registry-support](https://github.com/devfile/registry-support) as well.
> 
> First PR [devfile/registry#338](https://github.com/devfile/registry/pull/338) still unblocks [devfile/registry#339](https://github.com/devfile/registry/pull/339) 👍

FYI @thepetk

**Comment by thepetk** [comment]
> > > Fix applied for test registry under [devfile/registry-support](https://github.com/devfile/registry-support)
> > 
> > 
> > Need same fix for [devfile/registry-support](https://github.com/devfile/registry-support) as well.
> > First PR [devfile/registry#338](https://github.com/devfile/registry/pull/338) still unblocks [devfile/registry#339](https://github.com/devfile/registry/pull/339) 👍
> 
> FYI @thepetk

@michael-valdron 

Yeap! Was autoclosed when I merged the PR. I've added fix https://github.com/devfile/registry-support/pull/226 for registry-support. Moving also back to review.
