### ISSUE TITLE
Enable slack notifications for DEVREG JIRA project

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1486]
## Which area/kind this issue is related to?

/kind task

## Issue Description

In order to keep up with the tracking of issues under the DEVREG JIRA board as part of the devfile issue tracking process, we need to enable slack notifications for our issue activity in this project, this can be done under devfile github alerts slack channel for devfile issue/PR tracking.

## Acceptance Criteria

- [ ] Investigate what level of information we should post to the devfile github alerts channel
- [ ] Send new issue information to the devfile github alerts channel
- [ ] Send new issue information to the devfile github alerts channel

**Comment by Jdubrick** [comment]
Look into using a JIRA bot and if that is not possible we can use the same logic the has waiting bot is using
