### ISSUE TITLE
WildFly v2.0.1 stack sample fails to build and deploy

### ISSUE THREAD

**Issue by olexii4** [devfile/api#1493]
## Which area this feature is related to?

/kind bug

### Which area this bug is related to?

/area registry

### Web browser

**Operating System and version:**
macOS Sonoma 14.4
**Browser name and version:**
Google Chrome  v122.0.6261.129
## Bug Summary

**Describe the bug:**

Create a new workspace from [java-wildfly 2.0.1 stack](https://registry.devfile.io/devfiles/java-wildfly/2.0.1) with [Che](https://workspaces.openshift.com/).  A workspace is created successfully, but some commands don’t work
(`Containerfile` and `.charts/helm.yaml` couldn’t be found).

**To Reproduce:**
Opening the URL ```https://workspaces.openshift.com#https://raw.githubusercontent.com/devfile/registry/main/stacks/java-wildfly/2.0.1/devfile.yaml``` in your browser should start a workspace. Build and deploy commands run unsuccessfully. 

## Expected behavior

Opening the URL ```https://workspaces.openshift.com#https://raw.githubusercontent.com/devfile/registry/main/stacks/java-wildfly/2.0.1/devfile.yaml``` in your browser should start a workspace where all exec commands run successfully.

**Comment by thepetk** [comment]
@olexii4 FYI the https://github.com/devfile/registry/pull/368 was opened by @ehsavoie in order to fix the container file issue.

**Comment by thepetk** [comment]
A question is if the `devfile.yaml` is accessible inside the workspace, so for example someone can change the variables inside the devfile

**Comment by ehsavoie** [comment]
I added the devfile in the starter project
