### ISSUE TITLE
Define version management of K8S API versions and schema versions 

### ISSUE THREAD

**Issue by davidfestal** [devfile/api#150]
**Is your feature request related to a problem? Please describe.**

We should define:
- how we manage K8S API versions and JSON schema versions. How they are related together.
- how we update them,
- how that relates to release eng..., GH tagging (for GO module / package imports)

**Comment by elsony** [comment]
Designs on the K8s API versions and JSON schema versions can be found in https://docs.google.com/presentation/d/1ohM1HzPB59a3ajvB7rVWJkKONLBAuT0mb5P20_A6vLs/edit#slide=id.g9cf6e5096d_0_8

**Comment by johnmcollier** [comment]
Proposal up for review at https://github.com/devfile/api/pull/278

I've also created an example `make-release.sh` script and GitHub actions to perform a release on my repository:
- https://raw.githubusercontent.com/johnmcollier/api/master/make-release.sh
- https://github.com/johnmcollier/api/blob/master/.github/workflows/release-schema.yaml
