### ISSUE TITLE
Registry support integration test suite build and push image does not load podman alias

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1502]
## Which area this feature is related to?

/kind bug

### Which area this bug is related to?

/area registry

## Bug Summary

**Describe the bug:**

When using `bash docker-build.sh` and `bash docker-push.sh` under [registry-support](https://github.com/devfile/registry-support), the script does not load the `alias docker=podman` as when `bash build_registry.sh` is used: https://github.com/devfile/registry-support/blob/f66264f22310c3c93bf0c77db5f4cd4b560aba5e/build_registry.sh#L28

**To Reproduce:** 

1. Change into `tests/integration` by running `cd tests/integration`
2. Run `bash docker-build.sh` or `bash docker-push.sh` (if local image is already built) while having set `export USE_PODMAN=true` under your shell .rc file.

## Expected behavior

While having set `export USE_PODMAN=true` under your shell .rc file, all `docker` commands should be referencing `podman` commands instead, running `podman` instead of `docker` for the container engine.

## Any logs, error output, screenshots etc? Provide the devfile that sees this bug, if applicable

`docker-build.sh` failure:
```
docker-build.sh: line 24: docker: command not found
```

`docker-push.sh` failure:
```
docker-push.sh: line 22: docker: command not found
```

## Additional context

**Related Issues**

- #1503 
- #1426 

### Any workaround?

Manually changing all usages of `docker` under `tests/integration/docker-build.sh` and `tests/integration/docker-push.sh` while running locally with `podman`.

### Suggestion on how to fix the bug

**Either** of the following fixes will resolve this bug:

- The inclusion of [build_registry.sh#L21](https://github.com/devfile/registry-support/blob/f66264f22310c3c93bf0c77db5f4cd4b560aba5e/build_registry.sh#L21) and [build_registry.sh#L28](https://github.com/devfile/registry-support/blob/f66264f22310c3c93bf0c77db5f4cd4b560aba5e/build_registry.sh#L28) in `tests/integration/docker-build.sh` and `tests/integration/docker-push.sh` to support running the scripts with `podman`

**or**

- Addition of `podman` specific scripts `tests/integration/podman-build.sh` and `tests/integration/podman-push.sh`

**Comment by Jdubrick** [comment]
Unsure if this should be labelled `good first issue` since it is critical and blocking devs from running integration tests with Podman.
