### ISSUE TITLE
[Spike] Investigate registry support scripts to identify missing podman support

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1503]
## Which area/kind this issue is related to?

/area registry

## Issue Description

Currently there are issues #1426 and #1502 open that identified missing/broken `podman` support for a few [registry-support](https://github.com/devfile/registry-support) scripts. There should be an investigation done on the scripts under this repository to identify which scripts that perform container engine operations (with `docker`) do not have proper `podman` support, such missing the inclusion of [build_registry.sh#L21](https://github.com/devfile/registry-support/blob/f66264f22310c3c93bf0c77db5f4cd4b560aba5e/build_registry.sh#L21) and [build_registry.sh#L28](https://github.com/devfile/registry-support/blob/f66264f22310c3c93bf0c77db5f4cd4b560aba5e/build_registry.sh#L28) at the beginning of the scripts.

## Acceptance Criteria

- [x] Identify all scripts that perform container engine operations (with `docker`) which are missing/have broken `podman` support under [registry-support](https://github.com/devfile/registry-support)
- [x] For each identified script, create a bug report to fix the missing/broken `podman` support
    - See #1426 and #1502 for examples

**Comment by Jdubrick** [comment]
Here is a summary of my investigation and changes made:

## No-changes
The scripts contained under `/build-tools` utilize the `docker` container engine, however, these are used in various CI pipelines as they are all running with `docker`. A user does not need to run these scripts to perform local development. As a result of their use-case, I am opting to leave these unavailable to the `podman` engine as it would require extensive changes across multiple repositories to adopt this change without breaking CI.

## Changes
With the PR attached to this issue all of the major components that make up the `registry-support` repository will be buildable with both `docker` and `podman` engines. That includes the `/index/server`, `/oci-registry`, and `/registry-library`. Additionally, the scripts in the root of the `registry-support` repo, such as `build_registry.sh`, also support both `docker` and `podman`.

As a result of all these changes a developer should be able to run all of the necessary build scripts for each component of the `registry-support` repo with their choice of `docker` or `podman`.

**Comment by michael-valdron** [comment]
> The scripts contained under `/build-tools` utilize the `docker` container engine, however, these are used in various CI pipelines as they are all running with `docker`. A user does not need to run these scripts to perform local development. As a result of their use-case, I am opting to leave these unavailable to the `podman` engine as it would require extensive changes across multiple repositories to adopt this change without breaking CI.

@Jdubrick  Though I agree that given the current setup and use cases makes the priority of supporting `podman` on these scripts low, I feel there should be a separate issue created for supporting these scripts as it is possible although rare that users directly use these scripts, i.e. debugging, and there might come a day where the pipelines _may_ use `podman` instead of `docker` as the container engine.

Prior for issue could be set as minor and let go rotten if no interest arises in the near future, we could always re-open later.

WDYT?

**Comment by Jdubrick** [comment]
> > The scripts contained under `/build-tools` utilize the `docker` container engine, however, these are used in various CI pipelines as they are all running with `docker`. A user does not need to run these scripts to perform local development. As a result of their use-case, I am opting to leave these unavailable to the `podman` engine as it would require extensive changes across multiple repositories to adopt this change without breaking CI.
> 
> @Jdubrick Though I agree that given the current setup and use cases makes the priority of supporting `podman` on these scripts low, I feel there should be a separate issue created for supporting these scripts as it is possible although rare that users directly use these scripts, i.e. debugging, and there might come a day where the pipelines _may_ use `podman` instead of `docker` as the container engine.
> 
> Prior for issue could be set as minor and let go rotten if no interest arises in the near future, we could always re-open later.
> 
> WDYT?

Yeah that sounds like a good idea, you are right about future-proofing it incase we can only use `podman` moving forward.

**Comment by Jdubrick** [comment]
Issue opened as a result of this spike for `/build-tools` scripts: https://github.com/devfile/api/issues/1531
