### ISSUE TITLE
Update the content of the community page in devfile.io

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1515]
## Which area/kind this issue is related to?

/area landing-page

## Issue Description

The community page content seems outdated regarding the devfile community call: https://devfile.io/docs/2.2.2/community

As the frequency and the format of the meeting has changed, it would be nice to reflect those changes on the devfile.io side too.

## Acceptance Criteria

- [x] The https://devfile.io/docs/2.2.2/community page is up-to-date with the current format of the devfiles community call
- [x] Update the [Community call agenda](https://docs.google.com/document/d/1T2tGJF8TBplMcjXdm9y-d2AFqZE3eFnymGmXRoD04k8/edit) to reflect the current schedule changes to the call

**Comment by michael-valdron** [comment]
Should also update the devfile/registry `GOVERNANCE.md`: https://github.com/devfile/api/blob/e37cd6b0b4ac21524a724e68373746393b91b9ed/GOVERNANCE.md?plain=1#L56

Maybe point to the community page instead.

**Comment by michael-valdron** [comment]
PRs https://github.com/devfile/devfile-web/pull/127 and https://github.com/devfile/api/pull/1596 to update community page and devfile governance document are ready for review.

> Update the [Community call agenda](https://docs.google.com/document/d/1T2tGJF8TBplMcjXdm9y-d2AFqZE3eFnymGmXRoD04k8/edit) to reflect the current schedule changes to the call

[Community call agenda](https://docs.google.com/document/d/1T2tGJF8TBplMcjXdm9y-d2AFqZE3eFnymGmXRoD04k8/edit) has been updated :heavy_check_mark:

**Comment by michael-valdron** [comment]
All tasks are completed to close this issue.
