### ISSUE TITLE
Alter Current Registry Operator Release Branch Name

### ISSUE THREAD

**Issue by Jdubrick** [devfile/api#1517]
## Which area/kind this issue is related to?

/area registry

## Issue Description
With the changes coming to the registry operator release process, we need to decide on whether to leave the current release branch, `release-v0`, named as such. Since we are moving to having a release branch for every release, such as `v0.1.0` we either need to rename `release-v0` to the latest release it contains, or leave it and start the naming convention at the next release.

Incoming changes to release process: https://github.com/devfile/api/issues/1516

## Acceptance Criteria

- [ ] Decide on what to do with `release-v0` branch
- [ ] Rename `release-v0` OR close issue if applying new naming convention on next release

**Comment by michael-valdron** [comment]
Already been completed.
