### ISSUE TITLE
Older issues are not following issue lifecycle

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1529]
## Which area this feature is related to?

/kind bug

### Which area this bug is related to?

/area ci

## Bug Summary

**Describe the bug:**

A large portion of our older issues are not following the issue lifecycle via the [automation](https://github.com/devfile/api/blob/b7100849159375a14e1960037cca21c001a75bdb/.github/workflows/stale.yaml), i.e. label `lifecycle/stale` after 90 days then label `lifecycle/rotten` and close after an additional 60 days under `lifecycle/stale`.

**To Reproduce:**

Though this cannot be reproduced manually, it can be observed with older issues that have not recieved updates in +90 days, for example #913.

## Expected behavior

All issue should receive label `lifecycle/stale` after 90 days then label `lifecycle/rotten` and close as _not planned_ after an additional 60 days under `lifecycle/stale`.

## Any logs, error output, screenshots etc? Provide the devfile that sees this bug, if applicable

View example #913, last updated **Nov 28, 2023** which is long enough to make it stale as of writing, however, it is not labelled `lifecycle/stale` as expected.

### Any workaround?

Manually close all issues with a recent update long enough that it should be labelled `lifecycle/rotten` as _not planned_ with a post stating that the issue is rotten and can be re-opened if there is still interest (also recommending manual addition of `lifecycle/rotten` label as well). 

Caveat with doing this is that this won't cover all issues effected by this bug, issues that are still in the stale portion of the lifecycle (without the label) or recently updated could still be effected and will linger in the backlog. It is estimated that all issues older than the implementation of the [automation](https://github.com/devfile/api/blob/b7100849159375a14e1960037cca21c001a75bdb/.github/workflows/stale.yaml) handling this are effected.

### Suggestion on how to fix the bug

None found yet.

See #1528.

**Comment by michael-valdron** [comment]
Blocked by investigation task #1528.

**Comment by johnmcollier** [comment]
Waiting on resolution of https://github.com/devfile/api/issues/1528
