### ISSUE TITLE
Java Quarkus Devfile doesn't run in dev mode due to installed Maven being too old

### ISSUE THREAD

**Issue by datho7561** [devfile/api#1541]
## Which area this feature is related to?

/kind bug

### Which area this bug is related to?

> /area ci
> /area api
> /area library
/area registry
> /area alizer
> /area devworkspace
> /area integration-tests
> /area test-automation
> /area releng
> /area landing-page

### Go project

**Operating System and version:**

**Go Pkg Version:**

### Node.js project

**Operating System and version:**

**Node.js version:**

**Yarn version:**

**Project.json:**

### Web browser

**Operating System and version:**

**Browser name and version:**

## Bug Summary

**Describe the bug:**

**To Reproduce:**

1. Create a project using `odo` and the Quarkus Devfile
2. You will need a k8s cluster or podman installed for the next step. I used a kind cluster
3. Try to run the project using `odo dev`
4. It should mention a warning regarding port forwarding
5. Open the logs (`odo logs --follow`) and see that there is a compilation error related to Maven being too old

## Expected behavior

Devfile runs the Quarkus project

## Additional context

I discovered this bug in VS Code OpenShifot, but VS Code OpenShift just calls `odo` (v3).

### Any workaround?

Modify the Devfile to use the maven wrapper included in the project files.

eg. `mvn` ==> `./mvnw`

### Suggestion on how to fix the bug

Perform the substitution from `mvn` to `./mvnw` in the Devfile being served in the Devfile Registry.

**Comment by Jdubrick** [comment]
PR opened here that will close the issue: https://github.com/devfile/registry/pull/399
