### ISSUE TITLE
Devfile Library should be updated to support Go 1.21

### ISSUE THREAD

**Issue by johnmcollier** [devfile/api#1543]
/kind bug
/area library

Trying to consume the devfile library with Go 1.21 reports the following errors:
```
github.com/devfile/library/v2/pkg/devfile/generator
/home/admin/go1.21/gopath/pkg/mod/github.com/devfile/library/v2@v2.2.1-0.20230418160146-e75481b7eebd/pkg/devfile/generator/utils.go:600:14: cannot use corev1.ResourceRequirements{…} (value of type "k8s.io/api/core/v1".ResourceRequirements) as "k8s.io/api/core/v1".VolumeResourceRequirements value in struct literal
```

It seems that some of its dependencies need to be updated to a version that supports Go 1.21. We should also ensure that there's nothing else in the library that's blocking it from working on 1.21.

**Comment by michael-valdron** [comment]
I did an investigation into this, it appears to be a k8s API change in v1.29 and is breaking [pkg/devfile/generator/utils.go#L600](https://github.com/devfile/library/blob/090339307b56bf381092bdafdf2c764c180c6570/pkg/devfile/generator/utils.go#L600) in devfile/library rather than it being the Go version:

[**Kubernetes 1.28**](https://pkg.go.dev/k8s.io/kubernetes@v1.28.0/pkg/apis/core#ResourceRequirements)
```go
type PersistentVolumeClaimSpec struct {
...
	// Resources represents the minimum resources required
	// If RecoverVolumeExpansionFailure feature is enabled users are allowed to specify resource requirements
	// that are lower than previous value but must still be higher than capacity recorded in the
	// status field of the claim.
	// +optional
	Resources ResourceRequirements
...
}
```

[**Kubernetes 1.29**](https://pkg.go.dev/k8s.io/kubernetes@v1.29.3/pkg/apis/core#VolumeResourceRequirements)
```go
type PersistentVolumeClaimSpec struct {
...
	// Resources represents the minimum resources required
	// If RecoverVolumeExpansionFailure feature is enabled users are allowed to specify resource requirements
	// that are lower than previous value but must still be higher than capacity recorded in the
	// status field of the claim.
	// +optional
	Resources VolumeResourceRequirements
...
}
```

For this issue we'll need to do two changes:
1. Support k8s version 1.29 by bumping the version in our modules (might be an epic)
2. As part of bumping the version for devfile/library we'll need to refactor these breaking changes

With that if a consumer wants to continue using our modules until this is done they should be advised not to upgrade past the v1.28 k8s APIs to avoid breaking changes.

**Comment by michael-valdron** [comment]
> I did an investigation into this, it appears to be a k8s API change in v1.29 and is breaking [pkg/devfile/generator/utils.go#L600](https://github.com/devfile/library/blob/090339307b56bf381092bdafdf2c764c180c6570/pkg/devfile/generator/utils.go#L600) in devfile/library rather than it being the Go version:
> 
> [**Kubernetes 1.28**](https://pkg.go.dev/k8s.io/kubernetes@v1.28.0/pkg/apis/core#ResourceRequirements)
> 
> ```go
> type PersistentVolumeClaimSpec struct {
> ...
> 	// Resources represents the minimum resources required
> 	// If RecoverVolumeExpansionFailure feature is enabled users are allowed to specify resource requirements
> 	// that are lower than previous value but must still be higher than capacity recorded in the
> 	// status field of the claim.
> 	// +optional
> 	Resources ResourceRequirements
> ...
> }
> ```
> 
> [**Kubernetes 1.29**](https://pkg.go.dev/k8s.io/kubernetes@v1.29.3/pkg/apis/core#VolumeResourceRequirements)
> 
> ```go
> type PersistentVolumeClaimSpec struct {
> ...
> 	// Resources represents the minimum resources required
> 	// If RecoverVolumeExpansionFailure feature is enabled users are allowed to specify resource requirements
> 	// that are lower than previous value but must still be higher than capacity recorded in the
> 	// status field of the claim.
> 	// +optional
> 	Resources VolumeResourceRequirements
> ...
> }
> ```
> 
> For this issue we'll need to do two changes:
> 
>     1. Support k8s version 1.29 by bumping the version in our modules (might be an epic)
> 
>     2. As part of bumping the version for devfile/library we'll need to refactor these breaking changes
> 
> 
> With that if a consumer wants to continue using our modules until this is done they should be advised not to upgrade past the v1.28 k8s APIs to avoid breaking changes.

**\*\*Update\*\*** `k8s.io/api` v0.29.x (for Kubernetes 1.29) does require Go 1.21: https://github.com/kubernetes/api/blob/d47313059888ec984bf8432ed155fae5be935c31/go.mod#L5C1-L5C8

With that we'll need the the additional epic of updating to Go 1.21 before moving to Kubernetes 1.29, we could consider merging them into one epic as it could be one of the changes to a Go 1.21 update.

These changes would be towards a new version of the devfile schema.

cc @devfile/devfile-services-team

**Comment by michael-valdron** [comment]
Created epic issue #1555 to track all Go 1.21 and Kubernetes 1.29 upgrades.

**Comment by michael-valdron** [comment]
Blocked by #1556

**Comment by yangcao77** [comment]
FYI. https://github.com/devfile/api/issues/1593 also need to be done after pulling in latest devfile/api

**Comment by thepetk** [comment]
I think here we should create also a new release for library. Should it be `2.3.0`?

cc @johnmcollier @michael-valdron @yangcao77

**Comment by maysunfaisal** [comment]
@thepetk I think yes, it should be 2.3.0 in devfile/library after https://github.com/devfile/api/issues/1593

**Comment by thepetk** [comment]
> @thepetk I think yes, it should be 2.3.0 in devfile/library after #1593

Does it make sense to update the scope of https://github.com/devfile/api/issues/1593?
