### ISSUE TITLE
Update stack authors guide with the latest spec

### ISSUE THREAD

**Issue by elsony** [devfile/api#158]
The stack author's guide (https://devfile.github.io/devfile/assembly_making-a-workspace-portable-using-a-devfile.html and the linking partial pages) was created a while ago. New fields has been added and some of the samples and descriptions needs to be updated due to the updating of the spec since it was last created.

**Comment by jc-berger** [comment]
@elsony, I look forward to working on this issue. I've gone through the devfile docs and guide for stack authors that you included, and I know I must update the samples, specifications, and descriptions. How would I know all the information and content that needs to be updated?

**Comment by elsony** [comment]
@jc-berger The main thing that we need to do is to go through those documents and make sure the content covers and matches the specification under the schema doc https://docs.devfile.io/devfile/api-reference.html. Unfortunately, the original stack author's guide was created a couple months back and things get out of sync. The easiest way is probably for us to get together and I can pick one section of the doc and show you an example on how to do it. The schema doc already have some info documented in there and I can fill you in the rest if you have further questions.

**Comment by jc-berger** [comment]
@elsony, thank you. Yes, I think meeting will be the most efficient way, thanks for being willing to meet. I'll schedule something for us today, and feel free to counter to a different time. Talk soon!

**Comment by jc-berger** [comment]
@elsony, after talking to the doc team, we've decided it would be best if I made a separate PR for each doc that's getting modified, according to the schema. The goal is to make the review of each doc easier. 

Letting you know for your awareness and anyone else working on this issue. Thanks!

**Comment by jc-berger** [comment]
@elsony, for your awareness, I've linked 4 PRs to this issue (PRs #18-21). Each PR is for one doc that I've edited. One doc per PR hopefully makes the review easier.  Not all the assemblies linked to the guide needed updating. Hence, not every doc referenced in the guide needed a PR. 

Please let me know who will be doing the technical review of the PRs, and I shall be happy to work with him or her. 

Thanks for all the help you've been on this!

**Comment by elsony** [comment]
@jc-berger With the 4 PRs merged, is there any outstanding work that you are still planning for this item, i.e. is this item ready to be closed?

**Comment by jc-berger** [comment]
@elsony, this issue can be closed. thank you for the follow up!
