### ISSUE TITLE
[Spike] Investigate alternative logger for Alizer

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1581]
## Which area is this issue related to?

/area alizer

## Issue Description

Alizer is currently using `zap` as [logger](https://github.com/devfile/alizer/blob/main/pkg/utils/logger.go#L8). As this package adds the extra dependency of [controller-runtime](https://github.com/devfile/alizer/blob/main/go.mod#L19), it might be good to investigate any alternatives that we could use for logging purposes. Mostly because the `controller-runtime` is being used by the consumers of alizer and we might face potential conflicts when updating this dependency.

## Acceptance Criteria

- [ ] Investigation reports have been shared here and any required issues have been created.

**Comment by Jdubrick** [comment]
PR linked above closes this issue
