### ISSUE TITLE
Create an overview section in doc

### ISSUE THREAD

**Issue by elsony** [devfile/api#159]
On the front page of the web page, we should have an overview session to describe the basics of devfile, e.g. what a devfile is.  This will be the first piece of information that the user can read when they are interested to find out what a devfile is. We can move some of the background information from the stack author guide (https://devfile.github.io/devfile/assembly_making-a-workspace-portable-using-a-devfile.html) to that overview section.

**Comment by jc-berger** [comment]
Closing as the PR addressing these concerns have been merged.
