### ISSUE TITLE
support devfile 2.3.0 in devfile library

### ISSUE THREAD

**Issue by yangcao77** [devfile/api#1593]
## Which area is this issue related to?

/area library

## Issue Description

after https://github.com/devfile/api/pull/1571 has merged, devfile v2.3.0 has been released. 
devfile library should pull in the latest change and start supporting devfile 2.3.0

**Comment by yangcao77** [comment]
blocker of https://github.com/devfile/api/issues/1543

**Comment by michael-valdron** [comment]
Matching size of previous issue https://github.com/devfile/api/issues/1454 to move into sprint.

**Comment by michael-valdron** [comment]
Setting priority to **critical** to provide latest devfile 2.3.0 release support in library. Will update to **blocker** if anyone requests the support for development.

**Comment by michael-valdron** [comment]
> Matching size of previous issue #1454 to move into sprint.

Updating size to 1 due to work completion within a day.

**Comment by michael-valdron** [comment]
PR is ready for review: https://github.com/devfile/library/pull/219
