### ISSUE TITLE
Update migration guide with the latest spec 

### ISSUE THREAD

**Issue by elsony** [devfile/api#160]
The migration guide (https://devfile.github.io/devfile/migration_guide.html) was created a while ago. The guide needs to be updated to reflect the latest spec.

**Comment by boczkowska** [comment]
Hi @elsony! I'd like to pick this one up.

I've looked through the [2.0 milestone](https://github.com/devfile/api/milestone/1?closed=1) issues on GH.
The following changes do not seem to be mentioned in the Migration Guide:

1. [Find a better naming for chePlugin spec reference](https://github.com/devfile/api/issues/13)
2. [Rename command group type](https://github.com/devfile/api/issues/59)
3. [configuration option to avoid unncessary restarts of process](https://github.com/devfile/api/issues/64)
4. [default values on JSON schema](https://github.com/devfile/api/issues/74)
5. [mountsources default value for containers](https://github.com/devfile/api/issues/75)
6. [Manage merge keys of top-level lists in a more consistent way](https://github.com/devfile/api/issues/102)
7. [Support multiple remotes for projects to support forking workflow](https://github.com/devfile/api/issues/104)
8. [Exec command should make component required](https://github.com/devfile/api/issues/152)

Could you help me to identify those that need to go into the guide? I'll distil the descriptions from the issues/PRs, just need some help to figure out what's relevant from the docs perspective.

Also, are there any other places other than [the epic](https://github.com/devfile/api/issues/15) and [the milestone](https://github.com/devfile/api/milestone/1?closed=1) in GH where I can track the changes?

**Comment by rkratky** [comment]
Fixed by https://github.com/devfile/docs/pull/22
