### ISSUE TITLE
Copy odo-devfile starter projects to devfile-samples org

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1604]
## Which area is this issue related to?

/area registry

## Issue Description

The devfile registry is currently using starter projects from the https://github.com/odo-devfiles/ org. As this organization is not active enough at the moment, we should move all repos mentioned inside the devfile registry stacks to the https://github.com/devfile-samples/ org.

## Acceptance Criteria

- [x] Copy https://github.com/odo-devfiles/springboot-ex to devfile-samples org.
- [ ] Check if the nodeshift starter sample repository can be resued instead going forward, if not copy https://github.com/odo-devfiles/nodejs-ex to devfile-samples org.
- [ ] Update all references inside the devfile registry:
     - https://github.com/devfile/registry/blob/main/stacks/java-maven/1.2.0/devfile.yaml#L17
     - https://github.com/devfile/registry/blob/main/stacks/java-maven/1.3.0/devfile.yaml#L17
     - https://github.com/devfile/registry/blob/main/stacks/java-maven/1.3.1/devfile.yaml#L17
     - https://github.com/devfile/registry/blob/main/stacks/java-springboot/1.2.0/devfile.yaml#L18
     - https://github.com/devfile/registry/blob/main/stacks/java-springboot/1.3.0/devfile.yaml#L18
     - https://github.com/devfile/registry/blob/main/stacks/java-springboot/1.4.0/devfile.yaml#L18
     - https://github.com/devfile/registry/blob/main/stacks/java-springboot/2.0.0/devfile.yaml#L18
     - https://github.com/devfile/registry/blob/main/stacks/java-springboot/2.1.0/devfile.yaml#L18
     - https://github.com/devfile/registry/blob/main/stacks/java-springboot/2.2.0/devfile.yaml#L18
     - https://github.com/devfile/registry/blob/main/stacks/nodejs/2.1.1/devfile.yaml#L19
     - https://github.com/devfile/registry/blob/main/stacks/nodejs/2.2.0/devfile.yaml#L18
     - https://github.com/devfile/registry/blob/main/stacks/nodejs/2.2.1/devfile.yaml#L18

**Comment by ibuziuk** [comment]
Unrelated to odo, but I believe it would be nice to move  https://github.com/che-incubator/quarkus-api-example  to the devfile-samples as well. This is the devfile we use heavily for demos / e2e periodic tests and promote on the website - https://eclipse.dev/che/#StartNow

**Comment by maysunfaisal** [comment]
We want to make a new copy of these starter projects rather as current devfiles will have a reference to these starter projects and we dont want them to be broken
