### ISSUE TITLE
Publish `0.3.0` release for registry-operator

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1605]
## Which area is this issue related to?

/area registry

## Issue Description

After the merge of https://github.com/devfile/registry-operator/commit/94bde0908378e7013600087400d5feda4b67c171 we should publish a new release of the `registry-operator` as the repo now supports `go 1.21` instead of `go 1.19` and other dependencies (e.g `k8s.io/api` or `controller-runtime`) have been bumped up too.

## Acceptance Criteria

- [ ] Registry operator new release is published.

**Comment by thepetk** [comment]
The registry operator release process: https://docs.google.com/document/d/1olp6CwhHUMqGmaXXMLRn3z_S34Da4mdkLfm3k8DH-SM/edit?pli=1#heading=h.kayms0mswg2b

**Comment by thepetk** [comment]
Opened PR https://github.com/devfile/registry-operator/pull/95 to prepare the `registry-operator` repo for the 0.3.0 release.

**Comment by thepetk** [comment]
Currently blocked by https://github.com/devfile/api/issues/1620

**Comment by Jdubrick** [comment]
https://github.com/devfile/api/issues/1620 is now completed, this issue should be unblocked!
