### ISSUE TITLE
Update lastModified For Stacks/Samples Without Versions

### ISSUE THREAD

**Issue by Jdubrick** [devfile/api#1607]
## Which area is this issue related to?

/area registry

## Issue Description
After completion of https://github.com/devfile/api/issues/1327 investigation will need to be done for handling stacks or samples that do not have a version attached to them. This implementation will most likely need to be on the [`index/generator`](https://github.com/devfile/registry-support/blob/main/index/generator/library/library.go) side and may require fetching the date from a remote location. In addition to the investigation of this issue the implementation should also be contained within this issue as it shouldn't be a large fix.

## Acceptance Criteria
- [ ] Stacks or samples without version field no longer display the default `time.Time` value for `lastModified` field.

**Comment by Jdubrick** [comment]
Related issue: https://github.com/devfile/api/issues/1327

**Comment by Jdubrick** [comment]
Started looking into this issue. I noticed when trying to run [`generate_last_mod_file.sh`](https://github.com/devfile/registry/blob/main/.ci/generate_last_mod_file.sh) when there are samples present that don't have versions it will error out as the JSON parsing can't find the `versions` key. For reference about samples that don't have versions I was using the ones from [`registry-support tests`](https://github.com/devfile/registry-support/blob/main/tests/registry/extraDevfileEntries.yaml#L49-#L58) and also noticed there is no `revision`. 

This got me thinking about how we want to go about this, since for some of these yaml fields it isn't necessary we would need to have support for building all different combinations. I know our community registry will all have `versions` and `revision` but for others hosting their own registries do we want to accommodate every combination or have it up to their discretion to alter it?

wdyt @michael-valdron @thepetk

**Comment by thepetk** [comment]
> Started looking into this issue. I noticed when trying to run [`generate_last_mod_file.sh`](https://github.com/devfile/registry/blob/main/.ci/generate_last_mod_file.sh) when there are samples present that don't have versions it will error out as the JSON parsing can't find the `versions` key. For reference about samples that don't have versions I was using the ones from [`registry-support tests`](https://github.com/devfile/registry-support/blob/main/tests/registry/extraDevfileEntries.yaml#L49-#L58) and also noticed there is no `revision`.
> 
> This got me thinking about how we want to go about this, since for some of these yaml fields it isn't necessary we would need to have support for building all different combinations. I know our community registry will all have `versions` and `revision` but for others hosting their own registries do we want to accommodate every combination or have it up to their discretion to alter it?
> 
> wdyt @michael-valdron @thepetk

With our current format I think is necessary to support all combinations. The `registry-support` tests should also make sure of this (so we should have sufficient test cases). TBH I don't have a strong opinion if we should make a convention that the last modified field should be used only for versioned stacks/samples, although in that case we should make sure that our documentation makes it clear.

Slightly different scope, but your point makes me think of registry versioning. Meaning, if we had a versioning for the registry repo and a proper release process, for issues like that we could just create a new major version which introduces breaking changes.
