### ISSUE TITLE
Life cycle of devfile registry (start, stop, restart)

### ISSUE THREAD

**Issue by elsony** [devfile/api#162]
## User Story
As a devfile registry admin, I want to start and stop the registry and restart the registry for the changes to take place.

## Acceptance Criteria 
- [ ] It should provide the ability to start and stop a registry
- [ ] It should provide ability to restart the registry in order to pick up changes on the registry
- [ ] Handle gracefully and recover from registry abnormal exit, e.g. pod restart.

## Links 
- Related issue: 
This item is part of the epic #82

**Comment by johnmcollier** [comment]
Design docs for start, stop, and container restart:
https://docs.google.com/document/d/1rQHCp4SWslWWJv5KK3A_iXHvgbqjsuDkSKDD72ifJio/edit?usp=sharing
