### ISSUE TITLE
Bump up `github.com/docker/docker` to `v25.0.6` version.

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1620]
## Which area is this issue related to?

/area library
/area registry
/area test-automation

## Issue Description

The following repos need to be updated and their modules should use `github.com/docker/docker` version `v25.0.6`

#### devfile/library

- [x] `library`: Suggested fix is https://github.com/devfile/library/pull/221
- [x] `library`: Cut a new release for library.

#### devfile/registry

- [x] `tests/odov3`: https://github.com/devfile/registry/pull/461 has been opened to address the issue.
- [x] `tests/validate_devfile_schema`: library [fix](https://github.com/devfile/library/pull/221) needs to be merged first & then we should [bump up its dependency](https://github.com/devfile/registry/blob/main/tests/validate_devfile_schemas/go.mod#L6).
- [x] `tests/odov3` library bumped

#### devfile/registry-support

- [x] `tests/integration`: Suggested fix is https://github.com/devfile/registry-support/pull/251
- [x] `index/generator`: library [fix](https://github.com/devfile/library/pull/221) needs to be merged first & then we should [bump up its dependency](https://github.com/devfile/registry-support/blob/main/index/generator/go.mod#L7)
- [x] `index/server`: library [fix](https://github.com/devfile/library/pull/221) needs to be merged first & then we should [bump up its dependency](https://github.com/devfile/registry-support/blob/main/index/server/go.mod#L8)
- [x] `registry-library`: The `registry-generator` fix needs to be merged first & then we should [bump up its dependency](https://github.com/devfile/registry-support/blob/main/registry-library/go.mod#L7)

### devfile/registry-operator

- [x] Fix is suggested here: https://github.com/devfile/registry-operator/pull/93
- [x] Bump registry-library dependency after it is merged: https://github.com/devfile/registry-operator/blob/main/go.mod#L7

## Acceptance Criteria

- [x] All modules in `library`, `registry`, `registry-support` & `registry-operator` are using `github.com/docker/docker v25.0.6`

**Comment by Jdubrick** [comment]
Since the dependency bump is a critical severity we should be cutting new releases for affected items, I can cut a new library release so we can pull that dependency into most of the action items

**Comment by Jdubrick** [comment]
Added action item to registry-operator to bump up the registry-library hash to pull in the fix as well: https://github.com/devfile/registry-operator/blob/main/go.mod#L7

**Comment by thepetk** [comment]
> Since the dependency bump is a critical severity we should be cutting new releases for affected items, I can cut a new library release so we can pull that dependency into most of the action items

+1 for the new release. Initially I thought only updating the hash but it feels much cleaner. I've updated the criteria to include this action. As you're now the assignee feel free to update them as you see fit <3

**Comment by thepetk** [comment]
blocks https://github.com/devfile/api/issues/1605
