### ISSUE TITLE
Calculate and publish alizer binary sha256 checksums when releasing

### ISSUE THREAD

**Issue by vrubezhny** [devfile/api#1624]
## Which area is this feature related to?

/area alizer

## Which functionality do you think we should add?

Calculate and publish sha256 checksums for the created binaries created and publish them together with the binaries on release 

**Why is this needed? Is your feature request related to a problem?**

Having the sha256 checksums available will allow for dependent projects to provide a more or less safe way of bundling/downloading the alizer binary for the customers.

**Detailed description:**

Sha256 checksums are to be calculated after a binary is created for a supported platform/arch and then added to the release assets together with the created binaries.

**Comment by thepetk** [comment]
@vrubezhny thank you for the issue. I've merged https://github.com/devfile/alizer/pull/102 and released alizer [v1.6.2](https://github.com/devfile/alizer/releases/tag/v1.6.2) which contains the checksums of the binaries too. Feel free to re-open the issue in case you think is not resolved.

**Comment by vrubezhny** [comment]
@thepetk Thank you for fixing this!
