### ISSUE TITLE
Implement security policy for `devfile/api`

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1629]
## Issue Description

This issue is the implementation of the security policy related to the parent epic https://github.com/devfile/api/issues/1461. The file should be following the results of the investigation done for the policy in the previous issues of this EPIC. A necessary step is to update all available `SECURITY-INSIGHTS.md` files pointing to this doc.

## Acceptance Criteria

- [ ] `SECURITY.md` is created in `devfile/api` and all `SECURITY-INSIGHTS.md` are up-to-date.

**Comment by thepetk** [comment]
Sized based on the actual time spent for this issue.

**Comment by ijunxyz123** [comment]
?

**Comment by thepetk** [comment]
Re opened issue as we still need to update the README files of `alizer`, `library`, `registry`, `registry-support` & `registry-operator`.

I've opened the following:

* https://github.com/devfile/alizer/pull/100/
* https://github.com/devfile/library/pull/226
* https://github.com/devfile/registry/pull/478
* https://github.com/devfile/registry-support/pull/257
* https://github.com/devfile/registry-operator/pull/99
