### ISSUE TITLE
Packaging of devfile registry for deployment

### ISSUE THREAD

**Issue by elsony** [devfile/api#163]
## User Story
As a devfile admin, I want to create a package of the devfile registry that can be hosted for other devfile users to access.

## Acceptance Criteria 
- [ ] It should define how the packaging of the devfile registry looks like
- [ ] It should define the mechanism to deploy in different environment, e.g. cluster vs standalone registry

## Links 
- Related issue: 
This item is part of the epic #82

**Comment by johnmcollier** [comment]
Design doc for the packaging of the devfile registry https://docs.google.com/document/d/1trb4qfqY9fRKzJKhUALMIbiPcSB1MtZOPnaKum08agU/edit?usp=sharing
