### ISSUE TITLE
[Spike] Investigate Console failure when samples are used as starter project

### ISSUE THREAD

**Issue by thepetk** [devfile/api#1633]
## Which area is this issue related to?

/area library
/area registry

## Issue Description

The issue was first reported here: https://github.com/devfile/api/issues/1628. After an investigation it seems that the [update](https://github.com/devfile/registry/commit/25ef0662410b0cea0d3700beb8fe2a94ce116e89) of the `java-springboot` stack to use the `devfile-sample-java-springboot` as its sample, it has an impact on the console and all imports of this sample are failing with the error below:

```
Danger alert:Import is not possible.
Failed to parse devfile: mkdir docker: permission denied
```

This error should be investigated further and see why we're not able to use this sample as starter project. 

## Acceptance Criteria

- [ ] The reason of this failure is now clear and all issues needed to fix it have been created.

**Comment by maysunfaisal** [comment]
We should check why its fine for the other stacks but this particular has an exception

**Comment by thepetk** [comment]
> We should check why its fine for the other stacks but this particular has an exception

The difference between this sample and the others is that the parent stack is using the same repo as starter project. All the parents from the other samples do not have a starter project which is also a sample. That said I'd like to investigate what is different here and why this causes permission issues on the console side. WDYT?

**Comment by thepetk** [comment]
> > We should check why its fine for the other stacks but this particular has an exception
> 
> The difference between this sample and the others is that the parent stack is using the same repo as starter project. All the parents from the other samples do not have a starter project which is also a sample.
> 
> I'd like to see this happening for the other samples. So atm I'm trying to make the other samples fail for the same reason too, in an attempt to make a pattern of the error.

Tried to investigate this case, I was able to reproduce it with an update to the `devfile-sample-python-basic` although it seems to be unrelated to the failure, as the issue is still occuring after the update of the `java-springboot` stack. Therefore I'm closing the issue as not planned.
