### ISSUE TITLE
Setup custom pipelines and SAAS configuration

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1636]
## Which area is this issue related to?

/area ci
/area registry

## Issue Description

To complete the build pipeline process we need to perform some updates to our Konflux `on-push` tekton config and our SAAS configuration.

Refer to this [guide](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/FAQ.md?ref_type=heads#migration-to-konflux).

## Acceptance Criteria

- [x] Add `next` tag under `ADDITIONAL_TAGS`, see [example](https://github.com/michael-valdron/devfile-registry/blob/c3f5ee2ff3383a0fab8126dc42b26f36be95ff7a/.tekton/devfile-registry-push.yaml#L407).
- [x] Verify image is under `redhat-services-prod` _before_ making changes to SAAS.
- [x] Update your service to use the new image. This is usually done by updating an `IMAGE` OpenShift template parameter in a saas file. Add the new image to the `imagePatterns` list as well.
- [x] Update the Continuous Delivery pipeline to wait for an `image` instead of an `upstream` Jenkins job. More information in [saas-file-structure](https://gitlab.cee.redhat.com/service/app-interface/-/blob/master/docs/app-sre/continuous-delivery-in-app-interface.md#saas-file-structure).

**Comment by michael-valdron** [comment]
Waiting on #1649 and #1640 to be resolved once release team has given an approval to merge the needed release data: https://github.com/devfile/api/issues/1649#issuecomment-2515467964

**Comment by michael-valdron** [comment]
Onboarding has been unblocked and blocking release issues (#1649 & #1640) has been resolved: https://github.com/devfile/api/issues/1649#issuecomment-2539358701

**Comment by michael-valdron** [comment]
@Jdubrick Should be able to resume this issue.

**Comment by Jdubrick** [comment]
After setting everything up for the registry we realized the viewer needs the same process. @michael-valdron opened https://github.com/devfile/api/issues/1657 to handle this and onboard the viewer to Konflux.
