### ISSUE TITLE
Build tools for generating registry based on registry/catalog info on a github repo

### ISSUE THREAD

**Issue by elsony** [devfile/api#164]
## User Story
As a devfile admin, I want to generate a devfile registry based on the content in a registry catalog repo that defines all the available stacks to be added to the registry.

## Acceptance Criteria 
- [ ] It should read the content of a given registry catalog repo to gather all the info on the list of stacks to be include in the registry
- [ ] It should build a devfile registry packaged in the form as described in #163

## Links 
- Related issue: 
https://github.com/devfile/api/issues/163
This item is part of the epic #82

**Comment by johnmcollier** [comment]
I've put a PR up (https://github.com/devfile/registry/pull/1) for review that implements the following:
1) Build scripts and docker file for producing a Devfile index docker container, as outlined in https://github.com/devfile/api/issues/163
2) GitHub workflow actions for running the build on PRs and publishing new images to Quay.io
