### ISSUE TITLE
Create Konflux ReleasePlan for devfile registry

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#1640]
## Which area is this issue related to?

/area ci
/area registry

## Issue Description

As part of onboarding to using Konflux for building image, we'll need a `ReleasePlan` to setup the production environment container images.

Refer to this [guide](https://konflux.pages.redhat.com/docs/users/releasing/releasing-to-app-int-services.html#_create_a_releaseplan).

## Acceptance Criteria

- [x] Create `ReleasePlan` for production community registry images

**Comment by maysunfaisal** [comment]
we can take a look at what was done for the HAS strategy, we may have to look at commit history

**Comment by michael-valdron** [comment]
Item is in review, see https://github.com/devfile/api/issues/1649#issuecomment-2515467964.

**Comment by michael-valdron** [comment]
Status update: https://github.com/devfile/api/issues/1649#issuecomment-2518818763

**Comment by michael-valdron** [comment]
Status update: https://github.com/devfile/api/issues/1649#issuecomment-2520851337

**Comment by michael-valdron** [comment]
Releases are working as expected now, closing this issue as completed: https://github.com/devfile/api/issues/1649#issuecomment-2539358701
