### ISSUE TITLE
Add `attributes` free-form map field for tool-specific fields in a number of places 

### ISSUE THREAD

**Issue by davidfestal** [devfile/api#169]
**Is your feature request related to a problem? Please describe.**

How to support tool-specific fields in a number of places in Devfile 2.0 ?

**Describe the solution you'd like**

During the Devfile 2.0 early discussions, we had agreed that there should be an `attribute` free-form string map at a number of places in the top-level elements (commands, components, projects), to allow tools to provide tool-specific information.
This would be done the same as what already exists for `Endpoint`s
This would be good to have that before the 2.0.0 release.

**Comment by elsony** [comment]
I'd say yes for StarterProject as well. I don't see any reason for excluding StarterProject.

**Comment by elsony** [comment]
Based on the discussion, we are moving this to 2.1 to discuss together with how we associate commands to projects in a single devfile.

**Comment by elsony** [comment]
Can this be closed now given that PR #214 has been merged?

**Comment by davidfestal** [comment]
Yes, it can be closed

**Comment by elsony** [comment]
Closing this as per the last comment
