### ISSUE TITLE
Support `selector` and `entrypoints` in the `kubernetes` component

### ISSUE THREAD

**Issue by davidfestal** [devfile/api#171]
**Is your feature request related to a problem? Please describe.**

In the Devfile 1.0, there is a way to:
- select the components that we want to import from the `kubernetes` component manifest: `selector` field => https://www.eclipse.org/che/docs/che-7/end-user-guide/making-a-workspace-portable-using-a-devfile/#_component_type_kubernetes
- override the entrypoints of involved containers: `entrypoints` => https://www.eclipse.org/che/docs/che-7/end-user-guide/making-a-workspace-portable-using-a-devfile/#_overriding_container_entrypoints

**Describe the solution you'd like**

We'd need to add this to the Devfile 2.0 before the 2.0.0 release if we want to have feature parity with devfile 1.0 Che-wise 

Note that this are completely new attributes, so this would not break compatibility rules.

**Comment by kadel** [comment]
> * select the components that we want to import from the `kubernetes` component manifest: `selector` field => https://www.eclipse.org/che/docs/che-7/end-user-guide/making-a-workspace-portable-using-a-devfile/#_component_type_kubernetes

I'm starting to get a little bit worried that we are starting to make Devfile way complicated.

Is this something that the Devfile author could easily solve by splitting the yaml files into multiple files and using just upset of it?

**Comment by elsony** [comment]
There is currently no clear use case for this yet. Therefore, we'll remove this from the 2.1 plan.
