### ISSUE TITLE
The registry index-generator should function when imported as a go module

### ISSUE THREAD

**Issue by johnmcollier** [devfile/api#177]
Currently, the [index-generator](https://github.com/devfile/registry-support/tree/master/index/generator) tool functions as a CLI that can generate the index.json for use in a devfile registry. It's also a go module that can be imported by other tools written in Golang.

However, [the index generator functionality](https://github.com/devfile/registry-support/blob/master/index/generator/cmd/root.go#L107) is behind a non-exported function in the `cmd` package, that can't be imported into other tools. Which means that code that imports the index-generator library, is unable to generate the index.json without calling the CLI directly. 

We need to make sure that code that pulls down the index-generator library is able to call `generateIndex`.
- [x] Export the `generateIndex` function
- [x] Move `generateIndex` and any associated functions into their own package, separate from the CLI code

CC @GeekArthur

**Comment by johnmcollier** [comment]
One other change I might suggest is having `GenerateIndex` return the index.json struct, rather than writing it directly to disk.

**Comment by GeekArthur** [comment]
@johnmcollier Currently my PR refactors the index generator library and separate the functionalities of generating index strut and creating index file. Let me know if you need more features/requirements to support the registry go module.
