### ISSUE TITLE
Review Migration Guide for language and consistency

### ISSUE THREAD

**Issue by rkratky** [devfile/api#182]
**Is your feature request related to a problem? Please describe.**

The Migration Guide (https://devfile.github.io/devfile/migration_guide.html) needs to be reviewed and updated to follow Red Hat documentation and style guide principles.

**Describe the solution you'd like**

The content is consistent with language and style principles used by upstream Red Hat documentation projects.

**Comment by rkratky** [comment]
@boczkowska, I'd say at least some of this has already been completed in https://github.com/devfile/docs/pull/22, right? Could you please check if more is needed?

**Comment by boczkowska** [comment]
@rkratky sure, I'll pick it up

**Comment by jc-berger** [comment]
This issue can be closed as I've done a language review of [migrating-to-devfile-v2](https://docs.devfile.io/devfile/user-guide/migrating-to-devfile-v2.html) and it looks good, and the PR's been merged.

**Comment by rkratky** [comment]
The content does not follow our style guide and still needs to be worked on. @jc-berger, which PR are you referring to?

**Comment by jc-berger** [comment]
@rkratky, looking at PR #22: https://github.com/devfile/docs/pull/22

**Comment by rkratky** [comment]
@jc-berger, yes, I know about PR #22 -- that's why I commented above: _"I'd say at least some of this has already been completed in devfile/docs#22, right? Could you please check if more is needed?"_

A quick glance reveals that more work indeed is needed in https://docs.devfile.io/devfile/user-guide/migrating-to-devfile-v2.html

**Comment by jc-berger** [comment]
@rkratky, will review more next week, thanks.

**Comment by rkratky** [comment]
JIRA: https://issues.redhat.com/browse/RHDEVDOCS-2296
