### ISSUE TITLE
Re-write the OCI registry metadata container in Go

### ISSUE THREAD

**Issue by johnmcollier** [devfile/api#188]
The current metadata container for the OCI registry uses shell scripts to generate the index.json, push the devfiles to the registry, and start the Apache HTTP server. This approach gives us little flexibility in pushing up the devfile stacks, as we're not able to easily parse the index.json without pulling down additional dependencies like jq. It also means that we need to package the index-generator and ORAS CLIs (the latter of which is intended only for testing and not use in production) into the container

It would be wise to re-write the metadata container (and server) in Go to make use of the index-generator and oras Go libraries (rather than CLIs), as well as to host the index.json. This will give us additional flexibility in the future, as we look to define APIs on top of the metadata container's server.

**Comment by GeekArthur** [comment]
The metadata container written by golang should follow the changes in this degisn proposal: https://github.com/devfile/api/pull/197
