### ISSUE TITLE
Define onboarding requirement for a stack to be added to a public registry (include documentation on the devfile public website)

### ISSUE THREAD

**Issue by elsony** [devfile/api#191]
If the user wants to set up their own devfile registry with their customized devfiles, we need a document to tell the user how to do it.

This document should covers:
1. What is the structure of a devfile registry
2. index.json content
3. Expectation of the content structure under each stack and where to push related resource files referenced by the devfile (onboarding requirement)
4. metadata content that is needed for a proper catalog list on the stacks
5. secure devfile registry setup
6. Registry operator installation and registry deployment
7. Registry index (#195)
8. Registry library

When we create this devfile registry documentation, we should also restructure our existing overview page (i.e. entrance point for our doc website) to organize it a bit. We may want input from UX on this. Things that we can do:
1. On the overview page, we provide an overview of the devfile as before
1. The main path that the user will follow is the existing content that talks about the devfile specification itself, e.g. API reference, user guide, migration doc, etc.
1. The second path talks about the devfile registry. It'll contain the information list above.

**Comment by rkratky** [comment]
Related: #195 (set up docs site for publishing registry (and other components) docs.

JIRA: https://issues.redhat.com/browse/RHDEVDOCS-2570

**Comment by GeekArthur** [comment]
The main devfile registry docs also need to cover:
1. Registry operator installation and registry deployment
2. Registry index (https://github.com/devfile/api/issues/195)
3. Registry library

**Comment by elsony** [comment]
@GeekArthur I have added those to the original description to make a consolidated list. Thanks for bringing it up!
