### ISSUE TITLE
Update Devfile API reference for 2.0

### ISSUE THREAD

**Issue by rkratky** [devfile/api#192]
The published Devfile API reference (https://devfile.github.io/devfile/api-reference.html) needs to reflect 2.0 status of the specification.

**Comment by boczkowska** [comment]
@rkratky is it our of date? 
The API Reference is generated automatically, see https://github.com/devfile/docs#contributing and https://github.com/devfile/docs/pull/11

**Comment by boczkowska** [comment]
@rkratky devfile json schema also is pushed to the docs repo automatically: https://github.com/devfile/api/pull/176

**Comment by rkratky** [comment]
@boczkowska, great. I missed that. One thing we don't need to worry about.
