### ISSUE TITLE
Publish registry index schema to devfile website

### ISSUE THREAD

**Issue by GeekArthur** [devfile/api#195]
**Is your feature request related to a problem? Please describe.**
Currently we don't have registry index schema in public place, we should publish the registry index schema to devfile website, the layout/format should be similar to devfile schema.

**Comment by GeekArthur** [comment]
Discussed more details in today's cabal call, we may need a better design for devfile website landing page then use either sub-domain or sub-path mechanism to separate the contents (devfile, devfile registry/index) related to devfile.

**Comment by GeekArthur** [comment]
Move this issue to TODO and will revisit this one after we finalize the design of our website to hosts both devfile API and registry docs.

**Comment by rkratky** [comment]
TODO:

1) Propose new docs site structuring to accommodate other components (registry, parser, library, ...) in addition to the spec.
2) Set up the structure, create placeholders for indiv. component content.
3) Start populating the site.

JIRA: https://issues.redhat.com/browse/RHDEVDOCS-2569

**Comment by GeekArthur** [comment]
I am thinking probably we can expand the scope of this issue to make the new docs site includes all registry related information (eg. registry deployment/installation, registry index and registry library) instead of only registry index schema.

**Comment by elsony** [comment]
@GeekArthur We currently have https://github.com/devfile/api/issues/191 to track the general registry documentation. Feel free to add things to that item if you find areas that are not covered.

**Comment by GeekArthur** [comment]
> @GeekArthur We currently have #191 to track the general registry documentation. Feel free to add things to that item if you find areas that are not covered.

That's great, will add things to the main docs item.
