### ISSUE TITLE
Ability to generate devfile objects for specific devfile schema versions

### ISSUE THREAD

**Issue by yangcao77** [devfile/api#200]
As a consumer, I would like the common library to be able to convert provided information into a valid devfile object for a specific devfile schema version.  
It should be part of the writer utils. 

Usage in odo:
https://github.com/openshift/odo/blob/6a33350ad9baffef3a47b916872b8b718a1e467d/pkg/odo/cli/utils/convert.go#L275-L301

consumers should pass in params to common library and get the appropriate devfile object for specific devfile versions. So that consumers' code would be independent to schema definition.

**Comment by maysunfaisal** [comment]
We should probably wait on this issue until devfile/library switches to devfile/api override and merge functions because the odo's convert.go uses AddCommand which will be replaced by devfile/api override and merge functions

**Comment by adisky** [comment]
@yangcao77 @maysunfaisal I am not sure on this the devfile api objects are exposed, why the consumer cannot use them directly? we use kubernetes objects directly and I think having a library does not mean that consumers should not access devfile/api objects as everything cannot be covered by library. 

I agreed on updating those to use object definitions from devfile/api, and updating the writer functions to use from library.

**Comment by elsony** [comment]
This item has been replaced and addressed by #326
