### ISSUE TITLE
endpoint protocol type should be EndpointProtocol

### ISSUE THREAD

**Issue by yangcao77** [devfile/api#205]
Endpoint protocol type should be `EndpointProtocol` instead of string
https://github.com/devfile/api/blob/6aa1dc0e343760fb21e7d82fa0f5405f1c19ce3b/pkg/apis/workspaces/v1alpha2/endpoint.go#L86

**Comment by mmulholla** [comment]
This change is problematic, according to the api doc the endpoint can be set to https or wss, but this change does not allow these values. 

The way for a user to, for example, set https is to set the protocol to http and the secure attribute to true/.

Why have two attribiutes?  Who is responsible for converting the protocol http and secure true to protocol https?

**Comment by yangcao77** [comment]
@mmulholl IMO, the problem is unrelated to this change. you might want to argue with this line
https://github.com/devfile/api/blob/6aa1dc0e343760fb21e7d82fa0f5405f1c19ce3b/pkg/apis/workspaces/v1alpha2/endpoint.go#L5

**Comment by mmulholla** [comment]
@yangcao77 this change is good but it was the catalyst that brought the issue I discuss to our attention. In this sense it introduced the problem and this is arguabally an incomplete fix.
