### ISSUE TITLE
schemaVersion link is broken on doc

### ISSUE THREAD

**Issue by josephca** [devfile/api#207]
**Describe the bug**
From https://docs.devfile.io/devfile/assembly_making-a-workspace-portable-using-a-devfile.html#a-minimal-devfile_making-a-workspace-portable-using-a-devfile, click 'schemaVersion' which is broken. I think the file has been moved and it should be linked to 'https://github.com/devfile/api/blob/master/schemas/latest/devfile.json'

![image](https://user-images.githubusercontent.com/25185698/98289744-9fa62580-1f76-11eb-8ae8-0babcff0075c.png)

**Comment by elsony** [comment]
It looks like there are multiple problems to fix before it will work properly:
1. Those entries should be pointing to the corresponding entry reference found on the page: https://docs.devfile.io/devfile/api-reference.html

**Comment by elsony** [comment]
The PR https://github.com/devfile/docs/pull/19/files fixes the original immediate problem reported on this item. Therefore, I am removing this from the 2.0 release and we can address the rest of the problems that I listed https://github.com/devfile/api/issues/207#issuecomment-722685251 post 2.0 release.

**Comment by rkratky** [comment]
TODO:

* Ensure the reported problem are fixed or not relevant any more.
* Check for any other outdated links.

JIRA: https://issues.redhat.com/browse/RHDEVDOCS-2568

**Comment by jc-berger** [comment]
I just went through all the links in our Devfile 2.1.0 Alpha docs: https://docs.devfile.io/devfile/2.1.0/user-guide/index.html 

All the links work, so I'd advise that we close this issue as it is no longer pertinent.

**Comment by jc-berger** [comment]
Closing as this issue is no longer pertinent. Thankfully, all our links are currently working!
