### ISSUE TITLE
Add "message" field to DevWorkspace status and column for kubectl get

### ISSUE THREAD

**Issue by amisevsk** [devfile/api#220]
## Is your feature request related to a problem? Please describe.
There are many valid reasons for a DevWorkspace startup to fail and we represent status this via the `Failed` value for `.status.phase`. However, the only way to get insight into *why* a particular DevWorkspace failed to start is by inspecting the full yaml of the DevWorkspace and checking which Conditions are set.

## Describe the solution you'd like
We should add a field, e.g. `Message` or `StatusInfo` to `DevWorkspaceStatus` and include it in the output for `kubectl get`. This might result in output such as
```
$ kc get devworkspaces
NAME    WORKSPACE ID                PHASE    URL   INFO
theia   workspacecd070100795e4809   Failed         Plugin X not found in registry
```

cc: @davidfestal

**Comment by sleshchenko** [comment]
Do we have any example when INFO may be not empty for not failed state?

**Comment by JPinkney** [comment]
Personally, I like this idea. I dislike having to dig through the logs to find out why my devworkspace failed. I'd prefer it if we had some easy way to find out why it failed for users (and even ourselves)

**Comment by davidfestal** [comment]
@amisevsk Do we want to use the same field names are those used in [`PodStatus`](https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#podstatus-v1-core) for consistency:

- *message*: A human readable message indicating details about why the pod is in this condition.
- *reason*: A brief CamelCase message indicating details about why the pod is in this state. e.g. `Evicted`

**Comment by amisevsk** [comment]
> Do we have any example when INFO may be not empty for not failed state?

In general I'd use the field to communicate info that requires user intervention, since it cannot be hidden and a normal running state is captured by `phase = Running`. Ideally we'd hide the field when empty in the `get devworkspaces output`

> Do we want to use the same field names are those used in PodStatus for consistency:

That makes sense, I'm generally bad at naming things :D

**Comment by johnmcollier** [comment]
Just chiming in here since I'm trying to do a similar thing for the registry operator - what about exposing the detailed status message as part of the `kubectl describe devworkspace <resource>` output on each state change?

Seems like that can be done with the manager's event recorder.

**Comment by amisevsk** [comment]
> Just chiming in here since I'm trying to do a similar thing for the registry operator - what about exposing the detailed status message as part of the kubectl describe devworkspace <resource> output on each state change?

> Seems like that can be done with the manager's event recorder.

Sorry, getting back to this a little late. I don't know offhand how to do this -- could we create a follow-up issue to plan this? I think it's a good idea (I never think to use `kubectl describe`)

**Comment by johnmcollier** [comment]
Yeah, I think that sounds reasonable 👍
