### ISSUE TITLE
Define the structure of the devfile registry

### ISSUE THREAD

**Issue by elsony** [devfile/api#226]
Define how the stack content is organized and layout on a devfile registry

This item is part of #82

**Comment by johnmcollier** [comment]
I can tackle this.

Necessary tasks:
- Design doc outlining structure of the devfile registry repository (and how it feeds into the OCI registry)
- Updating the devfile registry bootstrap container based on the agreed-upon design doc

Public documentation for repository structure will be handled via https://github.com/devfile/api/issues/191

**Comment by johnmcollier** [comment]
Design doc created in https://github.com/devfile/api/pull/245 and I've updated the index schema accordingly in https://github.com/devfile/registry-support/pull/15

All that remains is updating the bootstrap process to use the new `resources` field. So moving back to in progress til I have a PR up.
