### ISSUE TITLE
define devfile validation rules

### ISSUE THREAD

**Issue by yangcao77** [devfile/api#229]
Before start working on devfile validation, the rule has to be defined

This issue is to create a design doc of devfile validation rules, and share with the team. dev-workspace, console and odo can review, add and comment on the rules. 
After the validation rules have been finalized, we can start work on devfile validation. 

The rules should be created by considering the following 

-  schema definition

-  generic validation in odo

- generic validation in dev-workspace

**Comment by yangcao77** [comment]
The doc is created: https://docs.google.com/document/d/14zFvpb48Q6sdn-W3zTImuwKjMZeCAkbwm12pCl-8WUU/edit?usp=sharing

**Comment by elsony** [comment]
Merged the doc
