### ISSUE TITLE
Enable attributes overriding

### ISSUE THREAD

**Issue by yangcao77** [devfile/api#233]
The current `attributes` filed in components/commands/projects are not able to be overriden. 
As we discussed in the meeting, we want to enable attributes overriding to provide a way for user to inject attributes to existing devfile in registry/git repo

**Comment by elsony** [comment]
Adding this to the 2.0 plan to be included as part of the 2.0 release as discussed.

**Comment by elsony** [comment]
@yangcao77 Is there any remaining work on this item? Can we close this?

**Comment by yangcao77** [comment]
This one can be closed.
