### ISSUE TITLE
the metadata filed should allow additionalproperty to be backward compatible 

### ISSUE THREAD

**Issue by yangcao77** [devfile/api#236]
**Describe the bug**
The current devfile schema is backward incompatible due to the `additionalproperty` in metadata field has been set to false. 
It would cause error while using the latest schema to parse an old 2.0 devfile
For example: devfile from [odo registry](https://raw.githubusercontent.com/odo-devfiles/registry/0b0e73401e462324a8db32b60c625f56ad639391/devfiles/java-openliberty/devfile.yaml)

schema validation failed due to the  following error:
```
invalid devfile schema. errors :
- metadata: Additional property alpha.build-dockerfile is not allowed
- metadata: Additional property alpha.deployment-manifest is not allowed
```

**To Reproduce**
use the latest schema to parse devfile from [odo registry](https://raw.githubusercontent.com/odo-devfiles/registry/0b0e73401e462324a8db32b60c625f56ad639391/devfiles/java-openliberty/devfile.yaml)

**Expected behavior**
should be able to pass the schema validation, even the extra fields will not be unmarshal/marshal

**Comment by elsony** [comment]
@yangcao77 Is there any remaining work for this given that PR #234 has been merged? Can we close this?

**Comment by yangcao77** [comment]
Yes. This one can be closed.
