### ISSUE TITLE
Integrate cert-manager into the Devfile Registry operator

### ISSUE THREAD

**Issue by johnmcollier** [devfile/api#241]
One of the items highlighted in the initial [Devfile Registry Operator design doc](https://github.com/devfile/api/blob/master/docs/proposals/registry/registry-operator.md), was an integration with [cert-manager](https://cert-manager.io/docs/) for provisioning TLS secrets for HTTPS support on Kubernetes. 

However, we weren't able to integrate it into the first pass of the operator, as the `cert-manager` Golang API was incompatible with the versions of `client-go` and `controller-runtime` used in the operator. For now, TLS support for generic Kube requires creating your own TLS secret before deploying the registry.

Integration with cert-manager is still an important thing to have in the operator, but we may need to look into workarounds for pulling in the API and / or tweaking the version of `client-go` that we use on the operator-side.

- [ ] Have the operator create `ClusterIssuer` and `Certificate` resources when TLS is enabled but no preexisting secret name is set in `tls.secretName`
    - Either done by pulling down the cert-manager API (and resolving version incompatibilities) or finding an alternative route
- [ ] Automatically add the provisioned TLS secret to the registry ingress resource.

**Comment by michael-valdron** [comment]
OLM deployments work without cert-manager due to OLM using its own cert manager and the operator only using self certs, only needs cert-manager when deploying independently.
