### ISSUE TITLE
Improve the status reporting of DevfileRegistry resources

### ISSUE THREAD

**Issue by johnmcollier** [devfile/api#242]
When a person runs `kubectl get devfileregistries` (or `kubectl get dr`, etc) on a cluster with the devfile registry operator installed, the following is shown in the output for a "non-ready" devfile registry:
```
Johns-MacBook-Pro-3:registry-operator johncollier$ k get dr
NAME                    URL
test-devfile-registry   
```

Once the registry has become available and is serving the index.json, we update the status to include the URL of the devfile registry:
```
Johns-MacBook-Pro-3:registry-operator johncollier$ k get dr
NAME                    URL
test-devfile-registry   http://test-devfile-registry.johncollier.ca
```

But, if something happens that prevents the registry from becoming available for some reason, we don't currently have a way of reflecting that information (or why it happened). Additionally, we don't show anything when the devfileregistry instance is being updated. It would be nice if we could show the current "status" or "phase" of the devfile registry:

```
Johns-MacBook-Pro-3:registry-operator johncollier$ k get dr
NAME                    URL                                           STATUS
test-devfile-registry   http://test-devfile-registry.johncollier.ca   Running
my-devfile-registry                                                   Failed
```

Some statuses that we should expose:
- `Deploying` -> Devfile registry has been created and its resources are being deployed by the operator
- `Running` -> Devfile registry has been deployed and is accessible.
- `Upgrading` (or `Updating`) -> One or more fields in the DevfileRegistry custom resource have been updated and the instance is being updated by the operator
- `Failed` -> The devfile registry failed to deploy
- `UpgradeFailed` (or `UpdateFailed`) -> The devfile registry's update failed

Another improvement we could make is to also expose detailed status messages on the `kubectl describe devfileregistry <instance>` output for each change in status:
```
Johns-MacBook-Pro-3:registry-operator johncollier$ k describe dr my-devfile-registry
  .
  .
  .
  Type     Reason    Age   From                        Message
  ----     ------    ----  ----                        -------
  Info     Deploying 0s     devfileregistry-controller  Deploying devfile registry
  Error    Failed    10s    devfileregistry-controller  Encountered error $error deploying the devfile registry
```

**Comment by elsony** [comment]
1. +1 for adding status
2. I prefer Updating instead of Upgrading. It is safer to say it is an upgrade for which sometimes, it can be just minor changes on the registry.
3. For the UpdatedFailed, if we are doing the update as discussed before, we'll not go ahead and switch the active instance until the update is completed and successful. That means even if UpdateFailed, the registry can still be up and running. If we only have one status, how can we display that correctly? I wonder if we should separate it out, e.g. update success and UpdateFailed status. Maybe we can separate those two out, e.g. displays the last update timestamp or failed to update on xxx. Maybe the last update timestamp only shows in the `describe` command. For `get` command`, it will be one of the `Deploying`, `Running`, `Failed`. 
4. I am not sure if there is any case that we also need to display `Stopping`

**Comment by johnmcollier** [comment]
> I prefer Updating instead of Upgrading. It is safer to say it is an upgrade for which sometimes, it can be just minor changes on the registry.

Agreed. 

> For the UpdatedFailed, if we are doing the update as discussed before, we'll not go ahead and switch the active instance until the update is completed and successful. That means even if UpdateFailed, the registry can still be up and running. If we only have one status, how can we display that correctly? I wonder if we should separate it out, e.g. update success and UpdateFailed status. Maybe we can separate those two out, e.g. displays the last update timestamp or failed to update on xxx. Maybe the last update timestamp only shows in the describe command. For get command, it will be one of the Deploying, Running, Failed`.

You're right. In that case, yeah, we should show it in the `describe` output only. I'll look into seeing if Kubernetes allows us to show only the most recent message in the `describe` output, or if we have to show everything.

> I am not sure if there is any case that we also need to display Stopping

I don't think we need it. Since that would only happen when the registry admin deletes a `DevfileRegistry` instance, and in that case, since the instance has been deleted, we wouldn't be able to change its status.

**Comment by thepetk** [comment]
closing as rotten (created > 2 years). Feel free to re-open if it's not a requirement.
