### ISSUE TITLE
Integrate the Devfile Registry Operator's integration tests onto OpenShift CI

### ISSUE THREAD

**Issue by johnmcollier** [devfile/api#243]
Now that we've merged the Devfile Registry operator into https://github.com/devfile/registry-operator, we need to get its integration tests running on the OpenShift CI for regular test coverage and for test coverage on PRs.

Information on running the tests can be found at https://github.com/devfile/registry-operator#testing

Tasks:
- [ ] Get the registry operator integration tests running on the OpenShift CI
- [ ] Add the integration tests as a required check on registry-operator PRs

CC @devfile/qe-team

**Comment by josephca** [comment]
The onboarding of 'registry operator' is done by 

- ci-operator: https://github.com/openshift/release/pull/14031
- initial integration tests: https://github.com/devfile/registry-operator/pull/3, https://github.com/devfile/registry-operator/pull/4, and https://github.com/devfile/registry-operator/pull/5
