### ISSUE TITLE
Parser api inconsistencies commands v others

### ISSUE THREAD

**Issue by mmulholla** [devfile/api#246]
The parser API treats commands differently from other objects:

GetCommands() map[string]v1.Command
AddCommands(commands ...v1.Command) error

compared to, for example,

GetComponents() []v1.Component
AddComponents(components []v1.Component) error

would be better if commands was: 

GetCommands() []v1.Command
AddCommands(commands  []v1.Command) error

**Comment by yangcao77** [comment]
fixed in https://github.com/devfile/library/pull/46
