### ISSUE TITLE
Authoring stacks: describe the common form of a devfile

### ISSUE THREAD

**Issue by themr0c** [devfile/api#249]
In https://docs.devfile.io/devfile/2.0.0/user-guide/authoring-stacks.html, we need to describe what is the common form of a devfile: a YAML document named devfile.yaml.

**Comment by themr0c** [comment]
cc: @jc-berger

**Comment by rkratky** [comment]
JIRA: https://issues.redhat.com/browse/RHDEVDOCS-2459
