### ISSUE TITLE
Git attributes `tag`, `commitId`, and `branch` 

### ISSUE THREAD

**Issue by themr0c** [devfile/api#250]
In https://docs.devfile.io/devfile/2.0.0/user-guide/adding-projects-to-a-devfile.html, the description for various attributes should be consistent with the description in the API reference https://docs.devfile.io/devfile/2.0.0/user-guide/api-reference.html

git attributes `tag`, `commitId` and  `branch` don't appear in the API reference: are they obsolete or missing?

**Comment by rkratky** [comment]
Related to https://github.com/devfile/api/issues/311 and #314.
JIRA: https://issues.redhat.com/browse/RHDEVDOCS-2557

**Comment by jc-berger** [comment]
@themr0c, see my PR that addresses this specific concern. I've run through the other docs in `authoring stacks` and none of them mention these three terms you've specified: `tag, commitld, branch` 

https://github.com/devfile/docs/pull/43
