### ISSUE TITLE
Add examples for `sparseCheckoutDir` attribute

### ISSUE THREAD

**Issue by themr0c** [devfile/api#251]
In https://docs.devfile.io/devfile/2.0.0/user-guide/adding-projects-to-a-devfile.html, please add examples to describe the usage of the `sparseCheckoutDir` attribute.

**Comment by rkratky** [comment]
Umbrella: https://github.com/devfile/api/issues/313
JIRA: https://issues.redhat.com/browse/RHDEVDOCS-2558
