### ISSUE TITLE
Set up vale for the repository

### ISSUE THREAD

**Issue by themr0c** [devfile/api#252]
Add vale configuration to validate content with IBM style guide.

Vale: https://docs.errata.ai/vale/about/
IBM style guide: https://github.com/errata-ai/IBM

* Add .vale.ini (example: https://github.com/eclipse/che-docs/blob/master/.vale.ini)
* Copy files from https://github.com/errata-ai/IBM/tree/master/IBM  in the `StylesPath` directory.

**Comment by rkratky** [comment]
JIRA: https://issues.redhat.com/browse/RHDEVDOCS-2567
