### ISSUE TITLE
Add placeholders to create directories for examples and images

### ISSUE THREAD

**Issue by themr0c** [devfile/api#256]
Add `.placeholder` file into directories to ensure the creation of these directories in git:  `examples`, `images`

```
└── docs/docs/modules/user-guide/
    ├── attachments
    ├── examples
    ├── images
    ├── pages
    └── partials
```

label: area/documentation
cc: @jc-berger

**Comment by rkratky** [comment]
@themr0c Is there any reason to create these directories before there's any content that would need to be placed in them?
