### ISSUE TITLE
Rewrite for v2: Adding plugin component to a devfile

### ISSUE THREAD

**Issue by themr0c** [devfile/api#258]
Plugins are now specified using a devfile. A plugin specified in a v1.0 meta.yaml will NOT work as it is in a devfile v2.0. (as stated in https://docs.devfile.io/devfile/2.0.0/user-guide/migrating-plug-ins.html).

As a consequence, it is necessary to review and rewrite  https://docs.devfile.io/devfile/2.0.0/user-guide/adding-plugin-component-to-a-devfile.html

label: area/documentation
cc: @jc-berger

**Comment by rkratky** [comment]
JIRA: https://issues.redhat.com/browse/RHDEVDOCS-2563
