### ISSUE TITLE
Complete list of components

### ISSUE THREAD

**Issue by themr0c** [devfile/api#260]
For a better syntax validation component now is defined as a polymorphic type and can be implemented as container, kubernetes, openshift, plugin or volume. (as stated in https://docs.devfile.io/devfile/2.0.0/user-guide/migrating-components.html)

* Complete the list of components in https://docs.devfile.io/devfile/2.0.0/user-guide/adding-components-to-a-devfile.html
* Add new page and navigation for missing components: `openshift` and `volume`

label: area/documentation
cc: @jc-berger

**Comment by rkratky** [comment]
JIRA: https://issues.redhat.com/browse/RHDEVDOCS-2561
