### ISSUE TITLE
clarify & update commands for v2

### ISSUE THREAD

**Issue by themr0c** [devfile/api#261]
*  https://docs.devfile.io/devfile/2.0.0/user-guide/migrating-commands.html needs clarification.
* Is the content of https://docs.devfile.io/2.0.0/devfile/user-guide/adding-commands-to-a-devfile.html on par with the specs for v2?

**Comment by josephca** [comment]
In addition, I noticed a typo in https://docs.devfile.io/devfile/user-guide/migrating-commands.html 
i.e. 
_This section describes how to migrate **plug-ins** to devfile v2._ 
should be changed to
_This section describes how to migrate **commands** to devfile v2._

**Comment by rkratky** [comment]
JIRA: https://issues.redhat.com/browse/RHDEVDOCS-2560
