### ISSUE TITLE
Add a CONTRIBUTING page

### ISSUE THREAD

**Issue by themr0c** [devfile/api#262]
Source of inspiration: https://github.com/eclipse/che-docs/blob/master/CONTRIBUTING.adoc

**Comment by rkratky** [comment]
JIRA: https://issues.redhat.com/browse/RHDEVDOCS-2559

**Comment by rkratky** [comment]
Update/maintenance policy:

* nightly: no guarantee; may break your apps and eat your breakfast
* current: active maintenance, improvements, and bugfixes
* current - _n_:
  * P1 & P2 bugfixes (and bugfix backports from 'current')
  * P3 bugfixes - best-effort only
  * no formatting and/or language updates/fixes or backports

**Comment by pmkovar** [comment]
@schultzp2020  I think we can close this?

**Comment by schultzp2020** [comment]
No longer needed
