### ISSUE TITLE
The devfile website should support hosting multiple devfile schemas

### ISSUE THREAD

**Issue by johnmcollier** [devfile/api#275]
Currently the https://devfile.github.io/ website hosts the latest schema generated from master in this repo (and synced to devfile/docs via a CI job). 

<img width="1792" alt="Screen Shot 2020-12-10 at 10 52 16 AM" src="https://user-images.githubusercontent.com/6880023/101795321-c6a3ca00-3ad5-11eb-97b3-3fa2f6d71453.png">

As part of https://github.com/devfile/api/issues/150, upon each release, we'll be syncing each new released schema and a schema pointing to the latest stable version over to the website as well.

To support this, the devfile website should support hosting multiple devfile schemas, and should (preferably) default to the latest `stable` version of the schema that's been published. There should also be an option to toggle between versions of the devfile schema for viewing (e.g. `latest`, `stable`, `2.1`, `2.0`, etc)

**Comment by elsony** [comment]
We may want to rename `latest` to something like `nightly` to make it clear that it is a WIP version.

**Comment by mmulholla** [comment]
all done.
