### ISSUE TITLE
Add registry usage telemetry to track registry usage

### ISSUE THREAD

**Issue by elsony** [devfile/api#281]
Add devfile registry usage telemetry to track public registry usage. 

Data of interested:
1. number of download of each stack or sample in the registry
2. which tool is being used for download, e.g. odo, che, dev console, dev workspace, etc.

**Comment by johnmcollier** [comment]
Some thoughts I've had on this:
- Telemetry should only be reported on the production registry (https://registry.devfile.io) and not staging
    - To this effect, most tests that are running against the registry right now (e.g.) should use the staging registry, so as not to pollute what's reported back to us.
- Getting telemetry from the OCI server will be _hard_
    - We're just using the [distribution](https://github.com/distribution/distribution) binary reference implementation, and can't  modify it
    - Workaround: We can measure the usage via the registry REST API on the index server, but that means the registry library must also use REST API to retrieve stacks (it's using the OCI API currently)
- Not sure how we'll be able to report the tool doing the download, it'll need to be part of the registry library I suppose?
    - This'll require more thinking, I'm coming up blank at the moment.

**Comment by johnmcollier** [comment]
Updating my thoughts from April:
1) We won't be able to inject telemetry into the OCI registry binary without rolling our own OCI registry
   -
