### ISSUE TITLE
Docs logo blocks left side menu

### ISSUE THREAD

**Issue by mmulholla** [devfile/api#300]
Go to the docs: https://docs.devfile.io/devfile/user-guide/index.html

and you will see the issue. 

It appears to have started in the last few days.

I am using firefox

**Comment by elsony** [comment]
I see the same problem using Chrome as well:
![image](https://user-images.githubusercontent.com/7669867/104332147-ddb34e80-54bd-11eb-8715-6026fa1da0fe.png)

**Comment by mmulholla** [comment]
Note that I started seeing this locally on my own build before I saw it in the public site, without the most recent commits. As a result it is possible that this is caused by an update in antora.

**Comment by mmulholla** [comment]
I did this experiment locally as there is only one download location for for the default ui. 

The last known good version of the doc was a commit in the doc repo on Dec 8, the first bad version was the next commit on Jan 11.

1. Cloned the antora ui repo - it only has a master branch
2. Checked out the last commit on Dec 8 of the master branch of the antora ui repo, and built the antora ui from it.
3. Rebuilt our docs using the antora ui I built in step 2 - open the home page and logo is small
4. Checkout antora ui repo master branch and rebuild the antora ui from it
5. Rebuild our doc using the antora ui built in step 4 - open the home page and the logo is big.

This seems to prove an antora change caused the issue.

fact: antora has 82 commits in the same period.

I propose we build a known good (for us) version of the antora ui, check it into the docs repo and run with it. 
Then at some frequency we rebuild. check it is OK and if so. update the version we have checked in. For first check in maybe we use the one I created based on the Dec 8 version of the antora ui - or any other arbitrary commit lol.

**Comment by mmulholla** [comment]
I opend this antora issue: 
https://gitlab.com/antora/antora-ui-default/-/issues/164#

**Comment by mmulholla** [comment]
antora team have responded to the issue, based on the response we have three options: 

1. Antora suggested a change we can make to our ui which should fix the issue. I don't fully understand but hopefully someone in the doc team does. Then carry on as normal, always downloading the latest antora ui  - at least until we get another issue. 
2. Build some random snapshot of antora ui and then build our doc from it. Our doc then uses a fixed version of the antora ui but it can be updated any time.
3. Create our own copy of the ui  and maintain and modify it. This is what the antora ui developer said: "This is an issue with your own UI that you'll need to fix. We make no guarantee about the behavior of UIs that are derived from the default UI. It's there for reference". 

Options get progressively more work.

My preference is option 2 is a quick fix, and option 3 the long term solution. To be honest I am surprised that Red Hat does not have a Red Hat version of the antora ui which is then used by each of the products, but then I guess you need an individual to maintain it.
