### ISSUE TITLE
Errors in devfile 2.0.0 documentation

### ISSUE THREAD

**Issue by mmulholla** [devfile/api#311]
some of the devfile snippets including in the documentation to not conform to the devfile 2.0.0. spec. Some examples:

Mixed case id/name: 
https://docs.devfile.io/devfile/2.0.0/user-guide/specifying-persistent-storage.html
https://docs.devfile.io/devfile/2.0.0/user-guide/defining-kubernetes-resources.html

Attributes included which are not part of 2.0:
runAsUser : https://docs.devfile.io/devfile/2.0.0/user-guide/adding-commands-to-a-devfile.html
selector: https://docs.devfile.io/devfile/2.0.0/user-guide/adding-kubernetes-component-to-a-devfile.html

what is this? : https://docs.devfile.io/devfile/2.0.0/user-guide/adding-event-bindings.html

These are just what I noticed. May add more when I can do a more through review.

**Comment by jc-berger** [comment]
Thanks for opening the issue, @mmulholl. I'm happy to help with the doc review.

**Comment by mmulholla** [comment]
More issues:

Git attributes are wrong, valid attributes are "checkoutFrom" and "remotes": file:///Users/martinmulholland/devfile/docs/build/site/devfile/2.1.0/user-guide/adding-projects-to-a-devfile.html

invalid attribute : previewUrl: https://docs.devfile.io/devfile/2.0.0/user-guide/adding-commands-to-a-devfile.html

invalid attributes: reference and preferences : https://docs.devfile.io/devfile/2.0.0/user-guide/adding-plugin-component-to-a-devfile.html

kubernetes components all invalid attributes : https://docs.devfile.io/devfile/2.0.0/user-guide/adding-kubernetes-component-to-a-devfile.html

invalid attribute: endpoints.configuration : https://docs.devfile.io/devfile/2.0.0/user-guide/adding-container-component-to-a-devfile.html

**Comment by mmulholla** [comment]
I don't see much value in continuing to find more schema violations, the docs clearly need a thorough review and rework. Obviously the words around the bad use of atttributes need addressing and I think we need to think about what example we want to provide.  

Also the migrating section need a serious review. What has changed?

**Comment by rkratky** [comment]
JIRA: https://issues.redhat.com/browse/RHDEVDOCS-2557
