### ISSUE TITLE
Consolidate devfile docs by pulling in generic content from odo devfile docs

### ISSUE THREAD

**Issue by Preeticp** [devfile/api#312]
**Is your feature request related to a problem? Please describe.**

Currently we maintain two copies of devfile reference docs in odo and in devfiles repos.

**Describe the solution you'd like**

Based on discussions between DV, Elson and Tim in the Sprint review call for track 2, it was recommended that all generic devfile content in this doc: https://odo.dev/file-reference/ should move to the devfile docs and the odo docs must reference the devfile docs and link to the devfile spec. If there's anything odo-specific we can leave it on odo.dev, but we need to redirect anything else to the devfile docs.

**Additional context**
Parallel odo issue:
https://github.com/openshift/odo/issues/4372

**Comment by rkratky** [comment]
Thanks for filing this, @Preeticp. The sooner we get this done, the the easier it will be to promote one and only canonical place for the devfile reference.

@jc-berger, please, work with @boczkowska on the odo side to:

1) Identify odo-specific stuff from the odo-published reference
2) Publish all generic stuff on the devfile website
3) Publish a whittled down version (with odo-specific things only) on the odo site with links to the devfile site

**Comment by rkratky** [comment]
JIRA: https://issues.redhat.com/browse/RHDEVDOCS-2530
