### ISSUE TITLE
More specific devfile doc examples needed

### ISSUE THREAD

**Issue by maysunfaisal** [devfile/api#313]
IMO when a new spec is added or updated(and also ensure for the current release or main branch), we should ensure that the devfile doc has a snippet of the new spec. This will help the devfile consumers with writing new devfiles and will also help devfile developers who did not work on the specific spec for reference and guide.

For example, I think we need snippets for

- plugin component with a kubernetes or URI
- kubernetes/openshift component with either inlined or URI
- vs code task and vs code launch with either inlined or URI
etc.

For URI, it would be preferred to have a mixture of absolute and relative links. 

If the examples are a lot for a documentation page, we can at least add more valid samples to our repo which is already linked in the docs.

**Comment by elsony** [comment]
Our stack author's guide (https://docs.devfile.io/devfile/2.0.0/user-guide/adding-components-to-a-devfile.html) is supposed to cover that. Having said that, there are improvements needed for the areas that you have pointed out.

**Comment by rkratky** [comment]
JIRA: https://issues.redhat.com/browse/RHDEVDOCS-2558

**Comment by scottkurz** [comment]
@maysunfaisal   - Maybe my comment is really more about the issue https://github.com/devfile/api/issues/36  (the idea, which was rejected, of folding the two component types ( 'openshift',  'kubernetes') into a single type.

But I'd be interested to see an example of the benefit of a separate 'openshift' component type.    It looks like the JSON schemas are exactly the same... I thought maybe the "exposure" selection of "public" might be a difference but both component types have same/similar text:   _"....typically through a K8S ingress or an OpenShift route..."_

Is there some ability you get with one/some of the tools by using openshift components?   I can't see how it could be solely for validation.        

Anyway, having an example of each component type seems fundamental so hope to see something like that.
