### ISSUE TITLE
Discussion about schema URI and location

### ISSUE THREAD

**Issue by maysunfaisal** [devfile/api#321]
Since the schema is not really descriptive about the usage of either URI or location, we may need to document the possible valid values for such properties and how they're used.

1. Can all the URI's be both absolute and relative? i.e., a user can provide an absolute http(s)(or an another URI scheme like file) link to the file or a relative link from the current devfile.yaml
2. If relative URI's are allowed, do we want to add validations so that `..` and `.` cannot appear anywhere in the link, `\` cannot be a prefix
3. Can the URI be an absolute location on the disk? URI's can accept scheme `file` and the schema's starterProject/project's zip location description says so - `file://$FILE_PATH`(devfile v2 is inspired from [devfile v1](https://www.eclipse.org/che/docs/che-7/end-user-guide/making-a-workspace-portable-using-a-devfile/#_adding_projects_to_a_devfile) but the example uses a URL for location)
4. What URI schemes are we going to allow in the devfile? Here is a [list](https://en.wikipedia.org/wiki/List_of_URI_schemes) and do we only validate to allow http(s) and file?
5. If we allow the file scheme for URI, do we need to validate for a WIN path?

**Comment by elsony** [comment]
1. Relative URL needs to be well defined by using variables like PROJECT_ROOT
2. no `.` or `..`
3. No file:// allowed, use PROJECT_ROOT variable to properly reference the location
4. Only HTTP and HTTPS are supported for the time being
5. NA since we don't allow file scheme
