### ISSUE TITLE
Remove devfile.projects[].github

### ISSUE THREAD

**Issue by benoitf** [devfile/api#340]
**Is your feature request related to a problem? Please describe.**
when referencing a project I have git or github parameter but they're equals so github brings no value there as we don't change the way of defining a project like
```yaml
github:
   - organization: eclipse
   - repository: che
```
but as we specify the full url to the repo it's useless

**Describe the solution you'd like**
remove github as it brings confusion or make it fancier to define a github repository but if it's just to paste the git url there is no value.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by elsony** [comment]
git and github are duplicated. So we'll deprecate github and recommend user to use git.

**Comment by elsony** [comment]
The `github` duplicate with the existing `git` setting. Instead of deprecating `github`, we have decided to remove `github` support in devfile 2.1.
