### ISSUE TITLE
AddApply, VSCodeLuanch and VSCodeTask command to tests

### ISSUE THREAD

**Issue by mmulholla** [devfile/api#342]
Extend test to include all command types

**Comment by yangcao77** [comment]
Note that vscodeLaunch and vscodeTask are going to be removed from the schema: https://github.com/devfile/api/issues/344

**Comment by sleshchenko** [comment]
The referenced issue is closed. @mmulholl Should we close this one as well? I assume yet, so closing but feel free to reopen
