### ISSUE TITLE
provides and publish types for different languages (interested in typescript)

### ISSUE THREAD

**Issue by benoitf** [devfile/api#353]
**Is your feature request related to a problem? Please describe.**
Using devfile v2 from a typescript client, and using https://github.com/kubernetes-client/javascript I have to perform the calls using `CustomObjectsApi` for custom resources that is returning `Object` type which is not convenient.

For example listing a Pod I've https://github.com/kubernetes-client/javascript/blob/master/src/gen/model/v1PodList.ts or https://github.com/kubernetes-client/javascript/blob/751488214d58feb40d21038c62a225e09487d600/src/gen/model/v1Pod.ts#L21 allowing to be sure what fields are proposed.

I would want to have a type allowing me to cast to the OpenAPI schema https://github.com/devfile/api/blob/9039e8fc60ad5d7b783900f14ceea22ce35b806b/crds/workspace.devfile.io_devworkspaces.v1beta1.yaml#L38

**Describe the solution you'd like**
I'm interested in typescript so having a typescript types (d.ts file) published on npmjs.com exposing DevWorkspace object would help to be sure that when the API is changing it's failing at compilation time.

**Describe alternatives you've considered**
N/A

**Additional context**
kubernetes-client is using openapi-generator 
https://github.com/kubernetes-client/gen/blob/master/openapi/openapi-generator/client-generator.sh

**Comment by sleshchenko** [comment]
typescript types are provided in https://github.com/devfile/api/pull/384
I think it can be closed now. If other languages needs it as well - we need a dedicated issue for each of language
