### ISSUE TITLE
Stop adding new features into Devfile v2

### ISSUE THREAD

**Issue by kadel** [devfile/api#362]
Sorry for the slightly click-bait title :-) 

Something that is starting to worry me quite a lot is that we keep adding new and new features into Devfile v2 without actually having someone using it. We don't even have tools that implement complete Devfile v2 spec and I'm afraid that we will never have.
 
**The complexity of the spec raised to the level where it could put people off from writing Devfiles**
Documentation is also far from ideal, and I see people struggling with writing Devfiles v2. 
I helped a few people with writing Devfiles and our documentation was never enough for them to create a Devfile. How can we expect someone else to start using Devfiles if they can't write it without help from our teams? 

Currently, the only big missing piece is the outerloop. After that, we should pause for a while. Make sure that our tooling can catch up with the spec, and more importantly try to understand what are the use cases and how is devfile getting used.

**Devfile v2 doesn't need to solve all the problems.** 

If there is something that only 20% of the users will benefit from, it is probably not worth adding it to the Devfile v2 spec. A lot of problems can already be solved with `kubernetes` components.

**Comment by elsony** [comment]
1. click-bait, you got me ;-).
2. +1 on slowing down on features. A spec without matching tools implementation will not be useful. Outerloop, tools adoption, and runtime adoption are the main items that we are currently focusing on. The new features that we are adding should be focusing on those.
3. In our recent change, we tried to simplify the spec to remove the confusing parts, e.g. plugin, vscodetask, etc. If there are other parts that are too complicated, we should review them to see how we can improve (of course, we need to keep backward compatible in mind). At a minimum, we can beef up the descriptions in the schema to clarify.
4. +1 on better documentation. The stack authors guide is meant to guide people but if people struggles, it shows that it is not enough. Do we happen to know which part of the devfile spec that people mostly have questions? Having that list will help us on prioritizing the doc work.

**Comment by kadel** [comment]
We can close this one. There is nothing that needs to be done. This was meant only for awareness.
/close
