### ISSUE TITLE
The v2 Devfile Registry should have a UI for browsing devfiles

### ISSUE THREAD

**Issue by johnmcollier** [devfile/api#366]
There's currently no "frontend" or UI for the new oci-based devfile registry. The only information currently shown in the browser when you access the devfile registry URL is just the index.json file that tools like Odo or Che/CRW would consume, e.g.:

<img width="1312" alt="Screen Shot 2021-03-08 at 10 35 53 AM" src="https://user-images.githubusercontent.com/6880023/110343033-1113e480-7ffa-11eb-8b2d-8c27451b0a58.png">

While it isn't strictly necessary (in that the tools that consume devfiles don't require it), a simple little UI based on the registry/stack metadata in the index.json would go a long way in improving user-friendliness of the devfile registry.

One example we could take pointers from is how Che/CRW displays the devfiles that are in its registry:
<img width="1254" alt="Screen Shot 2021-03-08 at 10 37 41 AM" src="https://user-images.githubusercontent.com/6880023/110343624-af07af00-7ffa-11eb-9841-62e671e4cfa6.png">

**Comment by maysunfaisal** [comment]
closing as dup of https://github.com/devfile/api/issues/382 since https://github.com/devfile/api/issues/382 is being linked for tracking.
