### ISSUE TITLE
Landing page for devfile website

### ISSUE THREAD

**Issue by elsony** [devfile/api#379]
The existing documentation is more spec-focused. We need a landing page that helps to promote devfile and let the user buy-in to adopt devfiles and use them in their day-to-day development.

The landing page will answer the following questions:
1. What is devfile?
2. What is the existing problem that different persona is facing, e.g. application developer, runtime providers, architect?
3. Benefits of devfile
4. How does it fit into the full development cycle, e.g. local, then container, then k8s, inner-loop to outer-loop, etc.

Then, the landing page will branch off to 4 main personas and provide the information targeted for each of them with samples and best practices:
1. application developer
2. runtime providers
3. registry admin
4. tools provider

Note: example of best practices include (depending on the persona): 
1. How to limit resources
2. What are the things I should put in my devfiles 
3. What are the things I should not put in my devfiles 
4. How to work with devfiles along with application development’s lifecycle

**Comment by rkratky** [comment]
JIRA: https://issues.redhat.com/browse/RHDEVDOCS-2790

**Comment by rtaniwa** [comment]
Link to the draft copy we have started to define: https://docs.google.com/document/d/1TGxPW1cGW6B8sSNCpE4gKmI97I9wkVyh8yepojm5JjU/edit?usp=sharing

**Comment by elsony** [comment]
Updated 

> Link to the draft copy we have started to define: https://docs.google.com/document/d/1TGxPW1cGW6B8sSNCpE4gKmI97I9wkVyh8yepojm5JjU/edit?usp=sharing

Here is the updated location for the draft copy:
https://docs.google.com/document/d/1-lSyhEzLaElt2_cGH93vSnOr5nP04f4co8AkywbCsSE/edit?usp=sharing

**Comment by johnmcollier** [comment]
As discussed on yesterday's call:

Required DNS changes for the domain:
1) Remove redirect for devfile.io -> docs.devfile.io
2) CNAME record for devfile.io to new landing page
3) Remove CNAME record for docs.devfile.io
3) Make docs.devfile.io redirect to devfile.io
4) Update blackbox probes for the domain changes:
   - 2xx codes for devfile.io
   - 3xx codes for docs.devfile.io

**Comment by jc-berger** [comment]
The landing page looks great! Do we know when this new landing page will be the default landing page for users as they search for `devfile.io`? That is, when the [docs page](https://docs.devfile.io/devfile/2.1.0/user-guide/index.html) will no longer be the default landing page for devfile.io?

**Comment by maysunfaisal** [comment]
The landing page is now the default page when users visit devfile.io @jc-berger
