### ISSUE TITLE
Devfile registry library doesn't support registries using self-signed certificates

### ISSUE THREAD

**Issue by johnmcollier** [devfile/api#388]
**Describe the bug**
The devfile registry library doesn't seem to support registries that are using self-signed certificates. Using the branch of odo in https://github.com/openshift/odo/pull/4525, I tried to list devfiles in my own devfile registry, that's signed with self-signed certs:

```
johncollier@jcollier-mac registry % odo catalog list components
 ⚠  Registry TestRegistry is not set up properly with error: Get "https://devfile-registry-default.apps.ci-ln-s8jsgq2-002ac.ci.azure.devcluster.openshift.com/index": x509: certificate signed by unknown authority, please check the registry URL and credential (refer `odo registry update --help`)
```

There should be an option to skip TLS verification when retrieving the index.json and retrieving devfile stacks. We will also need this for the registry tests, as it will be setting up a registry with self-signed certs.

**Comment by GeekArthur** [comment]
This could be a implementation of skipping TLS verification: https://stackoverflow.com/questions/12122159/how-to-do-a-https-request-with-bad-certificate
