### ISSUE TITLE
Hosting and access to devfile registries

### ISSUE THREAD

**Issue by deboer-tim** [devfile/api#39]
Opening this issue to have a discussion about where devfile registries can/should be hosted, and whether we want to have any guidance or recommendations about this. IMHO neither  devfile registry providers nor clients need to all support the same mechanisms, but it would probably be worth defining what access methods are core (assuming only url) or what kind of https/auth mechanisms are expected as a base. e.g. do we expect registries to be hosted with no auth, basic auth, on GitHub (with or w/o auth), GHE, or Kube? We don't need to list these, just generally what should be expected.

**Comment by elsony** [comment]
https://github.com/devfile/registry/blob/main/CONTRIBUTING.md has been added to the registry to document what is needed (with the test coverage) for onboarding to the devfile registry.
