### ISSUE TITLE
Move devfile stack creators over to devfile/registry from odo-devfiles/registry

### ISSUE THREAD

**Issue by johnmcollier** [devfile/api#391]
Odo's current devfile registry is currently located at [odo-devfiles/registry](https://github.com/odo-devfiles/registry/). Once the [PR](https://github.com/openshift/odo/pull/4525) to move odo's default registry to [registry.devfile.io](https://registry.devfile.io/) has been merged, we need to work with the odo team to start the process to move the devfile stack creators from that registry, to the feeder repository for the public registry, [devfile/registry](https://github.com/devfile/registry)

- [x] Communicate change to stack creators, setting up a timeframe to move over.
- [x] Mark odo-devfiles/registry as read-only, but **don't** shut it down
   - Chatted with @elsony earlier, want to keep the odo-devfiles/registry around for the odo installs still pointing to it.
   - Don't want any more stacks contributed, but also don't want to break things 🙂 

Anything else? 

 CC @elsony @kadel

**Comment by kadel** [comment]
> * Chatted with @elsony earlier, want to keep the odo-devfiles/registry around for the odo installs still pointing to it.
> * Don't want any more stacks contributed, but also don't want to break things 🙂

+1 odo-devfiles/registry will have to live for a while in read-only mode. It will take some time for everyone to update and old `odo` versions are going to depend on this registry being accessible.

There are open PRs on odo-devfiles/registrty. We should clean them. Merge what makes sense and copy changes to devfile/registry, close what needs more work, and ask them to do updates on devfile/registry repo.

**Comment by johnmcollier** [comment]
https://github.com/odo-devfiles/registry/ has been archived, closing this one out.
