### ISSUE TITLE
Fix redundancy of "additional resources"

### ISSUE THREAD

**Issue by jc-berger** [devfile/api#401]
Throughout all our documentation, we have "additional resources." For our [authoring stacks](https://docs.devfile.io/devfile/2.1.0/user-guide/authoring-stacks.html), we simply link to other devfile docs. For our [migration guide](https://docs.devfile.io/devfile/2.1.0/user-guide/migrating-to-devfile-v2.html), we simply link to GitHub issues. 

I don't think either of these approaches offer much value to our users. I suggest we do one of two things:

1. Eliminate the "additional resources" from our docs for the time being until we have more beneficial resources to direct our users to view.
2. Create new resources to direct our users from the "additional resources" section. 

The second option will obviously take longer to pursue and complete. 

Jira Issue: https://issues.redhat.com/browse/RHDEVDOCS-2890

**Comment by thepetk** [comment]
closing as rotten (created > 2 years). Feel free to re-open if it's not a requirement.
