### ISSUE TITLE
Registry library filter mechanism to filter by type (sample vs stack) and filter by tags

### ISSUE THREAD

**Issue by GeekArthur** [devfile/api#403]
**Is your feature request related to a problem? Please describe.**
With the introduction of sample vs stack, we probably want the filtering mechanism as part of the getter of the registry library.

**Describe the solution you'd like**
The filters can start with are filtered by type (sample vs stack) and filter by tags. We can build more fine-grained filtering in the future but we can start with those two.

To differentiate sample and stack in index.json, we can either add new field (eg. type) to metadata field or add new tag (eg. sample vs stack) to tags field.

This item is a child of #279

**Comment by elsony** [comment]
Given that our current repo does not support sample vs stack definition yet (pending the work for https://github.com/devfile/api/issues/279), our existing query API only returns a list of stacks. We can provide a temporary implementation to return a static list of samples, e.g. https://github.com/redhat-developer/devfile-sample, for the time being. The list can be a file stored under https://registry.devfile.io/ for the time being.

When we have done #279, we can then modify the implementation to do a life query on the registry. When querying the list of samples, we should probably combine the list of samples and the list of starters and return all of them as samples.

**Comment by elsony** [comment]
The initial implementation of the specific sample/stack filtering that I mentioned in the comment above will be covered by #409. Spinning off a separate item allows the dev console to easily track the dependencies on their devfile integration work.

**Comment by GeekArthur** [comment]
All the PRs related to this issue are merged, the issue is done.
