### ISSUE TITLE
Real life samples for devfile

### ISSUE THREAD

**Issue by rtaniwa** [devfile/api#419]
Problem:
We are missing devfiles for a sample project that will reflect different aspects of the capabilities of devfiles + associated tools that are leveraging devfiles

Goal:
In order to deliver coherent experiences across our tools, we should be:

Choosing a sample real life project
Implement and build the devfile, and documenting every steps we had to follow
Look at how the developer experience is looking like, from different tools: ODO, OpenShift Connector, CRW, ODC.
The application should be at least:

One back-end service
One front-end service
A database
A cache
We need to look at different scenarios (not exhaustive):

All source code for each microservices on the same repo
Separate repo for each microservices
Consuming external services (managed DB or others)
Why is it important?
Without getting that real example, we are focusing on code samples that are not realistic to what our customers are doing.  This creates discrepancies in the experiences and gap in our story.

**Comment by elsony** [comment]
Some potential apps to start with:
https://github.com/mcouliba/cloud-native-workshop
https://github.com/jbossdemocentral/coolstore-microservice

**Comment by jduimovich** [comment]
Another option https://github.com/jduimovich/graphtuitous  for sample
It is single repo, a microservice in 3 languages (quarkus, node, go) and some graphs in realtime.
The app has a local dev mode (desktop) and a gitops deploy mode live to kubernetes using github actions.
Missing but to be added 1) a database or kafka and 2) and external service (proposed stock service ticker price) and and 3) A/B rollout for gitops

**Comment by elsony** [comment]
More details on the requirements:
1. Create the devfile for an existing project
2. Integrate the project in OpenShift and show the value-added of devfile when integrating with OpenShift.
  i. Get the ability to edit the source code
  ii. Show how it could fasten interaction with Pipelines, or debugging
3. Identify nest-step and problem to solve
  i. Check what needs to be adapted from the specification
  ii. If I was to import the project, without having the devfile yet into the source code - how would we help the user to import his source code and get settled properly. = how do we help the user to create the devfile for/with him.
  iii. How to best provide the integration with build/pipelines
  iv. How can we “expand” the devfile. Example:
    1. I’m adding one new service to my application, how does that affect the devfile
  v. Can we expand the import/devfile onboarding flow - to a “Deploy on OpenShift” story? 
    1. Goal would be to allow people to easily test their application running on OpenShift and experience the developer experience we are providing. 
    2. devsandbox.com/githubURL
4. Publish a set of materials, that based on the sample will showcase devfile use cases.
  i. Blog post
  ii. Docs
  iii. Videos 
5. Another potential app: https://developers.redhat.com/articles/2021/06/14/bee-travels-microservices-coding-adventure#conclusion
6. Interop with tools like JKube, investigate how devfile can fit in (test out on a tool other than odo to refer to k8s yaml from devfile)

**Comment by yangcao77** [comment]
A sample devfile application with 4 subprojects using microservice architecture has been created. Differences and gaps found for [Odo scenarios](https://github.com/yangcao77/web-coolstore/tree/odo-scenario) and [Che scenarios](https://github.com/yangcao77/web-coolstore/tree/pure-che)

More details on those two scenarios can be found in doc: https://docs.google.com/document/d/1Jwsr0RvdFpfmKqpvLIialn8sZHdP1QI2AhDY7alwtGE/edit?usp=sharing

This doc also include the ideal unified experience on devfile applications for different tools and proposed solution.
