### ISSUE TITLE
Devfile documentation for different audiences

### ISSUE THREAD

**Issue by rtaniwa** [devfile/api#423]
**Problem**:
We are missing documentation depending on the audience 

**Goal:**
Provide documentation for different type of audience and separate:

- Docs for users
- Docs for Stack Provider
- Docs for Registry Admin

We would provide samples for each of those.

**Why is it important?**
Help grow adoption and improve readiness of the project for its adoption.

**Comment by michael-valdron** [comment]
@elsony Should this be closed now?
