### ISSUE TITLE
Devfile - Documentation on API

### ISSUE THREAD

**Issue by rtaniwa** [devfile/api#428]
**Goal**
Continue evolving the documentation so that API spec reference is kept up-to-date with devfile.

(this is an ongoing effort)

**Comment by michael-valdron** [comment]
The following workflow keeps the Devfile API spec up to date in the doc pages: https://github.com/devfile/api/blob/adde8ec27e812c21323beb6226846e4ce88dfb49/.github/workflows/publish-devfile-schema.yaml

With the addition of this workflow, I feel that this issue can be closed now.
