### ISSUE TITLE
The registry index generator tool requires an extraDevfilesEntry file

### ISSUE THREAD

**Issue by johnmcollier** [devfile/api#443]
**Describe the bug**

When the index generator tool is ran against a devfile registry without an `extraDevfilesEntry.yaml` file, the index generation fails with the following error:
```
failed to generate index struct: failed to read ooo/extraDevfileEntries.yaml: open ooo/extraDevfileEntries.yaml: no such file or directorySuccessfully built the devfile registry index
```

Since `extraDevfilesEntry.yaml` is an optional file for devfile registries, it shouldn't be required and the index generator shouldn't fail when it doesn't exist

**Comment by GeekArthur** [comment]
I will fix that.
