### ISSUE TITLE
Add devfile sample endpoint on devfile registry query

### ISSUE THREAD

**Issue by elsony** [devfile/api#446]
Provide devfile sample endpoint on devfile registry query in ODC. This item provides the ODC backend code linking to the registry query API to query the list of samples (https://github.com/devfile/api/issues/409). 

Note: The initial implementation of this will start with returning a hardcode list of samples and we'll later change it to call the query API after #409 is completed.

**Comment by maysunfaisal** [comment]
The placeholder samples to unblock ODC is provided by the PR https://github.com/openshift/console/pull/8687

**Comment by maysunfaisal** [comment]
The placeholder samples has been merged to the ODC
