### ISSUE TITLE
Provide option for registry index icon data

### ISSUE THREAD

**Issue by maysunfaisal** [devfile/api#450]
Index icon entry should have the option to include either base64 data of the image or an uri depending upon the registry API's filter query

For example, when ODC consumes the index data for a list of samples they would like to show the icon on the Console UI tile but on other hand odo would not consume the icon data and returning a uri should suffice for it.

**Comment by GeekArthur** [comment]
Proposal:
> I can see tools like odo will have no interest in the icon so they don't want the extra size on the return json. But ODC will always want the icon for the query. A flag to control may allow us to serve both cases properly, for example, the query with flag will return the index.json with base64 encoded string of the icon. The default should probably be just the URI to return a smaller result by default.
