### ISSUE TITLE
Prepare registry doc for registry admin persona

### ISSUE THREAD

**Issue by elsony** [devfile/api#453]
With the restructure of the landing page (https://github.com/devfile/api/issues/441), we are going to provide docs for different persona. One of the targeted persona is the registry administrator who will be interested in the docs related to the devfile registry. This item is to start preparing the content that we can include as part of the registry administrator persona. 

Here are the list of things that we can include:
- [x] Intro to devfile registry
- [x] Type of registries (community vs product vs private (custom/user-owned, on cluster)
- [x] Registry related schema (index.json, extraDevfileEntries.yaml, etc.)
- [x] Registry index, API (both REST and Go library) for registry access
- [x] How to provide your own registry (with tools integration, installing new and updating existing)?
- [x] Registry build + validation and registry source repo
- [x] OCI based registry structure with content structure

**Comment by GeekArthur** [comment]
I am working on 3 and 4 in the list and will push my docs to John's temporary repo above.

**Comment by johnmcollier** [comment]
Closing this one out since we delivered the temporary docs to https://github.com/johnmcollier/registry-docs/, and awaiting on doc review from the docs team (@jc-berger specifically)
