### ISSUE TITLE
Devfile Tutorial For Various Personas

### ISSUE THREAD

**Issue by maysunfaisal** [devfile/api#454]
### Background
This issue discusses the need for a devfile tutorial from different perspectives for the various personas. For example, we would like to have tutorials for Application Developers, Devfile authors/Stack providers, Registry Administrators, Devfile Consumers, etc.

We would like to showcase the various functionalities of the Devfile when curating tutorials for these personas and how to try devfiles out before diving in(Maybe point them towards [Developer Sandbox](https://developers.redhat.com/developer-sandbox), as we can spin up a OpenShift cluster and they can try out devfiles on ODC).

### Work
When working on these tutorials, we can leverage the devfile v2 documentation that we have and also update them as we see fit. We can craft slides, demos, samples, etc to reach our objectives.

These tutorials can be hosted on Red Hat’s website, devfile’s documentation and can be used for conferences in the future.

**Comment by yimikao** [comment]
Hi @maysunfaisal this issue looks interesting..I'd love to work on it :)

**Comment by maysunfaisal** [comment]
@yimikao that sounds awesome 

We will update the issue with specifics, so you can work on this

**Comment by maysunfaisal** [comment]
After having some discussion with the team, we realized that the approach we would like to take in this issue is to create a guide for the Application Developers persona.

In this proposed guide, we could elaborate on how to incorporate a devfile into an application/project. For instance, we could write up about how as an application developer, one would get their application running with a devfile workspace definition. We could leverage tools like [odo](https://odo.dev/) to test out the devfile and perhaps incorporate the example of using odo in our guide.

This [python devfile sample](https://github.com/devfile-samples/devfile-sample-python-basic/) could be used as an example if the guide is aimed towards creating [devfile sample](https://registry.devfile.io/index/sample) repositories.

For [devfile stack](https://github.com/devfile/registry/tree/main/stacks) (which is different from devfile samples), there is an issue https://github.com/devfile/api/issues/911 which is mostly geared towards it. When https://github.com/devfile/api/issues/911 is complete, we could potentially leverage that guide/documentation in our guide to say how to author a devfile from scratch.

**Comment by maysunfaisal** [comment]
@yimikao sorry for the delay in hashing this issue out. But I've posted some details on how to get started. Are you still interested in picking this up? If so, please assign yourself and I can get it tracked.
