### ISSUE TITLE
Update Registry Index & Devfile Schema Project Type to Framework

### ISSUE THREAD

**Issue by maysunfaisal** [devfile/api#464]
When discussing with @elsony about the Registry Viewer website https://github.com/devfile/api/issues/382, we saw the confusion that can arise between `projectType`(spring, vertx, etc) and `type`(stack, sample) for the users, esp since we're planning to use these keywords for the website content's filter. 

So, we should update our registry index schema and change `projectType` to `framework`.

**Comment by elsony** [comment]
Those metadata fields decide how we want to categorize/group our stacks. I think there are actually 3 common variables that we are usually interested in:
language, framework, runtime
For language, it is fairly common and I think it is safe enough for it to stand as a separate category.
Framework and runtime are the ones that are less obvious. It actually comes down to individual stack to see what it wants to promote. 
Some stacks, e.g. OpenLiberty, Quarkus, Node.js, would focus on the runtime vs some other stacks, e.g. java-maven and java-springboot, wants to promote the framework and the runtime being used is less relevant.

One way to represents it is that we can have 3 separate fields for them and maybe framework and runtime are optional. The benefit is the fields have a well-defined purpose. However, we may end up most stacks may be missing one of the fields.

A different approach is that we can have language with projectType and leaving projectType as the "thing" that stack wants to promote. And anything else would need to specify as tags. The pro on that one is every stack has consistent 2 fields to show. And those are keys that stacks want to distinguish themselves from other stacks. The downside of it is the projectType is vague in terms of categorization.

**Comment by elsony** [comment]
In order to simplify the categorization and also in some cases it is difficult to differentiate the framework vs runtime categorization, we have decided to:
1. remove the existing language and framework metadata
2. only provide tag-based categorization and filtering
3. tags are case-insensitive, i.e. `Java`, `JAVA` and `java` are considered as the same tag and will be handled as `java`
