### ISSUE TITLE
Registry Index may need a last update info

### ISSUE THREAD

**Issue by maysunfaisal** [devfile/api#465]
When discussing about the Registry Viewer website https://github.com/devfile/api/issues/382, we noticed that the tektonhub tiles had a last update information on their tile

![Screen Shot 2021-05-20 at 11 59 01 AM](https://user-images.githubusercontent.com/31771087/119011383-044d2e80-b963-11eb-9844-566d4dbf5055.png)

It would be nice if we were able to present this information on the registry viewer website

**Comment by johnmcollier** [comment]
Some questions:
- is the last update when the image was built or the last time it was promoted to staging/prod? The latter may be tricky to do since we’re deploying images that have already been built.
- I’ve been debating on adding a /version endpoint with the git hash, what about including the date/time of build as well? Would that be sufficient?

**Comment by maysunfaisal** [comment]
@johnmcollier yeah lets not do the staging/prod promotion time, we should do the other one.. when you say image build, do you mean the registry image?

**Comment by johnmcollier** [comment]
@maysunfaisal yup. So when we build the devfile registry container image, dynamically set the build time and git hash in a VERSION file of sorts and have /version read from that file (among other possible implementations too)

**Comment by maysunfaisal** [comment]
@johnmcollier so wouldn't that mean, all the samples/stacks have the same last update time whenever a new registry image is created? 

I was thinking more along the lines of the last git commit to a stack/sample 😆

**Comment by johnmcollier** [comment]
D'oh, just realized you were talking about a stack and not the service as a whole 🤦‍♂️ .

Yeah, that makes sense to me too. Could be stored in the index.json entry for the stack?

**Comment by maysunfaisal** [comment]
Yeah we can store each stack's hash and commit details in index.json

we could also include the registry service update on the viewer website too if we wanted
