### ISSUE TITLE
Create issue tracking templates

### ISSUE THREAD

**Issue by elsony** [devfile/api#472]
Our current issue template is outdated. We should come up with new ones, e.g. template for different areas, issue type, etc., with different template to fit the issue.

**Comment by kim-tsao** [comment]
We should also create an issue template for emergency registry updates.  The instructions for stack owners are documented here https://github.com/devfile/registry#registry-updates.  We can move all requested info into the template and update these instructions.

**Comment by kim-tsao** [comment]
We should also consider adding doc/test issue templates to sync with the updates we are planning to make for the PR template: https://github.com/devfile/api/issues/477

**Comment by yangcao77** [comment]
I have created a PR in devfile/library (https://github.com/devfile/library/pull/96) to redirect issue creation to api repo, since api repo is the one we used for issue tracking.
We can also add more redirection links if more templates has been introduced for this issue. 

also suggest to do the same thing for registry repos.

**Comment by yangcao77** [comment]
Proposing to create/update templates for the following areas:
- Bug Reports
- Feature Request
- Documentation
- User Story
- Task (small enhancement/ci/test/technical debt)???
- Emergency registry updates

**Comment by yangcao77** [comment]
Draft has been created and pushed to my branch, please click `raw` to view raw contents with hidden comments.
https://github.com/yangcao77/api/tree/472-issueTemplate/.github/ISSUE_TEMPLATE.

**Comment by slemeur** [comment]
Do we fell confortable that the project "devfile/api" is going to be the place that host all the issues on all the different components?

**Comment by yangcao77** [comment]
> Do we fell confortable that the project "devfile/api" is going to be the place that host all the issues on all the different components?

We are already doing that, except for dev-workspace.
