### ISSUE TITLE
Update PR templates

### ISSUE THREAD

**Issue by kim-tsao** [devfile/api#477]
We should update our PR templates to include a checklist of deliverables beyond the code fix/feature itself i.e. test automation, doc updates, impacts to other dependencies, etc.

This template should be consistent across our repos

**Comment by kim-tsao** [comment]
I like the [PR template](https://github.com/openshift/odo/blob/main/.github/PULL_REQUEST_TEMPLATE.md) from the odo repo.  We can borrow heavily from it and have something like this:

--------------------------------------------------------------
**What does this PR do?**:
_Summarize the changes_

**Which issue(s) this PR fixes**:
_Link to github issue(s)_

**PR acceptance criteria**:

- [ ] Unit test 
_Provide a link to the updated testcases and execution results.  If unchecked, explain why it's not needed_
- [ ] Integration test 
_Provide a link to the updated testcases and execution results.  If unchecked, explain why it's not needed_
- [ ] Documentation 
_This includes product docs and READMEs.  Provide a link to the updated docs_
- [ ] Client Impact
_Do we have anything that can break our clients?  If so, open a notifying issue_


**How to test changes / Special notes to the reviewer**:

--------------------------------------------------------------

**Comment by kim-tsao** [comment]
Summary of discussions with the team:

- We don't want to prevent the PR from being merged if there are missing tests and/or docs.  Having a link to tracking issues is good enough if new function impacts those areas
- PR testing requirements may differ depending on the components.  Some components may have distinct unit/functional/integration testing while others have an umbrella approach - in this case, we will use the general term `Test Automation` instead of itemizing everything out.   
- To avoid any confusion, we will consider the scope of `Integration Tests` as devfile validations with our ODO and console clients i.e. tests that fall under this repo: https://github.com/devfile/integration-tests.  These will be regarded as `QE Integrations Tests` 

Suggestions below:

**PR template For the api/library repos:**
--------------------------------------------------------------
**What does this PR do?**:
_Summarize the changes_

**Which issue(s) this PR fixes**:
_Link to github issue(s)_

**PR acceptance criteria**:
Testing and documentation do not need to be complete in order for this PR to be approved.  We just need to ensure tracking issues are opened.  

> - Open new test/doc issues under the [devfile/api](https://github.com/devfile/api/issues) repo
> - Check each criteria if:
> > - There is a separate tracking issue.  Add the issue link under the criteria
> > **or**
> > - test/doc updates are made as part of this PR
> -  If unchecked, explain why it's not needed


- [ ] Unit/Functional tests
_These are run as part of the PR workflow_
- [ ] [QE Integration test](https://github.com/devfile/integration-tests) 
_Do we need to verify integration with ODO and Openshift console?_
- [ ] Documentation 
_This includes product docs and READMEs._
- [ ] Client Impact
_Do we have anything that can break our clients?  If so, open a notifying issue_


**How to test changes / Special notes to the reviewer**:

--------------------------------------------------------------

### 
**PR template For the Registry:**
--------------------------------------------------------------

.....Similar to above but criteria is different.  I'm not sure if we have client impacts with the registry but I left the criteria in there just in case:
- [ ] Automated Tests
_These are run as part of the PR workflow_
- [ ] Documentation 
_This includes product docs and READMEs._
- [ ] Client Impact
_Do we have anything that can break our clients?  If so, open a notifying issue_

--------------------------------------------------------------

**Comment by elsony** [comment]
The PR template for api/library looks ok.

For registry one, we should focus on the requirements for the onboarding/updating of devfile in the registry, e.g. run through the steps in https://github.com/devfile/registry/blob/main/CONTRIBUTING.md. @johnmcollier @GeekArthur Anything else that needs to add, e.g. 
1. How to contribute/add tests of the stack?
2. metadata requirement, e.g. arch list, name, description, website, etc.

We can probably add those missing info to the contributing.md to have a single place to contain all the onboarding information and the PR just point to that.

**Comment by kim-tsao** [comment]
The api and library repos are done.  I'll re-assign this to @GeekArthur and @johnmcollier so they can take care of the registry repos
