### ISSUE TITLE
Registry Viewer Sample/Stack Page Technical Details

### ISSUE THREAD

**Issue by maysunfaisal** [devfile/api#481]
This is a sub-issue of https://github.com/devfile/api/issues/382

### Background
The stack and sample page will host information about the devfile stack/sample. Both the stack and the sample would present their metadata information. The stack page would display the starter projects and the devfile, while the sample page would display the git url associated with it.

### Mock ups
The mock up for these done by @Nadianw36 can be found in https://github.com/devfile/api/issues/382:
<img width="819" alt="120705590-a1d55180-c47d-11eb-9038-e811618ebfae" src="https://user-images.githubusercontent.com/31771087/120713286-aefb3c00-c48f-11eb-9c43-b0f8d04631eb.png">
<img width="1140" alt="120705593-a3067e80-c47d-11eb-9827-8d7ddf4a5e1f" src="https://user-images.githubusercontent.com/31771087/120713289-af93d280-c48f-11eb-9449-10b0439d6efe.png">

### Nice to have:
 - support git repos hosted on sites other than github (check comment below)

### Checklist:

- [X] Read the sample/stack metadata and present it in the top section 
- [x] Make UI more adjustable (specifically text font and spacing)
- [x] Clean up code and add documentation
- [x] add unit testing
- [x] add end-to-end testing

#### Stack
- [X] Fetch the devfile using the registry api endpoint. eg - https://registry.devfile.io/devfiles/java-maven
- [X] Parse the devfile to list the starter projects info
- [X] Provide option to download the starter projects
- [X] if a starterProject is a git project, provide option to download both as a git or a zip (not applicable)
- [X] if a starterProject is a zip project, provide option to download only as a zip (not applicable)
- [X] Download entire project as a zip
- [x] Download only the subDir of the starter project if present
- [x] add error popup for unsupported git types
- [x] check endpoints for thrown errors
- [x] fix error codes on api endpoint

#### Sample

- [x] Provide a link to open the git project

**Comment by Nadianw36** [comment]
###Nice to have: Ideas for git repos not hosted on github
-  use git archive to download as zip
    - Pros: generalizable to any site hosting git repos
    - Cons: wouldn’t be able to download a specific commit, branch, or issue, except through hard coding on a case by case basis, or via redirecting user to site 
- Resolve on a case by case basis and provide functionality to automatically submit an issue for unsupported site as well as a redirect to the git repo
    - Pros:  would be notified when a site is being used that isn’t supported yet
    - Cons: might lead to resolving a bunch of niche sites and possibly overcomplicating the application
- Just provide a redirect to the site 
    - Pros: wouldn’t have to resolve niche cases
    - Cons: wouldn’t know if a different git repo hosting site is becoming popular and would frustrate user if the site is confusing to navigate
