### ISSUE TITLE
Fix issues in Adding components docs

### ISSUE THREAD

**Issue by kim-tsao** [devfile/api#485]
**Describe the bug**
There are a couple of topics under the `Adding components` docs that require updates 

**To Reproduce**
1. Go to https://docs.devfile.io/devfile/2.2.0/user-guide/adding-kubernetes-component-to-a-devfile.html
2. There is a typo on the first line with `openshfit` being misspelled
3. Go to https://docs.devfile.io/devfile/2.2.0/user-guide/adding-components-to-a-devfile.html
4. Under `Procedure >  Step 3`, there's only 3 mandatory types listed when it should be 4; `kubernetes`, `container`, and `volume`.  According to the spec, we also have `openshift`, so that needs to be added.

**Expected behavior**
See details in the above section

**Screenshots**
![image](https://user-images.githubusercontent.com/84398375/120854211-d7943c00-c54a-11eb-9634-d96f319ddc6e.png)

**Desktop (please complete the following information):**
 - MacOS
 - FireFox 89.0
 

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by Jdubrick** [comment]
Closing issue, looking at the current docs I don't see these issues apparent anymore.
