### ISSUE TITLE
Devfile 2.2.0 Proposal

### ISSUE THREAD

**Issue by sbose78** [devfile/api#49]
## Devfile 2.2.0

The outer-loop guidance for tools would be added in devfile 2.2.0. This is a work-in-progress epic.

### Package files with a stack
1. Introduce the STACK_ROOT variable #46

### Image Build guidance
2. Support component: dockerfile  https://github.com/devfile/kubernetes-api/issues/51

### Image Deployment guidance
 
3. component: workload https://github.com/devfile/kubernetes-api/issues/57
4. component: podTemplate https://github.com/devfile/kubernetes-api/issues/52
5. component: helm Chart https://github.com/devfile/kubernetes-api/issues/53
6. component: objects ( Template-style ) https://github.com/devfile/kubernetes-api/issues/54

Examples in the [doc](https://docs.google.com/document/d/121Sghy2wdvOxCKF6gVPfuPhQHNaOn1nZP5BwnQnDbDw/)

**Comment by sbose78** [comment]
cc @l0rd @kadel @davidfestal @gorkem

**Comment by sbose78** [comment]
Issues to track explicit CI and CD guidance yet to be created - though tools can derive it partially from image build and image deploy guidance.

**Comment by EnriqueL8** [comment]
Is there an issue opened for the Worload component?

**Comment by sbose78** [comment]
@EnriqueL8 Had missed creating one for it. Here you go https://github.com/devfile/kubernetes-api/issues/57 .

**Comment by elsony** [comment]
Renaming this to devfile 2.2 since devfile 2.1 is now being used for dev workspace compatibility work.

**Comment by elsony** [comment]
Community call discussion 3/28:
1. This item will be closed and we'll track the work with the issues listed in the original issue.
2. Items 1-2 are part of devfile 2.2, we'll track them using those individual items.
3. Items 3-6 (#57,52,53,54) in the original description are not included as part of devfile 2.2.
