### ISSUE TITLE
Improper devfile generated for Test_ApplyCommandEdit 

### ISSUE THREAD

**Issue by kim-tsao** [devfile/api#498]
**Describe the bug**
There are a number of error messages in the test.log when this specific test case is run:
```

2021/06/15 14:22:12.480913 [INFO : Use Parser to write devfile ./tmp/library_test/Test_ApplyCommandEdit1.yaml]
2021/06/15 14:22:12.484244 [INFO : Parse and Validate ./tmp/library_test/Test_ApplyCommandEdit1.yaml : ]
2021/06/15 14:40:54.875134 [..... ERROR : From ParseAndValidate 
command group run error - there should be exactly one default command, currently there is no default command
command group test error - there should be exactly one default command, currently there is no default command : ]
```

The contents of the `Test_ApplyCommandEdit1.yaml` file shows there are a number of group commands but none of them have been specified as a default which apparently is a violation of the spec but this is not documented clearly.  We only have a couple of comments in the code and this [validation doc](https://github.com/devfile/api/blob/main/pkg/validation/validation-rule.md)

**To Reproduce**
1. Run the library_test.go/Test_ApplyCommandEdit test
2. Inspect the tests/v2/libraryTest/tmp/test.log

**Expected behavior**
Currently, we are only generating well formed devfiles, so no errors are expected

**Comment by kim-tsao** [comment]
Related bug: https://github.com/devfile/api/issues/577.  Seems like a warning is expected and if that's the case, then I can close this.

**Comment by thepetk** [comment]
closing as rotten (created > 2 years). Feel free to re-open if it's not a requirement.
