### ISSUE TITLE
Packaging starterProjects as part of the devfile registry

### ISSUE THREAD

**Issue by elsony** [devfile/api#516]
**Which area this feature is related to?**
/area registry

## Which functionality do you think we should add?
Stores starterProjects as part of the devfile registry instead of just having devfiles referencing the source repository.

**Why is this needed? Is your feature request related to a problem?**
For performance reason to avoid long download time during starterProject creation.

**Detailed description:**
When looking at the current design of the Che v1.0 devfile registry, it always stores the starterProjects as zip as part of the registry instead of pointing to the original repo from the stack devfiles. The reason that is being done that way is to avoid long download time when cloning the starterProject. Given that Che has seen performance issues in the past when the starterProjects are not stored as zip in the registry, we should consider doing the same in the devfile 2.0 registry.

## Describe the solution you'd like
As part of the registry build process, we download the starterProjects and package as zip file and store that within the registry. We'll adjust the devfile so that it knows where to find the starterProjects zip. 

Note that there is a side effect on this design change since it means the starterProjects in the original repo will not get picked up on our weekly scheduled registry update.

## Describe alternatives you've considered
Stay as the current design by referring to the original starterProjects repo.

## Additional context
N/A

**Comment by elsony** [comment]
Cabal discussion:
1. The existing devfile 1.0 registry only packages the zip files for projects only. `StarterProjects` do not exist in devfile 1.0. Therefore, we'll keep the current design (preserving original git and zip) information in the current registry.
2. For products that need to support offline support, e.g. CRW, they will need to install the registry in the cluster, and thus that installed version can make use of the offline support.
3. When we implement offline support, even though we convert git or zip location to the packaged zip path, we need to preserve the original git or zip location in the converted devfile. We can consider adding an attribute or comment to the converted `starterProjects` definition so users can still find the origin location.

**Comment by thepetk** [comment]
closing as rotten (created > 2 years). Feel free to re-open if it's not a requirement.
