### ISSUE TITLE
Provide a REST API for retrieving devfile stacks and cached devfile samples from the registry

### ISSUE THREAD

**Issue by johnmcollier** [devfile/api#519]
/kind user-story

**Which area this user story is related to?**

/area registry

## User Story

As a user, I want to be able to retrieve devfile stacks and (archived) devfile samples from the devfile registry without having to go through the registry library, as my tools may be written in a language other than Golang. 

Currently, devfile stacks can only be retrieved from the devfile registry by using the [devfile registry library written in Golang](https://github.com/devfile/registry-support/tree/main/registry-library). This means that tools written in other languages (Typescript, Java, etc), are unable to retrieve devfile stacks from the registry. A rest API should be provided that can retrieve these stacks to allow tools written in other languages (such as Typescript, Java, etc) to retrieve devfile stacks.

At the same time, as part of the work to validate the devfile samples (https://github.com/devfile/registry-support/pull/61), each devfile sample project, devfile.yaml, and icon are archived with the registry, but there is no mechanism to retrieve them at the moment. A rest API should also be provided to support downloading these archived devfile samples. This will be useful for the devfile registry viewer, which needs to support displaying the devfile.yaml and icons associated with each sample.

## Acceptance Criteria
- [ ] API for retrieving devfile stacks from the registry
   - `GET /stacks/<stack-name>` should download a zip archive of the devfile stack
   - `GET /stacks/<stack-name>/devfile` should download the devfile.yaml for the devfile stack
   - `GET /stacks/<stack-name>/icon` should download the icon for the devfile stack
- [ ] API for retrieving the devfile samples from the registry
   - `GET /samples/<sample-name>` should download the archived sample zip
   - `GET /samples/<sample-name>/devfile` should download the archived devfile associated with the sample
   - `GET /samples/<sample-name>/icon` should download the icon for the sample
- [ ] Test automation

**Comment by thepetk** [comment]
closing as rotten (created > 2 years). Feel free to re-open if it's not a requirement.
