### ISSUE TITLE
Update registryURL description across all spec levels

### ISSUE THREAD

**Issue by kim-tsao** [devfile/api#522]
/kind bug

### Which area this bug is related to?

/area api

## Bug Summary
**Describe the bug:**

There are two problems:

1. Typo in description 
![image](https://user-images.githubusercontent.com/84398375/124009116-35317200-d9ab-11eb-83a2-b60a7b333e10.png)
We should update the name to match the property `registryUrl`

1. v2.0.0 of the schema is missing the description

**Comment by yangcao77** [comment]
As we discussed in team meeting before, for this kind of change, we will only update the latest main branch to limit the maintenance on previously versions.
