### ISSUE TITLE
Missing 'required' label on parent/projects/git/remotes

### ISSUE THREAD

**Issue by kim-tsao** [devfile/api#529]
/area documentation

**Which area this documentation change is related to?**

 /area api

## Issue details

**What mistake did you find / what is missing in the documentation?**

The parent/projects/git/remotes object is missing the `required` label: https://docs.devfile.io/devfile/2.2.0/user-guide/api-reference.html.   The description does say `Must have at least one remote configured`

![image](https://user-images.githubusercontent.com/84398375/124840218-79e37d00-df58-11eb-94d0-3d6e74550c1f.png)

vs the non-parented project

![image](https://user-images.githubusercontent.com/84398375/124840252-8c5db680-df58-11eb-9832-ee70965488d5.png)

Affects all API versions

**Comment by kim-tsao** [comment]
Actually, it's denoted as `optional` in the api: https://github.com/devfile/api/blob/e535ef2c2d646c4e6f2ed9283660efaac8396dd9/pkg/apis/workspaces/v1alpha2/zz_generated.parent_overrides.go#L532-L534

@yangcao77 do you know if this is mandatory or optional?

**Comment by yangcao77** [comment]
it should be required. it's not a documentation issue.

**Comment by Jdubrick** [comment]
Closing issue as it is optional and does not have the required tag on the current docs. If we need to revisit we can reopen however there hasn't been much activity on this and seems low priority.
