### ISSUE TITLE
The "Authoring stacks" heading in "docs.devfile.io" should have a sub-heading describing devfile variables.

### ISSUE THREAD

**Issue by scottkurz** [devfile/api#531]
/area documentation

**Which area this documentation change is related to?**
/area api

## Issue details

Under the **Authoring stacks** heading there are subheadings:

```
Authoring stacks
   \- Adding schema version
   \- Adding a name
   \- Adding projects
   ...
```

There should be one:  "Adding devfile variables" and it should describe the rules (that only string-typed fields allow this substitution, and not free-form attribute typed fields, etc.)

**Comment by schultzp2020** [comment]
N/A after landing page redesign
