### ISSUE TITLE
Onboard Registry Viewer to registry.devfile.io

### ISSUE THREAD

**Issue by maysunfaisal** [devfile/api#534]
/kind user-story

**Which area this user story is related to?**

/area registry

## User Story
The [registry viewer](https://github.com/devfile/registry-viewer) would need to be hosted at registry.devfile.io. Since the index endpoint is served at registry.devfile.io as well, we should serve the website when default (anything other than HTML and json) or html is requested, and the index json when json contents are requested

The registry viewer website could also be hosted on the same container running the index server `devfile-index-base`, since it is lightweight and we want to reduce the cost of maintaining two containers and can hold the logic for serving the appropriate content. The viewer and the registry will have the same update lifecycle.

## Acceptance Criteria

- [ ] Create a Dockerfile layer that hosts the registry-viewer for the index server to interact with (@schultzp2020 )
- [ ] It should serve the appropriate content requested, html vs json (serve HTML for anything other than json on the request)
- [ ] Verify existing tools, e.g. odo, to make sure we don't introduce breakage to the existing product
- [ ] Ensure the registry library/tool providers are working as expected, as registry.devfile.io is expected to host the viewer
- [ ] Tekton pipelines and route definitions for staging/prod may need to be updated if it's exposed on a new port

Post:
- [ ]  It should trigger the registry-support push next image workflow via a DISPATCH event (perhaps with a workflow on a new release)

Related Issue: https://github.com/devfile/api/issues/527

**Comment by elsony** [comment]
Added new/updated requirements in the feature description

**Comment by maysunfaisal** [comment]
Summary:
`/ `  redirects depending on the content header; JSON to `/index` and HTML to `/viewer`
`/devfiles` will remain unchanged
`/viewer` will host the registry-viewer

Base image needs to be ubi rather than any docker image because of SRE requirement(should not be on dockerhub), may use https://catalog.redhat.com/software/containers/ubi8/nodejs-14-minimal/6065b8e1b92fbda3a4c65d91?container-tabs=overview.

Port can be anything other than 8080 as the index server is hosted on it(NextJS defaults to 3000). We can use the NextJS Dockerfile as a guide to define our Dockerfile - https://nextjs.org/docs/deployment. This should reside in https://github.com/devfile/registry-support/blob/main/index/server/Dockerfile. (NOTE: All the static pages to reside on the Node server)

Make sure to start the server via the entrypoint https://github.com/devfile/registry-support/blob/main/index/server/entrypoint.sh
