### ISSUE TITLE
The index server shouldn't return `null` if no samples exist

### ISSUE THREAD

**Issue by johnmcollier** [devfile/api#540]
/kind bug

### Which area this bug is related to?
/area registry

## Bug Summary
The index server currently returns `null` if no samples are in the registry when the `/index/sample` endpoint is called:
```
johncollier@jcollier-mac ~ % curl https://devfile-registry-devfile-registry-redhat-production.apps.app-sre-prod-03.z5a2.p1.openshiftapps.com/index/sample
null
```

**To Reproduce:**
```
$ curl https://devfile-registry-devfile-registry-redhat-production.apps.app-sre-prod-03.z5a2.p1.openshiftapps.com/index/sample
null
```

## Expected behavior
Either an empty array should be returned instead, or perhaps a more proper error message than `null`.

**Comment by Horiodino** [comment]
hi how about I work on this issue and get some idea about the project :)
it is possible to provide the files where to make changes!

**Comment by michael-valdron** [comment]
> hi how about I work on this issue and get some idea about the project :) it is possible to provide the files where to make changes!

Hi @Horiodino,

Sounds good! We welcome your contribution to this issue!

Reviewing [index/server/pkg/server/endpoint.go](https://github.com/devfile/registry-support/blob/35722ec1cc6e5599afe88983d7ead4145d87c8c5/index/server/pkg/server/endpoint.go) would be a good starting point for resolving this bug. 

For more information refer to our [README](https://github.com/devfile/registry-support/blob/35722ec1cc6e5599afe88983d7ead4145d87c8c5/README.md) or reach out to us on our [community channel](https://kubernetes.slack.com/archives/C02SX9E5B55) (which I see you have joined) if you have any questions :smile:

**Comment by michael-valdron** [comment]
Completed with https://github.com/devfile/registry-support/pull/246
