### ISSUE TITLE
Boolean properties are not being overridden

### ISSUE THREAD

**Issue by kim-tsao** [devfile/api#545]
/kind bug

### Which area this bug is related to?

/area api

## What versions of software are you using?
N/A

## Bug Summary
**Describe the bug:**

I have a main devfile that contains parent overrides but some properties (`isDefault`, `hotReloadCapable`) under the `exec` command do not get overridden.  Similar observation for the `parallel` property under the `composite` command.  I wonder if there's an issue with merging boolean properties

**To Reproduce:**

1.  Main devfile: 
[Test_Parent1.yaml.zip](https://github.com/devfile/api/files/6833186/Test_Parent1.yaml.zip)

2.  Parent devfile:  
[Parent1.yaml.zip](https://github.com/devfile/api/files/6833190/Parent1.yaml.zip)

## Expected behavior

properties should be overridden to false

## Any logs, error output, screenshots etc? Provide the devfile that sees this bug, if applicable.

Here is the result of the flattenedParent in debug mode:

![image](https://user-images.githubusercontent.com/84398375/126005188-61d6e82b-1fc3-4efd-9b55-6b450415accd.png)
![image](https://user-images.githubusercontent.com/84398375/126005299-c4a858da-b466-44b7-bc97-366a36876a72.png)

## Additional context

**Any workaround?**

**Suggestion on how to fix the bug**

**Comment by kim-tsao** [comment]
I just ran a test that successfully overrode the boolean property `MountSources` under a container component.  The difference between that property and the others mentioned above is that it's a pointer to bool rather than just a bool itself.  
https://github.com/devfile/api/blob/cde1b99bb1c2639b78a816347d55837c80a91cf1/pkg/apis/workspaces/v1alpha2/component_container.go#L58

**Comment by kim-tsao** [comment]
This problem surfaces when trying to override a `true` value with a `false` value.  When a `false` value is set, it's evaluated as an empty value upon marshalling and subsequently omitted from the patch content since we are specifying the `omitempty` option on these properties.    We can fix it the same way `MountSources` was fixed from v1 to v2 by using boolean pointers but it will change the way clients access these values if they are relying on them.   

Affected properties are:

**Commands**

- apply/group/isDefault 
- composite/parallel 
- exec/hotReloadCapable 

**Components**

- container/dedicatedPod 
- [container, kubernetes, openshift]/endpoints/secure 
- volume/ephemeral




@kadel @amisevsk, do you know if `odo`, `che`, and `devworkspaces` will be impacted by these proposed changes?

**Comment by amisevsk** [comment]
DWO would probably be impacted but it's a transparent change to the end-user so I'm fine with doing necessary updates when we bump our dependency.

**Comment by kadel** [comment]
odo will be in the same situation as DWO. When odo updates to this it will require a few changes, but it will be all straight forward I don't expect any big issues on odo side with this.

**Comment by amisevsk** [comment]
> any thoughts on this approach?

I think a getter method is the wrong approach, as we almost never see this sort of thing in Go. From a k8s API perspective, there are already multiple places where dealing with pointers to base types are used -- it's just the tedium that comes with how serialization is implemented in Go. I can understand however that it's more of a problem for odo, etc., where the k8s api doesn't fill defaults during processing.

Would dropping `omitempty` from the json tag be a valid workaround?

**Comment by kim-tsao** [comment]
@amisevsk, [Effective Go](https://golang.org/doc/effective_go) explains that getters can be used when necessary, but we should be looking to implement them for private fields.   I did look into removing `omitempty` on straight booleans but that broke the parent override scenario where an unset, default value of `false` could override a parent value.  I believe overrides were intended to operate on explicitly set values so this would not work.

**Comment by kim-tsao** [comment]
The K8s implementation for setting default values is to use `defaulting functions` which get called during deserialization (ref: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api_changes.md#edit-defaultsgo) This seems to be a pretty big change if we were to adopt something similar so at this point, maybe it's best to separate out the two issues and just fix the override bug that was originally reported.  We can track the setting of default values in a separate issue so we can continue to mull over it.

**Comment by kim-tsao** [comment]
I need to make corresponding changes to the library
