### ISSUE TITLE
Update registry readiness probe and liveness probe

### ISSUE THREAD

**Issue by GeekArthur** [devfile/api#554]
/kind bug

### Which area this bug is related to?

/area registry

## What versions of software are you using?

**Operating System:** Mac OS 11.4

**Go Pkg Version:** go version go1.16.4 darwin/amd64

## Bug Summary
**Describe the bug:**

Currently we use `/` for registry readiness probe and liveness probe, this can pollute the telemetry as `/` points to either registry viewer or index and that should be tracked for telemetry.

**To Reproduce:**

Check registry server log, `/` is pinned periodically for readiness probe and liveness probe.

## Expected behavior

We should use `/health` for readiness probe and liveness probe instead. We might need to do the changes on multiple places (eg. helm chart, openshift templates, operator), I will let @johnmcollier to double confirm this.

## Additional context

**Any workaround?**

**Suggestion on how to fix the bug**

**Comment by johnmcollier** [comment]
This can be closed 🙂
