### ISSUE TITLE
Allow querying of individual devfile JSON.

### ISSUE THREAD

**Issue by schultzp2020** [devfile/api#562]
**Which area this feature is related to?**

/area api

## Which functionality do you think we should add?
Allow querying of individual devfile JSON.

**Why is this needed? Is your feature request related to a problem?**
This will allow a more efficient build process of the registry viewer. In addition, if we support `/index/all` we should support individual querying.

**Detailed description:**
I want to be able to access the same information from https://registry.devfile.io/index/all but for individual devfiles.

## Describe the solution you'd like
If I want to access the `java-maven` JSON data I want to access it at `/index/java-maven`.

## Describe alternatives you've considered
N/A

## Additional context
N/A

**Comment by thepetk** [comment]
closing as rotten (created > 2 years). Feel free to re-open if it's not a requirement.
