### ISSUE TITLE
Expose validation rules in API docs

### ISSUE THREAD

**Issue by kim-tsao** [devfile/api#569]
**Which area this feature is related to?**

/area api

## Which functionality do you think we should add?

**Why is this needed? Is your feature request related to a problem?**

**Detailed description:**

We should detail the validation rules and expose them as part of the API docs.  Authoring a devfile based on the just [API reference](https://docs.devfile.io/devfile/2.1.0/user-guide/api-reference.html) can lead to a semantically incorrect format which will result in validation errors.

## Describe the solution you'd like

Update the API docs with the [validation rules](https://github.com/devfile/api/blob/main/pkg/validation/validation-rule.md) for each of the respective components.  This will improve the user experience since devfile authors will have the info in one place rather than having to reference two, disconnected sources.  

## Describe alternatives you've considered

None

**Comment by thepetk** [comment]
closing as rotten (created > 2 years). Feel free to re-open if it's not a requirement.
