### ISSUE TITLE
Devfile registry base images

### ISSUE THREAD

**Issue by l0rd** [devfile/api#574]
**Which area this feature is related to?**

/area registry

## Which functionality do you think we should add?

The first devfiles should probably be vendor neutral. Using images that work on vanilla Kubernetes but that are not optimized for a specific vendor cloud as UBI or AL2 images. Implmenting vendor specific devfiles are important too but those should be contributed by the specific vendor and as a community we should prioritize a vendors over community images.

**Comment by l0rd** [comment]
related to https://github.com/devfile/api/issues/570

**Comment by Jdubrick** [comment]
Moving to refinement to hear teams thoughts.

**Comment by thepetk** [comment]
closing as rotten (created > 2 years). Feel free to re-open if it's not a requirement.
