### ISSUE TITLE
Registry index server should support non root paths for sample devfiles

### ISSUE THREAD

**Issue by maysunfaisal** [devfile/api#575]
**Which area this feature is related to?**

/area registry

## Which functionality do you think we should add?

**Why is this needed? Is your feature request related to a problem?**
https://github.com/devfile/registry-support/pull/74 supports fetching a sample devifle from the root dir but Console Devfile Import supports cases where devfile is not in the root dir of a project repo like https://github.com/maysunfaisal/node-bulletin-board-5/tree/main/app

**Detailed description:**
Devfiles dont necessarily need to be in the root dir of a project repo, they can be anywhere in a git repo. We should ideally handle such cases.

## Describe the solution you'd like

Console has a field `context` on the import form to search for the devfile and the same idea can be adopted for the extra devfiles yaml entry

![Screen Shot 2020-12-09 at 2 59 23 PM](https://user-images.githubusercontent.com/31771087/128243114-c7db3c8e-7002-42aa-b81a-cce47a606ab3.png)

## Describe alternatives you've considered

N/A

**Comment by johnmcollier** [comment]
I think I remember we discussed this briefly earlier...

It'd be nice if we didn't have to search the entire subtree of the devfile sample to find the devfile.yaml. What if we add an entry to the `extraDevfilesEntry.yaml` that contains the devfile path? (Kind of like how the `icon` entry can point to a local path in the sample for an icon)

**Comment by thepetk** [comment]
closing as rotten (created > 2 years). Feel free to re-open if it's not a requirement.
