### ISSUE TITLE
Registry Viewer should allow filtering of devfiles via arch

### ISSUE THREAD

**Issue by maysunfaisal** [devfile/api#576]
**Which area this feature is related to?**

/area registry-viewer

## Which functionality do you think we should add?

**Why is this needed? Is your feature request related to a problem?**
Viewer should filter devfiles via arch

**Detailed description:**
Since the multi arch feature is delivered via https://github.com/devfile/api/issues/244; viewer should now let users filter via arch

## Describe the solution you'd like

Just like Stack/Sample and Tags, viewer should have an option for Archs.

## Additional context

Blocked by https://github.com/devfile/api/issues/566

**Comment by schultzp2020** [comment]
This issue should be fixed when the registry viewer design is updated

**Comment by michael-valdron** [comment]
This does not seem to be implemented yet, will leave this open as an upcoming addition. #959 would be useful to couple with this feature.

**Comment by thepetk** [comment]
closing as rotten (created > 2 years). Feel free to re-open if it's not a requirement.
