### ISSUE TITLE
Requirements of a "Devfile Registry"?

### ISSUE THREAD

**Issue by johnmcollier** [devfile/api#58]
This is something that I've been thinking about for a while, and haven't really been able to find concrete answers on. As there will be multiple consumers of devfile registries (Che, Odo, Codewind), we need to standardize/document what requirements we impose on both a devfile registry, as well as its consumers, so that a user could point Che, Odo, etc at one, and have it properly work across all of them.

Generally, a devfile registry consists of a simple HTTP server, devfiles, and an index.json linking to those devfiles. But there's some unanswered things that need to be documented:
- What exactly does the index.json need to contain?
    - Is there a defined schema for it? What fields are required and which are optional?
    - Can it link to devfiles on external servers (maybe a separate issue)
- Is there a restriction on _where_ the devfiles need to be hosted on the server?
    - On Che's devfile registry, the index.json and devfiles are hosted under `/devfiles`
- What metadata is required?
    - The Che devfile registry has a `meta.yaml` for each devfile. What requirements are imposed there?
        - Is there a schema for it?
    - Devfile v2 will have an expanded metadata field. Will metadata be pulled from there instead?

**Comment by GeekArthur** [comment]
I wonder currently do we have a place to host the existing definitions of `meta.yaml` and `index.json`?

**Comment by elsony** [comment]
I mark this as close since it looks like we have resolved all these in the existing devfile registry design already.
