### ISSUE TITLE
More consistent devfile descriptions

### ISSUE THREAD

**Issue by deboer-tim** [devfile/api#581]
/kind bug

### Which area this bug is related to?
> /area registry

## Bug Summary
**Describe the bug:**
For the current descriptions of the stacks & samples in the community devfile registry:
 - a couple have very short descriptions (e.g. "Upstream WildFly")
 - some are inconsistent with each other (e.g. "Python3.7 with Django" vs "Python Stack with Python 3.7")
 - some are full sentences ("A simple Hello World ..."), others aren't.
 - some use 'stack' or 'sample', others don't.

Can we do a quick pass at cleaning these up/making them a little more consistent? IMHO:
- we should set a rough precedent for the length and content (more than a few words, no more than a sentence?), whether version numbers should be included, etc.
- we shouldn't use the term 'upstream' (because that implies Red Hat downstream).
- we shouldn't use the term stack/sample in the description, since that's already implied (and shown on the tiles in the viewer).

**Edit by thepetk**:
Targeted date: 16/03/2023

**Comment by elsony** [comment]
While we are visiting this, it will be good to provide more info on the description, e.g. version of runtime

**Comment by thepetk** [comment]
If there is no objection I'm going to create a PR for those descriptions based on the following guidelines:
- The length of the description, is nice to be around a sentence.
- In this sentence try not to repeat unnecessary things (for example not having the title as a description)
- Try to include important information as much as possible (e.g. version of runtime).
- Check for any inconsistent description (for example wrong version number etc)

**Comment by thepetk** [comment]
Update
1) A fix was applied to [nodeshift-starters/devfile-sample](https://github.com/nodeshift-starters/devfile-sample/pull/24) and the readme of the sample is now up-to-date for the Express version
2) All requested changes have been resolved for the [PR which updates the stack descriptions](https://github.com/devfile/registry/pull/163)

**Comment by thepetk** [comment]
Update all of the review items have been resolved, the last PR is under review
