### ISSUE TITLE
Inconsistent error handling for validation scenarios

### ISSUE THREAD

**Issue by kim-tsao** [devfile/api#583]
/kind bug

### Which area this bug is related to?

> /area api

## What versions of software are you using?
N/A

## Bug Summary
**Describe the bug:**

While working through some negative path scenarios, I noticed some areas of validation returns the first error found while others returns a list.   For example, [commands.go](https://github.com/devfile/api/blob/4f7b6856e70a3d716d5911a2affed6830de1fd8f/pkg/validation/commands.go#L28) returns the first error found while [projects.go ](https://github.com/devfile/api/blob/4f7b6856e70a3d716d5911a2affed6830de1fd8f/pkg/validation/projects.go#L91-L96) returns a collection of error messages.  All this leads to an inconsistent display of error messages when calling [ValidateDevfileData](https://github.com/devfile/library/blob/9de9d4cb6be700bac3a55d3dc3a42dda67e5a072/pkg/devfile/validate/validate.go#L13).  You can wind up with a list of error message from commands, components, projects, etc but not all objects will contain the full validation results which can lead to a bad UX if an end user fixes one error then encounters a new one when re-validating

**To Reproduce:**

Here is a file with 4 errors in total; 2 errors in the commands section and 2 under projects

[Test_Command_errors.yaml.zip](https://github.com/devfile/api/files/6963150/Test_Command_errors.yaml.zip)

I only see 3 error messages:
```
=== RUN   Test_Command_Errors
    test_utils.go:341: [..... ERROR : Error validating testDevfile the command "testapplyparentcommand1" is invalid - command does not map to a container component
        error validating projects:
        project petclinic has more than one remote defined, but has no checkoutfrom remote defined
        unable to find the checkout remote origin2 in the remotes for project petclinic2 ]
```

## Expected behavior

I'm expecting the following error message for the composite command error:
`the command "test" is invalid - the command "testapplyparentcommand" mentioned in the composite command does not exist in the devfile`

## Additional context

N/A

**Any workaround?**

None 
**Suggestion on how to fix the bug**

Use a similar approach to what's being done in projects.go.  This may affect other properties aside from the ones mentioned above so some additional investigation is needed.

**Comment by kim-tsao** [comment]
I like the solution that was discussed in this [issue](https://github.com/devfile/api/issues/577#issuecomment-896172384).  We should look at adopting this approach so we can be consistent.

**Comment by yangcao77** [comment]
This issue has been done by https://github.com/devfile/api/issues/577
