### ISSUE TITLE
Onboarding process and requirements of the product registry documentation

### ISSUE THREAD

**Issue by elsony** [devfile/api#593]
/area documentation

**Which area this documentation change is related to?**
/area registry

## Issue details
Add documentation to describe the onboarding process and requirements of the product registry documentation. This will help any stack provider to onboard new stacks or update existing stacks in the product registry.

**What mistake did you find / what is missing in the documentation?**
see issue details.

**Comment by johnmcollier** [comment]
Contributing.MD added in https://github.com/redhat-developer/devfile-registry/pull/8
