### ISSUE TITLE
Update links in landing page and getting started info

### ISSUE THREAD

**Issue by elsony** [devfile/api#594]
**Which area/kind this issue is related to?**
/area registry
/area documentation

## Issue Description
Update the landing page with the latest content from the landing page content doc: https://docs.google.com/document/d/1-lSyhEzLaElt2_cGH93vSnOr5nP04f4co8AkywbCsSE/edit#. This item includes changes:

1. All the links and text on the "getting started" section for different personas on the "Getting Started" page.
2. Change "Why Devfiles?" to "Why devfiles?" on the landing page
3. Update footer links as specified in the footer section on the landing page doc
4. Change the Github link at the top right corner of the landing page to: https://github.com/devfile/api

**Comment by maysunfaisal** [comment]
delivered
