### ISSUE TITLE
Can't link to specific documentation

### ISSUE THREAD

**Issue by deboer-tim** [devfile/api#597]
/kind bug

### Which area this bug is related to?
Documentation on the website

## Bug Summary
**Describe the bug:**
There are currently 4 main areas (personnas) in the docs, each with a "Why devfiles" and "Getting Started" section. As you go to each page the URL is updated, but all of the "Why devfiles" sections have the same URL, and all of the "Getting Started" have the same URL. i.e. there are only 2 urls.

If you copy and paste the URL (or send it to someone, etc.) it always reverts to the first page.

**To Reproduce:**
Step through the pages and look at the URL changing between the two. Copy the URL when you're on a "Getting Started" page and go to another tab. If you paste the URL, it'll revert to the first "Why devfiles" page.

## Expected behavior
Each page in the docs should have a unique URL, and if you copy/paste it should go back to the same page.

**Comment by schultzp2020** [comment]
N/A after landing page redesign
