### ISSUE TITLE
Source types are not randomly generated for project tests 

### ISSUE THREAD

**Issue by kim-tsao** [devfile/api#600]
/kind bug

### Which area this bug is related to?

/area test-automation

## Bug Summary
**Describe the bug:**

Random coverage of Project/StarterProject tests is broken.  The problem is, there's only 2 types of ProjectSources we're testing; Git and Zip and the issue is with the way GetRandomNumber is called:

https://github.com/devfile/api/blob/9227ef221c8404de0ddc3d3df38e3b01761f2325/test/v200/utils/common/test_utils.go#L328

GetRandomNumber does not handle this case very well since it'll call `rand.Intn(0)` which results in the same index being returned all the time.  

https://github.com/devfile/api/blob/9227ef221c8404de0ddc3d3df38e3b01761f2325/test/v200/utils/common/test_utils.go#L284

**To Reproduce:**

## Expected behavior

Coverage of both Zip and Git types

## Additional context

The problem can be easily fixed by specifying min=0 but this does not align with the function description which says a number between 1 and max will be returned.

 
**Any workaround?**

**Suggestion on how to fix the bug**

**Comment by thepetk** [comment]
closing as rotten (created > 2 years). Feel free to re-open if it's not a requirement.
