### ISSUE TITLE
add provider/supportURL information to stacks/samples

### ISSUE THREAD

**Issue by yangcao77** [devfile/api#608]
**Which area this feature is related to?**

/area registry

## Which functionality do you think we should add?

**Why is this needed? Is your feature request related to a problem?**
This is a blocker for https://github.com/devfile/api/issues/539

**Detailed description:**

- [x] Create support doc for stacks & samples we own, stacks/samples within `devfile-samples`, and the following stacks hosted at devfile registry: 

- go
- java-maven
- Java-springboot 
- nodejs-angular
- nodejs-nextjs
- nodejs-nuxtjs
- nodejs-react
- nodejs-svelte
- nodejs-vue
- php-laravel
- Python
- Python-django

- [ ] Update devfiles in stack/samples we owned to include provider & supportURL information
- [x] Update registry index content to include provider field. (registry-viewer will need this information to create filter)

## Describe the solution you'd like

a new repo will be created under devfile-samples org, `devfile-samples/support`.  The repo will be used to track issues on stacks/samples we own. 
The support information will be stored in this repo's readme.

**Comment by yangcao77** [comment]
repo created under devfile-samples for issue tracking: https://github.com/devfile-samples/support

**Comment by yangcao77** [comment]
provider and supportURL information has been added to samples:
https://github.com/nodeshift-starters/devfile-sample.git
https://github.com/devfile-samples/devfile-sample-code-with-quarkus.git
https://github.com/devfile-samples/devfile-sample-java-springboot-basic.git
https://github.com/devfile-samples/devfile-sample-python-basic.git

and registry index for samples: https://github.com/devfile/registry/blob/main/extraDevfileEntries.yaml

**Comment by thepetk** [comment]
closing as rotten (created > 2 years). Feel free to re-open if it's not a requirement.
