### ISSUE TITLE
allow `.devfile.yaml`

### ISSUE THREAD

**Issue by maxandersen** [devfile/api#61]
(not sure if this is part of kubernets-api for devfile but it should for sure be part of the devfile spec - let me know if any better place this issue)

originally opened at https://github.com/openshift/odo/issues/3126 and https://github.com/openshift/odo/issues/3126

Simply asking that `.devfile.yaml` should be allowed for the name of the devfile to allow it to be hidden by default and not take up "visual space" in projects that create these files.

**Comment by sbose78** [comment]
Ack.

**Comment by metacosm** [comment]
@maxandersen you linked to the same 2 issues… 😄 
That said, I'm ambivalent on this since I'm not sure the devfile should be hidden as it's potentially an integral part of the project.

**Comment by l0rd** [comment]
That's not strictly speaking something that will be transled in a change in the OpenAPI spec. And Che at least already allow `.devfile.yaml` if the file is specified explicitely but it doesn't automatically discover it (it discovers `devfil.yaml`). 

But I agree that we may formalize that in the spec somehow: tools that supports the spec should automatically discover `devfile.yaml` and `.devfile.yaml` when a git repo or a local folder is provided.

**Comment by kadel** [comment]
> But I agree that we may formalize that in the spec somehow: tools that supports the spec should automatically discover `devfile.yaml` and `.devfile.yaml` when a git repo or a local folder is provided.

If we formalize that than we need to also define that tools need to error out when both `.devfile.yaml` and `devfile.yaml` are present.

**Comment by l0rd** [comment]
> if we formalize that than we need to also define that tools need to error out when both `.devfile.yaml` and `devfile.yaml` are present.

Right. Or define a precedence order.

**Comment by kadel** [comment]
> Right. Or define a precedence order.

That will just lead to a lot of confusion

Let's say that I have a project that uses `.devfile.yaml`
- Someone doesn't notice that there already is `.devfile.yaml` and adds new `devfile.yaml`
- Now there are two devfiles and each might be different.
- If tooling just priorities `devfile.yaml` over `.devfile.yaml` the users that are used to editing `.devfile.yaml` will get confused about why their changes are not being reflected or vice versa.

This won't create a good user experience.
I think that erroring out in case of both devfile naming styles is present is the only way to make sure that there is no ambiguity or confusion.

**Comment by l0rd** [comment]
> I think that erroring out in case of both devfile naming styles is present is the only way to make sure that there is no ambiguity or confusion.

You convinced me 👍

**Comment by maxandersen** [comment]
I would just print a warning rather than blocking users and error out.

But I'm fine either way.

**Comment by maxandersen** [comment]
Treat it the same as if you had a devfile.yml.

**Comment by gorkem** [comment]
I see a new PR on Che https://github.com/eclipse/che/pull/17537

**Comment by rkratky** [comment]
@l0rd, what is the documentation tasks here (I see you added the `area/documentation` label)?

**Comment by l0rd** [comment]
@rkratky probably adding a paragraph about that in the [devfile author guide](https://devfile.github.io/devfile/assembly_making-a-workspace-portable-using-a-devfile.html)

**Comment by elsony** [comment]
Based on the discussions, we'll support the .devfile.yaml. If both devfile.yaml and .devfile.yaml exists, then the tools will error out and let the user know that both files exist. We treat it as an error instead of a warning is to avoid any potential confusion on the user.

From the spec perspective, we'll:
1. add to the doc to specify this behaviour
2. check if the common library accepts a path (instead of including the devfile.yaml itself), then the parser will error out if both the devfile.yaml and .devfile.yaml exists at the specified path

**Comment by elsony** [comment]
@maysunfaisal pointed out that the existing devfile library does not currently have limitations on the devfile file name as long as it has the `.yaml` extension. I think it is fine to keep it that way to provide flexibility on the library code.

Having said that, we still need to make changes to support this on the registry library/registry build tools. We currently have to find the location of the devfile when building the index.jsp as part of scanning through the list of stacks. So the index.jsp build tools will need to look for either devfile.yaml or .devfile.yaml and flag as an error on the stack if both files are found in the registry as part of the index.jsp generation that is being run as part of the registry build tools. 

@GeekArthur Can you make the change on the registry index generator code?

**Comment by GeekArthur** [comment]
@elsony Sure, I can do that.
