### ISSUE TITLE
Create/refactor common test utils

### ISSUE THREAD

**Issue by kim-tsao** [devfile/api#623]
**Which area/kind this issue is related to?**

> /area library

## Issue Description

@yangcao77 raised this during a [PR review](https://github.com/devfile/library/pull/115#discussion_r710266411).  The suggestion was to have common boolean variables under one file so our tests can reference them.  As it stands now, unit tests and functional/automation tests have their own separate utils.  We should review and ensure there's no duplication of utils elsewhere.

**Comment by thepetk** [comment]
closing as rotten (created > 2 years). Feel free to re-open if it's not a requirement.
