### ISSUE TITLE
Better docs headings

### ISSUE THREAD

**Issue by rkratky** [devfile/api#628]
/area documentation

**Which area this documentation change is related to?**

* Developer
* Using stacks

## Issue details

**What mistake did you find / what is missing in the documentation?**

* *Developer* heading needs to distinguish b/w 'devfile developer' (involved in developing the devfile project) and a developer who uses devfiles for their work on other projects.
* *Using stacks* is too generic. And the content is self-referential:

**_Using stacks_**

_Use the following documents to learn how to write a stack by using devfiles._

IOW, the premise of 'using stacks' is not satisfied. Instead, the user is told to _use the docs_ to learn how to _use devfiles_ to _write stacks_.

**Comment by schultzp2020** [comment]
fixed
