### ISSUE TITLE
Allow specifying k8s annotations and labels for generated Deployments and other resources

### ISSUE THREAD

**Issue by kadel** [devfile/api#632]
**Which area this feature is related to?**
/area api
/area library

## Which functionality do you think we should add?

Add a way to define annotations and labels that should be applied to the generated Kubernetes resources.

In some cases annotations or labels can be application's functional requirement. In that case it should be defined in devfile.

**Why is this needed? Is your feature request related to a problem?**

In some cases it is required to add annotations or labels to the resources.
For example can Istio, requires Deployments to have `sidecar.istio.io/inject: "true"` annotation. 
Labels might be usefull ofr external visualizers, cleaners and other tools.

Related feature request for odo https://github.com/openshift/odo/issues/2623

**Comment by yangcao77** [comment]
we can use attributes with keys pre-defined in devfile ap, e.g. `api.devfile.io/resource-annotation`
we can either add the same annotation to all resources, or have different key names for different resource annotation, `api.devfile.io/deployment-annotation` / `api.devfile.io/service-annotation` etc. 
@kadel @elsony  any thoughts?

**Comment by kadel** [comment]
> I have a question about how this will work. For example, in the DevWorkspace Operator, we're required to maintain sync between the Devfile and the deployment it represents. Adding the istio annotation breaks that assumption, as istio will have to modify the deployment to inject sidecars and could cause conflicts.
> 

This is quite a common problem. Odo already had the similar problem with Service Biding Operator that injects volumes and environment variables into the Deployment.

> How is this handled in other applications (e.g. `odo`)?

The solution is to use [server side apply](https://kubernetes.io/docs/reference/using-api/server-side-apply/).
With this you don't keep everything in sync, but only the fields that you care about. In our case, only fields that are defined in devfile.yaml.

**Comment by amisevsk** [comment]
Sadly, I don't think server-side apply is supported in the controller runtime, but that makes sense.

**Comment by kadel** [comment]
> Sadly, I don't think server-side apply is supported in the controller runtime, but that makes sense.

I think that operators pattern was the main reason this was added to api.
I have never worked with controller runtime, but I would be surprised if this is not there. In client-go it is just `Patch` call with `ApplyPatchType`

**Comment by yangcao77** [comment]
As discussed in today's call, we changed the proposal to have container level annotation defines deployment & service annotation, and move ingress/route annotation to endpoint level.
Since currently we have all containers defined within same pod share the same service. In the future, if we want to have multiple services for a save pod, we can add service annotation to endpoint level, which takes priority to container level service annotation and overwrites it when generating the service resource spec. 


```
type Annotation struct {
	Deployment    map[string]string
	Service    map[string]string
}
```

Example of a valid case:
```
components:
- name: runtime
  container:
    annotation:
      deployment:
          key1: value1
          key2: value2     
      service: 
          key1: value1
    image: registry.access.redhat.com/ubi8/nodejs-12:1-45
    endpoints:
    - name: http-8888
      targetPort: 8888
      annotation:
          key3: value3
```
