### ISSUE TITLE
Update Registry Ingress for Charts & Operator

### ISSUE THREAD

**Issue by maysunfaisal** [devfile/api#636]
**Which area/kind this issue is related to?**

/area registry

## Issue Description

Ingress, CRD and other Kube resources have had their previous Kube APIs deprecated and later removed from the latest Kube version.

The registry charts and operator needs to be updated to reflect this to enable installing the registry on the latest Kube

More info: https://kubernetes.io/blog/2021/07/14/upcoming-changes-in-kubernetes-1-22/

**Comment by michael-valdron** [comment]
Closing since it was already marked as done in Sprint 208.
