### ISSUE TITLE
missing description for cpuLimit, cpuRequest, memoryLimit, MemoryRequest 

### ISSUE THREAD

**Issue by kadel** [devfile/api#640]
/kind bug

/area api

## Bug Summary

cpuLimit, cpuRequest, memoryLimit, MemoryRequest don't have any description in JSON schema

https://github.com/devfile/api/blob/e38e88c50482f0619639dce90eeb17447822816e/schemas/latest/devfile.json#L283-L287

## Expected behavior

Every field in Devfile schema should have description what it is for and what values are expected.
Resource related fields are `strings` but they need to have a specific format this all should be mentioned in description

**Comment by thepetk** [comment]
closing as rotten (created > 2 years). Feel free to re-open if it's not a requirement.
