### ISSUE TITLE
Mount a given volume in all containers when declaring a volume

### ISSUE THREAD

**Issue by benoitf** [devfile/api#644]
**Which area this feature is related to?**

As a user, sometimes I want to add inside a DevWorkspaceTemplate a volume and I want that this volume be available in all the containers of my workspace pod, without having to explicitly adds a volueMount/mountPath in all containers.

> /area api
> /area devworkspace

## Which functionality do you think we should add?
Add attribute on a volume to say this volume should be added/available on all containers

**Why is this needed? Is your feature request related to a problem?**

**Detailed description:**

## Describe the solution you'd like
It could be an attribute inside the volume definition

## Describe alternatives you've considered
Specific attribute name in the implementation

## Additional context
Some DevWorkspaceTemplate or parent devfile may want to declare specific volumes that should be added in all containers without every component to declare the volumeMount

**Comment by thepetk** [comment]
closing as rotten (created > 2 years). Feel free to re-open if it's not a requirement.
