### ISSUE TITLE
Telemetry: client tracking on registry usage

### ISSUE THREAD

**Issue by elsony** [devfile/api#646]
**Which area this feature is related to?**
/area registry

## Which functionality do you think we should add?
Add telemetry client tracking for different clients so that we can keep track on the clients who make the requests to the devfile registries.

**Detailed description:**
Clients to cover includes:
* odo
* registry viewer
* dev console

## Describe the solution you'd like
Add request header when making queries to the devfile registries on the client code. 

## Describe alternatives you've considered
N/A

## Additional context
N/A

**Comment by kim-tsao** [comment]
Registry Viewer issue: https://github.com/devfile/api/issues/678

**Comment by kim-tsao** [comment]
I'll consider this issue done and close it since the main telemetry work is done.  It's just a matter of updating the docs and bug fixing from now on.
