### ISSUE TITLE
use of devworkspace term in api-reference (json schema description)

### ISSUE THREAD

**Issue by kadel** [devfile/api#648]
/area documentation

Devfile api-reference/descriptipons fields in json schema mentions devworkspace  and IDE in a few places (for example apply command or events).
The main purpose for devfile is to be tool independent format. The specification description should try to avoid mentioning tools.

Every field in spec should have description of its purpose that uses just generic well known developer terminology or kubernetes terms. Mapping this description to tool specific behavior should be job of the given specification implementation (currently devfile/library and devworkspace-operator) 

/area api

**Comment by thepetk** [comment]
closing as rotten (created > 2 years). Feel free to re-open if it's not a requirement.
