### ISSUE TITLE
Registry Viewer - Banner is still displayed when turned off

### ISSUE THREAD

**Issue by schultzp2020** [devfile/api#653]
/kind bug

### Which area this bug is related to?
/area registry

## What versions of software are you using?
Chrome/Firefox

## Bug Summary
Banner is still technically displayed when the env var is turned on. (I suspect its a build issue and not a registry viewer issue)

**To Reproduce:**
Enable the env var `DEVFILE_BANNER`.

## Expected behavior
The banner should not take up space when enabled.

## Any logs, error output, screenshots etc? Provide the devfile that sees this bug, if applicable.
![image](https://user-images.githubusercontent.com/52387464/138123796-6db7ded5-c4a3-4019-871d-2e9a186b66ec.png)

**Comment by schultzp2020** [comment]
This issue should be fixed when the registry viewer design is updated

**Comment by michael-valdron** [comment]
@schultzp2020 Has this been resolved with the redesign?

**Comment by schultzp2020** [comment]
@michael-valdron yes

**Comment by michael-valdron** [comment]
> @michael-valdron yes

In that case I'll close this issue now.
