### ISSUE TITLE
Registry Viewer - Add GitHub like popup for copy button

### ISSUE THREAD

**Issue by schultzp2020** [devfile/api#654]
**Which area this feature is related to?**
/area registry

## Which functionality do you think we should add?
Add popup for the copy button. For [reference](https://lh6.googleusercontent.com/fzJRMFl0Vl39iDPmCi56HDwF5C5koLtK23D4HJOF4K5rqzm8ScvTlwRGd9qunja0xwAX3zkP2QeI_m7zzz21Zf14rFK-w10YaaO-g04vI5yfJpxRNq7Zz7m8Mz9RaavjeSEHMmnSilrw2A0PPSvYe3TT_Oah9RiXg9_Vuuu_WTmXi1ZjWGZL-_ySyhV91YxdNMq2yVZ1ZANuxNmA7kvRr9iqVIQnzqIq8tzbCn5KGbJKFEG4AkogENTfuSY6wx2pujzJTW3USE8X-fQN=w512).

**Comment by schultzp2020** [comment]
This issue should be fixed when the registry viewer design is updated

**Comment by michael-valdron** [comment]
This feature was added in #916
