### ISSUE TITLE
Link friendly API Reference

### ISSUE THREAD

**Issue by kadel** [devfile/api#657]
/area documentation

## Issue details

https://devfile.io/docs/devfile/2.1.0/user-guide/api-reference.html

Recently, I've been helping a few people to understand Devfile and its structure. 
The [API Reference](https://devfile.io/docs/devfile/2.1.0/user-guide/api-reference.html) is great for tool for helping people to understand  Devfile structure. 
One problem that I was having with it is that I can't send links to a specific field.
It would be great if we could find a way how to add an anchor to each field  so we can send link to a specific field.

**Comment by kadel** [comment]
I'm hitting this issue more and more often :-(
@jc-berger do you when you will be able to look into this?
If you are busy with other stuff I might try looking into this.

**Comment by jc-berger** [comment]
@kadel thanks for bringing this back to my attention. Yes, I'm busy with other doc PRs and issues now. However, we did recently raise a PR for Antora changes to fix the 404 error for the API: https://github.com/devfile/docs/pull/121 

Would any of this work be helpful for sending links to specific fields?

**Comment by kadel** [comment]
> Would any of this work be helpful for sending links to specific fields?

I'm afraid that this won't help with that.

I haven't looked into the code yet. But if I remember correctly the API reference page is not generated by Antora. Something else generates it, and then it is embedded using `iframe` into the page. This is not ideal, but `iframe` is not the problem I have with it.
Problem is that the actual HTML page describing fields doesn't have anchors (`<a name="xxx">`) for fields. So it is impossible to direct someone to a specific field.

**Comment by jc-berger** [comment]
Got it, Tomas, thanks. I can redirect my focus to this issue if time permit, I have a planning meeting tomorrow.

**Comment by schultzp2020** [comment]
This has been added in the landing page redesign

**Comment by kadel** [comment]
The new site design and especially the new API reference page are great!
It is much better, especially the examples on the right side of the api-referene page helps a lot with understanding devfile structure
