### ISSUE TITLE
Move Dev Console to use the live devfile registry

### ISSUE THREAD

**Issue by elsony** [devfile/api#658]
**Which area this feature is related to?**
/area library

## Which functionality do you think we should add?
The current devfile sample dev preview of ODC is using a hardcoded list of samples. This item will move the backend of the ODC to start doing live queries on the community devfile registry (https://registry.devfile.io/). 

**Why is this needed? Is your feature request related to a problem?**
This is part of the phased implementation of the devfile dev preview support in ODC. The registry support on samples was not available yet at the time when the dev preview was first implemented. Moving to registry support will allow ODC to reflect the latest samples from the registry.

**Detailed description:**
See above

## Describe the solution you'd like
This item includes:

- [x] Changing the backend of ODC to do a live query on a provided list of devfile registry, the API will merge the results to provide a single merged list of devfile entries to the caller
- [x] Moving the ODC devfile sample in devfile-samples org to start using devfile 2.2 and make it devfile 2.2 compliant
- [x] Moving to the latest devfile library that has both devfile 2.2 support
- [x] Propagate the provider information (new in devfile 2.2 spec) to the ODC which currently has UI to provide that information (odc issue to track: https://github.com/openshift/console/issues/10664)
- [ ] Change the samples to reference the parent stacks instead of keeping a copy of the parent devfile (https://github.com/devfile/api/issues/715)

## Describe alternatives you've considered
Currently using a hardcoded list of sample

**Comment by elsony** [comment]
PR on ODC backend work: https://github.com/openshift/console/pull/10394

**Comment by johnmcollier** [comment]
Closing since #715 is used to track the remaining piece
