### ISSUE TITLE
Investigate telemetry for the registry viewer

### ISSUE THREAD

**Issue by johnmcollier** [devfile/api#659]
/kind user-story

**Which area this user story is related to?**

/area registry

## User Story
As discussed on today's call, the existing telemetry implementation for the devfile registry cannot collect information from the viewer, only from the registry API. As the registry viewer caches results from the registry API and generates the pages from those cached results, our registry API telemetry cannot give us any meaningful insight into the usage of the registry viewer.

We should investigate:
- [ ] If we need specific telemetry for the registry viewer (is there significant value in doing so?)
- [ ] What the telemetry would look like / what would be collected.
- [ ] How it would be implemented

**Comment by kim-tsao** [comment]
Segment has a javascript library that we can look at using: https://segment.com/docs/connections/sources/catalog/libraries/website/javascript/quickstart/

I know we talked about some scenarios being more valuable than others but it might be worthwhile to collect both types if our intention is to track what the user behaviour/interaction is.  For example, we could use the metrics to determine what % of users are using the registry viewer for browsing/listing vs copying/downloading.
