### ISSUE TITLE
Update registry operator docs to mention required operator-sdk version

### ISSUE THREAD

**Issue by dharmit** [devfile/api#662]
/kind bug

### Which area this bug is related to?

/area registry

## What versions of software are you using?

**Operating System:** Fedora 34

**Go Pkg Version:** How do I find this? Which go package's version are you asking for?

## Bug Summary
**Describe the bug:**
On minikube 1.23.2 or OCP 4.9, `make install && make deploy` command to install the Registry Operator fails with below error:
```sh
$ make install && make deploy
/home/dshah/go/bin/controller-gen "crd:trivialVersions=true" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
/home/dshah/go/bin/kustomize build config/crd | kubectl apply -f -
error: unable to recognize "STDIN": no matches for kind "CustomResourceDefinition" in version "apiextensions.k8s.io/v1beta1"
make: *** [Makefile:63: install] Error 1
```

**To Reproduce:**
Get a latest minikube or CRC and try running `make install && make deploy` for Registry Operator on it.

## Expected behavior
Registry Operator installation to succeed.

## Additional context
https://kubernetes.io/docs/reference/using-api/deprecation-guide/#v1-22

**Target Date: 05-30-2023**

**Comment by kim-tsao** [comment]
We should get this updated as part of epic https://github.com/devfile/api/issues/1007

**Comment by michael-valdron** [comment]
Requirements for #1092 to close (changes being made in devfile/registry-operator#42) might resolve this issue. Operator SDK version requirement should be listed alongside the cluster version requirement.

**Comment by michael-valdron** [comment]
https://github.com/devfile/registry-operator/pull/42 has the required changes to close this issue, taking over this issue.

**Comment by michael-valdron** [comment]
Using this issue to track the addition of version requirements to the registry operator documentation.

These version requirements include:
- OpenShift
- Kubernetes
- Operator SDK
- Go Runtime

Please comment on this if anything additional should be added to this list.

**Comment by michael-valdron** [comment]
> **Describe the bug:** On minikube 1.23.2 or OCP 4.9, `make install && make deploy` command to install the 

The registry operator will now only support OCP 4.12 at the time of writing. Further support for newer OCP versions will be updated in the documentation.

We plan on adding a matrix document to best illustrate our version support of OCP and Kubernetes going forward.

**Comment by michael-valdron** [comment]
Extended target date due to other priority tasks and to provide additional time for review.

**Comment by michael-valdron** [comment]
A matrix document has been created to illustrate the registry operator support of container orchestration systems. The PR for this issue is now ready for re-review: https://github.com/devfile/registry-operator/pull/42

**Comment by michael-valdron** [comment]
Changes done to the documentation to tie in the Operator SDK versioning with the Kubernetes API versioning. The PR for this issue is now ready for re-review: https://github.com/devfile/registry-operator/pull/42

**Comment by michael-valdron** [comment]
> Changes done to the documentation to tie in the Operator SDK versioning with the Kubernetes API versioning. The PR for this issue is now ready for re-review: [devfile/registry-operator#42](https://github.com/devfile/registry-operator/pull/42)

Waiting on re-review of this PR, will extend into next sprint to provide more time for this.
