### ISSUE TITLE
Assess test coverage for union types

### ISSUE THREAD

**Issue by kim-tsao** [devfile/api#664]
**Which area/kind this issue is related to?**

/area test-automation

## Issue Description

We've introduced new union type (`ImageUnion`) for our 2.2 spec but our existing unit tests only cover one type.  We should ensure adequate coverage with other types that are missing.  
 
https://github.com/devfile/api/tree/main/pkg/utils/unions
https://github.com/devfile/api/blob/a313872749ed60b47fb015288bb6595df64dac33/pkg/apis/workspaces/v1alpha2/union_test.go

We should also update the override scenarios as well. 
https://github.com/devfile/api/blob/ff3c01bf82927e2936d66f31b93e9463f9be25b3/pkg/utils/overriding/overriding_test.go

**Comment by thepetk** [comment]
closing as rotten (created > 2 years). Feel free to re-open if it's not a requirement.
