### ISSUE TITLE
default value for `buildContext` in `image` component

### ISSUE THREAD

**Issue by kadel** [devfile/api#668]
/kind bug

### Which area this bug is related to?

/area api

## What versions of software are you using?

**Operating System:**

**Go Pkg Version:**

## Bug Summary
**Describe the bug:**
Currently, the default value for `buildContext` is defined as `${PROJECT_ROOT}` I don't think that this makes a good default value as this is related to 

The layout that we are promoting is that the `devfile.yaml` should be at the root of the project source code.

I think that the better default would be `./`. To indicate that the `buildContext` is the same as the directory where `devfile.yaml` is.

**Comment by thepetk** [comment]
closing as rotten (created > 2 years). Feel free to re-open if it's not a requirement.
