### ISSUE TITLE
Document environment variables that are used in devfile

### ISSUE THREAD

**Issue by kadel** [devfile/api#669]
/area documentation

**Which area this documentation change is related to?**

/area api

## Issue details

There should be a page describing special env variables that are used across the devfile like `PROJECT_ROOT` or `PROJECT_SOURCE`

**Comment by michael-valdron** [comment]
This could be a good candidate for #1080.

cc: @elsony

**Comment by thepetk** [comment]
closing as rotten (created > 2 years). Feel free to re-open if it's not a requirement.
