### ISSUE TITLE
Library is missing dedicatedPod support

### ISSUE THREAD

**Issue by yangcao77** [devfile/api#670]
/kind enhancement
/area library

## Summary
`dedicatedPod` is defined in devfile spec, for creating a separated pod for a single container component. 
devfile library currently does not support dedicatedPod. library need to support that if there is an actual use case turns that field on. 

generator for service/deployment should support `dedicatedPod` and returns a list of services & deployments

**Comment by thepetk** [comment]
closing as rotten (created > 2 years). Feel free to re-open if it's not a requirement.
