### ISSUE TITLE
Update .NET stack with correct starterProjects name

### ISSUE THREAD

**Issue by mohitsuman** [devfile/api#676]
/kind bug

### Which area this bug is related to?

> /area registry

## Bug Summary
**Describe the bug:**

Currently the devfile registry has [.NET 5.0](https://registry.devfile.io/viewer/devfiles/Community+dotnet50) and [3.1 ](https://registry.devfile.io/viewer/devfiles/Community+dotnetcore31)stack available. But the starterProjects name still shows as `s2i-example`. When we display this devfile in the OpenShift Connector extension, it refers as s2i and creates confusion.

## Expected behavior

Can we make sure the starterProjects name to refers to devfile, something like `dotnet-example`.

## Any logs, error output, screenshots etc? Provide the devfile that sees this bug, if applicable.

The stack is here: 

.NET 5.0: https://github.com/devfile/registry/blob/main/stacks/dotnet50/devfile.yaml#L14

.NET 3.1: https://github.com/devfile/registry/blob/main/stacks/dotnetcore31/devfile.yaml#L14

**Comment by callmetushar123** [comment]
@schultzp2020 Hey I am new to open source contribution and this seems perfect beginner issue to me, Please assign it to me

**Comment by callmetushar123** [comment]
@schultzp2020 Can you provide the entire documentation of the project? My email id is tusharbarman123@gmail.com

**Comment by schultzp2020** [comment]
https://devfile.io/docs/2.1.0/what-is-a-devfile

**Comment by Jdubrick** [comment]
Closing as completed, PR was merged but wasn't linked to issue to autoclose.
