### ISSUE TITLE
[question] Is there some plan to support dotnet50 and dotnetcore31 for s390x?

### ISSUE THREAD

**Issue by xkwangcn** [devfile/api#680]
/kind user-story

**Which area this user story is related to?**
IBM Z(s390x arch) is using devfile registry in odo. I get [dotnet60 supported Z](https://catalog.redhat.com/software/containers/rhel8/dotnet-60/6182efa2be25a74c00923848?architecture=s390x), so want to know dotnet related devfiles supported status on Z.

> /area registry

## User Story
As a ... I want to ..., so that ...

**Comment by Jdubrick** [comment]
Devfiles should work on any architecture given the dependencies inside them are compatible with that arch. For example I believe you would just need to make sure to use [your link for dotnet60](https://catalog.redhat.com/software/containers/rhel8/dotnet-60/6182efa2be25a74c00923848?architecture=s390x) inside your devfile as the image.

If this isn't the case someone please correct me :)
