### ISSUE TITLE
Chaining, labeling, and deletion

### ISSUE THREAD

**Issue by deboer-tim** [devfile/api#690]
**Which area this feature is related to?**
/area library
/area devworkspace

## Which functionality do you think we should add?

Documentation or prescription of how resources deployed from a devfile can be found (and hence deleted).

**Why is this needed? Is your feature request related to a problem?**

Devfile tools are inconsistent in how/whether they clean up resources when you're done deploying a devfile.

**Detailed description:**

Today multiple tools can deploy resources based on the contents of a devfile. However, there is no defined way to find what resource(s) have been deployed from the devfile, or (if you can identify one resource) how to find the other resources.

Within each tool this means that we are inconsistent in how we clean up resources when a devfile is undeployed, and if you make changes to a devfile when it is already deployed this may leave artifacts. With multiple tools this means that no tool can cleanly remove something that was deployed from another tool, which also means that if you switch tools you can't cleanly remove or replace what the previous tool deployed.

## Describe the solution you'd like

The two primary mechanisms used today are owner references (e.g. to an empty config map) and labelling everything. At a minimum we should recommend using one of these (unless there is a third way to do this).

## Additional context

We've asked as many teams as possible to add information to this issue on how/what they deploy and clean up today.

**Comment by thepetk** [comment]
closing as rotten (created > 2 years). Feel free to re-open if it's not a requirement.
