### ISSUE TITLE
bugs in devfile docs

### ISSUE THREAD

**Issue by yangcao77** [devfile/api#695]
/area documentation
/kind bug

## Issue details

**What mistake did you find / what is missing in the documentation?**
1. devfile 2.2.0 api reference page has 404 error. 
2. as circled in the screenshot below, the left bottom always shows `User Guide 2.1.0` no matter which version was selected
<img width="1679" alt="Screen Shot 2021-11-24 at 12 46 37 PM" src="https://user-images.githubusercontent.com/22285490/143289631-ebbe1e1b-8ac6-401d-852e-6045591d2322.png">

**Comment by themr0c** [comment]
Point 2. was addressed by https://github.com/devfile/docs/pull/114.
Point 1. remains an issue.

**Comment by themr0c** [comment]
Consider committing the API reference files into the code in the `master` branch, as they are in the other branches. See:
* https://github.com/devfile/docs/tree/v2.0.x/docs/modules/user-guide/attachments
* https://github.com/devfile/docs/tree/v2.1.x/docs/modules/user-guide/attachments
* https://github.com/devfile/docs/tree/master/docs/modules/user-guide/attachments

**Comment by kadel** [comment]
any progress on this? the api reference for 2.2.0 is still returning 404 :-/

**Comment by jc-berger** [comment]
THanks, @kadel   @robin-owen and I are discussing. Kind of a curve ball we've been thrown here but we're working on it now!

**Comment by schultzp2020** [comment]
This issue seems to have fixed itself
