### ISSUE TITLE
Explore Devfile integration with Backstage

### ISSUE THREAD

**Issue by slemeur** [devfile/api#705]
https://backstage.io/ is providing a platform to build developer portal. It would be interesting to explore how Devfile could be used within backstage to enhance the developer portal with a set of metadata that could enable tools to work on the components from the software catalog and/or the software templates.
- https://backstage.io/docs/features/software-catalog/software-catalog-overview
- https://backstage.io/docs/features/software-templates/software-templates-index
 

**Which area this feature is related to?**
/area api
/area registry

## Which functionality do you think we should add?
For the time being, this would be only an exploration. But we would like to explore how we would be able to bridge devfile with components+templates that are proposed in Backstage. 
Maybe a backstage plugin could be created that would bridge a devfile registry with a software catalog and templates from backstage.
We would then think about the potential use cases this could enable.

**Comment by michael-valdron** [comment]
Since we still need to define the acceptance criteria and create tied issues to what the to be found needs are to this epic I will add this issue to needs triage.

cc: @slemeur @elsony

**Comment by kadel** [comment]
It should be possible to write Entity provider for Backstage that reads data from devfile.yaml.

The important thing will be defining the mapping between the devfile metadata and the Backstage component descriptor.

The backstage component description has fields that don't have its counterpart in devfile. 
Required fields that every Backstage Component should have. 
- `type` (`website`| `service` | `library`)
- `lifecycle` (`experimental` | `production` | `deprecated`)
- `owner` (a reference to Backstage Group or User entity)

In addition to the required fields, there are optional fields that are often used, like `dependsOn`, `providedsApis`, `consumesApis`, `subcomponentOf`.


We could use top-level `attributes` in devfile.yaml to allow users to specify additional metadata inside `devfile.yaml` for Backstage. 

```yaml
schemaVersion: 2.2.0
metadata:
  name: myproject
  attributes:
    component.backstage.io/type: website
    component.backstage.io/lifecycle: production
    component.backstage.io/owner: teamA
```
