### ISSUE TITLE
Remove inner scrollbar from API reference web pages

### ISSUE THREAD

**Issue by deboer-tim** [devfile/api#711]
/kind bug

### Which area this bug is related to?
/area api

## What versions of software are you using?
Current website.

## Bug Summary
**Describe the bug:**
Nit: in the website API reference, there is a scroll bar within the generated api section on every page in addition to the normal scrollbar for the page. 

**To Reproduce:**
Go to the API reference in the docs and make sure the page is small enough (or text is zoomed big enough) that scrollbars are required.

## Expected behavior
Just use the normal page scrolling, API reference should not be within a frame.

**Comment by schultzp2020** [comment]
N/A after landing page redesign
