### ISSUE TITLE
making tag bubbles clickable 

### ISSUE THREAD

**Issue by kadel** [devfile/api#712]
**Which area this feature is related to?**

/area registry

## Which functionality do you think we should add?

It would be nice to make blue "tag" bubbles clickable.  
After user click on it, it would show just the devfiles with that tag.

![image](https://user-images.githubusercontent.com/57206/146018873-4f89c4a6-b05c-4d96-8ad6-38b745838306.png)

**Comment by schultzp2020** [comment]
This issue should be fixed when the registry viewer design is updated

**Comment by michael-valdron** [comment]
This issue has been resolved with PR devfile/devfile-web#40.
