### ISSUE TITLE
Add language filter to devfile registry

### ISSUE THREAD

**Issue by deboer-tim** [devfile/api#713]
**Which area this feature is related to?**
/area registry

## Which functionality do you think we should add?
As discussed on the cabal, `language` is the key filter that we expect devfile authors to include and users to want to filter by. We should add a language filter to the devfile registry viewer, above the tags filter. (IMHO I don't think we need the tags, or should now filter the languages out of there, but that's up to you)

**Why is this needed? Is your feature request related to a problem?**
This is a key way we expect users to want to filter the registry, and having the languages in a clean list is simpler to find than if the languages are buried within the longer list of tags.

**Comment by michael-valdron** [comment]
The new registry viewer changes #916 seems to address this issue, I will close it now.
