### ISSUE TITLE
Add language badge to devfiles

### ISSUE THREAD

**Issue by deboer-tim** [devfile/api#714]
**Which area this feature is related to?**
/area registry

## Which functionality do you think we should add?
The devfile registry viewer currently shows each devfile with blue badges for each tag the devfile has. We've decided that language is the key filter that users will want to filter by (see Issue 713), but many devfiles also include the language in the tags.

Proposal:
- In the viewer, make the first badge on every devfile the language. Possibly make it a different colour badge or have something different on it.
- Filter the language from the list of tags, both in the badges (i.e. don't have two Java badges on a devfile) and on the full list of tags filter on the left.

**Why is this needed? Is your feature request related to a problem?**
This makes language first-class, and consistently the first badge on every devfile. It doesn't block devfile authors from adding the language as a tag as well, but since this is redundant and completely unnecessary it discourages this (because adding it doesn't change anything).

**Detailed description:**

## Describe the solution you'd like
An ugly example of what I'm suggesting:
![146018873-4f89c4a6-b05c-4d96-8ad6-38b745838306](https://user-images.githubusercontent.com/19958075/146022679-866df5bd-aa6d-4705-8e8a-fdc33754a8c0.png)

## Additional context
See Issue 712 and Issue 713 for additional context. If you do 712 I'd expect clicking on the language would just activate the language filter on the left, and ditto for clicking a tag.

**Comment by schultzp2020** [comment]
This issue should be fixed when the registry viewer design is updated

**Comment by michael-valdron** [comment]
PR devfile/devfile-web#40 seems to have resolved this issue.
