### ISSUE TITLE
Using devfiles vs Authoring devfiles

### ISSUE THREAD

**Issue by rkratky** [devfile/api#724]
/area documentation

**Which area this documentation change is related to?**
https://devfile.io/docs/devfile/2.1.0/user-guide/using-devfiles.html

## Issue details

**What mistake did you find / what is missing in the documentation?**
Section "Using devfiles" contains:
* Adding schema version to a devfile
* Adding a name to a devfile

While right next to it, the "Authoring devfiles" section contains:

* Adding projects to a devfile
* Adding commands to a devfile
* Adding components to a devfile
* Adding attributes to a devfile
* Referring to a parent devfile in a devfile

.....................

Why are the two sections separate?

**Comment by jc-berger** [comment]
@rkratky thanks for raising the issue. Awhile ago, when we restructured the TOC, devs and I thought breaking into two sections might help the flow more. I'm fine with keeping it one section. Please let me know what you think about the changes I made in PR 123: https://github.com/devfile/docs/pull/123
