### ISSUE TITLE
Invalid docs link

### ISSUE THREAD

**Issue by rkratky** [devfile/api#725]
/area documentation

**Which area this documentation change is related to?**
https://devfile.io/docs/devfile/2.1.0/user-guide/index.html

## Issue details

**What mistake did you find / what is missing in the documentation?**
![image](https://user-images.githubusercontent.com/6623103/149347547-b30cb369-d15c-4821-9544-6e21c6420045.png)

**Comment by jc-berger** [comment]
@rkratky thanks for making an issue to track this work. 

I have a PR addressing this broken link: https://github.com/devfile/docs/pull/120
