### ISSUE TITLE
Update .NET devfiles tags to differentiate them

### ISSUE THREAD

**Issue by lstocchi** [devfile/api#729]
**Which area this documentation change is related to?**

/area registry

## Issue details
The .NET devfiles in the registry [dotnet5](https://registry.devfile.io/viewer/devfiles/Community+dotnet50), [dotnet6](https://registry.devfile.io/viewer/devfiles/Community+dotnet60) and [dotnet core](https://registry.devfile.io/viewer/devfiles/Community+dotnetcore31) have all the same tags. This makes impossible to select the proper devfile automatically based on the analysis performed on user project (made by [alizer](https://github.com/redhat-developer/alizer)).

It would be good if they had a tag which differentiate them, like `.net5`/`.net6`/`.net core` or something else.

Also the language is always `dotnet`. Shouldn't it be `C#`?

**Comment by Jdubrick** [comment]
Currently on the registry the .NET devfiles have tags that differentiate them:
https://registry.devfile.io/viewer/devfiles/community/dotnet50
https://registry.devfile.io/viewer/devfiles/community/dotnet60
https://registry.devfile.io/viewer/devfiles/community/dotnetcore31

But they still have the language as `.NET` so this should move to refinement.
