### ISSUE TITLE
Landing page and doc update for devfile slack channel

### ISSUE THREAD

**Issue by elsony** [devfile/api#732]
/area documentation

**Which area this documentation change is related to?**
General documentation changes to reflect changing from Gitter to the devfile slack channel in the Kubernetes workspace (https://kubernetes.slack.com/archives/C02SX9E5B55).

## Issue details
**What mistake did you find / what is missing in the documentation?**
The devfile project has been approved as a CNCF sandbox project. As part of the onboarding requirements, we are moving our chat system to the “devfile” channel in the Kubernetes slack https://kubernetes.slack.com/archives/C02SX9E5B55. No invitation is needed on that channel. If you haven’t joined the Kubernetes workspace before, follow https://slack.k8s.io/.

We are sunsetting the Gitter https://gitter.im/devfile/community and moving all devfile topics to the new slack channel. We need to update all references to the doc, readme and landing page to the new slack channel as our chat system.

**Comment by jc-berger** [comment]
@elsony thanks for the update. For the docs repo, none of the docs, including the repo's README, refers to or directs to any sort of Slack channel. 

Some of our docs to point users to the API and Docs repo if that's still alright?
