### ISSUE TITLE
Build a Devfile Editor Tool

### ISSUE THREAD

**Issue by schultzp2020** [devfile/api#748]
**Which area this feature is related to?**
/area registry

## Which functionality do you think we should add?

**Detailed description:**
We should have a devfile editor tool that allows users an easy way to create and see changes to a devfile.

## Possible Solutions

- Standalone tool
- Website (Under devfile.io)

#### Work Required

- A custom JSON Schema form would need to be create since there does not seem to be any readily available. https://github.com/rjsf-team/react-jsonschema-form for reference; however, this solution does not work for what we want to do.

#### Limitations
- The devfile yaml would not be editable, only copyable.

**Comment by elsony** [comment]
Removing from Sprint 213 since this item is currently not in priority.

**Comment by Jdubrick** [comment]
Closing this issue as this issue covers the same topic: https://github.com/devfile/api/issues/691
