### ISSUE TITLE
[Registry] Provide the devfile when downloading one of the sample application from a devfile stack

### ISSUE THREAD

**Issue by slemeur** [devfile/api#749]
/kind user-story

**Which area this user story is related to?**
/area registry

## User Story
As a user of the devfile registry, I want to be able to pick a technology, select an example application and download the source code with the devfile allowing me to start coding on the application. Once download, I should also be guided into what to do next (explaining how to use the devfile into my tools).

### Details
As a user coming to this devfile stack: https://registry.devfile.io/viewer/devfiles/Community+java-vertx, I've download the source code of one of the example application. But the devfile was not there, which adds a lot of manual steps and don't let really the user understand what is going on.

## Acceptance Criteria
- [ ] When an example application provide with a devfile stack is downloaded, there should be the devfile with it
- [ ] When downloaded, I should have instruction on what to do next

**Comment by thepetk** [comment]
closing as rotten (created > 2 years). Feel free to re-open if it's not a requirement.
