### ISSUE TITLE
missing description what command groups are for

### ISSUE THREAD

**Issue by kadel** [devfile/api#756]
/area documentation

**Which area this documentation change is related to?**

/area api

## Issue details

**What mistake did you find / what is missing in the documentation?**

There is no documentation for what each group in `commands.exec.group.kind` means.
The only thing that is there is a `Kind of group the command is part of` which is not helpful at all. 

Each group needs detailed documentation describing what it is for and what type of command it should be. By type here I mean if it should be long-running process (like in case of `debug` and `run`) or command that should exit in a reasonable time after it does its job (`build, `test`, `deploy`)

**Comment by thepetk** [comment]
closing as rotten (created > 2 years). Feel free to reopen if is still a requirement.
