### ISSUE TITLE
Set up daily registry tests to ensure stacks, starter projects and samples are functional

### ISSUE THREAD

**Issue by elsony** [devfile/api#759]
**Which area/kind this issue is related to?**
/area test-automation

## Issue Description
Set up daily registry tests to ensure stacks, starter projects and samples are functional.  Given that the starter projects and samples are stored in the provider's own repo. Those can be updated without a registry build which means that the starter projects or samples may get out of sync with the image and causes them to fail. A daily test run will help us to identify potential problems.

**Comment by johnmcollier** [comment]
This was merged in https://github.com/devfile/registry/pull/92, so closing.
