### ISSUE TITLE
Update devfile docs with registry library topic

### ISSUE THREAD

**Issue by kim-tsao** [devfile/api#760]
/area documentation

**Which area this documentation change is related to?**

 /area registry

## Issue details

**What mistake did you find / what is missing in the documentation?**

We don't have a topic for using the registry library and it's not obvious to find within our git repo.   This [PR](https://github.com/johnmcollier/registry-docs/pull/3 ) adds the registry library topic that links to the actual doc in the repo itself

**Comment by thepetk** [comment]
closing as rotten (created > 2 years). Feel free to reopen if is still a requirement.
