### ISSUE TITLE
nodejs 2.0 and 2.2 devfiles use terminating image under the hood and not usable by Eclipse Che

### ISSUE THREAD

**Issue by ibuziuk** [devfile/api#767]
### Which area this bug is related to
> /area registry

## Bug Summary
The following nodejs devfiles are using `registry.access.redhat.com/ubi8/nodejs-14:latest` image under the hood. The image is not usable by Eclipse Che / CRW since it is a terminating one, and does not specify non-terminating command / args.

Affected devfiles:
- https://registry.devfile.io/devfiles/nodejs 
- https://registry.devfile.io/viewer/devfiles/Community+nodejs-basic (uses https://registry.devfile.io/devfiles/nodejs as parent)

![image](https://user-images.githubusercontent.com/1461122/153381692-276bdd8f-6386-4593-b317-8d0f90aebca1.png)

## Expected behavior
Workspace is started without errors

## Any logs, error output, screenshots etc? Provide the devfile that sees this bug, if applicable.

runtime container which uses `registry.access.redhat.com/ubi8/nodejs-14:latest` puts the pod in the CrashLoopBackOff state

![image](https://user-images.githubusercontent.com/1461122/153384564-fbc9fd1d-501f-4a10-95bc-e64fff6fcf21.png)

## Additional context
The problem has been already raised in https://github.com/devfile/api/issues/681#issuecomment-972594175

**Any workaround?**

N/A

**Suggestion on how to fix the bug**

Update the image and make it non-terminating

**Comment by johnmcollier** [comment]
Believe this will be fixed by https://github.com/devfile/registry/pull/91

**Comment by ibuziuk** [comment]
@johnmcollier thanks for the pointer, however, I do not see any changes in this draft PR related to `ubi8/nodejs-14:latest` update. 
Could this issue be prioritized accordingly because currently 2.2 sample is non-working

**Comment by kadel** [comment]
We will have to specify `container.command` in most of the stack and sample devfiles.

@ibuziuk What would be the ideal command to make images non-terminating? `sleep inifinity`? `cat  > /dev/null`?

We should document what is the recommended way to do this. Most of the images that we are going to use in devfile stack will have default entrypoint that is terminating.So we will have to remember override it in devfiles.

**Comment by ibuziuk** [comment]
> What would be the ideal command to make images non-terminating

@kadel we normally use `tail -f /dev/null`

> We should document what is the recommended way to do this. Most of the images that we are going to use in devfile stack will have default entrypoint that is terminating. So we will have to remember override it in devfiles.

:+1: please, let me know if you need assistance with this

**Comment by l0rd** [comment]
Note that [this PR](https://github.com/devfile/registry/pull/102) would fix this issue (it adds `container.command: ["tail", "-f", "/dev/null"]` to all the terminating containers) but `odo` doesn't like that. So we are blocked.

**Comment by johnmcollier** [comment]
@kadel do you have any suggestions here? It seems overriding the command to the devfile causes odo to fail to deploy the devfile since supervisord isn't the entrypoint any more.

**Comment by kadel** [comment]
> @kadel do you have any suggestions here? It seems overriding the command to the devfile causes odo to fail to deploy the devfile since supervisord isn't the entrypoint any more.

Yes, sadly this is a bug in odo :-/ We should have a fix in a few days.
We should wait before merging this change until we have a new odo release with fix. 
But even after that this change will break all previous odo versions :-/

**Comment by schultzp2020** [comment]
@kadel has odo released a fix?

**Comment by kadel** [comment]
@schultzp2020 yes, a while back. More info is in the PR comments (https://github.com/devfile/registry/pull/102#issuecomment-1199122802)

**Comment by johnmcollier** [comment]
@ibuziuk Can this issue be closed out?

**Comment by l0rd** [comment]
This issue has been resolved. There is a PR check that verifies that there are no more terminating containers in the registry.
