### ISSUE TITLE
low memory limit for the quarkus devfiles which results in OOM during execution of the 'init-compile' command

### ISSUE THREAD

**Issue by ibuziuk** [devfile/api#768]
/kind bug

### Which area this bug is related to?

> /area registry

Problematic devfiles:
 - https://registry.devfile.io/devfiles/java-quarkus
 - https://registry.devfile.io/viewer/devfiles/Community+code-with-quarkus (references https://registry.devfile.io/devfiles/java-quarkus as parent)

## Bug Summary

memory limit set in the devfile for tools container is 512Mb which is failing on startup with:

```
Detected unrecoverable event FailedPostStartHook: Exec lifecycle hook ([/bin/sh -c cd $PROJECTS_ROOT mvn -Dmaven.repo.local=/home/user/.m2/repository compile]) for Container "tools" in Pod "workspace23fd164cde3a477d-6bd5cf85ff-6tzdz_ibuziuk-che(9d894efc-bd8f-4e10-984c-aa2312bf17bd)" failed - error: command '/bin/sh -c cd $PROJECTS_ROOT mvn -Dmaven.repo.local=/home/user/.m2/repository compile' exited with 137: , message: ""
```

```
memoryLimit: 512Mi ## default app nowhere needs this but leaving room for expansion.
```
**To Reproduce:**

Start quarkus devfile with Eclipse Che

![image](https://user-images.githubusercontent.com/1461122/153388154-aface6ba-0158-49fd-8ac2-eb430a487a21.png)

## Expected behavior
Workspace is started without problems 

**Suggestion on how to fix the bug**
Increase memory limit for the `tools` container

**Comment by elsony** [comment]
Does Che have an extra requirement on memory usage when running the samples? These samples were run by odo and ODC without a problem. I wonder why it requires more memory when running on Che.

**Comment by ibuziuk** [comment]
not sure what exactly is wrong with the devfile, but the main point is that all the samples should be tested across all the tools that are using the samples devfiles on OpenShift.

**Comment by kadel** [comment]
We should try to figure out why the memory limit is not enough for Che if in all other cases it is OK.

How Che translates resource limits to the containers? 

We should not just blindly increase limits if we don't know what is happening.

**Comment by l0rd** [comment]
`init-compile` works fine now. we currently add memory on top of the devfile mem request to run the IDE (the amount of memory depends on the IDE). Now, if the user adds IDE plugins/extensions that consume a lot of RAM (e.g. vscode-java), he/she can still get an OOM but I think that's ok.
