### ISSUE TITLE
Broken java-quarkus stack

### ISSUE THREAD

**Issue by kadel** [devfile/api#773]
/kind bug

### Which area this bug is related to?

/area registry

## What versions of software are you using?

```
$ odo version
odo v2.5.0 (247d001ee)

Server: https://api.crc.testing:6443
Kubernetes: v1.22.3+e790d7f
```
The current state of devfile registry  https://github.com/devfile/registry/tree/2cb3c679acc351d9da81593f80f80cf0688cb799

## Bug Summary
Quarkus application defined as a `community` starter project won't start with the current java-quakurs devfile stack. 

It thorws an error `Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.7.1.Final:dev (default-cli) on project code-with-quarkus: Detected Maven Version (3.6.2)  is not supported, it must be in [3.8.1,). -> [Help 1]`

Look like the Maven version inside the image that java-quarkus uses `registry.access.redhat.com/ubi8/openjdk-11` old version that is no longer supported by quarkus

**To Reproduce:**
```
odo create java-quarkus --starter community
odo push
odo log
```

## Expected behavior
running Quarkus application

## Any logs, error output, screenshots etc? Provide the devfile that sees this bug, if applicable.

```
[INFO] 
[INFO] --- quarkus-maven-plugin:2.7.1.Final:dev (default-cli) @ code-with-quarkus ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.778 s
[INFO] Finished at: 2022-02-15T11:36:03Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal io.quarkus.platform:quarkus-maven-plugin:2.7.1.Final:dev (default-cli) on project code-with-quarkus: Detected Maven Version (3.6.2)  is not supported, it must be in [3.8.1,). -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by elsony** [comment]
This is a quarkus stack specific problem which is tracked by: https://github.com/quarkusio/quarkus/issues/23562

**Comment by kadel** [comment]
the issue was fixed 
/close
