### ISSUE TITLE
Provide information how the devfile registry instance was built

### ISSUE THREAD

**Issue by kadel** [devfile/api#774]
**Which area this feature is related to?**

/area registry

## Which functionality do you think we should add?

It would be nice to be able to get information about the source that was used to build the running registry instance.

**Why is this needed? Is your feature request related to a problem?**

verify the source for devfile registry content

**Detailed description:**

## Describe the solution you'd like

One example of how this could be to add a new field into the index.

```
"buildFrom": {
   "registry: {
       "repository": "https://github.com/devfile/registry"
       "commit": "2cb3c679acc351d9da81593f80f80cf0688cb799"
    }
   "registry-support: {
       "repository": "https://github.com/devfile/registry-support"
       "commit": "e90825181600a98421a7f6ee63881fa45704dc8d"
    }
}
```

The root element in the index is currently an array.
To start adding metadata like this we would need to change a structure a bit. 

Instead of defining index as 
```go
[]Schema
```
it could be something like this.

```go
type Index struct {
   Metadata Metadata
   Items: []Schema 
}

type Metadata struct {
   BuildFrom BuildFrom
}

type BuildFrom struct {
  Registry        GitReference
  RegistrySupport GitReference
}

type GitReference struct {
   Repository string
   Commit     string
}
```

We have a good opportunity to add this as there will be breaking changes introduced with https://github.com/devfile/api/issues/735 anyway.

**Comment by kadel** [comment]
@yangcao77 What do you think about this? Do you think it would make sense?

**Comment by yangcao77** [comment]
> We have a good opportunity to add this as there will be breaking changes introduced with https://github.com/devfile/api/issues/735 anyway.

First of all, I want to clarify that #735 won't introduce breaking change, all changes will be backward compatible.  New endpoint and new query property(for registry library APIs) will be introduced to get the new index struct proposed in #735. We will switch the default to return new index struct when all consumers are ready for the  move. 

For this issue, may I know why Odo needs the commit information?

**Comment by yangcao77** [comment]
@kadel 
we publish to staging for every new commit, and move to staging to production registry every Wednesday.
The devfile out of sync is due to staging period. 

I think it's good to have this information stored in registry server, but should not in the index content. I do not want to break our current index struct. 
The information can be stored in registry image ENV. And a new endpoint `GET /version` can be introduce to get the registry version information, the returned content can be as suggested.
```
"buildFrom": {
   "registry: {
       "repository": "https://github.com/devfile/registry"
       "commit": "2cb3c679acc351d9da81593f80f80cf0688cb799"
    }
   "registry-support: {
       "repository": "https://github.com/devfile/registry-support"
       "commit": "e90825181600a98421a7f6ee63881fa45704dc8d"
    }
}
```

**Comment by kadel** [comment]
> we publish to staging for every new commit, and move to staging to production registry every Wednesday.
> The devfile out of sync is due to staging period.

Problem is that there is no way to confirm that.






> I think it's good to have this information stored in registry server, but should not in the index content. I do not want to break our current index struct.
> The information can be stored in registry image ENV. And a new endpoint `GET /version` can be introduce to get the registry version information, the returned content can be as suggeste

That makes sense, adding it into the index was just the first thing that I thought.  `GET /version` makes much more sense
