### ISSUE TITLE
More information about `deploy` and how to search docs?

### ISSUE THREAD

**Issue by dharmit** [devfile/api#775]
/area documentation

**Which area this documentation change is related to?**

/area api

## Issue details

**What mistake did you find / what is missing in the documentation?**

Where can I find more information about `deploy`? I don't see it on the `2.2.0-alpha` tree of the docs (I clicked quite a few links under "Authoring Devfile --> Adding Commands" section.) The one where I particularly expected it to exist was https://devfile.io/docs/devfile/2.2.0/user-guide/adding-composite-commands-to-a-devfile.html because odo documentation shows `deploy` as a composite command on https://odo.dev/docs/command-reference/deploy/. Correct me if I should be looking at a different section for it.

Also, I don't see any option to search on devfile docs like the one on https://odo.dev. It would help to have some sort of working search integration on the site.

**Comment by Jdubrick** [comment]
Closing issue. There is now a search functionality on https://devfile.io/docs. I believe information regarding deploy and composite commands can be found [here ](https://devfile.io/docs/2.2.2/adding-a-composite-command)and [here](https://devfile.io/docs/2.2.2/adding-a-kubernetes-or-openshift-component#procedure).
