### ISSUE TITLE
devfile.io doesn't load on Firefox

### ISSUE THREAD

**Issue by joschi** [devfile/api#776]
When trying to open https://devfile.io/ in Firefox 96.0.3 (on macOS Big Sur 11.6.1), the tab stalls and never loads.

Firefox is complaining that the tab is using too many resources and asks to close it.
<img width="628" alt="Firefox asking to close the requested website" src="https://user-images.githubusercontent.com/43951/152761806-115f7396-2090-475a-946f-f78b8507b797.png">

This can be reproduced on a freshly started Firefox and in private browsing mode.

The website successfully can be loaded and works on Chrome 98.0.4758.80 on the same machine.

**Comment by johnmcollier** [comment]
@schultzp2020 can you take a look?

**Comment by schultzp2020** [comment]
I tried Firefox on my Linux machine and it works.

**Comment by joschi** [comment]
FWIW, I can reproduce it on Firefox 97.0 (on macOS) too.

**Comment by schultzp2020** [comment]
This should no longer be an issue. Reopen an issue if it persists.

**Comment by joschi** [comment]
I can confirm that it's working with Firefox 104.0 on macOS now. Maybe Mozilla fixed some bug in Firefox. 🤷
