### ISSUE TITLE
Update schema to clarify that container image for inner loop needs to be long running

### ISSUE THREAD

**Issue by elsony** [devfile/api#780]
/area documentation

**Which area this documentation change is related to?**
/area api

## Issue details
When someone is specifying an image in the container component, the image should be long-running, i.e. the run command needs to stay up and running for the life cycle of the runtime. We should clarify that on the schema so the devfile authors will know about this requirement.

**What mistake did you find / what is missing in the documentation?**
Missing clarification on the requirement on the long-running command for the run command of the image container.

**Comment by thepetk** [comment]
closing as rotten (created > 2 years). Feel free to reopen if is still a requirement.
