### ISSUE TITLE
Full implementation of multi-arch support in a devfile registry

### ISSUE THREAD

**Issue by elsony** [devfile/api#782]
**Which area this feature is related to?**
/area api

## Which functionality do you think we should add?
Provide the full implementation of multi-arch support in a devfile registry

**Why is this needed? Is your feature request related to a problem?**
The current approach requires a stack to create multiple entries in a devfile registry with different stack names in order to provide multi-arch support.

**Detailed description:**
The first pass of the multi-arch support provides a simple approach to handle a stack with multi-arch support was implemented as part of https://github.com/devfile/api/issues/244#issuecomment-852157289. In the recent devfile cabal discussion (https://docs.google.com/document/d/1Zn6D1gNu1gDidtillni0hNAeU5pscfqwhx4mv3MmmwY/edit?pli=1#heading=h.66t07559x013). It has been decided to do the full implementation in order to avoid a stack creating multiple entries of the devfile in a devfile registry to support multi-arch scenario.

## Describe the solution you'd like
Implement case https://github.com/devfile/api/pull/1 in https://docs.google.com/document/d/1MTgxy2EAFYqvN7Twtbr_iWlG9xsghOyI89RRILxvsqY/edit#heading=h.esvxv0e8cpjx

## Describe alternatives you've considered
See detailed description

**Comment by thepetk** [comment]
I think this is completed from after EPIC https://github.com/devfile/api/issues/1608
