### ISSUE TITLE
Add devfile 2.2 go sample to the public community registry

### ISSUE THREAD

**Issue by elsony** [devfile/api#787]
**Which area/kind this issue is related to?**
/area registry

## Issue Description
Create a go sample similar to the existing devfile 2.2 samples in https://github.com/devfile/registry/blob/main/extraDevfileEntries.yaml. 

Requirements:
1. The contained devfile will be created based on the existing go devfile (https://github.com/devfile/registry/blob/main/stacks/go/devfile.yaml) and add the outer loop function to it.
2. The sample application is based on the starter project: https://github.com/devfile-samples/devfile-stack-go.git but need to add the devfile, Dockerfile and deployment.yaml as part of the new sample repo
3. Add the sample to the org https://github.com/devfile-samples
4. Onboard to the public community registry by adding the new sample to the extraDevfileEntries.yaml

**Comment by yangcao77** [comment]
The go sample is temporarily created under my own repo: https://github.com/yangcao77/go-sample
Will transfer to devfile-samples org after the sample has been approved.

**Comment by elsony** [comment]
The proposed repo looks good.
