### ISSUE TITLE
Instead of passing the analytics prop down, use the useContext hook.

### ISSUE THREAD

**Issue by schultzp2020** [devfile/api#791]
**Which area/kind this issue is related to?**

/area registry

## Issue Description
Currently we pass the analytics prop down to each component through `/pages/_app.tsx` file in both the registry-viewer and landing-page. This should be updated to use the useContext hook for simplicity.

- [ ] landing-page
- [ ] registry-viewer

**Comment by schultzp2020** [comment]
This issue should be fixed when the registry viewer design is updated

**Comment by michael-valdron** [comment]
PR devfile/devfile-web#40 seems to have resolved this issue.
