### ISSUE TITLE
Reorganize "Add a Component docs"

### ISSUE THREAD

**Issue by kim-tsao** [devfile/api#798]
/area documentation

**Which area this documentation change is related to?**

 /area api

## Issue details

**What mistake did you find / what is missing in the documentation?**

The Adding a component doc and subtopics should be re-organized to include the description of fields relevant to each sub-topic.  See comment https://github.com/devfile/docs/pull/147#pullrequestreview-902147333

**Comment by thepetk** [comment]
closing as rotten (created > 2 years). Feel free to re-open if you think is still a requirement.
