### ISSUE TITLE
devfile should have a special `local` component

### ISSUE THREAD

**Issue by gorkem** [devfile/api#80]
**Is your feature request related to a problem? Please describe.**
When using `devfiles` with tools like `odo` it should be possible to benefit from the local output of the local tools to optimize the developer's loop. 

**Describe the solution you'd like**
Declare a special component such as `local` as reserved for this purpose. If a command is targeted for command `local` `odo` runs it on the local computer. Che can run the command on the `editor` container. 

**Describe alternatives you've considered**

**Additional context**

/CC @kadel @l0rd

**Comment by l0rd** [comment]
For Che we need to have a devfile metadata attribute that defines the "local" component in the che context (e.g. `cheLocalComponent`). That should correspond to the dev tooling container and would be helpful to define the default terminal container cc @benoitf
