### ISSUE TITLE
Description for Git object needs to be switched

### ISSUE THREAD

**Issue by josephca** [devfile/api#800]
/area documentation

**Which area this documentation change is related to?**

## Issue details
Description of the keys within the Git object table in 'Adding projects to a devfile' doc is incorrect. They may need to be switched. 

Doc URL: https://devfile.io/docs/devfile/2.2.0/user-guide/adding-projects-to-a-devfile/

![image](https://user-images.githubusercontent.com/25185698/157759290-f40a27ea-3f5f-4da5-9129-b55642811bf3.png)

**What mistake did you find / what is missing in the documentation?**
The following changes are required. 

- checkoutFrom : The location of your git repository. -> The branch that you use.

- remotes : The branch that you use. -> The location of your git repository.

**Comment by thepetk** [comment]
closing as rotten (created > 2 years). Feel free to re-open if you think is still a requirement.
