### ISSUE TITLE
Migrate telemetry for the `download-starter-project` endpoint from viewer to server

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#803]
**Which area this feature is related to?**

/area registry

## Which functionality do you think we should add?

**Why is this needed? Is your feature request related to a problem?**

Migrate telemetry for the `download-starter-project` endpoint from the registry viewer to the registry server to remove the dependency of the client side being the registry viewer to track this endpoint.

**Detailed description:**

Currently telemetry for `download-starter-project` endpoint is taken care of in the registry viewer. With completion of issue #720 this endpoint is being managed by the registry server going forward, since this means any client could use this endpoint it would be best to also migrate telemetry for this endpoint to the registry server.

Currently the registry viewer tracks the following events.

1. User changes page
2. User copies devfile YAML.

## Describe the solution you'd like

Telemetry is collected when any client accesses `download-starter-project` endpoint on the registry server.

## Describe alternatives you've considered

Telemetry for this endpoint is left on the registry viewer which restricts tracking only to this client.

**Target Date: 01-23-2023**

**Comment by schultzp2020** [comment]
This issue should be fixed when the registry viewer design is updated

**Comment by michael-valdron** [comment]
Since the current telemetry needs for the community registry with this endpoint is action count, only generic information about starter project downloads can be captured by the telemetry component on the registry server with these changes applied.

Additional changes to capturing more unique data points can be considered if the needs for this change.

cc: @elsony @kim-tsao
