### ISSUE TITLE
Add devfile video showcase to Landing Page

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#812]
/area documentation

**Which area this documentation change is related to?**

/area landing-page

## Issue details

**What mistake did you find / what is missing in the documentation?**

This issue will include the following additions:

- [x] A video to showcase devfiles in action.
- [ ] Publication of the video as a YouTube video.
- [ ] Embed the YouTube video the landing page index.

**Target Date: ~~05-31-2022~~ TBA**

**Comment by elsony** [comment]
Some other existing videos that showcase using devfile with other tools, e.g. devWorkspace, vscode, for reference:
https://drive.google.com/file/d/1_t7Zogx6U9p9dMUJXR7CiVFChsMrWI2_/view
https://www.youtube.com/watch?v=oZeDLIkMvqs
https://www.youtube.com/watch?v=6f5qAv0QzV8

**Comment by elsony** [comment]
In the video, focus on the operation of the devfile instead of editing the devfile:
1. odo create (say nodejs)
2. ls and highlight the devfile.yaml entry
3. odo push
4. run the app on the browser or using curl
5. Switch to devWorkspace and show start of devfile workspace
6. highlight that there is a devfile.yaml to start

**Comment by michael-valdron** [comment]
> 6. run the app on the browser or using curl

This step would require an extra step before with odo:

```sh
odo url create --host $(minikube ip).nip.io --ingress
```

@elsony Probably not a big deal to skip this part in the video right?

**Comment by michael-valdron** [comment]
> > 6. run the app on the browser or using curl
> 
> This step would require an extra step before with odo:
> 
> ```shell
> odo url create --host $(minikube ip).nip.io --ingress
> ```
> 
> @elsony Probably not a big deal to skip this part in the video right?

Used OpenShift Dev Sandbox for deployment instead.

**Comment by schultzp2020** [comment]
Referenced in a larger issue
