### ISSUE TITLE
Scrolling speed bumps on homepage

### ISSUE THREAD

**Issue by deboer-tim** [devfile/api#815]
/kind bug

### Which area this bug is related to?
> /area registry

## What versions of software are you using?

**Operating System:**
Mac OS

## Bug Summary
**Describe the bug:**
The devfile.io homepage has a couple scrolling 'speed bumps' or pauses. It slows down scrolling at certain points and helps you to notice the sections, but the effect is too strong and can make users think they can't scroll any further. At first I thought the page was having loading issues and missing the bottom, or that the footer had been removed.

**To Reproduce:**
Open the homepage in a narrowish browser window or on a phone (where the page will requiring scrolling down), on a device that has a trackpad or gesture control for scrolling (e.g. iPhone).

On my Mac laptop in Safari, if I do the normal gesture for scrolling down it stops with the four column feature section. If I go back to the top and try a little harder it'll actually go a little further but then come back to that section. I have to know there's something else and scroll again to see the bottom of the page.

On my iPhone I have the same problem going down; scrolling back up it stops at Why Devfiles and I have to push hard to see the top of the page.

Ping me if you can't reproduce and I'll screen-share.

## Expected behavior
Scrolling should be smoother and never appear like you've reached the bottom or top of a page until you really have.

**Comment by Jdubrick** [comment]
Closing issue. Tested https://www.devfile.io on my iPhone and didn't experience any snapping to certain sections. It smoothly scrolls the entire time.
