### ISSUE TITLE
OCI-based registry support

### ISSUE THREAD

**Issue by gorkem** [devfile/api#82]
**Is your feature request related to a problem? Please describe.**
Provide a devfile registry solution that is easier to manage, takes advantage of the existing mechanisms of access control, distribution, caching, proxy 

**Describe the solution you'd like**
Existing [proposal](https://docs.google.com/document/d/15IbEz7Q4wGq45hbenk_B6GDMfHd_HR8oRx_uDnN76Ug/edit)

**Additional context**

**Comment by elsony** [comment]
MVP:
1. Initial setup of a devfile registry
   - Bootstrap a basic OCI registry with devfiles from a devfile registry on github (#143)
2. Define the structure of the devfile registry
3. Life cycle of devfile registry (start, stop, restart)
4. Formalize and define schema for devfile registry metadata (index.json) (#135) 
5. Packaging of devfile registry for deployment
6. Build tools for generating registry based on registry/catalog info on a github repo
7. Define a public common devfile registry that can be shared across different tools
8. Define on-boarding requirement for a stack to be added to a public registry

MVP+:
1. Handle update on the content of the devfile registry, e.g. add and remove a stack, update of the content of stack, update of metadata (index.json) of the stack.
2. Deployment of devfile registry in cluster
3. Validation support on build tool to standardize on-boarding requirement for a stack to be added to a public registry
4. Allow stack contents to be stored under stack owned repos
5. Define mechanism for stack providers to provide multiple versions of a given stack

**Comment by benoitf** [comment]
Hello,
In codeready workspaces we have the devfile registry serving zip file or getting started exemples ( it is cloning source code, zip it, and updating git locations of devfile.yaml and replace it as well icons, etc)
Main usecase is airgap mode
So I don't know how it fits there ?
Adding new oci layers ?
