### ISSUE TITLE
Remove Samples from Devfile registry

### ISSUE THREAD

**Issue by kadel** [devfile/api#827]
/area registry

## Issue Description
as discussed in many places (one of them at https://github.com/devfile/api/issues/679).
Sample stacks should be removed from the devfile registry. There is no need for them as they already is a similar feature in devfile spec (starterProject).

Currently, it is just confusing users and providing no benefit. Especially as there is no documentation what the Sample actually is.

**Comment by elsony** [comment]
Existing samples are using devfile 2.2. The goal is to eventually remove the samples and just use starter projects. However, we'll need to wait for devfile 2.2 released before we can complete that move.

**Comment by Jdubrick** [comment]
@johnmcollier does Konflux still depend on the sample entries? Currently trying to figure out if this issue is still relevant.

cc: @michael-valdron

**Comment by ibuziuk** [comment]
`Samples / Stack` selection based on Types is super confusing

<img width="811" alt="Screenshot 2024-04-17 at 16 53 23" src="https://github.com/devfile/api/assets/1461122/a3acb707-c8ce-46e2-b911-0fff5b93fb5c">

Can we remove this completely and not overload semantics?
