### ISSUE TITLE
Define how to manage devfiles on the Git repo

### ISSUE THREAD

**Issue by gorkem** [devfile/api#83]
**Is your feature request related to a problem? Please describe.**
Define how we will manage the devfiles on the git registry to manage the new devfile registry. 
This should include. 

1. The shape of the git repository
2. The branching and tagging practices for devfile versions.
3. Build process

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by l0rd** [comment]
https://github.com/devfile/catalog

**Comment by GeekArthur** [comment]
I think this repo https://github.com/devfile/registry-support should be used for implementing the OCI-based registry build process, and we may create another repo or use the existing catalog repo https://github.com/devfile/catalog to host the default devfiles to let the build process consume.

**Comment by elsony** [comment]
Community call discussion 3/28:
1. The information is already documented under https://github.com/devfile/registry/blob/main/CONTRIBUTING.md.
