### ISSUE TITLE
Add devfile description to the devfile CNCF page

### ISSUE THREAD

**Issue by cdrage** [devfile/api#830]
**Which area this documentation change is related to?**

/area documentation
CNCF

## Issue details

On the CNCF website the devfile description needs to be updated.
https://www.cncf.io/projects/devfile/

**Comment by schultzp2020** [comment]
There is now a link in devfile.io referencing CNCF. We still need to update https://www.cncf.io/projects/devfile/

**Comment by callmetushar123** [comment]
Can you be more specific on what needs to be updated? I mean what kind of description do you need?

**Comment by elsony** [comment]
@cdrage Can you clarify the request? All other CNCF projects only have a single-line description of the project on that link page and that's what we currently have.

**Comment by cdrage** [comment]
You're right, the description is only regarding what sandbox level they are. I'll close this issue.
