### ISSUE TITLE
Implement a commands variable in the registry schema for easier group ID retrieval.

### ISSUE THREAD

**Issue by cdrage** [devfile/api#831]
**Which area this feature is related to?**

> /area api
> /area library
/area registry
> /area devworkspace

## Which functionality do you think we should add?

**Why is this needed? Is your feature request related to a problem?**

I request that we add to the Schema a `commands` variable that lists all the commands implemented / used with their respective group kind.

**Detailed description:**

This is necessary in order to retrieve if the devfile.yaml has `debug`, `run`, `build`, or `test` commands available for when you pull in the information via registry. 

## Describe the solution you'd like

Implemented into the schema :)

## Describe alternatives you've considered

Alternatives were to http request each and every devfile.yaml and parse it instead, in order to simply retrieve what commands are being ran.

**Comment by thepetk** [comment]
closing as rotten (created > 2 years). Feel free to re-open if you think is still a requirement.
