### ISSUE TITLE
Dotnet stacks are missing logos

### ISSUE THREAD

**Issue by deboer-tim** [devfile/api#845]
/kind bug

### Which area this bug is related to?
> /area registry

## What versions of software are you using?
n/a

## Bug Summary
**Describe the bug:**
The Dotnet devfiles all have an invalid icon, which is showing up as a missing link on the devfile registry, VS Code explorer, etc.

**To Reproduce:**
Open the registry...

## Expected behaviour
No missing link icons.

## Any logs, error output, screenshots etc? Provide the devfile that sees this bug, if applicable.
<img width="896" alt="Screen Shot 2022-05-09 at 12 57 12 PM" src="https://user-images.githubusercontent.com/19958075/167459944-1c7e527a-f87f-4b7d-b481-9b55671f70e1.png">

## Additional context

**Suggestion on how to fix the bug**
1. We should fix the links in these specific devfiles.
2. If an icon is missing we should show something other than the broken link - either use a placeholder or revert to what we do if there's no icon.

**Comment by schultzp2020** [comment]
fixed
