### ISSUE TITLE
Mirror dockerhub base images on quay.io to avoid rate limiting issues

### ISSUE THREAD

**Issue by kim-tsao** [devfile/api#848]
**Which area/kind this issue is related to?**

/area registry

## Issue Description

We have a number of devfile stacks/samples that reference images on dockerhub but users that adopt these devfiles may run into rate limiting issues if they make repeated requests to pull these images.  

> Please uncomment and provide the target Odo version if this task is for QE integration test. 
> Leave if blank if it's a future QE issue.
> Delete this comment if it's not related QE integration test.
 
> Target Odo version: 

**Target:** May 27th

**Comment by johnmcollier** [comment]
PR up for review: https://github.com/devfile-samples/image-mirror/pull/1
