### ISSUE TITLE
Update stacks that reference images with the latest tag

### ISSUE THREAD

**Issue by kim-tsao** [devfile/api#849]
**Which area/kind this issue is related to?**

/area registry

## Issue Description

We should avoid having stacks that pull in the latest image since the latest version can change at any time and cause breakage.  Currently, the Go stack is the only one that we own that has this configured.  We should look to fixing the version to the latest Go version and update when needed so we can ensure stack has undergone proper testing.

> Please uncomment and provide the target Odo version if this task is for QE integration test. 
> Leave if blank if it's a future QE issue.
> Delete this comment if it's not related QE integration test.
 
> Target Odo version:

**Comment by maysunfaisal** [comment]
Remaining

### Stacks:

- [ ] java-maven https://github.com/devfile/registry/blob/main/stacks/java-maven/devfile.yaml
- [ ] java-quarkus https://github.com/devfile/registry/blob/main/stacks/java-quarkus/devfile.yaml
- [ ] java-springboot https://github.com/devfile/registry/blob/main/stacks/java-springboot/2.0.0/devfile.yaml and https://github.com/devfile/registry/blob/main/stacks/java-springboot/1.2.0/devfile.yaml
- [ ] java-vertx https://github.com/devfile/registry/blob/main/stacks/java-vertx/devfile.yaml
- [ ] udi https://github.com/devfile/registry/blob/main/stacks/udi/devfile.yaml

**Comment by thepetk** [comment]
I've created the [PR](https://github.com/devfile/registry/pull/183) for `java-maven`, `java-quarkus` and `java-springboot`. For `java-vertx` as the tag is `next` and not `latest` I'd say we can keep it the same.

**Comment by thepetk** [comment]
UPDATE: The [PR] tests are failing because of https://github.com/devfile/api/issues/1115.

**Comment by michael-valdron** [comment]
Blocked by #1115

**Comment by thepetk** [comment]
Unblocked as #1115 is now closed

**Comment by thepetk** [comment]
https://github.com/devfile/api/issues/849#issuecomment-1529763304
The above stacks have been updated
