### ISSUE TITLE
Extend deployByDefault to other components, drop the implicit apply command rule

### ISSUE THREAD

**Issue by l0rd** [devfile/api#852]
**Which area this feature is related to?**

/area api
/area library
/area devworkspace

## Which functionality do you think we should add?

**Why is this needed? Is your feature request related to a problem?**

Devfile adopters struggle to understand what components will be started when a workspace is provisioned.

**Detailed description:**

Understanding which components are started automatically (or builded in the case of an image) and which are not is currently complicated.

There is an implicit rule to start only components that are NOT referenced by a command of type `apply`. That's a hidden rule that is hard to understand and remember.

The new `deployByDefault` and `autoBuild` fields have improved the situation but only apply to kubernetes/openshift and image components respectively.

## Describe the solution you'd like

Add a `runOnDemand` boolean field for components of type containers (`false` by default).

Do not rely on the `apply` rule anymore, but forbid the following configurations (document in the spec, raise an error in the library):
- a container with `runOnDemand: false` is referenced by an apply a command
- a kubernetes/openshift with `deployByDefault: true` is referenced by an apply command
- a image with `autobuild: true` is referenced by an apply command

## Describe alternatives you've considered

We should add a new command of type `delete` that would be the complement of `apply`.

## Related issues

https://github.com/devfile/api/issues/204
https://github.com/devfile/api/issues/693

**Comment by viveksahu26** [comment]
Hey @l0rd , Ohh, I am bit late to know about this project. Hey, Myself vivek !! Currently a student, looking for new project to contribute. And it seems to me an interesting project. I have bit of experience of past one year in open source world. Contributed to  Kyverno project. Looking forward to know more about this project. Any useful resources ??

**Comment by dharmit** [comment]
AFAIU, `deployByDefault` should be used to start the component when the tooling is spinning up resources for inner loop mode. To start the same component in outer loop mode, we rely on it being a part of the composite command with group-kind `deploy`. Isn't that separate ways to segregate the same item between inner and outer loops? Also, why are we using a boolean with `deploy` in its name when it's meant to indicate that such a component should be start in the inner loop?

For `autoBuild`, my understanding is that a command with that boolean set to `true` will trigger `docker build` and then the resulting image is used to start the `Deployment` on k8s. But to use it in outer loop mode, they have to add the same command to composite commands for the command group-kind `deploy`. Why do we require only one boolean for inner loop mode, and explicitly putting it in composite commands for outer loop mode?

For outer loop mode, we only consider things which are marked with group-kind `deploy`. And everything that's not marked as group-kind `deploy` is implicitly a part of inner loop. As a result, reusing things in both modes requires additional flags like `autoBuild`, `deployByDefault`, etc., right? Is that by design?

Why does devfile have separate ways to do things for the two modes it supports, instead of having a straightforward way to do it in both modes? What if there was a need to add support for a third mode in devfile at some point?

**Comment by l0rd** [comment]
@rajibmitra is going to work on this issue as part of the [LXF mentorship program](https://mentorship.lfx.linuxfoundation.org/project/3feec75a-3d80-476a-83ab-89ee90f48aad/mentees).

**Comment by kadel** [comment]
> @kadel setting `autoStart: false` by default would add some syntax sugar AND change the semantic of existing Devfile that do not have an `autoStart` field. Although this is an interesting topic (are devfile containers started more often at startup or after running a command?) I would like to keep this issue about a new more explicit syntax without hanging the behavior of existing Devfiles.

I got a little bit carried away :innocent: . You are right this might not be a good idea right now as it would be incompatible with current Devfile behaviors, but it would simplify a lot of things :-) 



> I am ok to call it `autoStart` and it's a good idea to allow a component to have`autoStart: true` and to be referenced by an `apply` command for now. We can decide later, based on feedback, if we need to avoid it or not.


I'm afraid that if we want to keep default behaviors as `autoStart: true` we will need a different name for this field :-/
Some time back we agreed that we should try to keep default values for `boolean` fields `false`, as it makes it much easier to deal with them.
This means that we won't be able to use `autoStart`. We will need a different name that will have inverted logic (like the originally proposed `runOnDemand`).
`runOnDemand` sounds a little bit weird to me, but currently, I can't think of a better name for this.

**Comment by l0rd** [comment]
During the Devfile Cabal of the 20th of June we have discussed a couple of proposal as mentioned in [another issue](https://github.com/devfile/api/issues/864#issuecomment-1160463639) to use the field `deployStrategy` instead of `runOnDemand`:

> Proposal 1:
> DeployStrategy: AtStartupInMainPod, AtStartupInSeparatePod, StartWithCommandInMainPod, StartWithCommandInSeparatePod
> 
> Proposal 2:
> DeployStrategy: AtStartup, StartWithCommand
> DedicatedPod: true/false
> 
> @kadel Action: Come up with a proposal and examples on how these fields will behave.

**Comment by kadel** [comment]
**!!WORK IN PROGRESS !!**

# Controlling component creation

Devfile has 4 types of components:
- `container`
- `image`
- `kubernetes`
- `openshift`
- `volume`



## Current situation
By default there is an "apply" rule: If a component is not referenced by an `apply` command the component will be automatically created on startup. 

On top of that there is also `deployByDefault` field for `kubernetes` and `openshift` components and `autoBuild` for `image` component. 

If `deployByDefault` or `autoBuild` is `true` than the component will be created on startup regardless if it is referenced by the `apply` command or not.

**Comment by kadel** [comment]
Just copying the final proposal to the comment to make it easier to link to.

To see how I got to this point check previous comment https://github.com/devfile/api/issues/852#issuecomment-1185455118


## Proposal v2


**Each component, where makes sense, will get its own field to control "deployStrategy".**


Mario's `runOnDemand` makes sense for `container` component.

- `container`: `runOnDemand`
- `kuberetes`/`openshift`: `deployByDefualt`
- `image`: `autoBuild`
- `volume`: nothing

### `container` components


#### option 1: `runOnDemand: true/false`

- **When `runOnDemand: true`, the container is always created in a separate pod.**
- By default, containers are started in one pod at startup.
- `exec` command should behave like `apply` command for `container` component (container "onDemand" will be just before `exec` command is executed

| |`runOnDemand: true` | `runOnDemand: false` | `runOnDemand` not set |
|--|--|--|--|
| **referenced in apply command** | created when apply command is invoked  | automatically created on startup | created when apply command is invoked  |
| **not referenced in apply command** | never started ??? | automatically created on startup | automatically created on startup |

`dedicatedPod:true` & `runOnDemand:true` : OK
`dedicatedPod:true` & `runOnDemand:false` : OK
`dedicatedPod:true` & `                 ` : OK


`dedicatedPod:false` & `runOnDemand:true` : NOTVALID
`dedicatedPod:false` & `runOnDemand:false` : OK
`dedicatedPod:false` & `                 ` : OK




### `kubernetes`/`openshift` components
`deployByDefault: true/false`
| |`deployByDefault: true` | `deployByDefault: false` | `deployByDefault` not set |
|--|--|--|--|
| **referenced in apply command** | automatically created on startup | created when apply command is invoked  | created when apply command is invoked |
| **not referenced in apply command** | automatically created on startup |never started ??? | automatically created on startup |





### `image` components
`autoBuild: true/false` 
| |`autoBuild: true` | `autoBuild: false` | `autoBuild` not set |
|--|--|--|--|
| **referenced in apply command** |  automatically created on startup | created when apply command is invoked  | created when apply command is invoked |
| **not referenced in apply command** | automatically created on startup |never started ??? | automatically created on startup |





### `volume` components
no field to control the creation; it gets created automatically when it is used in the container definition.
