### ISSUE TITLE
[SPEC] Remove `endpoints` field from `kubernetes` and `openshift` component definition

### ISSUE THREAD

**Issue by kadel** [devfile/api#856]
/kind bug
/area api

I find `endpoints` field in `kubernetes` and `openshift` components quite confusing. 
The whole point for those two components is to be able to use normal Kubernetes resources. 

Having the `endpoints` there makes it just more confusing. If the devfile author is already using 
`kubernetes`/`openshift` component I don't think that they will have problem adding `Service` or `Ingress`.

**Comment by thepetk** [comment]
closing as rotten
