### ISSUE TITLE
Update EPL license to Apache

### ISSUE THREAD

**Issue by kim-tsao** [devfile/api#863]
**Which area/kind this issue is related to?**

 /area api
 /area registry

## Issue Description

Running a [search across our repos](https://github.com/search?p=2&q=org%3Adevfile+epl&type=Code) show there are still a number of files using the EPL licence.  We should update the headers and any boilerplate templates to use the Apache license instead.  
Affected repos are:

- [x] api
- [x] registry
- [x] registry-support
- [x] landing-page
- [x] docs
- [x] registry-viewer
- [x] integration-tests
- [ ] registry-operator (updates will be made as part of https://github.com/devfile/api/issues/499)

**Comment by amisevsk** [comment]
I forgot to update the DevWorkspace Operator docs repo at the time: https://github.com/devfile/devworkspace-operator-docs/pull/5
