### ISSUE TITLE
Registry viewer crashes at Chrome

### ISSUE THREAD

**Issue by yangcao77** [devfile/api#875]
/kind bug

### Which area this bug is related to?

/area registry

## What versions of software are you using?

**Operating System:**
MacOS 12.4
**Go Pkg Version:**

## Bug Summary
**Describe the bug:**

Registry viewer crashes at Chrome

the issue was gone after disable the telemetry key

## Any logs, error output, screenshots etc? Provide the devfile that sees this bug, if applicable.

![Screen Shot 2022-06-14 at 3 43 16 PM](https://user-images.githubusercontent.com/22285490/173675126-f3d1fa6b-0b79-4871-9cda-b396db4759a4.png)

see errors:
```
Failed to load resource: the server responded with a status of 404 ()
viewer:1 Uncaught (in promise) SyntaxError: Unexpected token p in JSON at position 4
api/get-layout-text:1          Failed to load resource: the server responded with a status of 404 ()
viewer:1 Uncaught (in promise) SyntaxError: Unexpected token p in JSON at position 4
api/get-layout-text:1          Failed to load resource: the server responded with a status of 404 ()
viewer:1 Uncaught (in promise) SyntaxError: Unexpected token p in JSON at position 4
api/get-layout-text:1          Failed to load resource: the server responded with a status of 404 ()
```

## Additional context

**Any workaround?**

use other browser

**Suggestion on how to fix the bug**

**Comment by michael-valdron** [comment]
@yangcao77 Can you confirm that this has been fixed?

**Comment by yangcao77** [comment]
closing this issue as this has been fixed.
