### ISSUE TITLE
Update Ginkgo version in registry operator

### ISSUE THREAD

**Issue by kim-tsao** [devfile/api#881]
**Which area/kind this issue is related to?**

 /area registry

## Issue Description

We are using a deprecated Ginkgo version in the registry operator repo. We should look into updating it using these instructions: https://github.com/onsi/ginkgo/blob/ver2/docs/MIGRATING_TO_V2.md#removed-custom-reporters

## Acceptance Criteria
- [x] Replace `ginkgo.RunSpecsWithDefaultAndCustomReporters` with `ginkgo.RunSpecs`
- [x] Pass `-ginkgo.fail-fast --ginkgo.junit-report=/tmp/artifacts/junit-devfileregistry-operator.xml` as CLI arguments under `test` GnuMake task to replace parameters to the deprecated `ginkgo.RunSpecsWithDefaultAndCustomReporters`

**Target Date: 08-31-2023**

**Comment by michael-valdron** [comment]
registry operator has updated this: devfile/registry-operator#45

**Comment by michael-valdron** [comment]
Issue is ready for review: https://github.com/devfile/registry-operator/pull/45

**Comment by michael-valdron** [comment]
https://github.com/devfile/api/issues/1106#issuecomment-1696505879

**Comment by michael-valdron** [comment]
unblocked: https://github.com/devfile/api/issues/1106#issuecomment-1697609971

**Comment by michael-valdron** [comment]
https://github.com/devfile/api/issues/1106#issuecomment-1698098326

**Comment by michael-valdron** [comment]
https://github.com/devfile/api/issues/1106#issuecomment-1699367564
https://github.com/devfile/api/issues/1106#issuecomment-1699402865

**Comment by michael-valdron** [comment]
https://github.com/devfile/api/issues/1106#issuecomment-1699848699

**Comment by michael-valdron** [comment]
https://github.com/devfile/api/issues/1106#issuecomment-1701206402
