### ISSUE TITLE
Add devfile snippet examples to devfile documentation

### ISSUE THREAD

**Issue by elsony** [devfile/api#885]
/area documentation

**Which area this documentation change is related to?**
/area api

## Issue details
**What mistake did you find / what is missing in the documentation?**
In order to help users to customize or create a new devfile, we need to add devfile snippets to provide concrete examples of how to do a certain operation with the devfile.

We can expose these as a list of specific tasks to be achieved by a user so that the user can copy, paste and customize snippets of devfile when editing their own.

This item includes:

1. Identify a list of common tasks that a devfile writer would like to do, some examples are: adding a container, adding a service via kubernetes yaml, add an endpoint, adding a database to the application, using multiple containers, adding a dockerfile image build, adding build, run commands, etc.
2. Add the code snippet to each identified task

**Comment by feloy** [comment]
Removed blocker as not sure why it has been set
