### ISSUE TITLE
Add tutorial to build devfile from scratch

### ISSUE THREAD

**Issue by elsony** [devfile/api#886]
/area documentation

**Which area this documentation change is related to?**
/area api

## Issue details
**What mistake did you find / what is missing in the documentation?**
Add a tutorial to walk through the steps of creating a devfile from scratch to build an application with a frontend and backend component using devfile. The tutorial should cover both inner loop and outer loop functions in the devfile.

The flow of the tutorial will include (for both the frontend and backend components):
1. Start with a minimal empty devfile
2. Add metadata and schema version to the devfile
3. Innerloop:
   1. Add a container
   2. Add an endpoint to the container
   3. Add a build command
   4. Add a run command
   5. Add a debug command
4. Outerloop:
   1. Add image component with dockerfile
   2. Add kubernetes component for the kubernetes yaml for deployment
   3. Add deploy command
5. How to test out the created devfile

For some of those steps, it can tie this tutorial to the devfile snippets created as part of #885 to help users on how to use the snippets doc as well.

**Comment by michael-valdron** [comment]
Since the steps of this guide ties into referencing the example snippets, #885 would be a blocker to this issue.

**Comment by michael-valdron** [comment]
> Since the steps of this guide ties into referencing the example snippets, #885 would be a blocker to this issue.

After further review this is not being blocked #885.

**Comment by thepetk** [comment]
closing as rotten
