### ISSUE TITLE
Stack/start projects for early adopters/incubators in devfile registry

### ISSUE THREAD

**Issue by elsony** [devfile/api#887]
**Which area this feature is related to?**
/area registry

## Which functionality do you think we should add?
This feature is to introduce a way to tag some early adoption stacks that make the usage of some early adoption stacks/samples to be "use at your own risk". This allows us to continue to evolve the specification in case we have found problems during early adoption and make adjustments on the stack/samples as needed.

**Why is this needed? Is your feature request related to a problem?**
In the past, we have seen cases where some of the tools may adopt a newer version of the spec earlier than others and before the specification GA, e.g. for devfile 2.2, some tools want early adoption of the outer loop specification. Tools to do some early implementation are a good way to verify the spec before the formal declaration of the spec.

However, adding those samples/stacks that are based on the "close to completion" version of the spec may have a longer-term effect and make the evolution of the specification more difficult (to avoid breaking existing tools).

**Detailed description:**
Mechanism to mark stack/start projects for early adopters/incubators:

* Add tag, e.g. "Preview", "Early Adopters" or "Incubators", to the devfile entry in a registry to allow adding an early adoption version of stack/sample without long-term commitment or breakage
* Allow stacks using a newer version of the stack without worry about breaking changes of spec before GA
* Tools can easily filter out those early adopter versions as needed during the normal operation of the GA product
* Tools can decide if they want to show some warnings when the user download and use these preview version of the devfile

## Describe alternatives you've considered
Put the early adoption stacks/samples in a different registry. Maintaining a different registry is relatively expensive.

## Additional context

**Comment by thepetk** [comment]
closing as rotten. Although the topic of stack/sample versioning is an important one and is already added for the next devtools week
