### ISSUE TITLE
Devfile.io blog and video content

### ISSUE THREAD

**Issue by rtaniwa** [devfile/api#889]
/kind user-story

**Which area this user story is related to?**

/area landing-page

## User Story
As a person interested in the devfile project, I would like to see some activity on the landing page that provides updates on the project's features and enhancements

It would be good to have a simple blog page/tab where we can socialize what has been delivered from sprint to sprint. Ideally we would also upload sprint demos to a devfile YouTube page, and include links to those videos in the blog entries.

- [ ] Blog page/tab on devfile.io
- [ ] devfile YouTube channel with sprint demos uploaded for content

**Comment by schultzp2020** [comment]
We have a video created; however, we are waiting for someone to create a blog post before we create a blog section in devfile.io.
https://github.com/devfile/api/issues/812

**Comment by thepetk** [comment]
closing as rotten
