### ISSUE TITLE
Document "fire & forget" nature of postStop events

### ISSUE THREAD

**Issue by dharmit** [devfile/api#894]
/area documentation

**Which area this documentation change is related to?**

/area api

## Issue details

**What mistake did you find / what is missing in the documentation?**

Currently, the documentation doesn't clarify that the postStop events should be of "fire and forget" nature from the tooling perspective. This means that the tooling should only ensure that the event is triggered. Any Kubernetes resources created as a result of this event don't necessarily need to be deleted by the tooling.

**Comment by thepetk** [comment]
closed as rotten
