### ISSUE TITLE
Registry docs incorrectly reference "Oracle Cloud Infrastructure"

### ISSUE THREAD

**Issue by marshall007** [devfile/api#896]
/area documentation

**Which area this documentation change is related to?**

/area registry

## Issue details

**What mistake did you find / what is missing in the documentation?**

The registry documentation incorrectly references "Oracle Cloud Infrastructure" when describing the OCI specification:

>  Devfile registries are based on the Oracle Cloud Infrastructure (OCI) Specification, and devfile stacks are stored as OCI artifacts in the registry.

- https://devfile.io/docs/devfile/2.1.0/user-guide/understanding-a-devfile-registry/
- https://github.com/devfile/docs/blob/master/docs/modules/user-guide/partials/con_understanding-a-devfile-registry.adoc

This seems like a mistake. It should be "Open Container Initiative (OCI) Specification".

**Comment by pratik2315** [comment]
Hey! Is this issue still open? I am new to this community and this issue seems like the perfect way to get started. I would like to work on this, If its alright with you😁

**Comment by schultzp2020** [comment]
Hey @pratik2315 that would be much appreciated! The new location for this reference is here. 
https://github.com/devfile/devfile-web/blob/main/libs/docs/src/docs/no-version/understanding-a-devfile-registry.md
https://devfile.io/docs/2.1.0/understanding-a-devfile-registry
