### ISSUE TITLE
Update schema documentation to be DevWorkspace/Devfile agnostic

### ISSUE THREAD

**Issue by amisevsk** [devfile/api#899]
/area documentation

## Which area this documentation change is related to?
/area api

## Issue details
Various places in the current [Devfile API documentation](https://devfile.io/docs/devfile/2.1.0/user-guide/api-reference/) refer to DevWorkspaces explicitly, as a holdover from early development work. This could be confusing as the DevWorkspace term appears in the Devfile schema -- writing a Devfile should not require understanding what a DevWorkspace is and how it is related.

Usages of specific terms should be reviewed across the schema documentation. If a doc line can be reworded to not include either, that's ideal, but if referencing an object is required, Devfile should be used instead of DevWorkspace.

**Comment by pratik2315** [comment]
Hey! Can I work on this issue if its alright with you?

**Comment by amisevsk** [comment]
No problem on my end :)

**Comment by pratik2315** [comment]
Hey! I am sorry I didn't notice that this issue was already assigned to @jc-berger 😅 My bad, I'll have a look at some other issues haha

**Comment by thepetk** [comment]
closed as rotten
