### ISSUE TITLE
An `envFromFile` attribute for container component

### ISSUE THREAD

**Issue by dharmit** [devfile/api#902]
**Which area this feature is related to?**
/area api

## Which functionality do you think we should add?
`envFromFile` attribute for container component that could help inject multiple environment variables into the container

**Why is this needed? Is your feature request related to a problem?**
I want to inject more than just a couple of environment variables in the container. 

**Detailed description:**
Currently, editing a devfile.yaml for this is the only way to inject environment variables into a container component. This is OK for a handful of environment variables, but as the number of environment variables increases, so does the pain of manually editing a devfile.

## Describe the solution you'd like
An `envFromFile` attribute that would take a file path and the tooling would then inject such environment variables into the container.

## Describe alternatives you've considered
N/A

## Additional context
This came up as a feature request by a user using odo v2.5.1 where `odo env set` is used to set environment variables. https://github.com/redhat-developer/odo/issues/5985

**Comment by Jdubrick** [comment]
Closing issue, looks like a duplicate issue here: https://github.com/devfile/api/issues/907
