### ISSUE TITLE
Clarification to specification to ensure consistent tools implementation behaviour

### ISSUE THREAD

**Issue by elsony** [devfile/api#905]
/area documentation

**Which area this documentation change is related to?**
/area api

## Issue details
**What mistake did you find / what is missing in the documentation?**
A couple of areas need to be improved in the documentation to ensure consistent tools implementation behaviour (to address some of the issues defined in https://github.com/devfile/api/issues/679):

1. entrypoint of components of type container
Tools will need to respect the entrypoint settings. If the entrypoint is not defined, use the default from the image. The containers need to be non-terminating or adding commands and args to make it non-terminating. (Provide example e.g. tail to show).

2. Projects vs starterProjects
For starterProjects and samples (will just refer to sample in the rest of this item), if a sample contains a devfile, the tools will keep that devfile and use the devfile that is included in the sample. If a devfile does not exist in the sample, the tools will copy the original devfile that contains the starterProjects definition and use that devfile.

**Target Date: 09-29-2022**

**Comment by michael-valdron** [comment]
Compiled this list of TODOs for this issue (subject to change):
- [ ] Complete 'Container Entrypoint' section of the [Adding container component](https://devfile.io/docs/2.1.0/adding-container-component) docs page.
- [ ] Add doc page for adding starter projects which mirrors current [Adding projects](https://devfile.io/docs/2.1.0/adding-projects) doc page (deprecated). [Migrating projects](https://devfile.io/docs/2.1.0/migrating-projects) will still be used for migrating to devfile v2.x.
- [ ] Add documentation on actions tools should take with samples with a devfile versus samples without a devfile.

All these items will contain documentation on respective content described in issue description.

**Comment by michael-valdron** [comment]
@elsony @johnmcollier Do we want all changes in this issue to be under all Devfile 2.x versions?

**Comment by michael-valdron** [comment]
> @elsony @johnmcollier Do we want all changes in this issue to be under all Devfile 2.x versions?

Only placing doc changes under Devfile 2.2.0 as discussed in team meeting.
