### ISSUE TITLE
An `envFromFile` attribute for the container component

### ISSUE THREAD

**Issue by dharmit** [devfile/api#907]
/kind user-story

**Which area this user story is related to?**
/area api

## User Story
As an application developer, I want to use a single file containing environment variables, so that I don't have to add them individually to the devfile.

## Acceptance Criteria
- [ ] An `envFromFile` field/attribute for the container component in the devfile. The value of this field should be of string type
- [ ] The environment variables should be specified as `<env-var>`=`<value>` and separated by newline character in the file specified by `envFromFile`. Example file:
  ```sh
  hello=world
  ice=cream
  version=1.2.3
  ```
- [ ] If an environment variable is specified both in this file and the devfile, the value in the devfile should be used
- [ ] It should be possible to store the file name in the Devfile variables and use this variable as value in `envFromFile`
- [ ] Documentation for this field/attribute

**Comment by thepetk** [comment]
closing as rotten
