### ISSUE TITLE
Specify `ServiceAccount` for a container component

### ISSUE THREAD

**Issue by dharmit** [devfile/api#908]
/kind user-story
/area api

## User Story
As an application developer creating [Operators](https://www.cncf.io/blog/2022/06/15/kubernetes-operators-what-are-they-some-examples/), I want to be able to specify [ServiceAccount](https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/), so that the tooling can create Kubernetes resources with specific privileges.

## Acceptance Criteria
- [ ] A `ServiceAccount` field/attribute for the container components. The value of this field would be of string type
- [ ] Multiple container components cannot specify distinct ServiceAccounts unless they are using `dedicatePod: true`
- [ ] Documentation for this field/attribute

**Comment by thepetk** [comment]
closing as rotten
