### ISSUE TITLE
Use OpenShift instead of Openshift in the API codebase

### ISSUE THREAD

**Issue by valaparthvi** [devfile/api#909]
/area documentation

**Which area this documentation change is related to?**

/area api
> /area api
> /area library
> /area registry
> /area devworkspace

## Issue details

**What mistake did you find / what is missing in the documentation?**
The codebase uses Openshift instead of OpenShift. This might be a nitpick, but I think the code should use the same case format as the official one.

**Comment by valaparthvi** [comment]
This issue is relevant to the library codebase as well.

**Comment by thepetk** [comment]
closing as rotten
