### ISSUE TITLE
Provide Service Definition and Endpoint info for the Devfile Sample outerloop components

### ISSUE THREAD

**Issue by maysunfaisal** [devfile/api#910]
**Which area/kind this issue is related to?**

/area registry

## Issue Description

Currently the devfile samples only have the deployment definition in the outerloop component. This task tracks the addition of Service definition in the outerloop yaml file and the addition of endpoints for the outerloop Kubernetes component

**Comment by yangcao77** [comment]
PR created for
java-quarkus: https://github.com/devfile-samples/devfile-sample-code-with-quarkus/pull/7
dotnet60: https://github.com/devfile-samples/devfile-sample-dotnet60-basic/pull/3
java-springboot: https://github.com/devfile-samples/devfile-sample-java-springboot-basic/pull/9

**Comment by yangcao77** [comment]
Go: https://github.com/devfile-samples/devfile-sample-go-basic/pull/8
python: https://github.com/devfile-samples/devfile-sample-python-basic/pull/11
