### ISSUE TITLE
Add devfile adopters to main (or high-level) page

### ISSUE THREAD

**Issue by deboer-tim** [devfile/api#917]
**Which area this feature is related to?**
/area landing-page

## Which functionality do you think we should add?
The new website is awesome, but one of my first questions as a new user is 'how would I use this?' or 'what tools support it?' and this information is hard to find - buried in the docs and incomplete.

**Why is this needed? Is your feature request related to a problem?**
It's too hard to find out what I do with devfiles/why they exist.

**Detailed description:**

## Describe the solution you'd like
Add a section to the landing page (or easily accessible from it) that has a list of adopters as links - ideally with icons, and maybe a very short description.

I don't know what fits (based on where you'd want to put it), but here some basic info on the tools (name - a tagline or tooltip - url to link to). There's at least one tool missing, and if you can't find appropriate icons by googling I can help find them:

- odo - Fast iterative CLI for deploying applications to Kubernetes - https://odo.dev
- Eclipse Che - Run your favorite IDE on Kubernetes - https://www.eclipse.org/che/
- Red Hat Dev Spaces - Start coding on Kubernetes - https://developers.redhat.com/products/openshift-dev-spaces/overview
- OpenShift Developer Console - OpenShift web console for developers - https://www.redhat.com/en/technologies/cloud-computing/openshift/try-it

**Comment by rtaniwa** [comment]
Should we also include [Jet Brains Space](https://blog.jetbrains.com/space/)?

https://blog.jetbrains.com/space/2022/05/04/space-dev-environments-support-for-rider-devfile-configuration-and-more/#devfiles

**Comment by deboer-tim** [comment]
Took a look again, and it was very hard to find devfile adopters anywhere on the site. Would be good to still add this, and include Amazon CodeCatalyst as well.
