### ISSUE TITLE
Devfile icon looks washed out

### ISSUE THREAD

**Issue by deboer-tim** [devfile/api#918]
/kind bug

### Which area this bug is related to?
 /area landing-page

## What versions of software are you using?
Latest

## Bug Summary
The devfile icon (what ends up on the web browser tab) is washed out because the light blue icon color is too close to a light or white background.

**To Reproduce:**
Open devfile.io on Safari dark mode, and create a second tab.
<img width="81" alt="Screen Shot 2022-08-23 at 3 46 58 PM" src="https://user-images.githubusercontent.com/19958075/186252455-03ddda9c-16fe-4d2f-a059-546ff3b9bd02.png">

Or on Chrome when you have a light-blue theme:
<img width="81" alt="Screen Shot 2022-08-23 at 3 49 39 PM" src="https://user-images.githubusercontent.com/19958075/186252927-5a1d4c95-56d5-4682-a6f0-c04eccf93150.png">

## Expected behavior

**Suggestion on how to fix the bug**
There are a couple options, but I'd make a white round-rect background part of the icon (similar to Safari above) and then tweak the current icon color to be a bit darker (or just switch the black) so that it stands out.

**Comment by schultzp2020** [comment]
I think we would need to redesign the devfile icon if we wanted the icon to stand out better because most websites do not have a background for their icon.

**Comment by Jdubrick** [comment]
As stated above this would require a change to the whole icon to make the colours pop more, however, after testing it on Safari and Chrome the logo does not appear washed out to me. I am going to close this issue as it is quite old, if the issue still persists we can revisit and open a new issue.
