### ISSUE TITLE
spike: Comments in devfile.yaml not preserved when using Devfile library

### ISSUE THREAD

**Issue by rm3l** [devfile/api#919]
/kind bug

### Which area this bug is related to?
/area library

## What versions of software are you using?

**Operating System:**
Fedora 36

**Go Pkg Version:**
- Go 1.17.8
- Version of Devfile library used by [odo](https://github.com/redhat-developer/odo): [v1.2.1-0.20220602130922-85a4805bd59c](https://github.com/redhat-developer/odo/blob/main/go.mod#L11)

## Bug Summary
**Describe the bug:**

[`odo`](https://github.com/redhat-developer/odo) commands (like [`odo add binding`](https://odo.dev/docs/command-reference/add-binding) or [`odo remove binding`](https://odo.dev/docs/command-reference/remove-binding) commands) that edit the `devfile.yaml` file will save the Devfile without comments preserved.
A [first investigation](https://github.com/redhat-developer/odo/issues/5789#issuecomment-1203640462) on the odo side led me to the Devfile library, which uses [sigs.k8s.io/yaml](https://github.com/kubernetes-sigs/yaml), which in turn relies on JSON as an intermediate format to convert YAML to/from Go structs.

**To Reproduce:**
See the test cases added in the following repo: https://github.com/rm3l/devfile-lib-comment-preservation-issue.

To reproduce the issue using `odo`, see https://github.com/redhat-developer/odo/issues/5789#issue-1260133878 instead.

## Expected behavior
Comments are preserved. I think this is important as we want the Devfile to be the main source of truth in odo. So users that write ("carefully crafted") comments should have their comments always preserved.

## Additional context
- Might be related to the properties ordering issue reported in #371
- Looks like all tools using [sigs.k8s.io/yaml](https://github.com/kubernetes-sigs/yaml) have the same issue with YAML serialization and deserialization. `kubectl` reportedly has a similar issue with commands that edit the kubeconfig file: https://github.com/kubernetes/kubectl/issues/1262

**Any workaround?**
No workaround so far.

**Suggestion on how to fix the bug**
[go-yaml v3](https://pkg.go.dev/gopkg.in/yaml.v3) brought in comment handling, via a new [Node](https://pkg.go.dev/gopkg.in/yaml.v3#Node) representation that allows preserving comments near the data they describe.
So the recommended way to have comments preserved is via this Node representation, but I guess this will not allow consistent handling of both YAML and JSON.

As we discussed during a community call, other tools might need JSON handling as well.

**Comment by valaparthvi** [comment]
/title Comments in devfile.yaml and the order is not preserved when writing to Devfile using the library

**Comment by johnmcollier** [comment]
Converting issue to spike to investigate feasibility
