### ISSUE TITLE
Landing Page - Updates to Introduction Section

### ISSUE THREAD

**Issue by kim-tsao** [devfile/api#925]
/area documentation

**Which area this documentation change is related to?**

## Issue details

**What mistake did you find / what is missing in the documentation?**

Proposed updates to the sub-topics under the Introduction section:

[What is a devfile](https://github.com/devfile/devfile-web/blob/main/libs/docs/src/docs/no-version/what-is-a-devfile.md)

The statement below implies that it's optional to distribute the devfiles you just authored in order to use it but that's not the case. 

Original:
 `With devfiles, you record the instructions for configuring and running your build environment as a YAML-formatted text file. Then, optionally, you can distribute those devfiles to other build tools and IDEs that support devfiles. Finally, to automatically configure and build a running application from a development project, you run the devfile instructions.`

Proposed changes:

`You can use devfiles to automate and simplify your development process by adopting the existing devfiles that are available in the [public community registry](https://registry.devfile.io/viewer)or by authoring your own devfiles to record custom instructions to configure and run your build environment as a YAML-formatted text file.  You can make these devfiles available in the supporting build tools and IDEs that can automatically process the devfile instructions to configure and build a running application from a development project`

**Comment by callmetushar123** [comment]
Hey, I just need to edit that part out right? Can you assign this to me?

**Comment by kim-tsao** [comment]
@callmetushar123 yes, it's just a straight replacement with the proposed text.  Thanks for offering to fix this, I will assign it to you.

**Comment by kim-tsao** [comment]
Confirmed this is done https://github.com/devfile/devfile-web/pull/43
