### ISSUE TITLE
Update release TypeScript models script

### ISSUE THREAD

**Issue by schultzp2020** [devfile/api#957]
**Which area/kind this issue is related to?**
/area api
/area registry

## Issue Description
Currently the workflow [`release-typescript-models`](https://github.com/devfile/api/blob/main/.github/workflows/release-typescript-models.yaml) releases TypeScript models only for the latest version of the devfile spec. As a consumer of devfiles, it would be nice to have TypeScript model support for all releases of the devfile spec, as well as TypeScript model support for the REST API responses. 

## Possible solutions

1. Generate an OpenAPI JSON (soon to be a complete superset of JSON schema - 90% there and in our case it shouldn't matter) either by [converting](https://www.npmjs.com/package/@openapi-contrib/json-schema-to-openapi-schema) the preexisting JSON schema or use [`swaggest/rest`](https://github.com/swaggest/rest/). Then convert to TypeScript models by [openapi-typescript](https://github.com/drwpow/openapi-typescript).
2. Use [`typescriptify-golang-structs`](https://github.com/tkrajina/typescriptify-golang-structs) on Go source code to generate TypeScript models.

Method 1 is preferred because it can be extended to easily test the API responses.

**Comment by schultzp2020** [comment]
@sleshchenko, @JPinkney, @l0rd do we still need to keep type support for devworkspace inside of the [`@devfile/api`](https://www.npmjs.com/package/@devfile/api) npm package?

**Comment by l0rd** [comment]
@benoitf @azatsarynnyy do we use the `@devfile/api` npm package in our editors?
@schultzp2020 FYI @sleshchenko and @JPinkney has left Red Hat and are not working on Devfile/DevWorkspaces anymore.

**Comment by benoitf** [comment]
yes we are using it in dashboard and in the "libraries" to enhance devfiles (theia and vscode)

**Comment by l0rd** [comment]
@schultzp2020 we still do need the DevWorkspace type support
