### ISSUE TITLE
spike: Fix and enable failing odo v3 tests

### ISSUE THREAD

**Issue by kadel** [devfile/api#960]
When odo v3 tests were added in https://github.com/devfile/registry/pull/132
A few stacks and starterprojects are currently failing.

It needs to be investigated and fixed 

**Test failing due to "ErrImagePull"**
- stack: java-openliberty-gradle starter: rest
- stack: java-websphereliberty-gradle starter: rest
- stack: java-websphereliberty starter: rest
- stack: java-openliberty starter: rest

```
  Normal   Scheduled  3m22s                default-scheduler  Successfully assigned default/java-openliberty-gradle-app-5b755bcbd-wgthg to minikube
  Warning  Failed     83s                  kubelet            Failed to pull image "icr.io/appcafe/open-liberty-devfile-stack:22.0.0.1-gradle": rpc error: code = Unknown desc = context deadline exceeded
  Warning  Failed     83s                  kubelet            Error: ErrImagePull
  Normal   BackOff    83s                  kubelet            Back-off pulling image "icr.io/appcafe/open-liberty-devfile-stack:22.0.0.1-gradle"
  Warning  Failed     83s                  kubelet            Error: ImagePullBackOff
  Normal   Pulling    71s (x2 over 3m22s)  kubelet            Pulling image "icr.io/appcafe/open-liberty-devfile-stack:22.0.0.1-gradle"
```
  This is specific to minikube configuration, this fauls on minikube because the image is not downloaded in time, and it reaches timeout. This could be fixed by increasing `runtimeRequestTimeout`  kubelet configuration.

**Starter project incompatible with devfile**

- stack: java-vertx starter: vertx-cache-example
- stack: java-vertx starter: vertx-cache-example-redhat

The application fails because there are 3rd party dependencies specific to this example that are not captured in the devfile.yaml (deploying cache service). This is described in the starter project readme (https://github.com/openshift-vertx-examples/vertx-cache-example-redhat#deployment)

- stack: java-vertx starter: vertx-crud-example-redhat
- stack: java-vertx starter: vertx-crud-example

requires postgresql instance that is not defined in devfile.yaml

- stack: java-vertx starter: vertx-istio-circuit-breaker-booster
- stack: java-vertx starter: vertx-istio-distributed-tracing-booster
- stack: java-vertx starter: vertx-istio-routing-booster
- stack: java-vertx starter: vertx-istio-security-booster

requires Istio that is not deployed on the cluster 

- stack: java-wildfly-bootable-jar starter: microprofile-rest-client

The starter project (https://github.com/wildfly/quickstart/tree/main/microprofile-rest-client) is multi-component and this devfile stack is not written to handle that

- stack: java-vertx starter: vertx-messaging-work-queue-booster

requires AMQP that is not defined in devfile.yaml

**Application is listening on a wrong address**

Following starter project in `java-wildfly` stack are not working because the application inside the container is listening on non-local address (`172.17.0.3`)

- stack: java-wildfly starter: microprofile-config
- stack: java-wildfly starter: microprofile-fault-tolerance
- stack: java-wildfly starter: microprofile-health
- stack: java-wildfly starter: microprofile-jwt
- stack: java-wildfly starter: microprofile-metrics
- stack: java-wildfly starter: microprofile-openapi
- stack: java-wildfly starter: microprofile-opentracing
- stack: java-wildfly starter: microprofile-rest-client

**odo bug**
odo has a bug that prevents odo to download starter project form git repository that has a default branch that is not called `master` https://github.com/redhat-developer/odo/issues/6232

- stack: java-vertx starter: vertx-http-example-redhat

to do:
- stack: java-vertx starter: vertx-circuit-breaker-example-redhat
- stack: java-vertx starter: vertx-circuit-breaker-example

**Comment by thepetk** [comment]
Closing https://github.com/devfile/api/issues/1391 as is already included in this issue. The acceptance criteria were:

- [ ] Investigate what type of tests could be added for java-vertx against odov3.
- [ ] Add test cases for java-vertx against odov3 to confirm that any future changes are working.
