### ISSUE TITLE
Update Release docs

### ISSUE THREAD

**Issue by kim-tsao** [devfile/api#968]
**Which area/kind this issue is related to?**

/area releng

## Issue Description

From today's Cabal call, we decided to keep the JSON Schema and API version in sync.  @kadel made a good point in support of this approach by saying the API is an implementation of the schema and would prefer not to see them decoupled.  This means for the Devfile 2.2 release, we will be breaking semver (this is a one time exception), by keeping the API version in sync as 2.2.  We will call out the breaking change in our release notes.   Going forward, if there is another breaking change we will update the major version for both the schema and API regardless of whether it's just one or the other that breaks.  We need to be update the versions as soon as we are aware of the breaking changes i.e. during dev not release time.

Some TODOs:

We should update our release notes to clarify the change in process:

https://github.com/devfile/api/blob/main/RELEASE.md
https://github.com/devfile/api/blob/main/docs/proposals/versioning-and-release.md

**Comment by elsony** [comment]
>Going forward, if there is another breaking change we will update the major version for both the schema and API regardless of whether it's just one or the other that breaks. We need to be update the versions as soon as we are aware of the breaking changes i.e. during dev not release time.

Before the major version update is merged, the major version update needs to bring to the devfile community call for discussion to get agreements from the community before committing the change.
