### ISSUE TITLE
UNIX permissions causing unwanted failures

### ISSUE THREAD

**Issue by michael-valdron** [devfile/api#973]
/kind bug

### Which area this bug is related to?

/area ci

## What versions of software are you using?

**Operating System:** N/A

**Go Pkg Version:** N/A

## Bug Summary
**Describe the bug:**

Changes in UNIX permissions in commits can cause build scripts and CI actions to fail. This is due to script executions using the property of being executable, example in shell: `./build.sh`

**To Reproduce:**

Though this is typically done by unintentional actions (e.g. actions done on a non-UNIX OS), this can be directly reproduced in a UNIX-based system by running the following:
```sh
chmod 644 <path-to-script>
```
or
```sh
chmod a+rw <path-to-script>
```

## Expected behavior

Scripts should be able to run without relying on the executable UNIX property.

## Any logs, error output, screenshots etc? Provide the devfile that sees this bug, if applicable.

N/A

## Additional context

**Any workaround?**

In the current state, review on UNIX permissions and corrections when needed is required to avoid this issue.

**Suggestion on how to fix the bug**

All script execution calls should be changed from directly executing the script file to passing the script file on call of the appropriate shell defined by the scripts shebang, e.g. in the case of a bash script `./build.sh` would become `bash ./build.sh`.

[Edit by @thepetk]
**Target date**: 28 Apr 2023

**Comment by thepetk** [comment]
Update: I've created as an example the [devfile-api#1107](https://github.com/devfile/api/pull/1107), where I've checked the `.github/workflows/` dir and updated the direct scripts execution.

**Comment by thepetk** [comment]
UPDATE: I've updated the documentation (tried to add `bash` wherever we mention that someone has to run a script locally) and updated the PRs after the first reviews.
