### ISSUE TITLE
Update the landing-page and registry-viewer to use Next.js 13

### ISSUE THREAD

**Issue by schultzp2020** [devfile/api#976]
**Which area/kind this issue is related to?**

/area landing-page
/area registry

## Issue Description
Next.js recently updated to Next.js 13 which adds the [Layouts RFC](https://nextjs.org/blog/layouts-rfc). This should allow us to reduce JavaScript sent to the client. 

Target date: To do

**Comment by michael-valdron** [comment]
This seems to be resolved now as Node.js has been updated to version 16 now.
