### ISSUE TITLE
The registry should have a headless REST API server build option 

### ISSUE THREAD

**Issue by schultzp2020** [devfile/api#977]
**Which area this feature is related to?**

/area registry

## Which functionality do you think we should add?

**Why is this needed? Is your feature request related to a problem?**

As a consumer of the registry REST API, I should have the option to spin up a headless REST API server.

**Detailed description:**

The only difference between the headed and headless REST API server is that the headless REST API server does not include the registry viewer.

## Describe the solution you'd like

A build arg should be passed to build either a headed or headless build of the REST API server.

## Describe alternatives you've considered

N/A

## Additional context
N/A

**Target Date: 11-08-2022**

**Comment by michael-valdron** [comment]
blocked by devfile/devfile-web#51
