### ISSUE TITLE
Add information around support for devfile in IDE extensions

### ISSUE THREAD

**Issue by mohitsuman** [devfile/api#978]
Moving this from https://github.com/devfile/devfile-web/issues/46

Currently, the devfile new page has information about `Tools that provide devfile support` as odo and EclipseChe.

https://devfile.io/docs/2.1.0/application-developer

We would like to add more supported tools that work with devfile-based workflow.

- [VSCode OpenShift Toolkit](https://github.com/redhat-developer/vscode-openshift-tools)
- [IntelliJ OpenShift Toolkit](https://github.com/redhat-developer/intellij-openshift-connector)

**Comment by michael-valdron** [comment]
@jc-berger is no longer working with us as our doc writer, I will reassign this to @gabriel-rh at this time.

**Comment by michael-valdron** [comment]
area/documentation

**Comment by mohitsuman** [comment]
@michael-valdron We are going to make a release of the OpenShift extension this week and having this information on the devfile.io website will be useful. Can this issue be taken up in this sprint?

**Comment by elsony** [comment]
On top of the OpenShift connectors, we also need to add a link to ODC as well.

**Comment by mohitsuman** [comment]
@schultzp2020 where can we see this change updated on the website?
