### ISSUE TITLE
The registry REST API should have the option to be deployed in docker or podman

### ISSUE THREAD

**Issue by schultzp2020** [devfile/api#979]
**Which area this feature is related to?**

/area registry

## Which functionality do you think we should add?

**Why is this needed? Is your feature request related to a problem?**

As a consumer of the registry REST API, I should have a simplified build process that allows the registry REST API to be deploy on docker or podman. 

As a developer of the registry REST API, I should be able to quickly iterate changes without needing to deploy to a Kubernetes instance.

**Detailed description:**

The registry REST API should have the option to be deployed in docker or podman.

## Describe the solution you'd like

The registry REST API should have the option to be deployed in docker or podman.

## Describe alternatives you've considered

N/A

**Comment by Jdubrick** [comment]
Closing issue as all devfile repos have podman support now. For registry REST API please see: https://github.com/devfile/registry-support?tab=readme-ov-file#instructions
