### ISSUE TITLE
Support Kubernetes extended resources for Kubernetes components

### ISSUE THREAD

**Issue by elsony** [devfile/api#988]
## Which area this feature is related to?
/area api

## Which functionality do you think we should add?
**Why is this needed? Is your feature request related to a problem?**
https://github.com/devfile/api/issues/920 has introduced the ability to allow specifying request/limits for resources other than memory and CPU. However, the function is specific to the container component. 

**Detailed description:**
In some cases, the user may want to do a similar override on the Kubernetes components. One concrete use case is that App Studio is currently having custom attributes to do those overrides which can be configured as part of the App Studio UI. App Studio is currently using its own custom attributes to achieve the override (see https://github.com/devfile-samples/devfile-sample-python-basic/blob/main/devfile.yaml for an example).

This item is to propose using the syntax of the same attribute to achieve override on the Kubernetes component.

## Describe the solution you'd like
Similar syntax of the override settings on the Kubernetes components. (detailed proposal will follow)

## Describe alternatives you've considered
Using the tool's specific attributes that are unique to a particular tool makes it less portable to another environment that we are trying to fix.

**Comment by kadel** [comment]
> This item is to propose using the syntax of the same attribute to achieve override on the Kubernetes component.

It is `kubernetes` component, so all those things can be defined in the Kubernetes file itself.

Why would anyone need to override this in the devfile?
