### ISSUE TITLE
 error in /api/build/typescript-model/generate.sh

### ISSUE THREAD

**Issue by ankit28pandey** [devfile/api#989]
Not able to run yarn command in generate.sh file. I am attaching the screenshot of the error that I got after running this file.
<img width="941" alt="Screenshot_20221118_012348" src="https://user-images.githubusercontent.com/91360605/202650131-a55ac483-95d2-4745-8f6c-80e8f6fb6eed.png">

Please allow me to resolve this issue for you so this this file can be run properly.

**Comment by thepetk** [comment]
All related ci failures have been included in an epic. Closing current issue in favor of #1232 which is part of EPIC #1236
