### ISSUE TITLE
Update go stack image to more standard images to avoid vulnerabilities

### ISSUE THREAD

**Issue by elsony** [devfile/api#990]
## Which area/kind this issue is related to?
/area registry

## Issue Description
The current go stack image uses a custom image and has lots of security vulnerabilities https://quay.io/repository/devfile/golang/manifest/sha256:684d791f8fd1b28485ee32239d92cde7099d97c88c5ed2e955f65f4adcf35d0f?tab=vulnerabilities. Ideally, we'll move it to the standard image from quay.io to reduce the maintenance of the images.

We should also inspect the other stack images provided by the devfile services team to address similar issue.

**Comment by johnmcollier** [comment]
As discussed on last Thursday's call, let's move to gotoolset, as its uncompressed size is not significantly larger than our existing go image.
